### ISSUE TITLE
Alpha Testing - Notifications? Who all need to be notified and when

### ISSUE THREAD

**Issue by geetajoshi2019** [episphere/connect#10]
Do we need to send notifications as user submits data from eligibility till consent?
If yes to whom and when?
Should we just have a bell icon on the Dashboard to inform there are updates? 
Or do we need to alert NCI/Sites that their respective information has been updated within system/Dashboard. (Hourly, every 5-6Hrs, every 12Hrs, nighly, refresh button etc)

**Comment by FrogGirl1123** [comment]
Do you mean "alert" NCI/Sites that ...... instead of "alter"?

**Comment by geetajoshi2019** [comment]
@bhaumik55231 @theEIC Spoke to Michelle about this requirement. This is not urgent and pushing it to Hold. we can determine in future its priority.

**Comment by danielruss** [comment]
how do sites want to receive notification of actions happening in our system (e.g. if someone consents or completes a user profile)? Who should be notified and how? What data do they need to receive?
