### ISSUE TITLE
Chicago Clinical Variable E2E Testing 

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#1001]
Please see the below testing checklist. Please check off when done and note date and initial of completion:

- [x]  @mnataraj92 Reach out to Chicago with testing plan and variables to test -5/6 MN
- [x]  @mnataraj92 Confirm with Erin that testing plan covers all scenarios -5/6 MN
- [x] Nina and Jaime to test sending variables via API to make sure that API failure does not occur -5/6 MN
- [x] @mnataraj92 Set up dev testing meeting with Chicago and internal team -5/6 MN
- [x] @mnataraj92 Confirm with Chicago that they will create dev participants for testing -5/6 MN
- [x] @JoeArmani Check firestore during Dev/Stage testing -5/20 JA
- [x] @erincschwartz or @wyattks Check Clinical Biospecimen Dashboard during dev/stage testing [ES 5/20]
- [x] @jacobmpeters Sync BQ and Firestore so @jeannewu can check BQ during dev/stage testing [JP 5/20]
- [x] @mnataraj92 Set up stage testing meeting with Chicago and internal team -5/13 MN

**Comment by mnataraj92** [comment]
Testing in dev and stage complete, ready for prod

Please check/initial/date next to all completed tasks when you get a chance!
