### ISSUE TITLE
Blocking Research or Clinical collection entry if collection type does not match previous collection at same timepoint- July release (Biospecimen Dashboard)

### ISSUE THREAD

**Issue by erincschwartz** [episphere/connect#1004]
**IGNORE THIS, SEE BELOW**

Add backend check during Specimen Link in both Research and Clinical Dashboards to determine whether a collection has already been entered for that timepoint (i.e. Baseline) of the other type (Research/Clinical). If so, disable specimen link button (gray out) and add pop up message "Specimen Link not allowed. Check previous collections for this participant." 

Block API push of clincial collection data if Research Collection was already completed.

**Comment by erincschwartz** [comment]
@Gbarra9 Updating this request, we no longer need to block clinical collections or backend clinical collection data. 

Add backend check during check in step in Research Dashboard to determine whether a **Clinical** collection (blood or urine) has already been entered for that timepoint (i.e. Baseline). If so, disable 'check in' button (gray out) and add pop up message "Check In not allowed, participant already has clinical collection for this timepoint."

**Comment by Gbarra9** [comment]
This is merged in dev and ready to be tested.

**Comment by Gbarra9** [comment]
// API Derived Variables from sites (Baseline)
693370086 - Clinical Site Blood Collected
786930107 - Clinical_Site Urine Collected
728696253 - Clinical Site Blood RRL Received
453452655 - Clinical Site Urine RRL Received

// DB Derived variable (Baseline)
316824786 - Any specimen collected at RRL
    
Upon further review with @erincschwartz and @brotzmanmj, the following derived variables will be used in the logic to block the research check-in workflow. If any of the above variables exist with a "yes" value then the research workflow check-in will be blocked.  The previous logic checked for the variable "Any clinical blood or urine sample received"(156605577). 

The variable for 156605577 is not reverting to a "null property" or a a "no value" when a  blood tube or urine tube was checked and saved and then all blood and/or urine tubes were unchecked and saved. This will need to be looked into at another time.

**Comment by erincschwartz** [comment]
@Gbarra9 Please update the wording on the error message pop up to the following: 
- At the top, please replace Check in Error at the top with WARNING
- After "timepoint." Please add: If you have questions, contact the Connect Biospeicmen Team: connectbioteam@nih.gov. 


![Image](https://github.com/user-attachments/assets/cd9da580-59e6-44fb-ac08-f63e26f7189e)

**Comment by sonyekere** [comment]
Testing is occurring and small issues found, Gene to proceed with fix.

**Comment by erincschwartz** [comment]
Testing showed that blocking check in functionality is working as expected. Only issue is that testing revealed that "cursor: not-allowed" is showing after clicking check-in, even when check in is allowed. The successful check in message pops up, as expected, but the "cursor: not-allowed" may be confusing to sites. @Gbarra9 confirmed that this is due to the programming for this issue and will investigate adjusting the timing of this showing up.

**Comment by Gbarra9** [comment]
> Testing showed that blocking check in functionality is working as expected. Only issue is that testing revealed that "cursor: not-allowed" is showing after clicking check-in, even when check in is allowed. The successful check in message pops up, as expected, but the "cursor: not-allowed" may be confusing to sites. [@Gbarra9](https://github.com/Gbarra9) confirmed that this is due to the programming for this issue and will investigate adjusting the timing of this showing up.

Tested the "not-allowed" cursor timing in dev and is ready for stage.

**Comment by erincschwartz** [comment]
Tested in Stage, ready for Prod

**Comment by sonyekere** [comment]
In production.
