### ISSUE TITLE
Pt received duplicated mouthwash kit reminders 

### ISSUE THREAD

**Issue by HanaShiho** [episphere/connect#1010]
We have one participant who received two 1st MW kit reminders (client side) on the same day. See below. We attempted to prevent the same reminder from going out multiple times last month, so it would be helpful to find out why that fix didn't do the trick. 

![image](https://github.com/episphere/connect/assets/148134271/c355b24b-b2f3-4272-be32-7f73dc8b0e5d)

**Comment by we-ai** [comment]
I never did fixes on client-side emails. All my previous work was on scheduled notifications.
What fix are you referring to? @HanaShiho

**Comment by HanaShiho** [comment]
I wasn't aware the fix only applied to the server side so that's good to know. Thanks for the clarification @we-ai

**Comment by we-ai** [comment]
This bug in client-side email handling can be fixed when moving client-side email templates to Firestore. @brotzmanmj @depietrodeanna @HanaShiho

**Comment by brotzmanmj** [comment]
That's what we were guessing. Thanks for confirming.
