### ISSUE TITLE
Research Dashboard - Collection Phlebotomist Initials are not saved when Save is selected (Biospecimen) (November)

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#1012]
On the research dashboard's Collection Data Entry screen, the Phlebotomists intials are not saved when "Save" is selected.  They are only saved when "Go to Review".  Please change so the intials are saved when "Save" or "Go to Review" are selected.

![Image](https://github.com/episphere/connect/assets/64605220/7da4d4c2-824f-4282-93f8-7e7d264eaec4)

**Comment by sonyekere** [comment]
A PR has been submitted

**Comment by erincschwartz** [comment]
Tested in Stage, ready for Prod

- When attempting to save without entering initials, received message indicating that phlebotomist initials are required, as expected
- Entered initials and saved page. Went back via Specimen search and initials were retained, as expected
