### ISSUE TITLE
PWA: Quest container - Accessibility - Minor navigation improvements.

### ISSUE THREAD

**Issue by JoeArmani** [episphere/connect#1013]
• For screen readers: read the progress bar, but skip reading the enclosing HTML group (simplify screen reader navigation).
• Reduce the container's whitespace a bit for easier access to navigation buttons, especially in mobile view (less scrolling).

**Comment by JoeArmani** [comment]
In dev, ready for testing. Will be tested alongside https://github.com/episphere/connect/issues/931

**Comment by cunnaneaq** [comment]
ConnectApp updates look good in dev - ready for stage

**Comment by JoeArmani** [comment]
Closing, in production.
