### ISSUE TITLE
Set participant Connect ID in DataDog sessions for error tracking (PWA)

### ISSUE THREAD

**Issue by anthonypetersen** [episphere/connect#1015]
### Discussed in https://github.com/episphere/connect/discussions/954

<div type='discussions-op-text'>

<sup>Originally posted by **JoeArmani** April  8, 2024</sup>
I wanted to put this idea up for discussion after a quick DevOps chat last week @brotzmanmj @Davinkjohnson  @anthonypetersen @we-ai.

**Issue:**
As the study grows and the PWA has more users, it becomes increasingly difficult to investigate individual technical issues in ConnectApp without a searchable identifier.

**Current Process:**
Currently, we drill down into issues based on times, expected user locations, and error types. This is reasonably effective for set geographic locations such as our lab and shipping locations (Biospecimen and SMDB). It is less effective in the PWA since participants are on the move and using mobile devices. As traffic increases, this will become increasingly challenging.

**Possible Solution:**
We can use DataDog's userID property to associate a participant's Connect ID with their DataDog's session. This would allow us to search for a session using the participant’s Connect ID instead of the lengthy drill-down process described above. We could take the same action with the user’s SSO email address in Biospecimen and SMDB (this is less important but would still help locate bugs and issues).

**Legal:**
We would need consent from participants based on GDPR and CCPA laws.

**Implementation:**
The technical implementation is straightforward. Associate the logged-in participant with the DataDog session after authentication.
```javascript
// Code sample from DataDog below. We only need to set 'id' -> 'Connect_ID'

// set user
datadogRum.setUser({
    id: '1234',
    name: 'John Doe',
    email: 'john@doe.com',
})

// in our context this would get set after confirming authentication:
window.DD_RUM && window.DD_RUM.setUser({id: participant[‘Connect_ID’})

//clear user (important for public/shared computers)
datadogRum.clearUser()
``
</div>

**Comment by JoeArmani** [comment]
Dev screenshots for two test participants: 

**Connect IDs captured in DataDog:**
<img width="1449" alt="dev-datadog-connectids" src="https://github.com/episphere/connect/assets/93854858/a817fe3d-a624-43b8-8643-0e3062e184e4">


**Search by ID 1:**
<img width="1455" alt="dev-datadog-connectid-search-1" src="https://github.com/episphere/connect/assets/93854858/6f6c697b-0256-4e65-ac78-aabdfccf6a6a">

**Search by ID 2:**
<img width="1453" alt="dev-datadog-connectid-search-2" src="https://github.com/episphere/connect/assets/93854858/3990e8be-f6fe-4609-af2f-6ae3759a6eec">

**Capture logout action:**
<img width="809" alt="log-logout-action" src="https://github.com/episphere/connect/assets/93854858/dc1454ff-07d0-430a-a368-ba8b80259209">

**Comment by JoeArmani** [comment]
Testing: Log into the PWA (dev). Provide your Connect ID, and I'll search for it in DataDog.

This is in dev and ready for testing.

**Comment by brotzmanmj** [comment]
HI @JoeArmani do you need someone from the Ops team to do this?

**Comment by JoeArmani** [comment]
Hi @brotzmanmj that would be great, thanks. I'm ready to check any time.

**Comment by brotzmanmj** [comment]
@kmazzilli is this something you can do and let Joe know?

**Comment by kmazzilli** [comment]
Hi @JoeArmani I just logged into the PWA in dev for connect ID 8569607460

**Comment by JoeArmani** [comment]
Perfect, thanks @kmazzilli 

Here are two confirmation screenshots:

(1)
<img width="1440" alt="Screenshot 2024-06-27 at 2 11 53 PM" src="https://github.com/episphere/connect/assets/93854858/8f94e851-28b9-4062-a307-ffeba65d6e05">


(2)
<img width="1134" alt="Screenshot 2024-06-27 at 2 14 23 PM" src="https://github.com/episphere/connect/assets/93854858/fb6c3aad-02ee-4dfe-b641-d996a72e1a02">

**Comment by JoeArmani** [comment]
Do we want to run any additional tests here or mark it ready for stage?

**Comment by anthonypetersen** [comment]
@JoeArmani I'm guessing you can filter by User ID, is there a `null` filter option for sessions made prior to your code push? Only other "test" I could see is just verifying that sessions are all getting a User ID associated to them when necessary, so maybe just come back in a few days and validate?

**Comment by JoeArmani** [comment]
@anthonypetersen All sessions still start in the window.onload call as the app opens. This is unchanged. Then, just after the participant is authenticated (the first successful `getMyData` call, we make a write call to add the Connect ID to the existing session.

Unauthenticated sessions can access the Home (login), About, What to expect, and Privacy pages. DataDog still captures these sessions, but they won't have an associated Connect ID to search by.

Sounds good, I'll check back this coming week.

**Comment by sonyekere** [comment]
Hi @JoeArmani ! Are we keeping this open in August as well?

**Comment by JoeArmani** [comment]
Hi @sonyekere, this is working well and I'll close it now. Thanks!
