### ISSUE TITLE
PWA - User Profile - Options for Cancer Location

### ISSUE THREAD

**Issue by meganstead** [episphere/connect#102]
Discussed during the 5/12 internal prep call

In the user profile, should participants have an option of selecting the location or organ of their cancer diagnosis?

**Comment by miagaudet** [comment]
For the early recruitment phase, we will evaluate how many participants indicate they had a cancer and the type of cancer. We suspect that few people should indicate that they have a history of cancer. THerefore, we want to leave the question as is for now.
