### ISSUE TITLE
Home Collection Date/Time format for date collected (Biospecimen) (June Release)

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#1022]
Certain home collection mouthwash samples have been showing up in the Kit receipt csv with NaN/NaN/NaN NaN:NaN for the Date Drawn.

I tested several scenarios in dev and had Gene check the backend data.  During discussion with Gene about the issue, he is this might be some error on the backend with saving the timestamp. Below is what was tested and the results:

![Image](https://github.com/episphere/connect/assets/64605220/ac04b226-024c-4652-90e6-62df945c76a4)

The issue is not tied to one site.  We would like to get this in the June release as this is causing issues for the lab, as they have to go back to the collection cards and re-enter data before uploading to BSI.

concept ID is 448660695

**Comment by wyattks** [comment]
Attached are the reports for when I have seen this issue in Prod.

[2024-05-22-Kit-data-export NAN Issue.csv](https://github.com/episphere/connect/files/15406635/2024-05-22-Kit-data-export.NAN.Issue.csv)
[2024-05-10-Kit-data-export NaN Issue.csv](https://github.com/episphere/connect/files/15406634/2024-05-10-Kit-data-export.NaN.Issue.csv)
[2024-04-12-Kit-data-export Data issue.csv](https://github.com/episphere/connect/files/15406633/2024-04-12-Kit-data-export.Data.issue.csv)

**Comment by sonyekere** [comment]
Hi @brotzmanmj. Quick question on the above. Does your statement in the issue regarding **"Storing the date/time correctly from manual entry into the dashboard into the proper format for UTC time"** imply that it refers to the "Enter Collection Date from Collection Card" and "Enter Collection Time from Collection Card" fields on the Kits Receipt page of the BPTL dashboard? @amber-emmes  is currently looking into this issue

**Comment by brotzmanmj** [comment]
HI @sonyekere Yes, that's correct, thanks

**Comment by amber-emmes** [comment]
A few notes:
1. It appears that the only thing this page currently requires to save, at least on the front end, is a package condition to be selected. Currently, if a collection ID is provided but not the date and time collected, it results in a timestamp value of `T`, which is quite likely the reason behind the NaN issue you're seeing. What validation behavior do we want for this page? Which fields should be always required, and which fields should be required if other fields have a value? My initial thought would be that the Return Kit Tracking Number, Package Condition, and Date Received fields should be required; that we should require either a collection ID _and_ collection date and time to be specified _or_ that `Check if Collection Card Missing` be checked (with a validation error shown if both a collection ID is provided and that field is checked) and the comments should always be optional. Is this correct?
2. Date received seems to be stored in the format of (for example) 2024-05-23T00:00:00.000Z, which seems to match the format that is created for the collection drawn date aside from the lack of Z at the end. (An example generated timestamp is 2024-05-21T15:26:28). If this isn't the right format then I need further clarification on what "the other date/time variables" refers to and what format those are in.

**Comment by brotzmanmj** [comment]
Hi @amber-emmes  we're working on a response for (1). 
For (2), we're referring to the Date/Time collected, not the date received. The data received should already be in the correct format.
Thanks

**Comment by brotzmanmj** [comment]
Hi @amber-emmes For (1) Will we require Return Kit Tracking Number, Package Condition, and Date Received fields, and regardless of whether the card was included or missing we will require Collection ID, Date Collected and Time Collected. (The staff have a way of approximating the date and time of collection if that information is not provided on the card or no card is returned).

**Comment by amber-emmes** [comment]
Are there any preferences as to the format in which the user is informed of missing fields? Currently, the Kit Assembly page does not specify which fields are missing and only shows a  notification that one or more fields are missing:

![image](https://github.com/episphere/connect/assets/160774541/f97cb40f-e74d-4699-8e67-088477bfd2d0)

While the Kits Received page has a dialog box about package condition being missing.

![image](https://github.com/episphere/connect/assets/160774541/a83f175a-45e7-475a-9668-6d14220c1d2a)

I have a variety of options, including specifying which fields are missing in the dialog which currently specifies missing package condition, removing the dialog and changing the format to match the Kit Assembly page, or changing the format entirely to display in another fashion without the dialog.

**Comment by wyattks** [comment]
I think matching the format to the Kit Assembly page would be the way to go

**Comment by amber-emmes** [comment]
So ultimately, using exactly the format from the Kit Assembly page is proving to be labor-intensive because it doesn't mix well with the confirmation dialog on the submit button. Would this be acceptable for the resolution of this ticket, or should I keep looking into a way to use the Kit Assembly format?

![image](https://github.com/episphere/connect/assets/160774541/cf54a740-7fa5-40ba-879d-dbe0e22be306)

**Comment by wyattks** [comment]
If its too time consuming right now to have it match the kit assmebly then yes the error pop up explaining package condition is missing is fine.  Thanks!

**Comment by sonyekere** [comment]
Look out for any possible issues once live.

**Comment by amber-emmes** [comment]
Merged into dev and ready to test there.

**Comment by wyattks** [comment]
Hi Amber,  I received the errors as expected when the Date and time were not entered as well as when jut the time was entered.  
Hwever, I was able to save the receipt when i just entered the date and not time.  In the receipt csv the Date Drawn showed up as NaN/NaN/NaN NaN:NaN
See attached file.

[2024-06-13-Kit-data-export (3).csv](https://github.com/user-attachments/files/15827866/2024-06-13-Kit-data-export.3.csv)

**Comment by amber-emmes** [comment]
Fix created and PR submitted to dev.

**Comment by amber-emmes** [comment]
Merged into dev and ready for re-testing.

**Comment by wyattks** [comment]
Works in Dev  ready for stage

**Comment by wyattks** [comment]
Tested and ready for ProdTested in Stage, ready for Prod
.
