### ISSUE TITLE
BSWH Race/Ethnicity Variable

### ISSUE THREAD

**Issue by mnataraj92** [episphere/connect#1024]
BSWH would like us to add a new race/ethnicity variable to the dictionary. They have decided to use the following categories to send de-identified race/ethnicity data:
•	White non-Hispanic
•	Black non-Hispanic
•	Hispanic/Latino
•	Asian
•	American Indian or Alaskan Native
•	Native Hawaiian or Other Pacific Islander
•	Multi-racial
•	Other
•	Unknown/Unavailable

In this case, Hispanic refers to patients of any race who select Hispanic ethnicity (so by default, all other categories are implicitly non-Hispanic). 

@rebexxxxxx please add this to the data dictionary change log

@sonyekere and @Davinkjohnson to please assign someone to program this on the back end

**Comment by mnataraj92** [comment]
> @mnataraj92 Is this change just for the Site defined race RcrtSI_Race_v1r0?

Yep, it'd need to be harmonized for the overall site race/eth variable!

**Comment by rebexxxxxx** [comment]
added to the DD change log!

**Comment by mnataraj92** [comment]
Concept IDs: 
"BSWH Reported Race/Ethnicity": "253532712"

723775357	0=White non-Hispanic
153444133	1=Black non-Hispanic
572474909	2=Hispanic/Latino
308427446	3=Asian
211228524	4=American Indian or Alaskan Native
277568192	5=Native Hawaiian or Other Pacific Islander
611398522	6=Multi-racial
181769837	55=Other
178420302	77=Unavailable/Unknown

**Comment by mnataraj92** [comment]
This variable has been added and tested, it is ready for prod
