### ISSUE TITLE
BPTL Home Collection Dashboard- FedEx label scanning issue (Biospecimen) (June Release)

### ISSUE THREAD

**Issue by erincschwartz** [episphere/connect#1033]
Programming was added in issue #988 in the May release to require double entry of the Return Kit Tracking Number on the Kit Assembly screen and double entry of the Supply Kit Tracking Number on the Kit Assembly screen. 

In production, it was discovered that the programming to truncate the FedEx tracking number that is applied to the original tracking number fields was not applied to the confirmation field, thus requiring manual deletion of the extra digits that precede the actual 12-digit tracking number: 

Kit Assembly: 

![Image](https://github.com/episphere/connect/assets/157617486/bd1f4bfc-6e9a-42a4-b8dc-e9fe3254d4f2)

Assign Kits: 

![Image](https://github.com/episphere/connect/assets/157617486/2301e3c7-a14c-42a0-bee0-5b3c7ab9a1d2)

We would like this corrected in the June release.

**Comment by amber-emmes** [comment]
Fix in place and PR created.

**Comment by amber-emmes** [comment]
Merged into dev and ready for testing.

**Comment by erincschwartz** [comment]
@amber-emmes Tested in Dev, ready for Stage

**Comment by erincschwartz** [comment]
Tested in Stage, ready for Prod

**Comment by wyattks** [comment]
Tested in Stage, ready for Prod
