### ISSUE TITLE
BSWH race/ethnicity var - add to SMDB bubble fields

### ISSUE THREAD

**Issue by robertsamm** [episphere/connect#1035]
The new BSWH race/ethnicity variable need to be added as a bubble field to the SMDB on the 'All Participants' page.

See: https://github.com/episphere/connect/issues/1028

**Comment by Gbarra9** [comment]
This is ready to be tested in dev. Refer to the last image below from the pull request:
- https://github.com/episphere/dashboard/pull/665#issue-2340989006

**Comment by mnataraj92** [comment]
BSWH race/ethnicity var looks good in the SMDB bubble fields in dev.

**Comment by Gbarra9** [comment]
> BSWH race/ethnicity var looks good in the SMDB bubble fields in dev. @Gbarra9 could you please move up the BSWH race/ethnicity bubble field to be next to the other race/ethnicity bubble fields?

This is merged to dev.

**Comment by robertsamm** [comment]
@Gbarra9 @mnataraj92 Looks good in dev, ready for stage! Thanks for making that update Gene.

**Comment by kmazzilli** [comment]
Looks good in stage, ready for prod
