### ISSUE TITLE
Race/Ethnicity Variable showing "Unavailable" in SMDB when it should be null

### ISSUE THREAD

**Issue by mnataraj92** [episphere/connect#1036]
When looking at the SMDB for BSWH and Sanford, the overall site race/ethnicity variable (state_d_849518448) is showing "unavailable/unknown" instead of null. BSWH and Sanford have their own race/ethnicity variables that are correctly being populated, but the overall site race/ethnicity variable should be null instead of unavailable/unknown for these sites. 

Here is an example for Sanford in dev for what the SMDB currently looks like:
![image](https://github.com/episphere/connect/assets/76711181/b196ebf0-0490-4880-a1da-087831e59661)

@sonyekere could you please assign someone to take a look at this?

**Comment by anthonypetersen** [comment]
@mnataraj92 @robertsamm fix pushed to dev

**Comment by mnataraj92** [comment]
Hi @anthonypetersen Thanks for looking into this! Confirmed that the "unavailable/unknown" does not show up anymore in the site overall race/ethnicity variable for BSWH, Sanford, and HFH. 

We did notice though that for BSWH, the site overall race/ethnicity variable shows as "other" sometimes when it should always be null. Could you please look into this?

**Comment by anthonypetersen** [comment]
@mnataraj92 those participants have that data in their record, so someone probably sent it

**Comment by mnataraj92** [comment]
@anthonypetersen thanks for the clarification! this looks good in dev!

**Comment by brotzmanmj** [comment]
Could be that happened before we put their BSWH-specific race/ethnicity variable into place. @mnataraj92  I suggest we just make sure when they test in stage next week they know not to send that variable and just send their own. Thanks.

**Comment by mnataraj92** [comment]
@brotzmanmj yes I think before we had the BSWH race/ethnicity var in place they sent the site overall race/ethnicity var to test. I will reiterate to them that they should just send their BSWH race/ethnicity var and not the overall site one.

**Comment by kmazzilli** [comment]
Checked in stage, the overall site one looks fine but the Sanford one is saying "Blank" sometimes
![Screenshot 2024-06-21 at 10 55 06 AM](https://github.com/episphere/connect/assets/40246056/ebf649e5-4653-4ecd-bf3a-67a993b38fad)

**Comment by sonyekere** [comment]
@kmazzilli Thank you for checking this in stage. @anthonypetersen this may be a small error . Madhuri noted that the data should not be stated as 'blank', but it can of course be displayed as blank

**Comment by anthonypetersen** [comment]
@kmazzilli @mnataraj92 per the data dictionary and our code, "Blank" is a valid response for Sanford Health reported race and is represented by Concept ID 986445321. Please let me know if this is no longer the case.

**Comment by mnataraj92** [comment]
@anthonypetersen yes you're correct. It slipped my mind that that response is just acceptable for the Sanford race variable. I think this should be fine then!

**Comment by sonyekere** [comment]
Fix is in Prod
