### ISSUE TITLE
Create UI to update/edit instant notification specs in SMDB

### ISSUE THREAD

**Issue by we-ai** [episphere/connect#1039]
Instant (client-side) email templates are moved to Firesotre in June (2024) release. UIs are needed for Ops team to easily update those instant notification specs when needed, similar to scheduled notification specs.

Related [issue](https://github.com/episphere/connect/issues/968) and [discussion](https://github.com/episphere/connect/discussions/812) can be found.

**Comment by we-ai** [comment]
Instant notifications (previously called "client-side emails" ) are triggered by actions in biospecimen site. Previously the instant notification email templates were part of biospecimen code base. After moving the 5 email templates to Firestore, biospecimen sites currently use category and attempt as filters to find the correct spec for instant notifications (emails).

Because of links of instant notification specs to biospecimen repo, a new instant notification spec should better be created by dev team when adding code handling the new spec. Also, since category and attempt fields of a spec need to match code fetching the spec in biospecimen repo, these 2 fields should better be updated (if needed) by dev team when making code updates.

So, the instant notification spec UI won't allow creating new specs. These fields can be updated/edited from the UI: description, email templates (English, Spanish). UI for SMS message templates can also be added if needed. With some updates, sending SMS messages together with emails is doable.

Let me know if you have questions or other requirements. @brotzmanmj @HanaShiho

**Comment by HanaShiho** [comment]
the team has decided this feature is no longer needed
