### ISSUE TITLE
HP - Token Workflow is not working as expected

### ISSUE THREAD

**Issue by dbakumar** [episphere/connect#104]
Its not honoring token (generated through batch process) we sent part of URL and asking PIN after email verification link clicked.  Also it assigned new token for that partcipant.    

Steps to recreate this issue.
Step 1 : 
The test patient received the below URL and completed signup. 
https://episphere.github.io/connectApp?token=0df789ef-2b31-4206-a502-324641dc71f9 

Step2. Home display the message to verify email and verify email sent

Step3 : The user clicked the link in email sent from NCI Connect Study.  

Step3 : Connect app launched and automatically signed in. 

**Step4 : Asking to enter PIN** 

**Step5: New Token assigned in background**

**Comment by bhaumik55231** [comment]
Hi @dbakumar, Thanks for reporting this bug. I have fixed it. Please try it out.

**Comment by dbakumar** [comment]
Great!.. Thanks, Its working good now.
