### ISSUE TITLE
Biospecimen Shipping Manifest Printing Issue

### ISSUE THREAD

**Issue by erincschwartz** [episphere/connect#1042]
On Friday, 6/14, KPHI reported that when using the Print Manifest button not all specimens were appearing on the Manifest. KPNW and Sanford (Fargo site only) also reported experiencing the same issue. Other sites, HP, UChicago, Sanford-Sioux Falls sites reported that their manifests printed as expected, no issues. 

It appears that updated versions of Chrome and Edge were released last week. In Dev, on a PC with most updated versions of both browsers, Print Manifest resulted in incomplete manifests, cutting off some of the specimens that should have been at the bottom of page 1 and top of page 2: 

![Image](https://github.com/orgs/episphere/projects/2/assets/157617486/b07f635a-94f6-4b06-8e27-c3b221124be6)

When using a Mac, with most updated versions of both browsers, all samples were included in the manifest: 

![Image](https://github.com/orgs/episphere/projects/2/assets/157617486/4ba44a6c-f630-49a1-b4b1-cc1bdd864a31)

The full manifest can be printed by selecting ctrl+A, ctrl+P while on the Box Manifest screen.

**Comment by we-ai** [comment]
Thanks you @erincschwartz for the info and screenshots. I'm adding software versions for troubleshooting.

In MacOS (version 14.5), manifest printing works normally with latest Edge (version 126.0.2592.61) and Chrome (version 126.0.6478.62) browsers.

In Windows 10 (version 22H2, OS build 19045.4412), manifest printing cuts off half page on each page, in latest Edge (version 126.0.2592.61) and Chrome (version 126.0.6478.115) browsers.

**Comment by we-ai** [comment]
Tested in dev. Ready for stage.

**Comment by we-ai** [comment]
The printing issue is fixed in prod.
