### ISSUE TITLE
Home mouthwash collection date and time persisting from previous entry in Kit Receipt (Biospecimen Dashboard) (July release)

### ISSUE THREAD

**Issue by erincschwartz** [episphere/connect#1043]
After receipting a kit into the Dashboard, the Collection Date and Time from Collection card that were entered for the kit previously receipted into the system carry over. This data should be cleared between entries. 

![Image](https://github.com/episphere/connect/assets/157617486/694ab28a-25b2-4078-b213-e6999ccf83dc)

**Comment by erincschwartz** [comment]
Tested in Dev, collection date and time cleared after saving. Ready for Stage.



![Image](https://github.com/episphere/connect/assets/157617486/5dc14425-e53e-437a-9a52-69d7870a2a37)

**Comment by erincschwartz** [comment]
Tested in Stage, ready for Prod.



![Image](https://github.com/user-attachments/assets/8c0197b3-63c2-4c36-8469-834ada43b2b0)

**Comment by sonyekere** [comment]
In production.
