### ISSUE TITLE
AppSettings: Add updatable app variables in firestore (for ConnectApp/Quest versioning). 

### ISSUE THREAD

**Issue by JoeArmani** [episphere/connect#1048]
Related: https://github.com/episphere/connect/issues/1066

AppSettings: Add updatable app variables in Firestore (for ConnectApp/Quest).

First use case: Enhance Quest fetching and versioning updates for ConnectApp.

With ongoing work in Quest, we need a more dynamic way to update Quest versions as they're released. These are not tied to PWA releases, and they need to be decoupled.

`getAppSettings` is a generalized function that introduces the `appSettings` collection in Firestore. Based on the stored value in Firestore, we can dynamically update the quest version in ConnectApp. This will have similar future use cases for dynamic in-app updates.

**Comment by JoeArmani** [comment]
ConnectApp PR ready for review: https://github.com/episphere/connectApp/pull/801
ConnectFaas PR ready for review: https://github.com/episphere/connectFaas/pull/612

**Comment by JoeArmani** [comment]
This is in dev and ready for testing.

Testing: we updated the loading process. It now uses Firestore for version tracking instead of GitHub. To test, please access all surveys and make sure they load as expected.

**Comment by brotzmanmj** [comment]
@JoeArmani should we test this for all surveys, English and Spanish?

**Comment by JoeArmani** [comment]
@brotzmanmj I'm realizing now that we need to test this in the stage environment because the Quest version we point to in dev is the working branch, which is not versioned with a number (e.g. 'v1.1.10').

We point to the production Quest version, which has a version number, in stage, prod, and local development, but not in the dev environment.

Once in stage, yes, I'm requesting they all be tested alongside the other English and Spanish survey testing. Successful survey load = successful test for this issue. Thanks.

**Comment by JoeArmani** [comment]
Edit: as I just realized above, this has to be tested in the stage environment because it impacts how the current version number is pulled and the dev environment is not versioned. See: https://github.com/episphere/questionnaire/blob/main/questVersions.js for versioning example

**Comment by brotzmanmj** [comment]
Hi Joe, adding @m-j-horner and @cunnaneaq here. It seems like this could be tested without any extra effort as part of the testing Marie Josephe and Aileen are doing to test the correct launch and stability of each of the survey versions for every survey in English and Spanish. However, if it can only be tested in stage then we will have to test in the short time we have (July 29-30). @m-j-horner please let us know if you have any concerns.

**Comment by m-j-horner** [comment]
@JoeArmani  @brotzmanmj  No concerns. 
It sounds like me & Aileen don't have to lay out a new testing plan. I will check that  the English/Spanish surveys are loading correctly in stage.

**Comment by JoeArmani** [comment]
Tested in stage, ready for prod.

**Comment by sonyekere** [comment]
In production.
