### ISSUE TITLE
Spanish Translation: Email Signature for Notifications

### ISSUE THREAD

**Issue by HanaShiho** [episphere/connect#1056]
The following sentence needs to be translated into Spanish for the email signature: "To unsubscribe from emails about Connect from the National Cancer Institute (NCI), click here. " This includes all the comms, including instant and scheduled notifications. See the screenshot. 
![image](https://github.com/episphere/connect/assets/148134271/8b9dbfaa-8a47-4d04-a062-e05b477d89e0)

**Comment by jhflorey** [comment]
@depietrodeanna @HanaShiho i found the solution for this issue. Please provide the Spanish content.

**Comment by depietrodeanna** [comment]
@jhflorey Spanish translation of unsubscribe prompt here:
 
Si desea darse de baja de Para cancelar la suscripción a los correos electrónicos sobre Connect del Instituto Nacional del Cáncer (NCI), haga clic aquí.

**Comment by HanaShiho** [comment]
tested in dev, ready for stage 
![image](https://github.com/user-attachments/assets/67f33eca-06b5-42fb-ae15-f5cabb9f2c0f)

**Comment by depietrodeanna** [comment]
@jhflorey My apologies, in reviewing this again, I recognized an error in the original phrase I provided. Corrected phrase below, please update in dev and we'll review again: 

Para cancelar la suscripción a los correos electrónicos sobre Connect del Instituto Nacional del Cáncer (NCI), haga clic aquí.

**Comment by jhflorey** [comment]
@depietrodeanna @HanaShiho Just updated. Please test it again.

**Comment by depietrodeanna** [comment]
Reviewed in dev and ready for stage @jhflorey 
<img width="1053" alt="Screenshot 2024-07-24 at 6 44 50 AM" src="https://github.com/user-attachments/assets/3cb3c274-e36b-4db3-9c48-ab14a471f9c8">

**Comment by HanaShiho** [comment]
Ready for prod
