### ISSUE TITLE
Spanish Translation: magic link emails for login 

### ISSUE THREAD

**Issue by HanaShiho** [episphere/connect#1057]
The default language for the magic link emails is currently English. We need to translate the email into Spanish. Jessica will require translations for 1) the subject line and 2) the body of the message so she can integrate it on her end. See the screenshot. 
![image](https://github.com/episphere/connect/assets/148134271/bf373b18-0d42-4540-989a-9ccbe601003c)

**Comment by sonyekere** [comment]
Hi! @HanaShiho @depietrodeanna  just to confirm, we do not have the translations needed just yet to begin working on this issue?

**Comment by jhflorey** [comment]
@depietrodeanna @HanaShiho i found the solution for this issue. Please provide the Spanish content.

**Comment by HanaShiho** [comment]
Thanks, @jhflorey! We'll update the content here when it's ready.

**Comment by depietrodeanna** [comment]
@jhflorey Spanish translation of this email:

**Subject Line:** 
 
Inicie sesión para Estudio Connect para la Prevención del Cáncer
 
**Body:**
 
Hola,
 
Recibimos una solicitud para iniciar sesión en el Estudio Connect para la Prevención del Cáncer usando esta dirección de correo electrónico. Si desea iniciar sesión con su cuenta [email address used to sign in], haga clic en este enlace:
 
Iniciar sesión para Estudio Connect para la Prevención del Cáncer: 
 
Si no solicitó este enlace, puede ignorar este correo electrónico de forma segura.
 
Gracias,
 
Su equipo del Estudio Connect para la Prevención del Cáncer
 
**Translation of unsubscribe prompt:**
 
Si desea darse de baja de Para cancelar la suscripción a los correos electrónicos sobre Connect del Instituto Nacional del Cáncer (NCI), haga clic aquí.

**Comment by HanaShiho** [comment]
Hi @jhflorey! I tested the magic link email in dev.  Spanish was selected in the dropdown in PWA (see the 1st screenshot); however, they got the sign-in email in English (2nd screenshot)
![image](https://github.com/user-attachments/assets/feb7afce-6310-4574-b0c7-ecf5f275baa3)
![image](https://github.com/user-attachments/assets/ac077e0f-30ef-40d4-b1e0-677c26361a1a)

**Comment by jhflorey** [comment]
@HanaShiho Just fixed it. Please check it again.

**Comment by HanaShiho** [comment]
Looks good, ready for stage

**Comment by depietrodeanna** [comment]
@jhflorey after clicking magic link in Spanish email, I see the "confirm email" screen in PWA still in English (it should be Spanish):
<img width="405" alt="Screenshot 2024-07-22 at 9 58 06 AM" src="https://github.com/user-attachments/assets/36e9079b-b500-4f5f-8d6d-4419a24735ef">

Is this work something that is under this GH issue? Or is it related to larger PWA Spanish work (Brian)?

**Comment by jhflorey** [comment]
> @jhflorey after clicking magic link in Spanish email, I see the "confirm email" screen in PWA still in English (it should be Spanish): <img alt="Screenshot 2024-07-22 at 9 58 06 AM" width="405" src="https://private-user-images.githubusercontent.com/74061787/351049819-36e9079b-b500-4f5f-8d6d-4419a24735ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NDA4ODEsIm5iZiI6MTcyMTc0MDU4MSwicGF0aCI6Ii83NDA2MTc4Ny8zNTEwNDk4MTktMzZlOTA3OWItYjUwMC00ZjVmLThkNmQtNDQxOWEyNDczNWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDEzMTYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZGQwMGVlODcyMmQ5YjliODc1OTE0ZDVjOWQ4ZWFhMmVlODczZGUzNWUxNWRmZmRlZjA3NjVkYmViYmIxNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dG0gjHte2El2C6JIWIklQ_Q8UttxpK53lQVDFj4qFNs">
> 
> Is this work something that is under this GH issue? Or is it related to larger PWA Spanish work (Brian)?

HI @bransteitterbr , please take a look at this issue.

**Comment by bransteitterbr** [comment]
@jhflorey  , @HanaShiho , @depietrodeanna This would probably fall under the umbrella of trying to get the firebase auth ui / sms messages work in Spanish.

**Comment by jhflorey** [comment]
@bransteitterbr could you handle this?

**Comment by HanaShiho** [comment]
@jhflorey @bransteitterbr can you please remind me whether this (i.e. "confirm email" being displayed in Spanish) would be part of the July release so I can confirm during stage testing today? Thank you!

**Comment by bransteitterbr** [comment]
@HanaShiho That screen is part of my ongoing work to update the firebase ui and will be part of the August release.

**Comment by HanaShiho** [comment]
Got it. Thanks for letting us know @bransteitterbr

**Comment by HanaShiho** [comment]
Ready for prod

**Comment by HanaShiho** [comment]
@jhflorey Note that we should do another round of testing in August to ensure that  the confirm email screen is displayed in Spanish where applicable.
