### ISSUE TITLE
Spanish Translation: SMS verification for login 

### ISSUE THREAD

**Issue by HanaShiho** [episphere/connect#1058]
For people who log in to PWA using their phone number, we want the sign-in text message translated into Spanish, if appropriate. @anthonypetersen mentioned this means the language they selected from the dropdown in PWA is set to Spanish, rather than depending on their preferred language per the signed consent form. Ops is okay with this approach, though it will require a PWA change by DevOps. We'd ideally like to have this ready for the July release; however, it can be pushed to the August release if needed.

**Comment by bransteitterbr** [comment]
In Dev ready for testing

**Comment by depietrodeanna** [comment]
Tested in Dev. Works as expected. Ready for stage

**Comment by sonyekere** [comment]
In Prod
