### ISSUE TITLE
case sensitive PINS

### ISSUE THREAD

**Issue by sarah-hague** [episphere/connect#106]
PINS are case sensitive, and it is not noted anywhere on that page. 

Additionally, since PINs will be used exclusively at our site, would it be possible to add a re-enter PIN field or a "Are you sure this is correct" when typing in the pin.  This would help with our verification process :)

**Comment by brotzmanmj** [comment]
I like the idea of adding a 're-enter PIN'  and think this is better than a "are you sure this is correct" question.

**Comment by sarah-hague** [comment]
In addition to above...this round of testing we had additional comments regarding the PINS.  Is the plan to always use upper case and have the field be case sensitive?  If so, could we use a font with the strike through the 0(zero) to help delineate the '0' and the 'O'.  If we plan to use lower case at all, we will need to think about upper case i (I) and lower case L (l) as those look the same.   Lastly, if we know pins will always be 6 characters, could we add a statement about this?   Our site's trigger for automated verification requires a PIN, so we want to make sure we make it as easily and obvious as possible for participants to enter their PINS correctly :)

**Comment by miagaudet** [comment]
HP requested "Would be nice if NCI PIN’s didn’t include zeros or the letter O as hard to distinguish." in aggregate issue #112 https://github.com/episphere/connect/issues/112.

**Comment by bhaumik55231** [comment]
> HP requested "Would be nice if NCI PIN’s didn’t include zeros or the letter O as hard to distinguish." in aggregate issue #112 #112.

I have modified PINs, it will not have 0 or O for newly requested PINs.

**Comment by bhaumik55231** [comment]
Closing this issue. Please re-open if needed.

**Comment by brotzmanmj** [comment]
Decision 3/4/21 to remove letter I and keep 1 and L. Newly generated pin will be a combination of any 6 characters from 123456789ABCDEFGHJKLMNPQRSTUVWXYZ

**Comment by depietrodeanna** [comment]
New language to be included as direction on page for entry of PINs: "If you received a PIN as part of your study invitation, please enter it here. Your PIN will be 6 characters and should include only uppercase letters."
