### ISSUE TITLE
Issues found in Dev testing Module 4 scenario #9 Spanish

### ISSUE THREAD

**Issue by joshid-ims** [episphere/connect#1061]
Testing document questions:

-Lines 35, 176, 190 and 240 have English response text. I assume those are typos but I figured I'd note them.
-In line 39, we answer NR for HOMEADD1_6 and HOMEADD2_6, I wouldn't expect to see HOMEADD3_6 based on the the document in Box:
image.png

However the testing document expects to see it. I figure that's a typo too.

-If I fill out some information in an ADD1 question like so:

![image](https://github.com/user-attachments/assets/31291024-3c12-4874-aea0-cd28f6fd7020)

and go next to get to an ADD2 question, I'll see this:

![image](https://github.com/user-attachments/assets/78852bf3-4cde-4339-a1c5-abd539dd18f6)

Should we still be able to fill out information for fields we've already responded to? I don't remember things working this way. The document seems to indicate this isn't the correct behavior:

![image](https://github.com/user-attachments/assets/4ef30927-d7e6-4315-9fe6-093f09e05e67)

-In this scenario, CURWORK11-13, CURSCHT3-CURSCHT5 and CURSCHT11-CURSCHT13 did not display. I tested this in our local renderer and they did display. IIs this PWA issue?

**Comment by boyd-mj** [comment]
@anthonypetersen do you need us to retest this using the updated internal testing link? Or were you able to reproduce the issue?

**Comment by anthonypetersen** [comment]
@boyd-mj @joshid-ims this should be resolved now, please confirm things look fine on your end before I close out this issue

**Comment by huip-ims** [comment]
@anthonypetersen Tony - So far, this is now working as expected in the renderer. We'll let you know if we see issues in Dev testing. Thanks!
