### ISSUE TITLE
Home mouthwash collection query changes- Biospecimen (August*)

### ISSUE THREAD

**Issue by erincschwartz** [episphere/connect#1063]
In the April release, https://github.com/episphere/connect/issues/960, we had the home mouthwash eligibility sort order updated to ascending order (oldest date/time stamp first).

Based on recent operational decisions, we would like the sort order flipped, to sort in **descending order** (most recent date/time stamp first).

We are also requesting that the query be updated to lag home mouthwash eligibility 5 days from date of dashboard entry of clincal blood/urine. 

At this time, it is not possible for us to send home mouthwash kits to participant's with PO box addresses. Please update the query to exclude any  participants with the word “Box” in line 1 or line 2 of the User Profile address.

**Comment by Gbarra9** [comment]
Note: Update query to exclude participants with "P.O. Box" in address line 1 and address line 2

**Comment by Gbarra9** [comment]
Merged to dev and in testing

**Comment by erincschwartz** [comment]
I have entered 3 clincial blood collections in order to work on this testing, however, the number of labels available to print remains at 0. @Gbarra9, any idea why the number here is not 3, as I would expect right now?
![image](https://github.com/user-attachments/assets/c4a4e7d8-5501-4c20-b986-b5e22f2b21a8)

**Comment by Gbarra9** [comment]
> I have entered 3 clincial blood collections in order to work on this testing, however, the number of labels available to print remains at 0. @Gbarra9, any idea why the number here is not 3, as I would expect right now? ![image](https://private-user-images.githubusercontent.com/157617486/359163069-c4a4e7d8-5501-4c20-b986-b5e22f2b21a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwODI2NjYsIm5iZiI6MTcyNDA4MjM2NiwicGF0aCI6Ii8xNTc2MTc0ODYvMzU5MTYzMDY5LWM0YTRlN2Q4LTU1MDEtNGMyMC1iOTg2LWI1ZTIyZjJiMjFhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQxNTQ2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjBlMzk4MjgyMGY1NmUxZmVmYzljZDJkZmFlMTFmZjQyZDEyNmY0MDY5MjI1ZDBlNmVhYzNmODdmNTQwYTdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hN99fMa2cyKNVSGPylTZ2L_mnGhdVtltlCPpp8pkn7U)

I think this might be due to the lag time condition. The condition excludes eligible mouthwash participants within the 5 day window (Current day to 5 days ago range). I used the blood or urine collected timestamp for this condition.

**Comment by erincschwartz** [comment]
@Gbarra9 Thanks for the reminder about the lag time. That part seems to be working! We can work together to appropriately backdate these entries.

**Comment by erincschwartz** [comment]
Tested in Dev, ready for Stage. 

- 5 day lag from collection to appearing on list for address printing tested and functioning 
- Most recent timestamps appears first, followed by next oldest timestamps on participant labels export spreadsheet
- Most recent timestamp appears at top of list, followed by next oldest timestamps on Assign Kit screen
- Participant with P.O. Box address does not appear in list of addresses available for printing

**Comment by erincschwartz** [comment]
The following Stage participants had clincial collections entered today, @Gbarra9, please back date them in order, with #1 having oldest date/time stamp 

1) Connect ID: 6618721881- blood collected
2) Connect ID: 6056450232- blood collected
3) Connect ID: 4130966470- urine collected
4) Connect ID: 5250803209- blood and urine collected  (set timestamp at just shy of 5 days ago, I will check to make sure they do not appear in the list, then we will set at 5 days, like we did in Dev testing)
5) Connect ID 5676354935 (address is PO Box, should not appear on the list)

**Comment by erincschwartz** [comment]
Stage testing is complete. Ready for Prod.

**Comment by Gbarra9** [comment]
Note: Regex matching used on eligible participants will be done for both the Print Labels and the Assign Kits page.

**Comment by erincschwartz** [comment]
Working on Dev testing now.

I changed address of 2 participants that were on the Assign Kits list already to PO box addresses (PO Box and PO Box 123). As expected, they fell off the list. Seems Regex matching is working for Assign Kits page.

I also entered clincal collections for the following:
**Connect ID 3519230792**  (changed address to pobox123)
**Connect ID 1353395415** (changed address to PO box) 
**Connect ID 1520977047** (no change to address; want to make sure this appears on the Assign Kits list) 
@Gbarra9, can you back date these collections >5 days so I can check if they appear in the Print Labels list?

**Comment by Gbarra9** [comment]
@erincschwartz The clinical collections have their dates changed and are ready.

**Comment by erincschwartz** [comment]
Tested in Dev, ready for Stage. 

All looks good, Connect IDs 3519230792 and 1353395415, with PO box addresses, did not appear in the Print Labels list (or, subsequently in the Assign Kits list) 

Connect ID 1520977047, which does not have PO box address, showed up in Print Labels and the Assign Kits list as expected. 

Out of curiosity, I changed address of Connect ID 3519230792 to a non-PO box address and they they appeared in the Print Labels and Assign Kits list. So, if participants update their User Profile in the future with an actual street address, they will be pulled into the queue for home mouthwash if eligible and previously excluded due to PO box address.

**Comment by Gbarra9** [comment]
> Out of curiosity, I changed address of Connect ID 3519230792 to a non-PO box address and they they appeared in the Print Labels and Assign Kits list. So, if participants update their User Profile in the future with an actual street address, they will be pulled into the queue for home mouthwash if eligible and previously excluded due to PO box address.

That is correct.

**Comment by erincschwartz** [comment]
Working on Stage testing now.

I changed address of 2 participants that were on the Assign Kits list already to PO box addresses (PO Box and PO Box123). As expected, they fell off the list. Regex matching is working for Assign Kits page in Stage. 

I also entered clincal collections for the following:
Connect ID 1316002636 (changed address to pobox123)
Connect ID 6549183613 (changed address to P.O. box)
Connect ID 1675561150 (no change to address; want to make sure this appears on the Assign Kits list)
@Gbarra9, can you back date these collections >5 days so I can check if they appear in the Print Labels list?

**Comment by Gbarra9** [comment]
@erincschwartz I changed the dates for these clinical accounts.

**Comment by erincschwartz** [comment]
Stage testing complete, ready for Prod,

All looks good, Connect IDs 1316002636 and 6549183613, with PO box addresses, did not appear in the Print Labels list (or, subsequently in the Assign Kits list)

Connect ID 1675561150 , which does not have PO box address, showed up in Print Labels and the Assign Kits list as expected.

Updated address for 6549183613 and they appeared in the Print Labels and Assign Kits lists.
