### ISSUE TITLE
Require reason not collected for Research Collections- Biospecimen (September/October)

### ISSUE THREAD

**Issue by erincschwartz** [episphere/connect#1065]
If site team member does **not** check that any of the blood, urine or mouthwash samples were collected In the Research Dashboard- Data Collection Entry screen, a Reason Not Collected should be required for that sample before the user is allowed to proceed to "Go to Review." 

![Image](https://github.com/user-attachments/assets/b074a808-4030-42e3-96a9-07f0c4711db0)

If a user attempts to "Go to Review," the same message should pop up briefly as when they attempt to move on without entering Specimen ID information, see below: 

![Image](https://github.com/user-attachments/assets/d3e40d82-7c82-47fd-8609-f97f476dfa77)

This message should appear in red text under each sample not collected where the Reason Not Collected is missing: "Reason Not Collected must be entered" and the box should be outline in red, in similar format to the following error: 

![Image](https://github.com/user-attachments/assets/cd3163b2-3c07-421c-a886-c8ae2eb7c55a)

**Comment by sonyekere** [comment]
In Dev and ready for testing

**Comment by erincschwartz** [comment]
Tested in Dev. New functionality worked as expected, example from testing below: 
![Image](https://github.com/user-attachments/assets/ce6cca74-1e12-4f89-880b-8811746037b6)

However, upon clicking 'Go to Review' this error message popped up. @amber-emmes also encountered this error in other testing today. After closing the error message pop up, I was able to select "Review Complete" and the collection was finalized (and moved into the Shipping Dashboard) 
![Image](https://github.com/user-attachments/assets/ce3c94b6-5f6f-4a9e-9d74-917923b22ec5)

**Comment by sonyekere** [comment]
Error has been fixed in Dev.

**Comment by erincschwartz** [comment]
Re-tested in Dev, Reason not collected functionality worked as expected and I was able to finalized without the error shown above appearing. 

**Ready for Stage.**

**Comment by erincschwartz** [comment]
**Tested in Stage, ready for Prod**


New functionality worked as expected, examples from Stage below.

Clicked "Go to Review" with collection/reason not collected data missing. This message popped up briefly and then went away, as expected: 
![Image](https://github.com/user-attachments/assets/028c2305-3de8-4a16-a34a-0d9965d72e6d)

Message that was hidden under pop up: 
![Image](https://github.com/user-attachments/assets/4919e325-a1ce-4f39-880b-b7ed53f859ae)
Tested for remaining blood tubes, urine and mouthwash, entering reason not collected one at a time and received the message in red for each specimen, as expected. Finalized the collection with no issues.
