### ISSUE TITLE
Quest Loading Updates for ConnectApp & ConnectFaas (July Release)

### ISSUE THREAD

**Issue by JoeArmani** [episphere/connect#1066]
This is a container for Quest-related updates in the July 2024 release.

AppSettings (link to issue with details):
https://github.com/episphere/connect/issues/1048

**Additional ConnectApp Items:**
Update the loading sequence to support Quest 2.0 changes
https://github.com/episphere/connectApp/pull/809

Fetch survey modules through the GitHub API
https://github.com/episphere/connectApp/pull/811

**Additional ConnectFaas Items:**
Fetch survey modules through the GitHub API
https://github.com/episphere/connectFaas/pull/623

**Comment by JoeArmani** [comment]
These updates are in dev and ready for testing.

Testing:
These updates all improve robustness in the Quest loading process across various systems.
Successful test:
•Load survey working as expected
•Continue survey working as expected

This can all be tested alongside Spanish updates.
Note: AppSettings can only be tested in stage due to the loading setup. Other updates should be tested in dev and stage.

**Comment by JoeArmani** [comment]
This has been tested in dev (alongside Spanish testing). Ready for stage.

**Comment by JoeArmani** [comment]
Tested in stage, ready for prod.

**Comment by sonyekere** [comment]
In production.
