### ISSUE TITLE
Post Question Button Order Changes After  Grids on Small Devices

### ISSUE THREAD

**Issue by woodruffr** [episphere/connect#1068]
This was noticed in Dev testing Spanish Module 2 Scenario 3 with an Android phone with Edge and testing Spanish Module 4 Scenario 11 with an Android phone and Chrome.

Generally, the navigation button after a question are in this order: Siguiente, Restablecer Respuesta, and Atrás.

![image](https://github.com/user-attachments/assets/9b973fce-1645-4998-9157-fb779b8c248b)

On small devices, after Grids, they are in inverse order.

![image](https://github.com/user-attachments/assets/4947234a-f046-4ad4-9cfc-825df454dcb0)

**Comment by woodruffr** [comment]
I don't have the option to Assign, so will tag here. @anthonypetersen @m-j-horner

**Comment by cusackjm** [comment]
We are aware of this issue and have it documented in another issue- it likely will be addressed at a later date.
