### ISSUE TITLE
Skip Pattern Issues

### ISSUE THREAD

**Issue by woodruffr** [episphere/connect#1069]
While testing the Spanish Module 4 multiple scenarios (9 on a PC with Firefox, 11 on an Android phone with Chrome, 10 on a Mac and Chrome), these questions were not present:
CURWORKT3-5, CURWORKT11-13, CURSCHT3-5, and CURSCHT11-13. This issue was originally mentioned in https://github.com/episphere/connect/issues/1061, but was dropped.  It is still an issue.

While Dev testing @cunnaneaq created Questionnaire Github Issues for these wherein questions that should be displayed are not:
https://github.com/episphere/questionnaire/issues/399
https://github.com/episphere/questionnaire/issues/400
https://github.com/episphere/questionnaire/issues/401

**Comment by boyd-mj** [comment]
@anthonypetersen could you please take a look at this? 

FYI @cusackjm & @m-j-horner

**Comment by boyd-mj** [comment]
@anthonypetersen @cusackjm any progress on this? This is the only issue preventing us from completing dev testing and delivering M4. Thanks.

**Comment by anthonypetersen** [comment]
I'll take a look today

**Comment by anthonypetersen** [comment]
@boyd-mj this should be resolved now
