### ISSUE TITLE
Safari email magic link issues

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connect#1070]
In Safari desktop, entry of email requires specific behavior that may not be intuitive to participants. Magic link email may not be received if the entry is done incorrectly. The outcome is inconsistent- sometimes it works and sometimes it doesn't (repeatedly) if cursor is still in text box with email. 

When you type in the email address, you have to click out of the text box first and then click next with your mouse (don't hit enter). If you hit enter while your cursor is still in the text box, you don't see the magic link email and this is what appears:

<img width="462" alt="Screenshot 2024-07-24 at 6 33 08 AM" src="https://github.com/user-attachments/assets/b860b9ab-60cc-467f-bd5d-925c395125d6">

If you recently signed into MyConnect with a different email on the same device and are trying to enter a separate email into the PWA to login but don't click cursor out of the text box, the other thing that may happen is the magic link may be sent to the previously entered email (not the email you just entered). This is glitchy and especially concerning for the shared devices. Caching issue?

**Comment by jhflorey** [comment]
@depietrodeanna this issue has been fixed. Please try in dev.

**Comment by depietrodeanna** [comment]
tested and works as expected in dev @jhflorey

**Comment by sonyekere** [comment]
Deanna confirmed - ready for stage
