### ISSUE TITLE
e-consent screens dev & stage (android, chrome & iPhone, Safari) seeing code

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connect#1071]
When going through the e-consent screens in MyConnect dev & stage on an android in Chrome and an iPhone in Safari (in English & Spanish), I noticed that there's code showing up.  Please see the screenshot below.  I don't see this on my Macbook in Chrome.

![Screenshot_20240723_184056_Chrome](https://github.com/user-attachments/assets/18aebcf5-f0a7-4db5-b336-24db9277cc1d)

**Comment by sonyekere** [comment]
Thanks Aileen for noting this in an issue. We'll look into this shortly.

**Comment by cunnaneaq** [comment]
looks good in stage - ready for prod

**Comment by sonyekere** [comment]
In production.
