### ISSUE TITLE
Fall 2024 eNewsletter - September Testing

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#1072]
Placeholder for the requirements of the upcoming Fall 2024 eNewsletter. The timeline for sending it to participants is early to mid-October, which means testing will largely occur in September.

**Comment by sonyekere** [comment]
Hi Team! I want to note that this item is not tied to the release. My current understanding is that @jhflorey  will not be programming or making any code changes for the September release. However, @depietrodeanna /@HanaShiho  will be testing the html and will loop in Jessica mid September if needed. Please confirm if this is the case and please add additional requirements as needed.

**Comment by depietrodeanna** [comment]
Content for testing @HanaShiho and @jhflorey:

Newsletter blurbs and associated graphics for each section, to be filled into the html template for email that we've used in the past. You can create a new html content template based on the last newsletter. Note for Jessica- "Read more" in each section should be hyperlinked to the public facing website but I don't have those exact links for you yet.

**What’s New**
At the milestone of 50,000 participants, Connect Senior Scientist, Mia Gaudet, Ph.D. reflects on the path that brought her to Connect and provides insight into her daily responsibilities overseeing the operations of the study at the National Cancer Institute's Connect Coordinating Center. [Read more]

Image: https://nih.app.box.com/file/1654448485567

**In the Spotlight**
Connect Study Manager at Henry Ford Health (HFH), Kirsti Autio, shares how being a trusted partner with the National Cancer Institute, HFH patients, and community members can help shape the future of cancer prevention. [Read more]

Image: https://nih.app.box.com/file/1656167284551

**Did You Know**
Returning results is a way to share valuable insights with Connect participants who share their information with us. It also helps participants learn about the work researchers are doing. Connect is going to begin by sharing individual level physical activity results and information through MyConnect. [Read more] 

Image: same one as always: https://nih.app.box.com/file/974705920135?s=ni0cpwnyafrs919quvg4vksiwgr2ndkl

**Comment by depietrodeanna** [comment]
@jhflorey @HanaShiho Spanish content for testing:

Newsletter blurbs and associated graphics for each section, to be filled into the html template for email that we've used in the past. You can create a new html content template based on the last newsletter. Note for Jessica- "Seguir
leyendo" in each section should be hyperlinked to the public facing website but I don't have those exact links for you yet. This means "read more."

**Novedades**
Tras alcanzar el hito de 50.000 participantes, la Dra. Mia Gaudet, científica sénior de Connect, reflexiona
sobre cómo llegó a Connect y da detalles sobre sus responsabilidades diarias en la supervisión de tareas
del estudio en el Centro de Coordinación de Connect del Instituto Nacional del Cáncer. [Seguir leyendo]

Image (three different sizes here:) https://nih.app.box.com/folder/287243819182

**En primer plano**
Kirsti Autio, administradora del estudio de Connect en Henry Ford Health (HFH), nos cuenta cómo el
mantener una relación colaborativa de confianza con el Instituto Nacional del Cáncer, los pacientes de
HFH y los integrantes de la comunidad puede darle forma al futuro de la prevención del cáncer. [Seguir
leyendo]

Image: https://nih.app.box.com/file/1656167284551

**¿Sabía que…?**
Devolver resultados de investigación es una forma de compartir información valiosa con los
participantes de Connect que comparten su información con nosotros. También ayuda a los
participantes a conocer el trabajo que están haciendo los investigadores. Connect comenzará por
compartir información personal de actividad física a nivel individual mediante MyConnect. [Seguir
leyendo]

Image: https://nih.app.box.com/file/1661626873884

**Comment by jhflorey** [comment]
@depietrodeanna @HanaShiho these below images are the new content english fallnewsletter 2024. Please check it and let me know if there is any update needed.

<img width="470" alt="image" src="https://github.com/user-attachments/assets/c2208fa9-014f-4b3b-9ed6-fdd968046e82">
<img width="472" alt="image" src="https://github.com/user-attachments/assets/1117300f-4e8a-4e55-ae67-1d19978a193f">

**Comment by jhflorey** [comment]
@depietrodeanna Please provide the spanish text for this paragraph.

<img width="658" alt="image" src="https://github.com/user-attachments/assets/49bdab69-2fcb-48b2-9d7d-4cdd614f9bf6">

**Comment by depietrodeanna** [comment]
@jhflorey will do. For the footer of the email, content and hyperlinks translated into Spanish are below the English image:
<img width="490" alt="Screenshot 2024-10-16 at 10 37 28 PM" src="https://github.com/user-attachments/assets/d480f3cc-6eb4-48cc-8d0f-88ce5ec5092d">

Connect for Cancer Prevention Study, el logotipo de Connect for Cancer Prevention Study y “Connect today. Prevent cancer tomorrow” son marcas comerciales del Departamento de Salud y Servicios Humanos de los Estados Unidos (HHS).

[Departamento de Salud y Servicios Humanos de los Estados Unidos (HHS) (en inglés)](http://www.hhs.gov/) 
[Institutos Nacionales de la Salud](https://salud.nih.gov/) 
[Instituto Nacional del Cáncer](https://www.cancer.gov/espanol) 
[USA.gov en español](https://www.usa.gov/es/)

**Comment by depietrodeanna** [comment]
@jhflorey there is a missing "the" in the English paragraph under the 50,000 participants graphic (my apologies for missing this in the content provided):
<img width="696" alt="Screenshot 2024-10-18 at 8 33 50 AM" src="https://github.com/user-attachments/assets/713169da-98c6-4da6-baa5-b9c49455dced">

could you add a "the" before "study" in this line?

**Comment by jhflorey** [comment]
> @jhflorey there is a missing "the" in the English paragraph under the 50,000 participants graphic (my apologies for missing this in the content provided): <img alt="Screenshot 2024-10-18 at 8 33 50 AM" width="696" src="https://private-user-images.githubusercontent.com/74061787/377927762-713169da-98c6-4da6-baa5-b9c49455dced.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MTgyNDAsIm5iZiI6MTcyOTUxNzk0MCwicGF0aCI6Ii83NDA2MTc4Ny8zNzc5Mjc3NjItNzEzMTY5ZGEtOThjNi00ZGE2LWJhYTUtYjljNDk0NTVkY2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDEzMzkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MjdmMjAyOGMzNDc4MDMzYjMzZDRiOTgxZmMyNTBmN2E0NDNkMWEwNGNmNWY1ZGMxYTZkNzY2NGE5YjdiZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Fh9AQkpZKMO52nlmlx9Ed1lzYBl9jFbCOg7ZEMKL2a0">
> 
> could you add a "the" before "study" in this line?

@depietrodeanna Please confirm whether it matches your expectations.
<img width="705" alt="image" src="https://github.com/user-attachments/assets/c44ee0fe-11f5-4a3a-802f-4d53c98a0321">

**Comment by depietrodeanna** [comment]
Thanks Jessica, looks good @jhflorey

**Comment by depietrodeanna** [comment]
@jhflorey Read more hyperlinks for English:

What's New: https://www.cancer.gov/connect-prevention-study/news/senior_scientist
Spotlight: https://www.cancer.gov/connect-prevention-study/news/kirsti-autio 
Did You Know: https://www.cancer.gov/connect-prevention-study/return_results

These links won't work until I publish the content when the newsletter goes live. 

Note that the view in browser will also need to be updated. 

Sending Spanish links next.

**Comment by depietrodeanna** [comment]
@jhflorey  Spanish hyperlinks:

What's New: cancer.gov/connect-prevention-study/espanol/noticias-del-estudio/científica-sénior 
Spotlight: cancer.gov/connect-prevention-study/espanol/noticias-del-estudio/kirsti-autio 
Did You Know: cancer.gov/connect-prevention-study/espanol/noticias-del-estudio/devolver-resultados

**Comment by depietrodeanna** [comment]
Hi @jhflorey sorry for the last minute change. We are revising the graphic that shows the enrollment metric. Please replace the graphic in the html with these for English and Spanish.

We can just test in stage, no need to repeat in dev. Hana, please update both sets of specs when Jessica updates the html. Thank you Jessica! 

![50k graphic English update](https://github.com/user-attachments/assets/0ab71ed7-cf13-4687-a0ff-ece4558b4513)
![50k graphic update Spanish](https://github.com/user-attachments/assets/eac74540-e104-4585-a234-d15e0a9b1746)

**Comment by depietrodeanna** [comment]
Also uploaded these to Box: https://nih.app.box.com/folder/290598167582

**Comment by depietrodeanna** [comment]
tested in stage. ready for prod
