### ISSUE TITLE
2024 Connect Experience Survey requirements

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#1073]
The revised requirements for the 2024 Connect Experience Survey (formerly known as the Participant Experience Survey) have been posted to Box. 
https://nih.app.box.com/file/1253587581669 

This is planned for the **September** prod release though some work will begin in August. 
Please review the requirements and the tasks list below.

During August, tasks are:
(1) IMS re-programming and testing in English (Marie Jospehe coordinating) - continue in Sept as needed
(2) Spanish translation of the survey (Deanna coordinating) - DONE
(3) IRB submission of the Spanish survey (Kaitlyn coordinating) - SUBMITTED
(4) IMS programming and testing of the Spanish version (Marie Josephe coordinating) continue in Sept as needed
(5) Comms team draft email and SMS communications and request Spanish translation (Hana and Deanna coordinating) - in progress, continue in Sept as needed
(6) Spanish translation of the survey description to appear on the PWA (Deanna coordinating)- DONE, in comment below

During September, tasks are:
(1) Create the variables that will be needed and leave them null until the Sept release (Madhuri coordinating)
(2) Create query to identify eligible participants, and prepare to set survey status to not started for them (final query will be run right before launch)
(3) PWA- add survey, include survey description in English and Spanish
(4) SMDB- update Participant Summary page to include survey
(5) Metrics and QC - update
(6) Email and SMS notifications- add to SMDB and test

**Comment by depietrodeanna** [comment]
Description of survey on PWA:

English: **Questions about your experience with Connect and your preferences for completing study activities, using MyConnect, and getting messages.**
Spanish: **Preguntas acerca de su experiencia con Connect, y sus preferencias para realizar actividades del estudio, utilizar MyConnect, y recibir mensajes.**

**Comment by cunnaneaq** [comment]
Title of the survey (Spanish updated 9/9/24 via email with translator)

**English**: 2024 Connect Experience Survey
**Spanish**: 2024 Encuesta Sobre Experiencia de Connect

**Comment by mnataraj92** [comment]
Concept IDs for new variables: 

 2024 Connect Experience Survey Status (SrvCoE_ConExpStatus_v1r0; CID d_956490759)

 Autogenerated date/time stamp for Start of 2024 Connect Experience Survey (SrvCoE_ConExpTmStart_v1r0; CID d_263355177)

 Autogenerated date/time stamp for Completion of 2024 Connect Experience Survey (SrvCoE_ConExpTmCompl_v1r0; CID d_199471989)

 Refused 2024 Connect Experience Survey (HdRef_2024ConExpSrv_v1r0; CID d_685002411_d_101763809)

 Refused All future Connect Experience surveys (HdRef_AllFutConExpSrv_v1r0; CID d_685002411_d_525277409)

 Autogenerated date/time for Refused 2024 Connect Experience Survey (HdRef_2024ConExpSrvDt_v1r0; CID d_688172931)

 Autogenerated date/time for Refused All future Connect Experience surveys (HdRef_AllFutConExpSrvDt_v1r0; CID d_182718292)

**Comment by brotzmanmj** [comment]
For the new refusal variables Madhuri listed above related to the Connect Experience Surveys, we need those to be added to the SMDB refusal/withdrawal page so NORC can record them as needed. For whomever is doing the work on the SMDB portion of this task, can that be included? Sorry I had not noticed that was not specifically listed as a task until now.

**Comment by sonyekere** [comment]
@bransteitterbr Quick question, were you planning to add refusal variables Madhuri listed above to the SMDB refusal/withdrawal page? Please refer to the above message for context.

**Comment by bransteitterbr** [comment]
@mnataraj92 I am missing one concept id.  I need one to store the version of the experience survey that is started.

**Comment by bransteitterbr** [comment]
@cunnaneaq and @depietrodeanna Do we know when the English version of the survey is going to be loaded to the questionnaire project?

**Comment by cunnaneaq** [comment]
@bransteitterbr then plan is early this week

**Comment by lorszag** [comment]
@brotzmanmj here is initial list of eligible dev participants. Confirmed with Jake it was okay to send directly. 
@jacobmpeters @FrogGirl1123 

Here is the list of connect IDs eligible. Let me know if you want this list delivered in another format? https://app.box.com/s/7jzm82nqdbtnbi14ns40c84uebaoke3u

Code below if anyone from DevOps wants to review.

```sql
SELECT Connect_ID
FROM `nih-nci-dceg-connect-dev.FlatConnect.participants_JP`
WHERE d_821247024 = "197316935"                             -- RcrtV_Verification_v1r0 = 1
  AND (CAST(LEFT(d_914594314,10) as DATE))>= '2024-03-01'   -- RcrtV_VerificationTm_V1R0 >= 3/1/2024
  AND (CAST(LEFT(d_914594314,10) as DATE))<= '2024-07-31'   -- RcrtV_VerificationTm_V1R0 <= 7/31/2024
  AND d_747006172 = "104430631"                             -- HdWd_WdConsent_v1r0 = 0
  AND d_906417725 = "104430631"                             -- HdWd_Activepart_v1r0 = 0
  AND d_685002411_d_867203506 = "104430631"                 -- HdRef_Allsrv_v1r0 = 0
  AND d_987563196 = "104430631"                             -- HdWd_Deceased_v1r0 = 0
```

**Comment by brotzmanmj** [comment]
Hi @lorszag and @jacobmpeters  Thanks for the list of those who are eligible. Do you also have people in dev who are ineligible (at least one who is ineligible per each of the criteria just to make sure the correct people are being excluded)?

**Comment by brotzmanmj** [comment]
Hi @lorszag This is very helpful. @mnataraj92 I think we should add at least one person to dev who would be excluded for each of the two reasons Leila pointed out that we don't have covered. They would need to meet all other criteria so you'd need to ask Gene to backdate the date of verification to between 3/1/24 and 7/31/24.  Can you coordinate this? And per your testing plan, are we missing participants for any other scenario?

**Comment by mnataraj92** [comment]
Hi @brotzmanmj those scenarios are already in the test plan. I believe we have all scenarios included but if you think any are missing please let me know! https://nih.app.box.com/file/1644382823692. @cunnaneaq has already created the test pts and Gene has verified them.

**Comment by mnataraj92** [comment]
> @mnataraj92 I am missing one concept id. I need one to store the version of the experience survey that is started.

@bransteitterbr I added this to the data dictionary, once a concept ID is assigned I will let you know!

**Comment by brotzmanmj** [comment]
> Hi @brotzmanmj those scenarios are already in the test plan. I believe we have all scenarios included but if you think any are missing please let me know! https://nih.app.box.com/file/1644382823692. @cunnaneaq has already created the test pts and Gene has verified them.

HI @mnataraj92 please see the two criteria above that have no participants associated with them in dev. If those participants do exist in dev, please check with Leila as to why they aren't appearing in her counts. Thanks.

**Comment by mnataraj92** [comment]
@brotzmanmj the refusals/withdrawals have not been pushed yet for the test scenarios, the participants have just been verified (nor not verified) accordingly. I can let Leila know when the refusals/withdrawals have been pushed.

**Comment by mnataraj92** [comment]
@bransteitterbr the GitHub/Survey Version for Connect Experience is d_905236593

**Comment by mnataraj92** [comment]
@lorszag Aileen pushed the refusals in dev so you should hopefully see pts for those 2 scenarios

**Comment by lorszag** [comment]
@mnataraj92 I am still getting null results when I run the following:

```sql
SELECT Connect_ID
FROM `nih-nci-dceg-connect-dev.FlatConnect.participants_JP` 
WHERE d_685002411_d_867203506 != "104430631" 
```

and
```sql
SELECT Connect_ID
FROM `nih-nci-dceg-connect-dev.FlatConnect.participants_JP` 
WHERE d_906417725 != "104430631" 
```

meaning within these datasets there are no participants that meet these filters. I tried checking directly by connect_id listed in row 8 [here](https://nih.app.box.com/integrations/officeonline/openOfficeOnline?fileId=1644382823692&sharedAccessCode=) but it what is in dev for that participant doesn't seem to match the spreadsheet

**Comment by mnataraj92** [comment]
Hmm that's strange. I just confirmed that those refusals/withdrawals were pushed in the SMDB in dev and checked BQ in dev as well. Could you try running your queries again? I ran

SELECT d_685002411_d_867203506 FROM `nih-nci-dceg-connect-dev.FlatConnect.participants_JP` 
WHERE Connect_ID = "5772421724" and it showed that d_685002411_d_867203506 = yes. And when I run your query 
SELECT Connect_ID
FROM `nih-nci-dceg-connect-dev.FlatConnect.participants_JP` 
WHERE d_685002411_d_867203506 != "104430631" 
I'm seeing the correct Connect ID pop up (5772421724)

**Comment by lorszag** [comment]
@mnataraj92 now it's working! I will upload new file to the box (linked [here](https://nih.app.box.com/file/1654352975937?s=i1jtf3opxbgvbf0byfyo24u5bucjtj72))

**Comment by jacobmpeters** [comment]
@lorszag Just wanted to provide some insight into why it wasn't working before 9:30AM, but worked for you after 9:30 AM because there is some magic happening behind the scenes...

The updates to the data were made last night in Firestore, but the data in the FlatConnect dataset are not updated until after 9:30 AM when the flattening process runs. 

If something like this happens again, you can confirm in the details tab for the table of interest in BQ. If you need it updated or are curious about the timing, feel free to reach out to me. I can force the flattening to occur earlier if needed.

Let me know if you have questions.

<img width="400" alt="Screenshot 2024-09-24 at 9 54 38 AM" src="https://github.com/user-attachments/assets/aabe30fb-4dcb-4b79-99d2-bba472eda5da">

**Comment by depietrodeanna** [comment]
@bransteitterbr for the survey time estimate for completion that appears within the survey description, please update the time estimate to 15-20 minutes (for English): 
<img width="962" alt="Screenshot 2024-09-30 at 2 07 50 PM" src="https://github.com/user-attachments/assets/68c13c2b-9876-4f9e-8e1d-6f32b2e635e4">

and "De 15 a 20 minutos" for Spanish:
![image](https://github.com/user-attachments/assets/91c3b696-bd8d-4016-8d6e-aebc79021db2)

**Comment by amber-emmes** [comment]
Brian is still on PTO; I'll grab these.

**Comment by amber-emmes** [comment]
Updated in dev.

**Comment by cunnaneaq** [comment]
Looks good in dev

![Screenshot 2024-09-30 at 2 59 51 PM](https://github.com/user-attachments/assets/de427aa0-eda5-4292-8c5b-c8bfbb9a19ab)
![Screenshot 2024-09-30 at 3 00 35 PM](https://github.com/user-attachments/assets/4545f890-51da-475f-aee4-35c9a7377ed5)

**Comment by amber-emmes** [comment]
Now also in stage.

**Comment by cunnaneaq** [comment]
Looks good in stage

![Screenshot 2024-09-30 at 3 18 22 PM](https://github.com/user-attachments/assets/f42b0516-4419-45ce-b7ed-8238d313cecc)
![Screenshot 2024-09-30 at 3 18 33 PM](https://github.com/user-attachments/assets/e5af7b96-3c59-43f8-88c2-0edb15d3ef98)

**Comment by mnataraj92** [comment]
@amber-emmes On the SMDB participant summary page for timeline, similar to the 3-mo QOL survey status, the timeline for the 2024 Connect Experience Survey also says "Follow up 3-mo". It should say "Cross-Sectional 2024" instead.

**Comment by amber-emmes** [comment]
Now in dev; please review and confirm and I'll get it out to dev.

**Comment by amber-emmes** [comment]
Should now also be in stage.

**Comment by mnataraj92** [comment]
Looks good in stage!

**Comment by sonyekere** [comment]
In Prod
