### ISSUE TITLE
User Profile - email and/or phone required

### ISSUE THREAD

**Issue by sarah-hague** [episphere/connect#108]
When completing the user profile, it is not clear that a phone number OR email are required.  Users get an error if they don't complete, but could a note be made that one of these is required on the initial screen?

**Comment by choimichelle** [comment]
Also, there is no asterisk (*) by either of the boxes so it looks like they are no required.

**Comment by brotzmanmj** [comment]
changed requirement so an email is always required and one phone number is required (of any kind, does not have to be mobile). this issue no longer relevant.
