### ISSUE TITLE
Populate Preferred language when a participant signs in

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/connect#1088]
This is in relation to issue https://github.com/episphere/connect/issues/1085

In order to backfill data, we'll need to add logic which populates a participant's preferred language if the participant is consented and the variable is currently null. (possibly within the "check derived variables" code)

**Comment by anthonypetersen** [comment]
@KELSEYDOWLING7 to confirm, this flag should be set on the participant table?

**Comment by KELSEYDOWLING7** [comment]
@anthonypetersen d_255077064 is in the participants table, yes

**Comment by anthonypetersen** [comment]
@KELSEYDOWLING7 so are we basically saying, anyone that is consented that doesn't have a preferred language set it to English?

**Comment by KELSEYDOWLING7** [comment]
@anthonypetersen  Correct

**Comment by anthonypetersen** [comment]
@KELSEYDOWLING7 this is done in Firestore, please let me know when you confirm in BQ

**Comment by KELSEYDOWLING7** [comment]
@anthonypetersen  Still seeing null values in all 3 environments' raw participants tables. I'll check again at the end of the day

**Comment by anthonypetersen** [comment]
@KELSEYDOWLING7 this has been resolved for prod specifically, I can run on stage and dev later. I'm running the below query in prod and no results are returning

`SELECT Connect_ID FROM `nih-nci-dceg-connect-prod-6d04.Connect.participants`
where d_255077064 is null and d_454445267 is not null

 LIMIT 1000`

**Comment by KELSEYDOWLING7** [comment]
@anthonypetersen Just refreshed and now it looks as expected!

**Comment by anthonypetersen** [comment]
@KELSEYDOWLING7 should be good on all tiers now, might need to wait for BQ to sync
