### ISSUE TITLE
Supply Kit and Return Kit- Consistency check and force uppercase- Biospecimen (September release)

### ISSUE THREAD

**Issue by erincschwartz** [episphere/connect#1089]
Our QC report recently flagged a case where the Return Kit ID was entered into the Dashboard with lower case "c" and the Supply Kit was entered with uppercase "C," thus the two did not match. 

Please update programming to force all alpha characters to uppercase, even if entered in lowercase. 

Also, please note in re-creating this issue in Dev, it looks like even when the error message appears due to the case sensitivity, the system still allows you to move forward, when clicking "Save & Next" and creates the kits with the mismatched IDs 

![Image](https://github.com/user-attachments/assets/5bf81dbe-3361-4cea-90e4-9cef5b81ab30)

![Image](https://github.com/user-attachments/assets/4b7fd1c6-7274-4295-9a8a-e60aa4b2846b)

I also tested this scenario and found the same when using completely different Supply Kit and Return Kit IDs. 

![Image](https://github.com/user-attachments/assets/d9890e02-a63f-4b6f-9720-509ba7b7c681)

![Image](https://github.com/user-attachments/assets/9b5e6c4f-901b-4298-9eba-1810e0c4824d)

**Comment by amber-emmes** [comment]
To be clear, is this ticket also requesting that we add validation to ensure that the Supply Kit ID and Return Kit ID match? If so, should similar validation be added for the Cup ID and Card ID?

**Comment by amber-emmes** [comment]
Both the front end and back end work enforcing this validation are in dev and ready to be tested.

**Comment by erincschwartz** [comment]
@amber-emmes This is looking pretty good.

- Confirmed that even when entering lowercase characters (ch and cha), the system now forces them to be uppercase 
- System is now prohibiting Kit Assembly when Supply Kit and Return Kit IDs don't match  

![image](https://github.com/user-attachments/assets/b2f96374-e748-4e7e-b024-cee7c53e07a0)

-System is also prohibiting Kit Assembly when Cup and Card IDs don't match. 

![image](https://github.com/user-attachments/assets/9d73389f-3614-41f1-8c64-d66ecba05216)

 Is there any way to get the error message to go away when the FNL team member removes the mismatching information? Or will this persist until they click the X to close the error message?

![image](https://github.com/user-attachments/assets/b60da7fa-4d23-4097-bdad-d1f01914d051)


The presence of this error message, even when the correct information is entered may be confusing: 
![image](https://github.com/user-attachments/assets/2c6b3fca-68af-4702-b0a9-12bcfdc193bb)

**Comment by amber-emmes** [comment]
Currently, the error message will persist until the x is clicked. I am not aware of any other way to close it.

**Comment by erincschwartz** [comment]
We will inform the FNL team that they need to close the error message by clicking the X. 

This is ready for Stage.

**Comment by erincschwartz** [comment]
Tested in Stage, Ready for Prod

- Confirmed that even when entering lowercase characters (ch and cha), the system now forces them to be uppercase in Stage
- System is now prohibiting Kit Assembly when Supply Kit and Return Kit IDs don't match in Stage
- System is also prohibiting Kit Assembly when Cup and Card IDs don't match in Stage
