### ISSUE TITLE
My Samples Page Changes - UChicago 

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#1091]
Placeholder, requirements will be added.

**Comment by depietrodeanna** [comment]
Tracked changes here @sonyekere: https://nih.app.box.com/file/1601424272908

**Comment by depietrodeanna** [comment]
Spanish version- does NORC need to supply updated json for the UC My Samples? This is only a deletion of information, which I can ensure looks correct in Spanish/point you to the right language to remove @bransteitterbr but I'm now thinking you will need a json anyway. Let me know and I can get from NORC fairly quickly

**Comment by jhflorey** [comment]
@depietrodeanna My code changes are ready in dev. Please check it.

**Comment by depietrodeanna** [comment]
ready for stage

**Comment by depietrodeanna** [comment]
Tested in stage ready for prod
