### ISSUE TITLE
PROMIS Survey Not Moving to "Completed" Tab in PWA Once Submitted

### ISSUE THREAD

**Issue by mnataraj92** [episphere/connect#1103]
During the PROMIS survey trigger testing in Dev, we noticed that once the PROMIS survey was submitted, it would disappear from the "to do" list in the PWA; it would not move to the "Completed" tab as expected. 

@sonyekere could you please assign someone to look into this?

**Comment by jhflorey** [comment]
@mnataraj92 @HanaShiho It's been fixed. Please check in dev.

**Comment by HanaShiho** [comment]
tested in dev, ready for stage

**Comment by HanaShiho** [comment]
ready for prod
