### ISSUE TITLE
BSWH MySamples Update 

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#1108]
*Placeholder for content*

**Comment by depietrodeanna** [comment]
Tracked edits to English here: https://nih.app.box.com/file/1615266097676

Spanish in progress, with NORC.

**Comment by Gbarra9** [comment]
@depietrodeanna This is merged in dev and ready to be checked. Thanks.

**Comment by depietrodeanna** [comment]
@Gbarra9 I reviewed in dev- under "Where Do I Donate My Samples?" there are a couple of minor fixes needed. I added two comments to indicate in this document: https://nih.app.box.com/file/1615266097676?s=uxd92xgjgrc2c1plx7fs9sb1zibptvi2

Same updates needed for both Spanish and English.

**Comment by Gbarra9** [comment]
@depietrodeanna fixes are in dev and ready to be reviewed. Thanks.

**Comment by depietrodeanna** [comment]
@Gbarra9 reviewed and all looks good in dev. ready for stage.

**Comment by depietrodeanna** [comment]
looks good in stage. ready for prod @Gbarra9
