### ISSUE TITLE
Implementing an End Date/Stop Function for Notification Specs in SMDB 

### ISSUE THREAD

**Issue by HanaShiho** [episphere/connect#1112]
Currently, we determine when a notification should be sent by specifying the timing in the Primary Field. In the wake of multiple MC survey reminders going out to participants outside the completion window for the MC survey, we need a stop function in the SMDB UI so we can specify when notifications should stop sending. The goal is to prevent notifications from being sent to ineligible pts per the time-based eligibility criteria.

**Comment by we-ai** [comment]
After notification stop functionality implementation, existing notification specs need data updates to have "stop" time to support the new functionality. Based on discussion on 9/23, existing notification specs will have default stop day as 400, except MC survey reminders.
For MC survey reminders attempts 1 , 2, 3 and 4, the  stop time should be 4 days larger than start time, and attempts 5 should have stop day as 45.
@HanaShiho @brotzmanmj Any additional suggestions on notification specs data updates?

**Comment by HanaShiho** [comment]
@we-ai Sounds good! I adjusted the cadence in dev. I tested the stop function on the MC survey reminders, and it works as expected. As a sanity check, I also verified that the stop function works on the anniversary email. The good news is that imposing a stop time of 400 days won't affect other notifs programmed in SMDB. I will check the subsequent MC survey reminders over the next few days to ensure only one reminder is sent at once.

**Comment by we-ai** [comment]
@HanaShiho Thanks for the updates and comments.
Moving forward, we can update notification specs in stage and prod for stop time.
Let me know if you want dev specs be updated as well to use 400 days as the default stop time.

**Comment by HanaShiho** [comment]
@we-ai yes, please do! Ready for stage

**Comment by HanaShiho** [comment]
Ready for prod

**Comment by sonyekere** [comment]
In Prod
