### ISSUE TITLE
RCA - remove non-melanoma skin from structure

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connect#1113]
@JoeArmani can you please remove non-melanoma skin as a primary cancer site from the RCA data structure?

In an email chain with Brooke Thompson, Heather Feigelson, and Mia they decided that non-melanoma skin should not be included in the RCA because it is not an invasive cancer.

**Comment by brotzmanmj** [comment]
Adding @mnataraj92  because we might want to also deprecate this from the data dictionary. Madhuri, please check with Nicole.

**Comment by JoeArmani** [comment]
Hi @cunnaneaq, Yes, I will plan on updating this.

**Comment by sonyekere** [comment]
Noting that this work might be scoped for the October release. @cunnaneaq, based on @brotzmanmj feedback -  sites may need a reminder not to send data on non-melanoma skin cancers to the RCA in prod.

**Comment by cunnaneaq** [comment]
@sonyekere October sounds good, thanks Sandra!  I will send the sites an email to inform them of the changes to the structure

**Comment by JoeArmani** [comment]
The documentation is updated to remove references to Concept ID 487917585 Non-melanoma skin (basal or squamous)
• https://nih.app.box.com/file/1393159438842
• https://nih.app.box.com/file/1404701245622

**Comment by JoeArmani** [comment]
This PR is in review: https://github.com/episphere/connectFaas/pull/666

**Comment by JoeArmani** [comment]
This is in dev and ready to test.

The only change is the removal of Concept ID 487917585 (Non-melanoma skin), so POST requests with that cancer type will now be rejected.

**Comment by cunnaneaq** [comment]
KPCO tested this in dev and confirmed that their POST failed.  They sent along this screenshot of the error response as documentation

<img width="804" alt="Screenshot 2024-10-23 at 6 55 04 PM" src="https://github.com/user-attachments/assets/ae212ce1-42a1-4baa-b585-b79d69782e6f">

**Comment by JoeArmani** [comment]
Thanks @cunnaneaq. Are we doing any other testing, or is this ready for stage?

**Comment by cunnaneaq** [comment]
I think this is all the RCA testing we're doing this month.  If the screenshot looks good to you, we're ready for stage!

**Comment by JoeArmani** [comment]
Thanks Aileen! Confirming that's the desired response. It includes all the valid cancer types.

This is tested ready for stage.

**Comment by JoeArmani** [comment]
KP completed testing. This is ready for prod.

**Comment by JoeArmani** [comment]
Closing - in production.
