### ISSUE TITLE
Update regex for Home mouthwash collection query (Biospecimen)

### ISSUE THREAD

**Issue by Gbarra9** [episphere/connect#1118]
This issue is related to issue [#1063](https://github.com/episphere/connect/issues/1063).

A user added a variation of "P.O. box" that the current regex did not match as true. 

Ex. "pobox123"

**Comment by erincschwartz** [comment]
@Gbarra9 The Biospecimen Team reviewed the list you provided yesterday and we would like the program to flag as 'true' all of the variations listed with the exception of the following, which can remain 'false' and unflagged: 

- Box drive 

- Random Street 1234 

- #332

The other cases currently listed as 'false' could occur and we would like to err on the side of ensuring that these do not get pulled into the queue for addresses to be printed. 

Can the program be updated to make these changes?

**Comment by Gbarra9** [comment]
Reference for testing
- https://github.com/episphere/connect/issues/1063#issuecomment-2379751419

**Comment by sonyekere** [comment]
Ready for Prod
