### ISSUE TITLE
Assign Kits window in BPTL Dashboard showing incomplete list (Biospecimen)

### ISSUE THREAD

**Issue by erincschwartz** [episphere/connect#1119]
All participants with 'Address Printed' status used to appear in the window on the Assign Kits screen in the BPTL Dashboard. Now, it appears only a subset of those participants are listed. It is the understanding of the Biospecimen Team that participants would remain in the Assign Kits list indefinitely until a kit is assigned to them. 

Please investigate the reason that not all participants with 'Address Printed' status are no longer showing up in the Assign Kits list.

**Comment by amber-emmes** [comment]
Are you able to give some examples of specific participants in dev which you would expect to show in this list but are not showing?

**Comment by sonyekere** [comment]
Tied to issue #1118 @Gbarra9  can you kindly add feedback here as well.

**Comment by Gbarra9** [comment]
Note: Regex matching used on eligible participants will be done for both the Print Labels and the Assign Kits page.
- https://github.com/episphere/connect/issues/1063#issuecomment-2371903134

**Comment by erincschwartz** [comment]
@Gbarra9 Can this issue be closed now that we know those missing were the participants with PO Box addresses and that we do not want them added back in to the Assign Kits list?

**Comment by Gbarra9** [comment]
@erincschwartz This can be closed.
