### ISSUE TITLE
HP team - PWA Testing Feedback

### ISSUE THREAD

**Issue by dbakumar** [episphere/connect#112]
S.No | Description | Type
-- | -- | --
1 | Module   1 seems like it has not completed yet | Question
2 | the   DOB didn’t match inclusion criteria and the system asked me if I wanted to   proceed. Should this be a hard stop? | Question
3 | Should   we have the zip auto-populate so it’s correct and can’t inadvertently be   entered incorrectly? | Question
4 | Would   be nice if NCI PIN’s didn’t include zeros or the letter O as hard to   distinguish. | Improvement
5 | Some   of the NCI’s screens took longer than I thought they would to load or   progress.  Not enough to make me stop   but enough to make me look at my watch. | Improvement
6 | I   have missed preferred email which shows "Please provide perferred email   or mobile phone" and not clear | Improvement
7 | The   User profile form Error messages are not friendly and and its not highlighted   list of correction need. | Improvement
8 | The   participant first name and last name details asked mulitple times like email   based account creation and consent and also in user profile which is   confusing and creates data inconsistancy | Improvement
9 | When   I was routed to the User Profile it sent me to the middle of the page, I had   to scroll up to get to the top. This can be confusing | Improvement
10 | A pop-up appeared   “Episphere Github would like to know your location,” is this necessary? | Improvement
11 | The zip code I entered was   only 4 digits, pop- up appeared to “please match the requested format” Make   sure the pop-up has specifics about the format needed | Improvement
12 | During   Module 1, each time I went to the next page I was routed to the bottom of the   page, again should be routed to the top of the page | Improvement

**Comment by miagaudet** [comment]
@dbakumar could you please enter these at two separate issues?

**Comment by dbakumar** [comment]
@miagaudet,  I have created seperate issues for bug but on this only for questions and improvement suggestion. please advice do you still need seperate issues logged?

**Comment by bhaumik55231** [comment]
>> A pop-up appeared “Episphere Github would like to know your location,” is this necessary?

We are asking the location permission(not storing this detail in our database) to narrow down the user profile address suggestions list. Without that location address suggestion would not be always accurate.

We will work on other improvements.

Thank you!

**Comment by miagaudet** [comment]
In the list here, moving 6, 7, 8, and 11 to @deanna and OCPL.

**Comment by miagaudet** [comment]
Newly generated pins will be a combination of any 6 characters from '123456789ABCDEFGHJKLMNPQRSTUVWXYZ' (no I, 0 or O).

**Comment by brotzmanmj** [comment]
2. DOB is required entry but will not stop the user from submitting the user profile if it is outside the range of eligible age. Ages outside of eligible range will be resolved as part of verification.
