### ISSUE TITLE
Add variables to be retained in the stub record

### ISSUE THREAD

**Issue by mnataraj92** [episphere/connect#1122]
@jhflorey These new variables from the participants table should be retained in the stub record upon data destruction: 

d_320303124 (3-month Quality of Life (PROMIS) survey completion flag)
d_843688458 (Autogenerated date/time when PROMIS survey completed)
d_956490759 (2024 Connect Experience Survey Status)
d_199471989 (Autogenerated date/time stamp for Completion of 2024 Connect Experience Survey)

**Comment by jhflorey** [comment]
@mnataraj92  My changes are ready on dev. Do we need to test in dev or we will test in stage?

**Comment by brotzmanmj** [comment]
Hi, I don't see a response to the question, @mnataraj92  was this tested in dev?

**Comment by mnataraj92** [comment]
@brotzmanmj this will be part of today's dev testing.

**Comment by mnataraj92** [comment]
This will be tested in stage.

**Comment by mnataraj92** [comment]
Tested in stage, and the variables were retained as expected! 

However, it seems that the Connect Experience Survey data still needs to be configured from firestore to BigQuery so we were not able to check that the 2024 Connect Experience Survey data has been deleted since the table is not yet in BQ.

**Comment by mnataraj92** [comment]
Looks good in stage! Ready for prod
