### ISSUE TITLE
2024 Connect Experience Survey- Changing the Survey Status display in the SMDB for Ineligible Pts

### ISSUE THREAD

**Issue by mnataraj92** [episphere/connect#1124]
During Stage testing for the 2024 Connect Experience Survey, we noticed that in the SMDB, the survey status said 'not started' for ineligible participants (these participants have a value of null for survey status in firestore). If possible, we would like to change the language for the survey status for ineligible participants to indicate that they are not eligible for the study. @sonyekere could you assign someone to look into this for the October release?

**Comment by sonyekere** [comment]
@mnataraj92 we can look into this for the October release

**Comment by sonyekere** [comment]
Hi @mnataraj92 and @robertsamm - Brian confirmed this is in Dev and ready to be tested.

**Comment by mnataraj92** [comment]
This is ready for stage. Kaitlyn and Aileen took a look at this in dev. The dev environment may be a difficult place to determine if the status is set correctly because it may have previously been set as a default. The status of the actual variable in Firestore matches what's in the SMDB, so this is good in dev.

**Comment by kmazzilli** [comment]
Tested in Stage, looks good, ready for prod
