### ISSUE TITLE
Create Passthrough API for BQ data

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/connect#1126]
We need to share unique tables, views, etc. with external entities through an API. To do this, the proposal is to create a new endpoint in the connectFaaS which would expose those different data through a request. The calling entity will have to have sufficient permission to view the data in the table/view.

**Comment by Davinkjohnson** [comment]
Return format: response object with JSON data in response data area

How will this be called? REST call

Follow-up: confirm with Analytics that no parameters need to be set/passed in when scheduled query runs
Will not be able to get data from any table in BQ, this will be specific to tables/views used 

How will we secure this so users cannot see other tables/views? Ideally, use IAM services in GCP to see whether calling service account (or user credential) has view access to table/view and grant/deny access.

Who will test? Sandra is reaching out to NORC for data transfer efforts this week. NORC will assign someone to build out the calling/receiving side of this and perform testing.

Need: an example of the desired URL and the desired data output
Brian can look at Postman documentation for some guidance. https://documenter.getpostman.com/view/7490604/SVYnT26j#783e2fea-a8f8-4887-90e2-1b0c62e2fae5

**Comment by bransteitterbr** [comment]
<img width="1094" alt="Screenshot 2024-10-04 at 1 42 09 PM" src="https://github.com/user-attachments/assets/b9ef6a99-6158-45bd-a2c9-c9c1cb6020aa">
Flow chart of the current process

**Comment by sonyekere** [comment]
In Prod
