### ISSUE TITLE
Participant PWA Testing

### ISSUE THREAD

**Issue by choimichelle** [episphere/connect#113]
Link (https://episphere.github.io/connectApp/) does not work in Microsoft Edge Private Window.

**Comment by bhaumik55231** [comment]
Hi, @choimichelle Could you please specify what version of Microsoft Edge you are using? 
As I was not able to recreate this issue in version 83.0.478.37

**Comment by choimichelle** [comment]
Hi @bhaumik55231, I apologize for the late reply. I have Microsoft Edge 44.18362.449.0.
