### ISSUE TITLE
NORC enable incentive eligible

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#1131]
DevOps will need to set and enable NORC's incentive eligible

Placeholder for additional requirements. @mnataraj92  please add on to the requirements if needed.

**Comment by mnataraj92** [comment]
For someone to be NORC incentive eligible (d_130371375_d_266600170_d_222373868 = 353358909), Payment Eligible = yes (d_130371375_d_266600170_d_731498909 = 353358909 and Payment Round = Baseline (d_130371375 = 266600170). This is for Baseline NORC Incentive Eligible. The payment variables are nested under Payment Round. 

For someone to be Payment Eligible (d_130371375_d_266600170_d_731498909 = 353358909), from the derivation notes in the data dictionary: 
First checks if participant is still currently marked as NOT eligible. Sets true / false variables for each of the four modules based on if the status of the modules is completed, sets true / false variable for blood collected based on if baseline blood is yes or the variable for clinical site blood collected is yes. If these five values are all true, the participant is eligible for the incentive. If the modules are all true but blood collected is false, we filter through all baseline research collections for that participant and if any of the tubes have a reason not collected equal to anything other than refused, the participant is eligible.

Translated into variables, this looks like:
If SMPaym_PaymElig_v1r0 = 0 and 
SrvBOH_BaseStatus_v1r0 is 2 and 
SrvMRE_BaseStatus_v1r0 is 2 and 
SrvSAS_BaseStatus_v1r0 is 2 and 
SrvLAW_BaseStatus_v1r0 is 2 and 
BioFin_BaseBloodCol_v1r0 is 1 or BioClin_SiteBloodColl_v1r0 = 1 
then SMPaym_PaymElig_v1r0 is 1  
OR IF   
SMPaym_PaymElig_v1r0 = 0 and 
SrvBOH_BaseStatus_v1r0 is 2 and 
SrvMRE_BaseStatus_v1r0 is 2 and 
SrvSAS_BaseStatus_v1r0 is 2 and 
SrvLAW_BaseStatus_v1r0 is 2 and 
BioFin_BaseBloodCol_v1r0 is 0 or BioClin_SiteBloodColl_v1r0 = 0 and if BioCol_NotCol_v1r0 != 681745422 for BioCol_0001_v1r0 and BioCol_0002_v1r0 and BioCol_0003_v1r0 and BioCol_0004_v1r0 and BioCol_0005_v1r0 
then SMPaym_PaymElig_v1r0 is 1

Note that d_883732523 (BioCol_NotCol_v1r0) exists for each tube type and has nested structure. 

The Timestamp for becoming baseline incentive eligible (d_130371375_d_266600170_d_787567527) also needs to be set for when the pt became baseline incentive eligible. 

@brotzmanmj please let me know if there are any additional details to include. And just to confirm this is only for the NORC incentive eligibility; we're not testing payment issued, payment refused, or payment chosen?

**Comment by brotzmanmj** [comment]
@mnataraj92  I think we do not need this level of detail here regarding the derivation because we won't be doing anything to the derivation and I don't think Tony typically checks through all of that when we does a prod manual change to make someone incentive eligible. All we need this to do is exactly what would happen if you entered a prod manual change for Tony to make someone incentive eligible, regardless of what the derivation says. Provide the variables just like you would in the prod manual change log. 

And please ask NORC where/how they would like this to appear on the SMDB UI. Thanks.

**Comment by mnataraj92** [comment]
@brotzmanmj no problem that sounds good! I wasn't sure what level of detail to include but I have modified the comment to not include as much. I'll provide the list of variables shortly & reach out to NORC!

**Comment by brotzmanmj** [comment]
Looks good, thanks!

**Comment by mnataraj92** [comment]
@anthonypetersen here is the list of variables and concept ids that are typically impacted during prod changes to make someone baseline incentive eligible https://nih.app.box.com/file/1670572108080 (in the Vars to Make Pt Incentive Elig tab). Please let me know if additional details are needed.

**Comment by rohanjay10** [comment]
@mnataraj92 @anthonypetersen @Gbarra9  The conditionality for the baseline incentive eligible variable (d_130371375_d_266600170_d_731498909) has been updated here: https://nih.app.box.com/file/1668730770583?s=kc8ugxvosd9h5z3glinufwr0thvwlpgi
(under the 'Derived Variables' -> 'incentive eligible')

**Comment by brotzmanmj** [comment]
Hi @rohanjay10  can you tell us what if anything has changed? Is this just adding documentation of what currently exists in prod?

**Comment by brotzmanmj** [comment]
Great thanks!

**Comment by rohanjay10** [comment]
Dependencies for preferred 'Select Tool' option for Incentive Eligibility tool discussed in today's call:

- Only the Baseline option will be selectable in the dropdown as Follow Up Options aren't available. Follow Up 1 will be added to the dropdown once it is available.

 If a participant is already Incentive Eligible:
-   The option to 'Update Date of Eligibility' and changing 'Incentive Eligibility' will not be selectable 
-  Displaying current eligibility status would be helpful 
- 'Payment Chosen' variable once populated out should have the Incentive Eligibility tool updates buttons not selectable and participant shouldn't be eligible to get another payment. Once populated it part of NORC eligiblity derivation 

Other:
- Verification Status/Duplicate Type/ Recruitment type should work how we currently do it in the SMDB in prod 
- Nothing to note for Prod Manual Changes as both tools are straightforward 

Feel free to add on

**Comment by rohanjay10** [comment]
Both the 'Payment Issued' and 'Payment Chosen' variables are updated during prod changes(and can indicate if the tool is selectable or not) however they aren't changed when making someone incentive eligible.

**Comment by brotzmanmj** [comment]
@mnataraj92 are we trying to also implement manual updates to payment issued, payment chosen, and date issued with this tool? I had been thinking we were only trying to implement making someone incentive eligible.

**Comment by anthonypetersen** [comment]
Payment Issued and Payment Chosen are not updated during prod changes. We only update Incentive Eligible, NORC Incentive Eligible, and Eligibility Date

**Comment by mnataraj92** [comment]
@brotzmanmj right we're only trying to implement making someone incentive eligible. I think on the call we had discussed maybe graying out that option if someone already had their incentive issued.

**Comment by brotzmanmj** [comment]
Thanks. We only need to gray it out if it they are already incentive eligible = yes. There is no dependency for that on whether it was issued so let's drop that from the requirements.

**Comment by anthonypetersen** [comment]
From this tool's POV we should only be looking at if they are already Incentive Eligible (whether done automatically or manually through this tool), there's no reason to look at Payment Chosen.

Edge case example: someone has been marked as incentive eligible but hasn't chosen a payment yet, this tool would still be able to update incentive eligible date.

**Comment by brotzmanmj** [comment]
Tony, have we ever done that... had someone who was incentive eligible but without a date (or with an incorrect date)?

**Comment by anthonypetersen** [comment]
No we haven't, my point was that if we implemented the requirements above you would still be able to modify the eligibility date until they chose a payment, which we wouldn't want to do.

**Comment by brotzmanmj** [comment]
Oh got it, yes, I agree with that

**Comment by rohanjay10** [comment]
Hi all, 
Here is a link to the technical requirement based on previous discussions: https://app.box.com/s/nlja7cno6fr1so7qlye7c8vw2n7t4caq

It also includes links to the variable documents and mockups.


Please review and feel free to make additions/changes. Tony and Gene also looked over this. Thanks

**Comment by rohanjay10** [comment]
This has been tested in stage and is ready for prod
