### ISSUE TITLE
Mouthwash Overhaul Print Labels (Biospecimen) 

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/connect#1134]
(High priority)

Current Process: (1) Query pulls ALL participants where:

-not withdrawn

-not deceased

-no active refusals

-baseline blood/urine collectied = true

-time more recent than 04/01/02024

-add five day delay

(2) Then, it filters out participants where a mouthwash specimen exists (173836415.266600170.319972665)

Proposed change:

(1) Apply a kitStatus: initialized value to the participant profile based on the existing conditions when a specimen’s entry is finalized in the Biospecimen collection entry form (check all the current conditions and apply the status when conditions align).

(2) On the ‘Print Labels’ screen, we can use Firestore’s .count() query for labels to print. This counts as one read per 1000 documents instead of one read per document. We can query the specific participant data, ordered and limited, based on the number entered in the ‘labels to print’ input field. With this flow, we can simply query for participants whose kit status is ‘initialized’ and order based on the desired condition.

(3) Update status based on successful CSV generation.

-Note: the current process only gives one shot for those CSV files (I think). We should check whether that has been an issue — has there been any data loss on the BPTL side?

Note: This will require retroactive handling with a cloud function at prod release: Identify currently eligible participants in the ‘labels to print’ queue’ and assign kitStatus: initialized to these participants. We may have to monitor for crossover issues with collection sites running cached versions of the biospecimen app for the first 1-2 weeks (like we saw when Streck tubes were added).

Note: For future duplicate kit handling, it’s probably most effective to have a separate query for duplicate kits that gets merged into normal kit results. That way, we can prioritize the duplicate kits where needed. For example, if we’re printing 25 labels with 6 duplicates to handle that have priority, we can route the system to query 6 duplicates and 19 regular records.

-Lastly, it would benefit from code documentation and cleanup for future developers (this is non-essential)

@amber-emmes Check with @erincschwartz and @wyattks for their perspective, but I'm guessing this should be priority for Oct.

**Comment by erincschwartz** [comment]
In response to the note above:

_-Note: the current process only gives one shot for those CSV files (I think). We should check whether that has been an issue — has there been any data loss on the BPTL side?_

It is correct that the Print Address CSV file is only available 1x. This has not presented an issue to date for BPTL. Adding @wyattks here. Do you think we need this functionality changed at all? We wouldn't want BPTL to be able to generate the file again once additional participants have become eligible for address printing, I could see that leading to serious confusion. 

Also, as discussed via chat with @amber-emmes, the "Query pulls ALL participants where:" list above should say **AND Collection setting = clinical** where highlighted below.


![image](https://github.com/user-attachments/assets/15af92a4-6b65-459a-a729-c4f3bf5b3cbc)

**Comment by wyattks** [comment]
Correct.  It hasn't been an issue and I'm not sure if there is a way to have it print more than 1x without confusion.  BPTL saves the files when they print in a secure loction incae they need to go back to it.

**Comment by mnataraj92** [comment]
Concept ID for 'initialized' response for Kit Status: 728267588

221592017     Kit Status     517216441	0 = Pending
		                           728267588   1 = Initialized
                                           849527480	2 = Address printed
                                           241974920	3 = Assigned
                                           277438316	4 = Shipped
                                           375535639	5 = Received

**Comment by amber-emmes** [comment]
This should now be in dev and ready to test. Please review the process thoroughly from participant check-in to specimen submission to label printing, as this involved some thorough reworking. Let Dev-Ops know if you need anyone to manually review any of the data in Firestore to ensure appropriate flags are set.

**Comment by amber-emmes** [comment]
This is now in dev and ready to review.

**Comment by erincschwartz** [comment]
Tested in Dev, ready for Stage 

- Put test participants from data entry to finalization on Collection Data Entry screen
- Participant with normal address moved to 'Initialized' status, backdated the collection date > 5 days and they appeared at the top of the Print Address list 
- Participant with P.O. Box address was not updated to 'Initialized' status
- All variables populated as expected for Assign Kit, Ship Kit and Kit Recept

**Comment by brotzmanmj** [comment]
Planning ahead for something related to this.... in the January release we will be adding fields for Physical Address to User Profile and will be adding a checkbox for people to indicate if the Mailing Address (what we currently capture) is a PO Box. It seems to me that after we have that in place, we should update the Home Collection Print Address to take this into account. Create a new GitHub issue for January to do this in tandem with that UP change?

**Comment by erincschwartz** [comment]
Stage testing update:

1) Entered clincal collections (blood and urine) for 2 test participants: 
         Connect ID 1279947153 
         Connect ID 2357066971 (P.O. Box address)
2) Gene backdated concept ID 740582332 for both to a date >5 days ago
3) Connect ID 1279947153 appeared at top of Print Address list  (2 other Stage test participants were on the list too); Connect ID 2357066971 (P.O. Box address) did **not** appear on the list, as expected
4) Created and Assigned, Shipped and Received kit **CHA100205 0007** for **Connect ID 1279947153** 
Additional kit information (in case you need this to check backend)
       Return Kit Tracking Number 776655228906
       Supply kit tracking 336655228905

Please check the backend data to make sure everything looks as expected. 

During testing, I did notice that the Blood and Urine collection status for both participants is showing as 'Not Collected' in the SMDB. Please check <878865966>BioFin_BaseBloodCol_v1r0 (Baseline Blood Collected - derived from biospecimen dashboard) 
<167958071>BioFin_BaseUrineCol_v1r0 (Baseline Urine Collected - derived from biospecimen dashboard)

**Comment by amber-emmes** [comment]
Blood and Urine collection status (878865966) is set to no (104430631) for both participants listed here. As this is one of the variables that was having problems in "Update to when derived variables are set and preventing overwriting (Biospecimen) #1169" and this uses the same method as in that ticket, I strongly suspect that this is related to #1169. 1169 is already the behavior "in the wild"; do we know whether this behavior is the same?

**Comment by erincschwartz** [comment]
This is different, I entered these collections cleanly (i.e. they were not duplicate collections, I did not enter partial data and save, then add more data and finalize, which is where we noticed the errors in previous testing of the derivation issue). I simply entered the collections with blood and urine and finalized. 

I just entered a 3rd clinical collection of blood and urine, Stage Connect ID 3152773927, appears to have the same result when I searched for them in SMDB---showing blood and urine as not collected.

**Comment by sonyekere** [comment]
@erincschwartz and @brotzmanmj I do understand that you are crucially awaiting next steps to address the data not populating correctly - showing blood and urine as not collected in SMDB. Alerting a bit of time is needed as @JoeArmani and @amber-emmes are currently working together to provide feedback/next steps. Thank you!

**Comment by sonyekere** [comment]
@erincschwartz please hold off on testing this agin until DevOps provides an update on the issue. Thank you!

**Comment by erincschwartz** [comment]
@sonyekere, I will wait until further notice.

**Comment by sonyekere** [comment]
Hello @erincschwartz/ @brotzmanmj , Joe and Amber have a good strong lead of what the issue may be. However, time is needed to test this thoroughly. Davin will be reaching out to suggest next steps.

**Comment by JoeArmani** [comment]
@erincschwartz Okay, this is in dev and ready to test

**Comment by JoeArmani** [comment]
@erincschwartz @amber-emmes @sonyekere @Davinkjohnson just wrapped up testing:
Tested in stage, ready for prod
