### ISSUE TITLE
Shipped mouthwash sample showing back up in UChicago list of Available Collections - Biospecimen 

### ISSUE THREAD

**Issue by erincschwartz** [episphere/connect#1143]
Mouthwash sample for collection CXA032601 was entered into and finalized in the Biospeicmen Dashboard. UChicago team added this specimen (CXA032601 0009) to Box 2006 and finalized the shipment on 10/25. The package was received at FNL on 10/26. This sample appeared on the Box Manifest and the receipt .csv, however, the UChicago team reports that this sample is still in their list of Available Collection on the Shipping Dashboard. The prod data file is showing BioCol_CollBoxedStatus_v1r0 status of 'partially boxed'

This issue is similar: https://github.com/episphere/connect/issues/833

It seems that a manual prod change may be needed to clear this mouthwash sample out of the Available Collections list. Please confirm and we can move this through for approval.

**Comment by sonyekere** [comment]
Biospecimen team is requesting investigation on this mishap with this one collection. A prod manual change may be needed.

**Comment by erincschwartz** [comment]
Manual prod change completed on 11/8/2024 to update "Collection boxed status" (Concept ID 771580890) value from 775512390 (Partially Boxed)  to 210720511 (Boxed) for collection CXA032601. 

UChicago team confirmed on 11/11/2024 that the mouthwash sample from this collection is no longer showing up in their list of Available Collections. This issue can be closed.
