### ISSUE TITLE
Consent+HIPAA HTML: remove the 'I agree' and signature lines (December release)

### ISSUE THREAD

**Issue by robertsamm** [episphere/connect#1144]
We have had multiple CSC tickets where recruits expressed confusion about where they need to digitally sign on the consent page of the PWA as there is a signature field in the HTML display of both forms and at the very bottom of the screen. In an effort to reduce this confusion, we would like to remove the 'I agree' and signature lines from the HTML box displays of both the consent and HIPAA forms. This way, the signature language is only displayed at the very bottom of the screen where the digital signature is captured.

Please remove the language at the end of each forms HTML display from 'Yes, I agree to join Connect' through 'Name'/'Date'/'Signature'. This should be removed for both the English and Spanish versions of the consent and HIPAA forms for all 10 sites and the testing NCI site (in dev). The signature fields will remain as is on the PDF versions of the forms.

See below for example of language to be removed from HTML.
![image](https://github.com/user-attachments/assets/4a96dada-0197-49ea-96bb-37f1dcc96480)
![image](https://github.com/user-attachments/assets/4c17ae34-e54e-4a64-a7f7-e2e09210ec4e)
![image](https://github.com/user-attachments/assets/e9fa3001-a48e-4c40-be70-32014c2f66dc)
![image](https://github.com/user-attachments/assets/ac55bb41-aec5-4399-9acc-1cba5d936c0b)

**Comment by robertsamm** [comment]
Good morning @bransteitterbr! has this change been merged to dev or is it still in review? I tried testing this morning with NCI and HPs forms using incognito browser and clearing my cache but I'm still seeing the 'Yes I agree' and signature language in the HTML box display for the consent form and HIPAA form.

![image](https://github.com/user-attachments/assets/7c5946f6-3c28-4f7c-858b-f2be46b581de)

![image](https://github.com/user-attachments/assets/50381062-8cbf-4b36-9aa1-f797b859c8aa)

**Comment by bransteitterbr** [comment]
I am sorry I thought this was merged a while ago.  I just merged it, just give it a few minutes and it will be updated in dev

**Comment by bransteitterbr** [comment]
@robertsamm  I am sorry I thought this was merged a while ago. I just merged it, just give it a few minutes and it will be updated in dev

**Comment by robertsamm** [comment]
@bransteitterbr Thanks! Tested in dev, ready for stage!

**Comment by robertsamm** [comment]
@bransteitterbr tested in stage, ready for prod!
