### ISSUE TITLE
yob - birth year in PWA for qx markdown

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connect#1146]
"input data" variable needed to pass "544150384 | Birth Year" into the PWA.  Would prefer for this to be called "yob" and will ask IMS to code "yob" in the markdown.

Hoping to have this in dev as soon as possible following the 10/30/24 production push

**Comment by cunnaneaq** [comment]
tested in dev - ready for stage

**Comment by sonyekere** [comment]
In Prod
