### ISSUE TITLE
Part 3: User Profile Enhancements with SendGrid email validation(December Release) 

### ISSUE THREAD

**Issue by rohanjay10** [episphere/connect#1149]
Original Issue: Issue #994 
Requirements here: https://nih.app.box.com/file/1674557082093
Edits to [User Profile Criteria](https://nih.app.box.com/file/501193852134?s=8p7esmx0eafr7ela6gbne4zorvsgnwal)

Mailing Address and Physical address changes/additions in the PWA, MyProfiles Page, and SMDB.
- Changing the mailing address entry so that mailing address is run through the USPS API upon entry;

- Add checkbox for P.O. Box entry into mailing address

- Adding an option of a physical mailing address upon entering a P.O. Box;

- Improving email address entry by switching to sendGrid email validation API

- All new text on the PWA, including error messages, to be translated into Spanish

**Comment by jhflorey** [comment]
https://github.com/episphere/connect/issues/994#issuecomment-2479079337
https://github.com/episphere/connect/issues/994#issuecomment-2479083704

**Comment by rohanjay10** [comment]
Hi @Davinkjohnson and @bransteitterbr, for the mailing address fields, would the USPS API validate the mailing address fields that a participant enters in(as opposed to the API filling in those fields)?

Chatted with @jhflorey , Amelia, and Sandra on this via teams and wanted to confirm the above with you, along with any details that may be of use.

**Comment by bransteitterbr** [comment]
@rohanjay10 My understanding is that the USPS API is for validation not auto filling.  I am fairly certain they say in their docs that it shouldn't be used for real time validation just for post entry validation.

**Comment by rohanjay10** [comment]
Soft warnings/Hard errors with SendGrid email validation API
**Hard errors**
- When validating emails sendGrid has verdict of Valid/Invalid/Risky for each email based on checks sendGrid does. In previous discussion with Brian, we could craft error messages by combining verdict with those checks.
- Jessica mentioned that we are only able to send out error messages to emails deemed "Invalid" with those with a verdict of "Valid"/"Risky" allowed to go through. 

These are the checks that sendGrid uses, where we need to decide in which scenario would an error be returned, or when to let the email be submitted even if it does not pass a certain check(I've put my suggestion in parenthesis). Once we determine that we'd be able to come up with the error messages that would need to be translated into Spanish.

1 . Ex: has_valid_address_syntax = false then "the email address is invalid" due to incorrect email address syntax.(Invalid)
2.	has_mx_or_a_record = false then "Domain you provided is missing the required DNS records and will result in a bounce"(invalid)
3.	is_suspected_disposable_address = true then "This email appears to be a disposable address, Connect will need to reach out to you from time to time so please provide a more permanent address"(risky)
4.	is_suspected_role_address  - Email is from a suspected role(HR or admin) address(could be risky).
5.	has_known_bounce - This email has been submitted to SendGrid before and has resulted in a bounce(invalid).
6.	has_suspected_bounce - SendGrid ML models suspect that the email might bounce(risky).


**Soft warning**

- 	Suggestion field: Is used for providing suggestion for correct domain in the scenario of typos

Ex: gmial.com > gmail.com or when validating john.doe@gmial.com suggestion field of 'gmail.com' can be combined with local field 'john.doe' to create john.doe@gmail.com as a suggestion

-  Option to let the user know that they may have a typo, by alerting them once and then allowing submission a second time

**Comment by rohanjay10** [comment]
Hi @depietrodeanna , could you please help finalize the error messages listed in the error messages documentation [here](https://nih.app.box.com/integrations/officeonline/openOfficeOnline?fileId=1699379771757&sharedAccessCode=) so they can be translated into Spanish?

It is under "Pt 3(contact info)" for the fields in red labelled "Preferred email" and "Additional email". My draft messages are in blue and they are based on Email Validation checks that are outlined in [this SendGrid documentation under "Checks"](https://www.twilio.com/docs/sendgrid/ui/managing-contacts/email-address-validation/real-time-email-address-validation-overview#verdict-score-and-checks-fields). I've also provided additional information on this in my previous comment

**Comment by rohanjay10** [comment]
In discussion with Michelle, adding that we would like to see if we could track the number of User Profiles that don't get submitted due to failing email validation. This could be something that could be tracked with the number of "Invalid" verdicts but likely has to be built out. 

The number of "invalid" verdicts for the last 30 days can be tracked through the Email Address API dashboard per SendGrid documentation. @jhflorey is the Email Address API dashboard something that we are able to access via the SendGrid UI?

**Comment by depietrodeanna** [comment]
@rohanjay10 Interpreting the decisions above, there are now just two messages we need for the hard error and warning, and then the soft edit for email validation in the event of domain typos?

**Comment by rohanjay10** [comment]
@depietrodeanna Yes I believe so, considering the timeline it would be those two messages + the soft edit, compared to the previously detailed list of messages

**Comment by brotzmanmj** [comment]
Hi @rohanjay10 to prepare for testing this functionality, can you prepare a testing plan that covers emails each of the circumstances above (those that should fail for each reason and those that should pass)? Thanks.

**Comment by rohanjay10** [comment]
Hi @brotzmanmj I can work on the testing scenarios for the different types of email validity, I would need help putting the entire testing plan in place though.

**Comment by depietrodeanna** [comment]
@rohanjay10 final English suggestions. If no concerns I will get them translated to Spanish:

Hard error message: "This email address is invalid. Please enter a valid email before continuing."
Warning message: "Warning- this email address may be invalid. Please double check your entry before continuing."

Soft suggestion for email typo: "Did you mean [insert email @ email client]?"

**Comment by rohanjay10** [comment]
@depietrodeanna Those final suggestions look good for me to get translated. I'll update them on the error messages document accordingly https://nih.app.box.com/file/1699379771757?s=h1jdjwe8ah3ydkwfcaow223q3irae2i4

**Comment by rohanjay10** [comment]
Hi all, regarding sendGrid domain suggestions for typos:
 In discussion with Jessica it appears that the domain suggestion for typos("did you mean gmail.com?") is something that would likely have to be built out and thus not something that is likely prioritized for this release, as confirmed with Davin. Spoke with Bryan regarding detecting typos and one way to help detect typos is by enabling the double entry of emails, alongside sendGrid validation checks. I think this would help with lowering the number of typos until the sendGrid typo solution is built out but open to other suggestions.

I think if we go along this route then @depietrodeanna we may need another error message for the double entry of emails not matching(ex: "The email addresses don't match"). Another option is to use the previous invalid/error messages

**Comment by brotzmanmj** [comment]
So for this release, we will include a partial SendGrid validation check but just not with the domain suggestion. It will otherwise be the same critieria for valid, risk, invalid as described above?

Since we currently have double entry of emails, do we already have an error message for the double entry that says that?

**Comment by depietrodeanna** [comment]
Yes- I just pulled it from Stage. It's: "Your email addresses do not match. Please retype your email addresses."

**Comment by rohanjay10** [comment]
> So for this release, we will include a partial SendGrid validation check but just not with the domain suggestion. It will otherwise be the same critieria for valid, risk, invalid as described above?
> 
As Jessica continues to work through UP Pt 3, she'll update the specifics of this release/scenario.

**Comment by sonyekere** [comment]
Per our internal call held Friday 12/13: @brotzmanmj @Davinkjohnson @jhflorey @amber-emmes @rohanjay10 

We will proceed **without** implementing the modals ( for warning purposes) for the December release, but this can be revisited in January. 

In the meantime, @jhflorey will need to share with @HanaShiho whether the Monitoring API call and history of participant responses are available within SendGrid. Is there a log in SendGrid where Comms can check to see how many people had a risky vs. hardstop? Ops would like to monitor from Sendgrid how often participants are experiencing issues with User Profile workflow, something isn't working or when ppts can’t provide inputs as requested.

**Comment by HanaShiho** [comment]
Hi @jhflorey how does SendGrid determine which email addresses to validate? We send about 10-12K emails daily--where does SG pull the total of 722 from? Also, under the Source section, it says we can subset results by the type of reminders sent (e.g., newsletter vs. other types of reminders). Am I understanding that correctly? Thank you!

**Comment by rohanjay10** [comment]
A component of the email validation is part of the current release, and ready for stage. However other parts of email validation(monitoring, warning modal, etc.) and PO Box + physical address components will be part of the next release. All, please update this info if needed

**Comment by robertsamm** [comment]
@jhflorey @rohanjay10  The physical address fields are still showing in the participant details page on the SMDB as 'editable'. For this release we either need to remove the physical address fields from the SMDB pt details page completely or grey out the edit buttons for those fields so that sites and CSC staff can't put any data in for those fields. Which would be easier to implement?

**Comment by jhflorey** [comment]
@robertsamm We can remove it.

**Comment by jhflorey** [comment]
@robertsamm @rohanjay10 the code changes for removing physical fields temporarily are ready in dev/stage.

**Comment by sonyekere** [comment]
New issue was made to address new UP work. Closing.
