### ISSUE TITLE
Part 2: User Profile Enhancements for Former Names (December Release)

### ISSUE THREAD

**Issue by rohanjay10** [episphere/connect#1150]
Original Issue: Issue #994 
Requirements here: https://nih.app.box.com/file/1674557082093
Edits to [User Profile Criteria](https://nih.app.box.com/file/501193852134?s=8p7esmx0eafr7ela6gbne4zorvsgnwal)

Add field for 'Former Names' in 'Names' section. 

**Variable Updates/Requirements:**
* To be retained in User Profile history and stored under the nesting structure for User Profile (first, middle, last) name
* Former names for First, Middle, Last names are stored under current User Profile history name field nesting structure for User Profile name(First/Middle/Last). This is an array in DD structure, on PWA there is a soft limit of 50.
* Current name would remain current User Profile Name, it would not be overwritten. Former Name entered would be backfilled into history variable. Consent name does not change 

 **UI**
1. Add intro text(on above Criteria document page 3) on MyProfile page
2. 'Former Names' to be added as sub category after 'Preferred first name' field in 'Names' section
3. Displayed as drop down with responses of 'First', 'Middle', 'Last', and open field text box to type Former Name(stored under User Profile name nesting structure). Display 2 entries with ability to add more(soft limit of 50).
4. Drop Down required if data is entered into textbox. Display error: 'Please choose a name category. If you do not have a name to enter, please remove text from Former Name textbox’
5. All new text on the PWA, including error messages, to be translated into Spanish

**Testing Dependencies:**

- Confirm during testing that 'former names' are imported into the user profile history variable only and that the consent name and current user profile names are locked down (so not edited when former names are entered). 
- Confirm this in all places name is displayed (consent name and user profile name on site API, SMDB, PWA MyProfiles page, BSD)

Please add any additional information/changes below. Thanks

**Comment by jhflorey** [comment]
@robertsamm  do we need to have a remove button to remove each field?

**Comment by jhflorey** [comment]
@rohanjay10 @mnataraj92 Do we have new concept ids for this issue.

**Comment by mnataraj92** [comment]
Hi @jhflorey former names will not have new concept IDs. Former names will get stored in the UP History (d_569151507) in the same existing variables as UP first name (d_569151507_d_399159511), last name (d_569151507_d_996038075), middle name (d_569151507_d_231676651), and suffix (d_569151507_d_506826178). They'll be nested under the array for user profile history names.

**Comment by JoeArmani** [comment]
Here's a reference screenshot of the UPHistory data structure from a dev testing account. I think it's important to match this structure for potential long-term needs.
<img width="580" alt="Screenshot 2024-11-20 at 4 12 18 PM" src="https://github.com/user-attachments/assets/1db62e7a-baff-454b-916e-5bcb9884e046">

**Comment by rohanjay10** [comment]
[Former names error message translated in Spanish by NORC](https://github.com/episphere/connect/issues/994#issuecomment-2492295879)

**Comment by jhflorey** [comment]
@rohanjay10 my code changes are ready in dev. We can test part 2.

**Comment by rohanjay10** [comment]
The changes are in Dev and this is ready for stage - Confirmed with Jessica and Amelia

**Comment by rohanjay10** [comment]
The changes are in stage and ready for prod
