### ISSUE TITLE
Add suspended contact flag and dates to NORC Phone Calling Survey data

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#1151]
NORC has requested to add the Suspended Contact flag and date start and stop suspended contact to the phone calling survey data they pull. So they can avoid calling people who have already requested suspended contact. 

@Davinkjohnson  please comment if we should aim to add this to the file they pull in Box, or will they be able to soon pull that information via the new NORC API starting in early December?

**Comment by Davinkjohnson** [comment]
I don't have a preference either way. Nicole's team will have to make a change in either case, to ensure the flag is in the table in BQ. Once that's done this will be accessible via the API (still planned for early December).

**Comment by brotzmanmj** [comment]
Got it. @FrogGirl1123 is this something we can do this month in BQ? If so, we just need @mnataraj92 's help to identify the suspended contact flag, start date, and stop date, and communicate these to Jake and to the NORC team so they can prepare to receive them in BQ.

**Comment by brotzmanmj** [comment]
Closing because we have stopped phone calling for the time being, will re-open if needed in future
