### ISSUE TITLE
Update My Samples page content for SFH (December release) (Biospecimen)

### ISSUE THREAD

**Issue by erincschwartz** [episphere/connect#1157]
Sanford Health is closing one site and relocating to a new site, the information on their My Samples page needs to be updated. Tracked version is located here: https://nih.app.box.com/file/1700222720602

**Comment by brotzmanmj** [comment]
@erincschwartz Do we need anything for translation for the Spanish version of this?

**Comment by erincschwartz** [comment]
@brotzmanmj That is a great question, I do not see any Spanish versions of My Samples pages in the "In Prod" folder of Box---is this something that gets translated depending on how a participant's browser is set up? Or, could be that the Spanish versions are just saved somewhere else and in that case, yes, it will need to be translated. I will have to connect with Deanna on this on Monday.

**Comment by brotzmanmj** [comment]
I see there are Translations in this folder on Box https://nih.app.box.com/folder/256165177865?s=7hrw4m74sa6ymqsg6nr5zkn5uldghhh2 but please follow up with Deanna on Monday about asking Glyph to make the changes

**Comment by sonyekere** [comment]
Noting that a PR will be submitted for the English content. Spanish translations are currently pending.

**Comment by sonyekere** [comment]
In dev and ready for testing

**Comment by erincschwartz** [comment]
I just logged into MyConnect in Dev from SFH test participant account, the My Samples page is not showing the updated information. Imagenetics location is still showing.

**Comment by depietrodeanna** [comment]
@Gbarra9 Spanish content for the SF changes below:



Sioux Falls, SD: Edith Breast Cancer Center

Dirección e indicaciones
1210 W. 18th St
Sioux Falls, SD 57104 –
Entre por la puerta BB
 
Instrucciones de estacionamiento
Hay servicio de estacionamiento gratuito cerca de la entrada del frente del Edith Breast Cancer Center. Los pacientes también pueden estacionar gratis en el estacionamiento de la esquina de S Grange Ave y W 18th Street. Entre por la puerta BB. No se necesita ninguna validación de estacionamiento.

**Comment by erincschwartz** [comment]
Reviewed in Dev, there are a few formatting inconsistencies and one language inconsistency between the word version linked above and what is presenting on the My Samples page. I will review with Deanna to confirm we want the changes made and report back in this issue.

**Comment by erincschwartz** [comment]
@Gbarra9 
Can you please update the My Samples pages (English and Spanish) in Dev with the following: 

- Remove this '+' sign (Deanna mentioned working with other programmers who were unable to remove it but might be worth a look?)
-![Image](https://github.com/user-attachments/assets/e667be00-f3f8-4240-9e41-812f4d71083c)

- Add spaces between these headers and the Option 1 text to be consistent with other formatting on this page:
![Image](https://github.com/user-attachments/assets/03719a78-0d91-4e1f-98c6-f9bdb3e0c076)

![Image](https://github.com/user-attachments/assets/ae30ea46-e0b0-4e98-b1af-93bbe76a3c35)

![Image](https://github.com/user-attachments/assets/ad1e10d0-f970-4c97-bb54-3d470358b36c)

**Comment by Gbarra9** [comment]
> @Gbarra9 Can you please update the My Samples pages (English and Spanish) in Dev with the following:
> 
> * Remove this '+' sign (Deanna mentioned working with other programmers who were unable to remove it but might be worth a look?)
>   -![Image](https://private-user-images.githubusercontent.com/157617486/394846548-e667be00-f3f8-4240-9e41-812f4d71083c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MzkxNTksIm5iZiI6MTczMzkzODg1OSwicGF0aCI6Ii8xNTc2MTc0ODYvMzk0ODQ2NTQ4LWU2NjdiZTAwLWYzZjgtNDI0MC05ZTQxLTgxMmY0ZDcxMDgzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQxNzQwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNWY1NTE0Y2FmMzE3ZGVkMmRkMGIyMmRhMWI5ZTRkMDY5ZGVkYzE1ODZiNTE0OTdlMmVmZjdhNDE3Y2JhZmZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cjO--a6ziGENc4nSmO7ihwT-V0aKQApXPKNr1ULm7ps)
> * Add spaces between these headers and the Option 1 text to be consistent with other formatting on this page:
>   ![Image](https://private-user-images.githubusercontent.com/157617486/394855855-03719a78-0d91-4e1f-98c6-f9bdb3e0c076.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MzkxNTksIm5iZiI6MTczMzkzODg1OSwicGF0aCI6Ii8xNTc2MTc0ODYvMzk0ODU1ODU1LTAzNzE5YTc4LTBkOTEtNGUxZi05OGM2LWY5YmRiM2UwYzA3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQxNzQwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOWFmNzZjNWI1NmE3MDQzNmQ4YzlmOTU3ODMyYWEwZWRmZWVhOGEzNmExOWMzYjc4ZGM2OTc1NWY4MmI1ODYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9bIZqvOvjwCUFYAguNFxZVTm7CUoAs8I9dF5XO9URNE)
> 
> ![Image](https://private-user-images.githubusercontent.com/157617486/394853438-ae30ea46-e0b0-4e98-b1af-93bbe76a3c35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MzkxNTksIm5iZiI6MTczMzkzODg1OSwicGF0aCI6Ii8xNTc2MTc0ODYvMzk0ODUzNDM4LWFlMzBlYTQ2LWUwYjAtNGU5OC1iMWFmLTkzYmJlNzZhM2MzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQxNzQwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Y2VjMmJiODcxYjI0YzczYmIyZTA1MTNlOGFlOTFjMWIyNTZhM2NiMTNkOTk4ZTQ0OTM1ODViNmIxMzkyYWUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aoY9eC-Ck-9fod53iII3LMdqA8ALdrHlmzZhncVFljg)
> 
> ![Image](https://private-user-images.githubusercontent.com/157617486/394853648-ad1e10d0-f970-4c97-bb54-3d470358b36c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MzkxNTksIm5iZiI6MTczMzkzODg1OSwicGF0aCI6Ii8xNTc2MTc0ODYvMzk0ODUzNjQ4LWFkMWUxMGQwLWY5NzAtNGM5Ny1iYjU0LTNkNDcwMzU4YjM2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQxNzQwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NjdiZGJjZmU3YWNhNzAzYzUzYTYzZDRmNDE1NTFjMTFiZTUzOWQ0OWE1NjllMDA2ZDA5MzFiYWM2YjU2MTRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.t68HH1lMGplZJzR_MjIR1ebZ0fXV0qh0MvYtL8NjEXo)

@erincschwartz Thanks for the update. I'll make the changes.

**Comment by Gbarra9** [comment]
@erincschwartz The changes are in dev and ready to be reviewed. Thanks.

**Comment by erincschwartz** [comment]
Tested in Dev, ready for Stage

- Reviewed in Dev, all spacing issues are resolved and '+' is removed.

**Comment by erincschwartz** [comment]
@Gbarra9 I realized when doing the side-by-side from Stage and the tracked version linked above that one minor edit is missing: 
![Image](https://github.com/user-attachments/assets/bca83f52-ae75-4b16-b747-cc6b3390cc00)


Can you please make this change in Stage (please note, this is not to be underlined, it was just that way with tracked changes)? This was also missed by the team doing the Spanish translation, please use this language for the Spanish My Samples page: “**Anúnciese en el mostrador de registro o información.**” 

Please let me know when this is ready for me to re-test. Thanks!

**Comment by erincschwartz** [comment]
Checked in Dev and Stage, edits look as expected. **Ready for Prod.**
