### ISSUE TITLE
ConnectFaas/PWA: Update Response handling from Submit Endpoint

### ISSUE THREAD

**Issue by JoeArmani** [episphere/connect#1168]
Update the 'submit' endpoint to await the response and return a response for all cases.

Implementation: This is used for response confirmation, in-app handling & communication, and question reversion when a response to a question fails to update server-side in Quest 2.

**Comment by JoeArmani** [comment]
This is in dev. It can be tested alongside ConnectApp and/or Quest 2 updates.
Successful test -> check survey response write operations in Quest 1 or Quest 2

**Comment by JoeArmani** [comment]
This is confirmed working based on Kelsey's survey data checks in testing scenario 4 from @cunneaq. Ready for stage.

**Comment by cunnaneaq** [comment]
tested in stage - responses stored after exiting and re-entering a survey

**Comment by JoeArmani** [comment]
ready for prod

**Comment by JoeArmani** [comment]
Closing - in prod
