### ISSUE TITLE
Adding check for previous clinical collection and update to Collection Data Entry screen (Biospecimen)

### ISSUE THREAD

**Issue by erincschwartz** [episphere/connect#1173]
We have had several cases where clinical collections have been linked to the wrong participant. In order to prevent this from occurring, please add a backend check to occur when the 'Submit' button is clicked on the Clincal Dashboard Collection Data Entry screen. 

- If team member enters a blood Accession ID a blood sample has previously been finalized for this participant, pop-up message should say "This participant already has a baseline blood specimen collected. Please confirm that you wish to proceed." Options: Confirm (moves on to Specimen Link) Cancel (goes back to Participant Search page)
-   If team member enters a urine Accession ID and a urine sample has previously been finalized for this participant, pop-up message should say "This participant already has a baseline urine specimen collected. Please confirm that you wish to proceed." Options: Confirm (moves on to Specimen Link) Cancel (goes back to Participant Search page)
- If team member enters blood and urine Accession IDs and both blood and urine urine samples have previously been finalized for this participant, pop-up message should say "This participant already has a baseline blood and urine specimens collected. Please confirm that you wish to proceed." Options: Confirm (moves on to Specimen Link) Cancel (goes back to Participant Search page)

Also, please update the display of name and add date of birthday to Collection Data Entry page under the participant's name

Participant Name: Last name. First Name (make this font slightly bigger than current)
DOB: mm/dd/yyyy
![Image](https://github.com/user-attachments/assets/ec94f793-c6fa-4c2d-9c28-7f4121915b4c)

**Comment by sonyekere** [comment]
This issue already exists - closing
