### ISSUE TITLE
User Profile sendGrid Email validation tracking on Firestore

### ISSUE THREAD

**Issue by rohanjay10** [episphere/connect#1177]
Related to issue: #1149 
Write sendGrid email validation results to a collection in Firestore. SendGrid classifies emails as "Valid", "Risky", or "Invalid"

**Comment by brotzmanmj** [comment]
Can we discuss what visibility we have without this (just via SendGrid UI) and what visibility we have with this? And also we need to discuss what requirements we need for how these data are stored in Firestore so they can be utilized for the operations intended purpose.

**Comment by rohanjay10** [comment]
Messaged with Hana and confirmed that she can access the sendGrid Validation tab, that Jessica referenced on issue #[1149 ](https://github.com/episphere/connect/issues/1149#issuecomment-2545799852)
> @HanaShiho please try accessing to this page as the image below, and let me know if you need any update.
> 
> <img alt="image" width="1427" src="https://private-user-images.githubusercontent.com/24559107/396136148-197929ad-fa91-4b0e-840a-824aa989f622.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MzM2MzAsIm5iZiI6MTczNDUzMzMzMCwicGF0aCI6Ii8yNDU1OTEwNy8zOTYxMzYxNDgtMTk3OTI5YWQtZmE5MS00YjBlLTg0MGEtODI0YWE5ODlmNjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDE0NDg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ZjU0MTk4YWJlNDk1OWFkOTk1ZjQwOGIyYTZjYzFjYzlkODk2YzAyMTIwZjBhYjEzYThjNzQ4YjVlM2IwMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-fP64o391_zTi7eWt0cRus8IgGccvUr6vpdfmyv1F2s">

**Comment by sonyekere** [comment]
Hi @rohanjay10 It has been discussed that we will no longer need to implement this, so closing this issue. We can connect on this soon!
