### ISSUE TITLE
Sendgrid Email Validation and Monitoring in SendGrid UI

### ISSUE THREAD

**Issue by rohanjay10** [episphere/connect#1180]
Related to issue #1149 

SendGrid email validation is currently used to validate emails for User Profile

- Currently the sendGrid validation dashboard shows validations done in the last 30 days in Dev/Stage, with the option to filter by email score, valid/invalid/risky. It also shows the number of unique invalidations.

- CSV exports can be done for those emails but PII has to be considered since they are email addresses from participants, who have consented but not yet verified, and would need to be stored securely. 

Previously discussed points:
•	The ability to monitor API calls and call history, if available in SendGrid as a log. This would be used by Communications team to check how many people had risky vs hard stops(to find pts who are facing issues with inputting emails)
•	Ability to track the number of user profiles that don't get submitted due to failing email validation
•	We would need a way to get back a list of api responses being done and saving it in the participant record(tracking in Firestore will not be done for now)

Please add any additional requirements

**Comment by brotzmanmj** [comment]
@rohanjay10 Hana will be monitoring this in the SendGrid UI so there is no development work needed at this time. I suggest we close this issue.
