### ISSUE TITLE
PWA Testing Feedback - University of Chicago

### ISSUE THREAD

**Issue by paulzakin** [episphere/connect#119]
Good news! All three of my testers (along with myself) were able to enroll successfully, which was the primary objective of this test.

They do have some other feedback which I have posted below. I suspect much of it isn't relevant yet, as the features are not yet built. However, I included it just in case you want to see it.

**From study manager #1:**
- The question: How did you hear about the study? No option for research staff. We don’t represent our research staff as clinical staff in the clinic. It would be good to add that option.
- Other: There is not a text field to specify. I would add this for the first 6 months at least.
- Consent: This looks like just a form. Assuming this will change to a video + form.
- All of the logos look squished. Even the Connect logo.
- There is a little forward sign above connect. I would assume that links to an email...but I guess it means take a picture/scan and send?
- Assuming all of the GitHub links will be removed. If not, that is super confusing. 

**From study manager #2**
- Agreed on the logos, photos blurry too.
- Consent form - currently blank. It's just going to be copy and pasted in there? No nice little storyboard of the informed consent process?
- After you do that module 1 - you get stuck. You get to the end and there is only a back button. Is that correct? I think it should say "Finish" or "Back to Dashboard" etc.
- Also was very slow for me, but that could have been my laptop!
- My feedback on the site manager dashboard: It seems way too premature to give feedback. However, will we be able to click on the bars and get a list of people? Will there be date ranges? Will it show additional study activities i.e surveys, biospecimens, etc.? It shows active/passive but not total? Unless it's meant to be that basic and if that's the case we likely wouldn't use it because I assume there will be some platform where we can export all the study activities like HealthPro and/or REDCap.

**From study manager #3**
- Password creation- should enter twice to confirm
- Photos blurry.
- Thanks for joining the landing page - no direction what to do next. We will have to answer calls to guide participants here.
- Clicked dashboard and it took a while for pin prompt to appear
- Module 1 back button - same issue.
- Slow
- That GitHub tab won't stay, will it?
- Where do I enter the token?
- I like how it asks if the phone # can receive texts and messages
- The management site looks like it will be useful. I like how you can see participant-level details. Note: when you look at participant details, the headings are a little" robot". For example, address = RcrtUP_AddressLn1_v1r0

**Comment by miagaudet** [comment]
Add some of the topics for OCPL and Deanna.

**Comment by TammyEllis** [comment]
Marshfield would also like to request to have the ability to filter and export any of the data in the Study Manager's Dashboard to manage downtimes and any QC that might need to be done. Thank you.

**Comment by brotzmanmj** [comment]
Hi Tammy, I added your comment to the Github project specifically for the Dashboard: https://github.com/episphere/dashboard/issues/124
