### ISSUE TITLE
submitParticipantData API Issue

### ISSUE THREAD

**Issue by don-martin** [episphere/connect#120]
It appears that if 2 or more json objects with valid tokens are sent in the submitParticipantData API call, the API is unable to handle the request.  Strangely, it appears that it is only the number of valid tokens sent that determines if the API will be able to return a 200 code.

Examples:
Send 2 or more valid tokens and 0 or more fictitious tokens: Error:  could not handle the request
Send 1 valid token and 0 or more fictitious tokens: success
Send only fictitious tokens: success

See the linked file for additional info and a specific example.

[SubmitParticipantData Git Hub Issue.txt](https://github.com/episphere/connect/files/4794071/SubmitParticipantData.Git.Hub.Issue.txt)

**Comment by bhaumik55231** [comment]
Hi @don-martin Would you please try again, you should be able to include 500 JSON objects in a single API call. The error **Error: could not handle the request** that you are getting is unexpected behavior. It should store the data associated with valid tokens and would neglect fictitious tokens without giving an error.

**Comment by don-martin** [comment]
It looks like the issue has been resolved.  I am no longer able to generate
a 500 response with any combination of valid/ invalid objects.  Thanks for
the quick response!

**Comment by bhaumik55231** [comment]
Thank you @don-martin for reporting this issue and quick re-testing 😄.
