### ISSUE TITLE
Participant Follow-up Tracking - Standardized Data Elements For NCI & IHCS exchange

### ISSUE THREAD

**Issue by dbakumar** [episphere/connect#121]
In GLC3 meeting, Mia & Michelle initiated discussion about participant followup tracking and data exchange between NCI and IHCS site for bio specimen collection.   This is just a proposal and NCI team needs to decide further discussion on this if needed. 

The benefit of standardized data variable (data item name/variable name) use in context of participant tracking  :  
1. IHCS will report participant followup details in standard way across the site
2. IHCS will able to develop algorithm or system rule to automated/manual follow-up with participant based on NCI follow-up status
3. NCI able to generate insight about site progress including follow-up level and reporting.
4. NCI and IHCS able to exchange information about participant refusal or withdrawal  
5. NCI will able to develop algorithm or system rule to automated/manual follow-up with participant based on IHCS follow-up
6. To improve the participant experience on communication from IHCS and NCI.
7. To use existing API infrastructure  (Submit Participant Data & Get Participant Information)

Example data variable : 
- NCI - Number of follow-up attempt  : after consent , before/after user profile , before/after bio specimen collection , questionnaire follow-up etc.
- IHCS  - Number of follow-up attempt  : before consent , before bio specimen collection (after consent, user profile and identify verification).
- follow-up mode :  letter, phone, email, text, app etc.
- follow-up date
- follow-up reason : to consent, to bio-specimen appt etc
- follow-up status : reachable, not reachable if available

**Comment by Davinkjohnson** [comment]
believe we have this already.
