### ISSUE TITLE
Get Participants Data Filter

### ISSUE THREAD

**Issue by don-martin** [episphere/connect#122]
Would it be possible to filter the results returned from the getParticipants API based on whether or not a participant had a "studyId" in the "state" object?  For patients with a "notyetverified" status, we have a different workflow for patients with a studyId (Invited) vs patients without a studyId (self-enrolled).  This enhancement isn't vital, but it would simplify our process.  Thanks for considering.

For reference, the studyId field below is what I'm talking about.
{
    "data": [
        {
            "RcrtUP_City_v1r0": "Sioux Falls",
            "state": {
                "uid": "EYaPo4ILzFNb1SBCNzOl1FbNCgt1",
                "studyId": "SH00050",
                "RcrtSI_Account_v1r0": 1,
                "RcrtV_Verification_v1r0": 0
            },
            "RcrtES_Aware_v1r0": {
                "RcrtES_Aware_v1r0_Family": 0,
                "RcrtES_Aware_v1r0_Invite": 0,

**Comment by bhaumik55231** [comment]
Hi @don-martin we can return the data that has **studyId**, but our database doesn't support query to return data that **doesn't have studyId**.

**Comment by FrogGirl1123** [comment]
Hi @don-martin and @bhaumik55231 we have a passive vs active recruit flag.  You should be able to do a query based on "notyetverified" and the recruitment type flag. Correct, @bhaumik55231?  I'll go over the flags when we present the data dictionary and Concept IDs at the next F&R meeting.

**Comment by bhaumik55231** [comment]
@FrogGirl1123 Yes, we can have a filter to get an active or passive recruit. But passive recruit not always means that they don't have a studyId in their record. For example if someone mistypes the PIN they will be labeled as passive recruit but would still have studyId in their record.

**Comment by FrogGirl1123** [comment]
@bhaumik55231 Agreed, that's something that needs to be resolved as part of the verification process.

**Comment by dbakumar** [comment]
I have encountered this issue and it would really helpful to have filter by "notyetverified".  This approach saves lot of API calls and will change IHCS programming how we build identify verification module/reporting. Thanks for consideration @bhaumik55231  and @FrogGirl1123 .

**Comment by sonyekere** [comment]
Closing issue. Last update posted 08/2020.
