### ISSUE TITLE
Add 2nd and 3rd as options to the Suffix drop down in the user profile

### ISSUE THREAD

**Issue by FrogGirl1123** [episphere/connect#123]
@bhaumik55231 Could you please add the "2nd" and "3rd" as additional options for the suffix drop down menu in the User Profile of the PWA? I have added the additional options to the data dictionary here: https://nih.app.box.com/file/693543685476 and started a change log in the same document. @naiyume could you please add the new corresponding Concept IDs to the data dictionary and update the change log when you are done?

**Comment by naiyume** [comment]
The Concept IDs are now on the github, I will move them over to box.

**Comment by bhaumik55231** [comment]
Done!
