### ISSUE TITLE
Biospec - Dshbrd   visit type button

### ISSUE THREAD

**Issue by StephanieWeinstein** [episphere/connect#125]
on the Participant check in screen, for the drop down menu for visit type, can you default this to the baseline visit?
@bhaumik55231 
(sorry, I don't have permission to assign this to biospecimen)

**Comment by bhaumik55231** [comment]
@StephanieWeinstein I have given you permission to triage issues.

**Comment by StephanieWeinstein** [comment]
> 
> 
> @StephanieWeinstein I have given you permission to triage issues.

I still don't see triage options on the right hand side of my screen the way Michelle does.
@bhaumik55231

**Comment by bhaumik55231** [comment]
@StephanieWeinstein You would have received an invitation link in the email id associated with your Github account. Please access that invitation.

**Comment by StephanieWeinstein** [comment]
> 
> 
> @StephanieWeinstein You would have received an invitation link in the email id associated with your Github account. Please access that invitation.

ok, I got the invitation and accepted it, then I logged out and logged back in, but I still don't see the triage buttons.

**Comment by bhaumik55231** [comment]
> ok, I got the invitation and accepted it, then I logged out and logged back in, but I still don't see the triage buttons.

You will be able to see **assignees** on the right side of the issues page. If you click on the cog logo you would be able to assign them.

![image](https://user-images.githubusercontent.com/26577910/90437658-bee09580-e0a0-11ea-9327-7d76d866dfb3.png)
