### ISSUE TITLE
Biospec- Dshbrd- Vary list of tubes by site and subsite

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#129]
We will need to vary the list and images of tubes that display by site and subsite. Some sites will be more tubes than others and the photos of the tubes will differ. We will provide a final list of expected tubes per site (not yet available) but want to make sure this functionality exists.

**Comment by StephanieWeinstein** [comment]
@bhaumik55231 
Here is a link to the Excel file which shows which tubes need to display for which sites: https://nih.box.com/s/8xvuv5d80iase7s6p7w7a5x1i6qgjtk5
you should be able to access it now.

**Comment by StephanieWeinstein** [comment]
@bhaumik55231, I just added the tubes/bags for Henry Ford clinical collection to the above Excel file.  It will be the same as what most of the KPs have.
