### ISSUE TITLE
Move file storage to Box/Google Cloud.

### ISSUE THREAD

**Issue by geetajoshi2019** [episphere/connect#13]
Now that we have GCP can we make this as issue and please move our Heroku Data/Code to GCP?

**Comment by geetajoshi2019** [comment]
Hi Jonas - We would like to move content from Heroku to GCP so we can make progress on API UI/Dashboard. Would you please grant Praful and Bhaumik access so they can move content?

**Comment by danielruss** [comment]
@bhaumik55231 this appear to be complete.. ok to close
