### ISSUE TITLE
Biospec- Dshbrd- Photo for urine and mouthwash tubes

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#132]
We will be adding a photo of urine and mouthwash containers to the collection and processing screens, so will need room for these.  Do you want placeholders photos for now? (we will eventually have Norma take photos of our actual tubes which we will need to put in)

**Comment by bhaumik55231** [comment]
I will add them when we have actual photos of those tubes.

**Comment by wyattks** [comment]
Closing - will open new issue when photos of the tubes have been taken with clear instructions on where they go
