### ISSUE TITLE
Biospec- Dshbrd- Unique staff login and change history

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#134]
Need each staff member to log in separately and our system needs to keep track of which staff member did what (change history, audit trail). Does this already exist, and is the audit trail accessible/searchable?

**Comment by bhaumik55231** [comment]
Yes, it already exists and we have logs for audits.

**Comment by bhaumik55231** [comment]
Closing this issue. Please reopen it if I'm missing something.
