### ISSUE TITLE
Biospec- Dshbrd- Add Collection Site to Specimen Link Page

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#136]
Please add a drop down menu on the Specimen Link page called "Select Collection Site".  The drop down menu will be specific for each collection group.  A  list of sites for each group is being collected now.

**Comment by bhaumik55231** [comment]
@wyattks moving this issue on hold, for now, let me know when we have the list ready.

**Comment by wyattks** [comment]
Attached is a list of collection Sites.  The Henry Ford site will depend on which dashboard they are using.  They will have both Clinical
[Connect Collection site locations for dashboard drop downs.xlsx](https://github.com/episphere/connect/files/5263178/Connect.Collection.site.locations.for.dashboard.drop.downs.xlsx)
 and Research collections.

**Comment by wyattks** [comment]
Some decisions still need to be made so please hold off on working on this for now!

**Comment by StephanieWeinstein** [comment]
Bhaumik, here is a document describing several variable related to location of specimen collection.  Please review and let us know if you have any questions.  I think this provides everything you need to now move forward on this issue.  
 https://nih.app.box.com/file/723332082925?s=dbl60licke8lpiorbzoeq2fkrgmum3vs

**Comment by bhaumik55231** [comment]
Done!
