### ISSUE TITLE
Biospec Dshbrd - Participant Check-Out Screen for Research Workflow

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#140]
We need to add a Participant Check-Out screen to the research workflow.  Please see the attached example.

[Research Check Out Screen.docx](https://github.com/episphere/connect/files/5170553/Research.Check.Out.Screen.docx)

**Comment by bhaumik55231** [comment]
Hi @wyattks where would this checkout screen fit? In the word document, it is displayed after Ready for Shipment, but we don't have the Ready for Shipment screen in Biospecimen Dashboard?

**Comment by wyattks** [comment]
HI Bhaumik - it would go after the Finalize Screen.  And Finalize should be changed to Ready to Sip.

Thanks!

**Comment by bhaumik55231** [comment]
Got it, Thanks!
