### ISSUE TITLE
Sex at birth - concept id (848089812) is not received through getParticipants API

### ISSUE THREAD

**Issue by dbakumar** [episphere/connect#146]
As part of identity verification, site needs to pull participant data and sex at birth (848089812) data item is missing in getParticipants API response.

**Comment by bhaumik55231** [comment]
Hi @dbakumar check out 383945929. This was the original concept Id assigned to SEX and accidentally got deleted when we were trying to remove duplicate concepts and a new concept was assigned to SEX which was 848089812. We have restored it back to 383945929.

**Comment by bhaumik55231** [comment]
Closing the issue. Please reopen if you have any problem. Thank you!
