### ISSUE TITLE
Connect App profile

### ISSUE THREAD

**Issue by Jsawyer1** [episphere/connect#152]
I was allowed to misspell the name on the consent when signing.

**Comment by hzhao392** [comment]
We do not have a requirement on matching the name with the signature right now. Please let us know if this is needed.

**Comment by brotzmanmj** [comment]
Our system will not know the name of the person signing the consent - we won't have anything to match against. The sites would catch this during the verification step.

**Comment by Davinkjohnson** [comment]
stale
