### ISSUE TITLE
Connect App profile-iPad 

### ISSUE THREAD

**Issue by Jsawyer1** [episphere/connect#156]
I entered the wrong spelling on last name and the verify last name box went away. It did not flag for misspelling when submitting information. It also did not flag for incorrect email, DOB, and wrong sex. It did warn me that the date of birth did not make me eligible for the study, but I was able to press continue anyway and submit the information.

**Comment by hzhao392** [comment]
Closing as it is the same as https://github.com/episphere/connect/issues/153
