### ISSUE TITLE
Connect App dashboard-iPad

### ISSUE THREAD

**Issue by Jsawyer1** [episphere/connect#159]
Dashboard did not refresh after selecting verify email. It took 3 times selecting verify email, getting the email in mailinator.com and trying to link from the email to finally get to the page where I was able to enter a PIN and move forward to entering the profile information.

**Comment by bhaumik55231** [comment]
Hi, @Jsawyer1 Did you had to click 3 times to receive a verification URL?

**Comment by Jsawyer1** [comment]
Yes, for some reason it did not send the email link to verify right away. I went to my participant's email to check for the verification email and because it had not been received I went back to the app to request again. It took three times. Eventually, all the verification emails went through but for some reason, it got held up.

**Comment by Davinkjohnson** [comment]
stale
