### ISSUE TITLE
User Profile and verification feedback

### ISSUE THREAD

**Issue by muessigkr** [episphere/connect#165]
Test member CO126, I entered  a spelling error in the first name (Nelsan instead of Nelson) wrong DOB year 2000, and for the email address 2nd entry gmail instead of .com.
When trying to submit 3 times, only one error at the time was highlighted to be resolved. e.g. 1. verify name; 2. email;, DOB. 
The summary overview showed for suffix a number 537892528. I had entered "3rd".
I used an iPad. Lots of things to enter on a tablet...time consuming.

When getting to the Identity Verification on KPCO SMS, I received an error message for all 2 options to enter (Cannot verify, Add to Cohort, Verify).
![image](https://user-images.githubusercontent.com/64497530/95396396-b2650600-08b5-11eb-9287-a941cdc39e11.png)

**Comment by muessigkr** [comment]
Comment about another person KPCO129.
Wrong state, sex entered were not questioned or caught when submitted
Email/phone are not required indicated by a red star as other fields but emails comes up when trying to submit. I think email and phone should be both mandatory as well. If we need to communicate with members we need this info.
DOB: the month is listed as number and spelled out. Could be wrongly indicated as day and month.
When using a tablet, a message to 'verify your email' did not appear, and the dashboard did not show, I had to access the menu to get there.

**Comment by Davinkjohnson** [comment]
stale
