### ISSUE TITLE
Mobile compatible?

### ISSUE THREAD

**Issue by cyndeekphi** [episphere/connect#166]
I was attempting to do the Connect PWA testing on my work cellphone, however I found it difficult. Or perhaps it is the iPhone 7 that I am using, maybe too old? The images do not load so the important "Join Now" button is also not visible.

FYI:  the iPhone's Automatic Updates are turned on. It is currently running iOS 13.5.1, "the latest software update allowed by your administrator"

**Comment by hzhao392** [comment]
We will be addressing these issues during UI/UX testing and review
