### ISSUE TITLE
USER TESTING: AGE, User Profile feedback

### ISSUE THREAD

**Issue by muessigkr** [episphere/connect#168]
KPCO-132.
I'm using an iPad. 
1. When accessing the Connect app holding the tablet upright, the header sections don't show, so I cannot see the e.g., dashboard icon only the 4 lines for the menu which gets me to the dashboard. When holding the tablet horizontal, I can see the header row; though when navigating through the questions [Please verify email, enter Pin, how did you hear] those text first row vanishes under the header sections. Turning the tablet back upright, the questions show without issue, though the headers are not visible.
2. Entering User Profile: 
- When getting to this screen, it starts showing with the middle of the page [Suffix] and no arrow or hint indicate to scroll up.
- Entering DOB: for year I can scroll from1954-1980. There is no information, that there is a specific age [year] range required or what to do if the birth year cannot be selected from options shown. Though, I can enter typing in another year e.g., 2003. When submitting after resolving other errors like email, the year finally pops up to check on. 
- Why not showing all errors at once?
- Email/ phone not marked as required. Email comes up when submitting anyway. 
- Autofill is very annoying when trying to type in anything like email, names etc. Had repeated "corrections" through autocorrect, which makes it easy to submit typos or other errors.
- email address should not be case sensitive KP versus Kp
- I can copy and paste the first email address into the repeated entry field, to disable?
- for states suggestion to include acronyms as well.
- question: Have you been diagnosed with cancer is optional- I assume intended but some people might not know or are not sure. Option IDK to add?
- submit:  a little pop up: "please check for errors" next to the submit button would be helpful/ a user friendly option. I don't see any reason why submit  does not work immediately and finally scrolled up to see that I made an error.

**Comment by Davinkjohnson** [comment]
stale
