### ISSUE TITLE
User Profile - Suffix

### ISSUE THREAD

**Issue by cyndeekphi** [episphere/connect#171]
I logged in as a Passive recruit using an iPhone 7 (iOS13.5.1) and added "Sr" for Suffix.  On the Connect website User Profile, the suffix now displays as "undefined"

**Comment by strennr** [comment]
After adding a suffix, the profile review screen is showing the concept ID for our selection instead of the user supplied value.  For example, instead of "Jr." it is displaying "612166858).

**Comment by hzhao392** [comment]
The data from the Connect site is going to be different set from the site CRM so its possible there are discrepencies in names and other user profile

**Comment by brotzmanmj** [comment]
Hui, do we need to fix that it is displaying what appears to be a concept ID maybe (numeric code) rather than the value 'Jr' that cyndee entered?

**Comment by bhaumik55231** [comment]
@brotzmanmj Suffix is a selection category and all responses are stored as concept Ids.

**Comment by brotzmanmj** [comment]
@bhaumik55231 When the participant see the list of categories they can choose on the PWA, they should see the response categories, right, and not the concept IDs? Even though we are storing as concept IDs.

**Comment by bhaumik55231** [comment]
Yeah they will see labels, not concepts.

**Comment by brotzmanmj** [comment]
@bhaumik55231 so the issue reported with concept codes showing for Suffix rather than the labels, is already fixed?

**Comment by bhaumik55231** [comment]
@brotzmanmj there was never an issue, it was already showing labels in the PWA before this issue was created. If they are fetching data using API then it will show them Concepts.

**Comment by bhaumik55231** [comment]
![image](https://user-images.githubusercontent.com/26577910/96298809-162bb500-0fc1-11eb-94b0-c44e5c94e454.png)

**Comment by brotzmanmj** [comment]
Got it. Thanks for the screenshot and explanation. I'm closing the issue.
