### ISSUE TITLE
Module completion issues

### ISSUE THREAD

**Issue by strennr** [episphere/connect#172]
This may have been addressed elsewhere (and previously), so feel free to close if needed:

1.  We are having issues completing module 1.  There doesn't appear a way to submit and move onto the next module.  This is happening for all testers at our site and we are using Chrome.  The only option is the "back" button.

2. If we don't clear the browser cache, we are taken to the last completed module question for the previous user even if we previously signed out.  This may be an issue for households with multiple recruits sharing the same device.

**Comment by hzhao392** [comment]
Questionnaire is still being worked on and has not been integrated with the connect PWA
