### ISSUE TITLE
Connect App Customization

### ISSUE THREAD

**Issue by strennr** [episphere/connect#174]
Is it possible to allow site customization on some of the questions, especially for active recruits once a PIN is entered that associates with a IHCS?

For the "How did you hear about this study?" question, the "MyChart invitation" does not apply to Marshfield and presumably some other sites as well.

**Comment by brotzmanmj** [comment]
For the "How did you hear about this study", we have decided to display the same list for all sites. We think it will not be a burden for participants to ignore those that don’t apply to them. We have circulated the list to the study managers to confirm that it encompasses all active and passive recruitment modes and will provide the final list to Bhaumik when available. Thanks.

**Comment by hzhao392** [comment]
Closing per Mia
