### ISSUE TITLE
PWA - user profile - data entry validation

### ISSUE THREAD

**Issue by dbakumar** [episphere/connect#175]
Need data entry validation for the below fields
1.	Birth Year dropdown in user profile page stopped at 1980. I was not able to select year past that. 
2.	Mobile/Home Phone Validation is not done. I entered all 0’s and the system still accepted it.

**Comment by hzhao392** [comment]
1980 is correct as the age range for Connect is 40-70. All zeros are still going to be considered to be valid as we dont know if a phone number exists or not
