### ISSUE TITLE
PWA Feedback - HFHS

### ISSUE THREAD

**Issue by Eusuf2000** [episphere/connect#176]
![hfhs_feedback_page1](https://user-images.githubusercontent.com/57463904/95622958-8034df00-0a42-11eb-974b-1758d88b21c4.jpg)
![hfhs_feedback_page2](https://user-images.githubusercontent.com/57463904/95622989-8cb93780-0a42-11eb-8a47-4270c1e821d6.jpg)
![hfhs_feedback_page3](https://user-images.githubusercontent.com/57463904/95623002-917deb80-0a42-11eb-8a62-4c57cfafafd7.jpg)

**Comment by hzhao392** [comment]
Closing after review by @FrogGirl1123 and @miagaudet
