### ISSUE TITLE
User Profile Feedback

### ISSUE THREAD

**Issue by BrandiR-KPGA** [episphere/connect#177]
For Study ID CO111, I misspelled the first name, entered the wrong DOB, a different sex than assigned, and another test subject's email address. Also, before entering the user profile page, I signed the consent with the wrong spelling of the test subjects first name. I also did not select the box directly above the signature panel.

**Comment by hzhao392** [comment]
We currently do not verify name from Connect as its a different set of data from the site CRM.

**Comment by brotzmanmj** [comment]
Hui, is there an issue with the box above the signature panel? The participant shouldn't be able to submit the consent without checking that box. Thanks.

**Comment by bhaumik55231** [comment]
@brotzmanmj Check box is already a required field on the consent screen.

![image](https://user-images.githubusercontent.com/26577910/96296416-3eb1b000-0fbd-11eb-9849-bea0657fa329.png)
