### ISSUE TITLE
"Thanks for joining...Study" message prior to verifying email 

### ISSUE THREAD

**Issue by brookekpco** [episphere/connect#178]
The messaging does seem to flow in a logical manner. When a recruit clicks "join now" and enters an email address the message that appears is " Thanks for joining the Connect Study" and there is no instruction about needing to verify one's email address to proceed with the enrollment process. Plus, they haven't joined the study yet. 
I had to navigate to the "Dashboard" to find the message about needing to verify my email address. I don't think participants will know to do this. 
Suggest that after entering an email address that the pop-up message be the "Please verify your email" & include the blue button to verify. Also include instructions about what will happen next.

**Comment by hzhao392** [comment]
The email in the Dashboard is only for contact information, there is no verification of the email just like any of the other data that is gathered in the dashboard.

**Comment by brotzmanmj** [comment]
It seems like from Brooke's comments the communications from the PWA are not as clear as they could be in this step. Hui, can we try to replicate and walk through what she is seeing?

**Comment by hzhao392** [comment]
Hi @brookekpco can you attach a screenshot of where you are expecting the verification? perhaps I'm talking about a different location than what you've reported

**Comment by brookekpco** [comment]
[Screenshots PWA testing_VerifyEmail.docx](https://github.com/episphere/connect/files/5388528/Screenshots.PWA.testing_VerifyEmail.docx)

**Comment by Davinkjohnson** [comment]
This functionality is significantly different in prod now.
