### ISSUE TITLE
Alpha Testing - Create Account

### ISSUE THREAD

**Issue by geetajoshi2019** [episphere/connect#19]
Here are requirements for the Create Account (Alpha Testing)
There are some questions by business group. Please address them or should we meet as Jonas returns?
https://nih.app.box.com/file/498633069223

**Comment by meganstead** [comment]
Alpha Tester feedback from Vijay:

https://app.box.com/file/533538811942

**Comment by meganstead** [comment]
BACKLOG ITEM - Reach out to Google, is there a workaround when 3rd party cookies are blocked?

**Comment by bhaumik55231** [comment]
We will address this issue at a later stage, possible solution at https://github.com/firebase/firebase-js-sdk/issues/865.

**Comment by meganstead** [comment]
Hackathon feedback from KPCO:  Allow multiple accounts to be created in the same browser session.

**Comment by meganstead** [comment]
Hackathon feedback from KPCO:  The authentication code time-out is set for 15 seconds.  We recommend it be set to 30 to 60 seconds.

@bhaumik55231 - if DevOps has a reason why we shouldn’t do this, please let us know and document it.

**Comment by bhaumik55231** [comment]
I checked on this. The actual timeout for the code is more than 1 minute. The timeout you see is for code resending. So for some reason, if you don't receive the code initially, you would be able to click on a button that resends a new code after 15 send.
![image](https://user-images.githubusercontent.com/26577910/66444412-25247280-ea11-11e9-8516-2fe919fdf9b2.png)

**Comment by meganstead** [comment]
From 11/06/19 Alpha Tester meeting - 

Please look into auto-redirect functionality from the email verification to the web/app

**Comment by meganstead** [comment]
10/16 [Hackathon ](https://app.box.com/file/540210218509)update - Connect system should continue even if email is not verified.

**Comment by danielruss** [comment]
This appear to have been competed.
