### ISSUE TITLE
Biospec - Dshbrd - Search Page Phone Number

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#190]
For both the Clinical and Research dashboards, on the search page, please show format for the phone number.  i.e. xxx-xxx-xxxx

**Comment by anthonypetersen** [comment]
is this still needed? not seeing a phone number option when searching for participants

**Comment by anthonypetersen** [comment]
@wyattks going to try to knock this out today... can you confirm that this only needs fixed on the Research Dashboard? Not seeing a Phone Number search option on the Clinical Dashboard.

**Comment by wyattks** [comment]
Yes just on the research dashboard

**Comment by anthonypetersen** [comment]
pushed to dev
