### ISSUE TITLE
Biospec - Dshbrd - Activate Scanning ability 

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#192]
Please make all scanning options active for testing.  
Research Dashboard: Specimen Link, Collect/Process
Clinical Dashboard: Specimen Link, Labeling and Receipt

**Comment by bhaumik55231** [comment]
It should already be activated. Please give it a try.

**Comment by bhaumik55231** [comment]
Closing it, please re-open if you still have issues.

**Comment by wyattks** [comment]
Hi Bhaumik,   Is it possible to activate the scan function when the user clicks in the box?  It is a little confusing that you have to click on the barcode to pull up the scan function.  We want to make it more intuitive.  This would be on the following screens in both dashboards: Specimen Link; Labeling and Receipt, Collect/Process

**Comment by bhaumik55231** [comment]
Hi, Kathleen, I have it set up as a separate button because if the user wants to manually type in, then it would still pop up the scanner. For example, in the collect/process screen each tube has 1 field for tube ID(full specimen ID), if we do not have a separate button for scanning it will pop up the scanner even if they are trying to type in manually.

**Comment by wyattks** [comment]
Ok is there a way to make it clearer that they are supposed to click on the barcode to pop up the scan function?

**Comment by bhaumik55231** [comment]
@wyattks we can have the button at the start of the field instead of at the end. Would that help?

**Comment by wyattks** [comment]
It might.  we can get feedback during testing as well.

**Comment by bhaumik55231** [comment]
Hi Kathleen @wyattks , I tried putting the scan buttons at the start of the field, but it doesn't align well with other fields. Please see the image below.
![image](https://user-images.githubusercontent.com/26577910/101801738-a6c3d480-3adc-11eb-9874-bbd77e2e3498.png)

**Comment by wyattks** [comment]
HI Bhaumik,
Ok can we add in wording to indicate they should click on the barcode to scan?

**Comment by bhaumik55231** [comment]
Yeah, that would work.

**Comment by wyattks** [comment]
Thanks!  We just want to make it obvious what they have to do to scan

**Comment by wyattks** [comment]
Wording can be something like: "Click here to use camera to scan barcode"

**Comment by wyattks** [comment]
Completed
