### ISSUE TITLE
Update User Profile

### ISSUE THREAD

**Issue by bhaumik55231** [episphere/connect#199]
https://nih.app.box.com/file/501193852134

**Comment by brotzmanmj** [comment]
One additional change to user profile has been added to specifications document in Box: Add 'other phone' with yes/no for permission to leave voicemail. This also become part of the requirement that at least one phone number be provided and that can be mobile phone, home phone, or other phone.

**Comment by brotzmanmj** [comment]
One more change to user profile... we'd like to add a double manual entry of the Preferred Email. We only need to store it once in the data, but include on-screen error message if the double entry doesn't match.

**Comment by brotzmanmj** [comment]
As part of her review of transitional language on MyConnect, Deanna has updated the Introduction Text at the start of the user profile (after the user submits consent). Please refer to the new Introduction Text on the User Profile criteria document: https://nih.app.box.com/file/501193852134

**Comment by depietrodeanna** [comment]
Updated user profile criteria document (what appears after user submits consent): https://nih.app.box.com/file/501193852134 
Rearranged order of questions and made minor additional edits.

**Comment by Davinkjohnson** [comment]
stale
