### ISSUE TITLE
Check if the exact same submission has been created before.

### ISSUE THREAD

**Issue by PrafulB** [episphere/connect#2]
If a Site sends the exact same file with no change in any record 2 or more times, this needs to be flagged by QC. Maybe create a hash of each submission and store in the masterFile?

**Comment by aMaloneKPCO** [comment]
Hello Praful,
What is the context for this email?    Is this a requirement for all data content posted to the Connect API?   I do agree a hash table is a practical method to track data (and reduce duplicates) sent to the Connect API.

Allen Malone
Sr. Data Specialist
Institute for Health Research
Kaiser Permanente Colorado

**Comment by danielruss** [comment]
In addition to our side, need the sites to make sure they don't verify the same user twice.

**Comment by bhaumik55231** [comment]
Not relevant anymore.
