### ISSUE TITLE
Biospec- Dshbrd- Clinical Labeling and Receipt workflow

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#200]
Consolidate the Deviations onto the Labeling and Receipt page.   We would like to have everything, scanning of specimen ID and deviation selection, on one page and not one two separate pages.  Add column for deviation drop downs and name it Deviation Type.  If the check box for deviations is selected have the dropdown "activate" so the user can choose the deviation type.  Once a deviation type is selected have a pop up with free text space for additional comments.  If Comments are entered they should also appear on the page.   See attached for example.

[Clinical Updated Labeling and Receipt Page 13Nov2020.docx](https://github.com/episphere/connect/files/5537773/Clinical.Updated.Labeling.and.Receipt.Page.13Nov2020.docx)

**Comment by bhaumik55231** [comment]
@wyattks What happens for tubes not collected? Are we still asking for the reasons in a different screen?

**Comment by wyattks** [comment]
For clinical collections, the person entering the tubes into the system will not know the reason the tubes were not collected.  We do not need to capture the reasons.

**Comment by bhaumik55231** [comment]
And for research collection, everything stays as it is now?

**Comment by wyattks** [comment]
Yes the research page should stay as it is now.

**Comment by wyattks** [comment]
As discussed today, remove the check box from the page and make the first selection in the dropdown area "None".  Make "None" the default selection for the drop down.

**Comment by wyattks** [comment]
Clinical Labs will now be collecting Urine in addition to the blood samples.  We need to add in a spot on the Clinical Labeling and Receipt screen for the Urine samples.   Please add after the Yellow Top ACD tube and before the biohazard Bag.  

The tube has been added to the nomenclature file: https://nih.app.box.com/file/728481198995 

I have updated the Mockup to include the changes.  https://nih.app.box.com/file/752449089210

**Comment by wyattks** [comment]
Closing - any remaining actions to take will be put into a new issue.
