### ISSUE TITLE
Biospec - Dshbrd - Research Specimen Link Page

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#209]
Update the Research Specimen Link page to include the following:
  o	Add a section called "Participant Collection" that will include a table with columns for Collection ID, Visit, Collection Date, and Action, where the sole action will be a Continue to Collect/Process button
      o	  The link for ‘Continue to Collect/Process’ should be disabled after the specimens in that collection are received at 
                  Norma’s lab (the BSI API will push to tell us they were received)
o	Add a header for Start a New Collection
      o	Add a button for select visit type (default to Baseline) right after the heading for ‘Start a New Collection’- this is being 
                moved here from the check-in screen
o	Make sure the headings are visibly distinct for ‘Participant Collection’ and ‘Start a New Collection’ as these are essentially now two different parts of the screen. The navigation buttons at the bottom of the screen need to be more clearly associated with the ‘Start a New Collection’ set of activities and not the page as a whole.

Please see the mock-up located in box:   https://nih.app.box.com/file/742719859703

**Comment by bhaumik55231** [comment]
@wyattks can the link to **Continue to Collect/Process** be disabled after the specimen is Finalized?

**Comment by wyattks** [comment]
We want to leave it open in case there is a straggler tube.

**Comment by bhaumik55231** [comment]
@wyattks So then we don't lock it until Norma receives the tube?

**Comment by wyattks** [comment]
yes when she receives all the tubes or 3 days past the shipment date.

**Comment by bhaumik55231** [comment]
I would imagine the same thing would apply to clinical workflow?

**Comment by bhaumik55231** [comment]
Got it, Thanks Kathleen @wyattks

**Comment by wyattks** [comment]
yes  Thank you
