### ISSUE TITLE
Alpha Testing - Consent

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#21]
The consent requirements are ready for DevOps: https://nih.app.box.com/file/498658793646

**Comment by meganstead** [comment]
Two additional pieces of feedback:

1) Name (first and last) will be stored encrypted - @ashreves - kindly update the consent requirements and comment when complete. @bhaumik55231 - once requirements are updated please update configuration accordingly. 

2) Should   we offer touch signature for touch screens?- One of our sites said AoU does   this and people like it, asked us to consider. Add to our internal prep   meeting agenda for next week?

**Comment by brotzmanmj** [comment]
New requirement from NIH IRB meeting 1/21/2020: Each site must have a unique consent form. So the PDF that is displayed at the end of the consent process (on the page where they give consent) needs to be unique for each site. @bhaumik55231
