### ISSUE TITLE
Shpg - Dshbrd - Add Contact Information to Manifests

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#213]
A site specific contact person and phone number needs to be added to each manifest.  A list of contacts and phone numbers will be provided.

**Comment by robertsamm** [comment]
The format for the contact info for each site's shipping manifests should be like below. We will provide the name/email/phone at a later date.
Contact Info:
Full Name
Email
Phone Number

**Comment by wyattks** [comment]
Shipping Locations with Contact information have been added to the following file in box:
https://nih.app.box.com/file/883717580538

**Comment by Davinkjohnson** [comment]
Does contact info need to be "dynamic" and pulled from a current doc, or can it be stored in the code? 
Dynamic = L 
Static = S

**Comment by wyattks** [comment]
It can be stored in the code.

**Comment by Gbarra9** [comment]
Important Note: To thoroughly test, test accounts should be made for one site account. Accounts under NCI will have an empty Site Contact Information as seen below.

    'NCI': 'National Cancer Institute',
    'KPGA': 'Kaiser Permanente Georgia',
    'SFH': 'Sanford Health',
    'UCM': 'University of Chicago Medicine',
    'KPHI': 'Kaiser Permanente Hawaii',
    'MFC': 'Marshfield Clinic',
    'KPNW': 'Kaiser Permanente Northwest',
    'KPCO': 'Kaiser Permanente Colorado',
    'HP': 'HealthPartners',
    'HFHS': 'Henry Ford Health System'

Given the account's registered site location, the correct site contact information will be displayed on the manifest. Below Images are two accounts. One registered under NCI and one registered under MFC.

On the Shipping Page 
<img width="800" alt="Shipping Screenshot 1" src="https://user-images.githubusercontent.com/33293205/146070578-645fba0e-a8d6-4f23-a0d7-09463399f674.png">

NCI Site Account
<img width="1334" alt="Shipping manifest NCI" src="https://user-images.githubusercontent.com/33293205/146070622-3b0ba778-7af5-499a-ac09-6cbc7eea1489.png">

MFC Site Account 
![MFC Manifest](https://user-images.githubusercontent.com/33293205/146070693-a3a1a542-0e07-4138-8b3d-fa9469c57503.png)
