### ISSUE TITLE
Shpg - Dshbrd - Alert/Comment Tracking

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#214]
Need ability to set up alerts about specific packages and add comments/notes to the packages.  For example - If a package was not picked up by the courier when expected.

**Comment by brotzmanmj** [comment]
Need to determine where this should go on the dashboard. If it's before the box if finalized, we could give them a place to enter a comment about a box on last page in the workflow. If after it is 'finalized', the Box will no longer be accessible to add data to in that workflow so would need to include it elsewhere, perhaps in the form of a Notification to Norma's lab.

**Comment by wyattks** [comment]
Closing- alert will be launched from Norma's dashboard which still needs to be developed.  If sites needs to let Norma know specifics about a shipment - for now they will have to email.
