### ISSUE TITLE
Biospec - Dshbrd - Update Clinical Specimen Link Page

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#217]
Please update the Clinical Specimen Link page to include entering in the Accession ID and the previous collection table.  Please see example located in box:
https://nih.app.box.com/folder/121993753390

**Comment by wyattks** [comment]
Hi Bhaumik,  I made two additions to the Clinical Specimen Link page:
1 - if KPHI is the collection site, they will need to have the drop down in order to select Oahu or non-Oahu
2 - If they have to type in the Accession ID, they will need to enter it twice

**Comment by wyattks** [comment]
HI Bhaumik,
Entering in the Accession ID will be required for KP Site.  For Henry Ford sites this will not be a requirement as they will not have the accession ID on their tubes.

**Comment by bhaumik55231** [comment]
Hi Kathleen do you have a mock-up handy? Where would this fit in? Specimen link screen?

**Comment by bhaumik55231** [comment]
Just noticed the heading needs to be included in the Specimen Link Page. So just KPHI will see these Accession ID fields?

**Comment by wyattks** [comment]
No all the KP sites need the Accession  ID fields.  I have attached a mock-up
[Updated Clinical Specimen Link Page.docx](https://github.com/episphere/connect/files/5653573/Updated.Clinical.Specimen.Link.Page.docx)

**Comment by bhaumik55231** [comment]
Thanks for the document @wyattks. Is the Accession ID required for all KP sites or just KPHI?

**Comment by wyattks** [comment]
Hi Bhaumik,
We want to make the verification of the Collection ID a pop up and not have it just located down at the bottom of the Specimen Link Page.  Please see example in box: https://nih.app.box.com/file/742724565401

**Comment by wyattks** [comment]
HI Bhaumik,
On the Clinical Dashboard, the Accession ID field needs to be present on the table in the Specimen Link Page. It is a required field for all the KP sites to fill in (not just KPHI).  It will not be required for Henry Ford but can still be included in the dashboard for Henry Ford.

**Comment by bhaumik55231** [comment]
Hi Kathleen @wyattks , Should I show the accession ID for all sites and only make it required for KP Sites?

**Comment by wyattks** [comment]
Yes please

**Comment by bhaumik55231** [comment]
I have added it to the Specimen Link page. Please verify and close the issue. Thanks!

**Comment by bhaumik55231** [comment]
Please re-open if needed.

**Comment by wyattks** [comment]
Please remove the Is Collection Correct wording from the bottom of the Specimen Link page.  Now that the question is in the pop up we do not need it on the page.  Also please make sure the buttons in the pop up match what is in the mock up: 
Please see example in box: https://nih.app.box.com/file/742724565401

**Comment by bhaumik55231** [comment]
Hi @wyattks I'm not making any changes to UI/UX at the moment as my plate is overloaded and have other priorities.

**Comment by wyattks** [comment]
ok

**Comment by wyattks** [comment]
Closing - main request was completed.
