### ISSUE TITLE
Shpg - Dshbrd - Temperature Monitors

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#218]
The randomization of the temperature monitors by the system is not needed, Norma will be handling this.  Disable that function and remove the single check box currently in place and replace it with a question that appears for every shipment: "Does this shipment include a temperature monitor? If yes, in which box?" [dropdown of all the boxes being shipped].

**Comment by robertsamm** [comment]
Please make the select the box that contains the temp monitor bigger make bigger, have it default to blank, and make it a required field if they checked it off on the packing page.  Also spell out “Temperature”

**Comment by wyattks** [comment]
If a temp monitor is being used, please make the user select a box for it's location and add that to the box's manifest.  I thought this capability was  there but in going through the shipping dashboard it was no longer there.

**Comment by FrogGirl1123** [comment]
@wyattks and @naiyume I think this needs a variable in the dictionary too, I'll add to the list and let you know when the update is available.

**Comment by FrogGirl1123** [comment]
@wyattks @naiyume Never mind, it's already there.
