### ISSUE TITLE
Biospec - Dshbrd- Collection Setting

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#221]
Please add variable ‘Collection Setting’. The three categories will be Research, Clinical, or Home. If a sample was entered into the Research dashboard, it will by default be 'research'. If entered into the clinical dashboard, it will by default be 'clinical'. And if entered into the home collection dashboard (to be developed), it will by default be 'home' . 

This should apply at the level of the Collection ID and for all of the tubes that are part of that Collection ID. 

It does not need to display on the dashboard because it is always a default. However, we do need this variable to be available for reports, queries, and metrics.

**Comment by bhaumik55231** [comment]
Hi Nicole @FrogGirl1123, we will need a concept ID for this.

**Comment by brotzmanmj** [comment]
Hi Bhaumik, it would be used to filter reports and used for analyses, among other things. So you could see a report of all specimens or you could filter it to see only specimens collected in a clinical setting. Or for selection for assay, you could use it to exclude specimens collected at home, if appropriate. Is this what you meant?

**Comment by bhaumik55231** [comment]
@brotzmanmj I was thinking about a wild scenario where a collection Id is duplicated across research and collection settings. If that scenario is impossible then neglect my earlier question.

**Comment by brotzmanmj** [comment]
I see. I can't think of any scenario where that would happen.

**Comment by bhaumik55231** [comment]
Thank you Michelle @brotzmanmj. I have added the Collection Setting concept and closing this issue.
