### ISSUE TITLE
Shpg - Dshbrd - Reports/Queries page

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#222]
Here is the mockup of the Reports/Queries for the shipping dashboard: https://nih.app.box.com/file/745227310483 This should go on the home page under 'Report/Queries'. We may request to add more reports and queries at a later time, but these are the initial two we want to start with.

**Comment by wyattks** [comment]
We have reduce the report requirements to only one table displaying what has been shipped for the prior 30 days, with the newest additions at the top of the list, to reduce the size of the list. I have added the variables at the bottom of the mock-up page but some still need the concept IDs to be created.  We will not be using a filter on the different columns but will utilize google search to find specific shipments. We are making this report MVP.  If additional report needs are identified once we launch, we will add new issues for those reports.

**Comment by Davinkjohnson** [comment]
L

**Comment by Gbarra9** [comment]
@wyattks @HopkinsDC 
From our discussion in changing appearance of the existing reports/query page's table:

Remove Column
- "Courier"
- "Number of Tubes"
- "# Tubes Received"

Change Column
- "Status" to "Received(Yes/No)"

Add Column
- "Comments"

Reports/Query Table (Without Updates)
![episphere github io_biospecimen_ (4)](https://user-images.githubusercontent.com/33293205/146214342-9e470dbe-a2eb-4c75-9cc4-2e911ab72d6d.png)

Reports/Query Table (With Updates)

![localhost_5000(6)](https://user-images.githubusercontent.com/33293205/146214736-2996f868-ae81-4c74-8b5d-c1b6369c2e7e.png)

**Comment by wyattks** [comment]
Waiting on concept IDs to be created to fully test.

**Comment by wyattks** [comment]
Concept IDs are available now so the report can be finalized.  Thanks!
