### ISSUE TITLE
Biospec- Dshbrd- Update Middle Initial on Participant Search and Results Page

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#223]
On both the Clinical and Research dashboards please update Middle Initial to Middle Name in the participant Search page and participant search results page.

**Comment by bhaumik55231** [comment]
Hi Kathleen @wyattks, we do not have a middle name on the participant search page.

![image](https://user-images.githubusercontent.com/26577910/100798407-9e3f1000-33f1-11eb-9f67-534929974c20.png)

**Comment by wyattks** [comment]
OK this will just apply to the results page.  Thanks!
