### ISSUE TITLE
SSN 

### ISSUE THREAD

**Issue by miagaudet** [episphere/connect#225]
1. SSN should be asked as standalone module. 
2. The module should be visible in the list of randomized questionnaire modules.
3. Research dashboard -- see issue #139

**Comment by bhaumik55231** [comment]
Hi Mia, SSN is already included as a standalone module in PWA.

**Comment by bhaumik55231** [comment]
Duplicate of https://github.com/episphere/connect/issues/215

**Comment by bhaumik55231** [comment]
Research dashboard #139 will remain open, closing this one.

**Comment by brotzmanmj** [comment]
On biospecimen research dashboard check-in screen, the Connect staff need to be able to enter the SSN for a participant if they have not already provided it (if the participant provides it verbally in person at check in). And we would like the participant at check-in to be able to enter it securely on a keypad if they do not want them to provide it verbally to the Connect staff.

**Comment by bhaumik55231** [comment]
Hi @brotzmanmj we will track it at #139 .
