### ISSUE TITLE
Shpg - Dshbrd - Error message for Bags scanned

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#229]
Four error messages are needed when bags are being scanned to be placed in a box.  Currently if an ID not on the list is scanned a quick pop up appears but disappears very quickly.  Depending on the scenario, we need the following error messages to pop up:

1 - When an ID is scanned that has not been entered into the system as having been collected: "Item not reported as collected.  Go to the Collection Dashboard to add specimen."
2 - When an ID is scanned that the system shows as already being in a box, the box number the bag should be in should show: "Item has already been recorded as being placed in box 5".  
3 - When an ID scanned that the system shows as already shipped: “Item reported as already shipped.”
For this last one we are still discussing how this scenario will be handled.

**Comment by wyattks** [comment]
Closing - will open new issue if needed when site feedback is complete.

**Comment by anthonypetersen** [comment]
Size: M

**Comment by Gbarra9** [comment]
Notes to self:

Error Message References

No Shipping Location Selected from dropdown
<img width="502" alt="Screen Shot 2022-07-19 at 9 48 09 AM" src="https://user-images.githubusercontent.com/33293205/179766315-d181b095-e6b0-47e6-9d25-62fb91c5cf57.png">


Adding an empty input with spacebar inputs
![Screen Shot 2022-07-18 at 9 58 36 AM](https://user-images.githubusercontent.com/33293205/179765529-5c0726d4-499e-4675-90a3-c05ec5c5b5eb.png)

Check and search if item scanned is already shipped (Checks Specimen Bag ID and Full Specimen ID)
<img width="502" alt="Screen Shot 2022-07-19 at 9 46 51 AM" src="https://user-images.githubusercontent.com/33293205/179766042-50655441-e0d7-45a0-a1b1-c21e8e8f7499.png">

Check and search if item scanned is already added to the Box#s, not yet shipped, (Checks Specimen Bag ID and Full Specimen ID)
![Screen Shot 2022-07-18 at 9 55 50 AM](https://user-images.githubusercontent.com/33293205/179765906-715e49fe-3deb-4daa-93e6-ab9e17a41dc2.png)

Not found in either Available Collections table or hidden Orphan Table
<img width="499" alt="Screen Shot 2022-07-19 at 9 49 49 AM" src="https://user-images.githubusercontent.com/33293205/179766647-ce9c2d08-b318-4889-8c26-a067d546be64.png">

**Comment by Gbarra9** [comment]
@wyattks I believe this issue is related to the ongoing bug involving orphan tubes not being properly found via search bar.
There were problems in the past that involved orphan tubes not being properly added to the Orphan Table that remains hidden at the moment. 

This bug is similar to [Issue#542](https://github.com/episphere/connect/issues/542) where one of the straggler tubes was not found. I suspect this bug involves adding to the hidden orphan table. I'll try and take a look if I can resolve this bug.
