### ISSUE TITLE
Shpg - Dshbrd - Tab Labeling

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#230]
Change the Tab labeled "Shipping" to "Packaging"

**Comment by robertsamm** [comment]
Also change the final page for shipment tracking info to a separate tab titled "Review and Ship". This page should have two buttons 1. "return to shipment tracking" and 2. "return to packaging"

**Comment by robertsamm** [comment]
The tabs should all be navigable to where a person can click on one of the previous tabs to go back to the previous page
