### ISSUE TITLE
Biospec - Dshbrd - Master Spec ID Error on Specimen Link Page

### ISSUE THREAD

**Issue by robertsamm** [episphere/connect#232]
Can you please add an error that pops up if staff scan in an incorrect Master Specimen ID on the Specimen Link page? They should get an error if it does not start with CX.

**Comment by bhaumik55231** [comment]
Hi @robertsamm, the camera will only detect barcode starting with CXA.

**Comment by bhaumik55231** [comment]
Closing it, please re-open if you have any issue.

**Comment by robertsamm** [comment]
@bhaumik55231 Thanks Bhaumik. When we add the next set of samples (e.g. first follow up), we will move to CXB, then CXC and so forth. So at some point we will need to allow the camera to detect the different CX Master Specimen IDs.

**Comment by bhaumik55231** [comment]
Thank you, Amelia, for the clarification. It would now allow all Master Specimen IDs that start with CX and are 9 characters long. Master specimen ID starting with CXA, CXB, CXC ..... CXZ would be considered valid.

**Comment by robertsamm** [comment]
Perfect, thanks Bhaumik!
