### ISSUE TITLE
Shpg - Dshbrd - Shpmt Tracking #

### ISSUE THREAD

**Issue by robertsamm** [episphere/connect#240]
1. Shipment scan box manual entry should require them to entire it twice
2. FedEx tracking info have a required field for number of digits of tracking number – @wyattks  will look up the Fed-Ex tracking number format

**Comment by wyattks** [comment]
The FedEx tracking number is a 12 digit number in the following format 9999 9999 9999. Please put a QC check in when the sites enter a number it must have 12 digits excluding the spaces.

**Comment by wyattks** [comment]
When you enter in multiple tracking numbers, move to the next screen, realize a mistake was made on one and go back to the tracking page, it does not retain any of the tracking numbers that were inputted.  Is it possible to have it retain the inputted numbers if you have to go back and make a change so you don't have to input all the numbers again?  If a site is setting up multiple boxes for a shipment this would be helpful to them.

**Comment by wyattks** [comment]
World Courier's tracking number if 9 digits, all numbers.

**Comment by wyattks** [comment]
Closing   - will open new issue if needed when site feedback is complete.
--

**Comment by wyattks** [comment]
Reopening - need to still complete: Shipment scan box manual entry should require them to entire it twice

**Comment by Davinkjohnson** [comment]
Size: S
