### ISSUE TITLE
Biospec - Dshbrd - Update labeling on Biohazard bags

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#244]
In both the Research and Clinical dashboard please update the Biohazard Bag labels on the Collect/Process and Labeling and Receipt pages to the below.

Research Collect/Process Page:
8- Biohazard bag- please update label to '8- Biohazard bag blood/urine'
9- Biohazard bag- please update label to '9- Biohazard bag mouthwash'

Clinical Labeling and Receipt Page:
6- 'Biohazard bag'- please update label to 'Biohazard bag blood/urine' 
Add a place underneath that for a second biohazard bag that will be labelled '7- Biohazard bag extra'. The 'extra' bag they can use for tubes that arrive late and need to be shipped in a separate bag. They will use one of the extra ID labels for this bag (the ones that end in 0050-0054)

**Comment by FrogGirl1123** [comment]
@wyattks  Hi Kathleen, currently we only have one Biohazard bag variable for the clinical dashboard which can be populated by with the extra label IDs, which then needs to be flagged when extra labels are used.  It sounds like I need to add a variable for the extra bag to the dictionary.  Is it possible that the research process could also use an extra bag variable?  
Also, in the future please assign me and Madhuri to any issues you post that might require changes or additions to the Biospecimen data dictionaries.

**Comment by wyattks** [comment]
HI Nicole,
Yes I will make sure to add you both to the cases.  Yes we will need to add a variable or the extra bag to both the clinical and research.

**Comment by StephanieWeinstein** [comment]
Nicole, 
We are also going to need an extra bag for two KP sites that will be pouring urine into containers for shipping (all the other sites will be able to transfer to tubes, so those will go in the same bag as the blood tubes).  I have it on my to do list to discuss any other changes we might need for urine now that the clinical sites are also collecting it, but we have not had this discussion yet.  So not sure if you want to hold off on this until we have a full list of changes, or go ahead as we will definitely need it (for KPGA and KPHI in case that matters).

**Comment by wyattks** [comment]
Closing - will open new issue if still needed.
