### ISSUE TITLE
Biospec - Dshbrd - Review Complete Button Navigation

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#249]
On the Clinical dashboard's Receipt Summary screen, when the button labeled "Review Complete" is selected, navigate the user back to the "Participant Search"  screen and not the Home/Welcome screen.

**Comment by bhaumik55231** [comment]
Hi @wyattks, It was initially going back to participant search, but was modified after https://github.com/episphere/connect/issues/224.

**Comment by wyattks** [comment]
Yes.  After discussions it was decided to change it back to the participant search screen.

**Comment by bhaumik55231** [comment]
Is also applicable to the research dashboard or just the clinical dashboard?

**Comment by wyattks** [comment]
Research should remain as it is.  Currently it goes to the Check-Out screen.  So keep it that way.  Thanks!

**Comment by bhaumik55231** [comment]
After checkout should it go back to participate search?

**Comment by wyattks** [comment]
yes.  Check-out should go back to participant search
