### ISSUE TITLE
Biospec - Dshbrd - During testing Barcode scan function not working

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#250]
During Testing Amelia and I have both been unable to use the scan barcode function in the dashboards.  What we tried so far where it will not work:
Clinical: Specimen Link; Specimen Search; Tube scan on Labeling and Receipt
Research: Specimen Link; Specimen Search; Tube Scan on Collect/Process 
Devices tried on: iPhone and PC using Chrome 

Issue: When you go to scan the labels, the scan function will open up and ask to use the device camera.  It then proceeds to search for the barcode and appears to register the barcode is present but does not capture the barcode and keeps searching.  It does not pull in any information from the barcode into the dashboard.

**Comment by bhaumik55231** [comment]
Hi Kathleen,

I'm also having the same issue. The issues seem to be with the camera quality. As the barcodes are small in size, the open-source barcode scanning library is having a hard time detecting them. It works with a very good quality camera, which is not available on most devices.

Is there a way that we can utilize the white space around barcodes and make them a little bigger? If not then I'm afraid we will have to use a licensed version of the barcode scanner.

**Comment by wyattks** [comment]
I can check with Norma on the possibility of making the barcode larger.  With everything we need on the label it might not be possible.

**Comment by wyattks** [comment]
HI Bhaumik- what is the name of the scanner program we are using?

**Comment by bhaumik55231** [comment]
Quagga js - https://serratus.github.io/quaggaJS/

**Comment by wyattks** [comment]
Thanks

**Comment by wyattks** [comment]
Hi Bhaumik,  Unfortunately we can't increase the size of the barcode.  Both Amelia and I tried scanning with a QR Code app and were able to get the barcodes to scan with our phones.  Norma also tried with an app called Scandit and was able to get them to scan.  She said she used Code 128 to embed the data.  Not sure if that information helps.

**Comment by bhaumik55231** [comment]
Yes, my code is looking for code 128 encoded barcodes. If you try scanning the image below it would work.

![PXL_20201211_195500014](https://user-images.githubusercontent.com/26577910/102129352-350dc280-3e1d-11eb-830f-bd6632f94038.jpg)

**Comment by wyattks** [comment]
I tried and couldn't get it to scan.

**Comment by bhaumik55231** [comment]
> I tried and couldn't get it to scan.

That is weird, it works on my [phone](https://photos.app.goo.gl/Lfu5H5MhqoBvm4RC9). Anyway if it is not practical to increase the size of the barcode then we will have to purchase a licensed version.

**Comment by wyattks** [comment]
I tried on both my phone and ipad.

**Comment by wyattks** [comment]
Scanning is still not working - remove the use of the camera for scanning but allow a handheld scanner to input into the scan field.

**Comment by wyattks** [comment]
Issue #275 is related

**Comment by wyattks** [comment]
The only place the scanning ability is not turned on is for the research and clinical Specimen Link pages.  I am not able to scan in to either of those.  I was able to use the scanner on the collect/Process page of the research dashboard.  Let me know if the function on the specimen link page can be activated and I will try there.

Thanks

**Comment by wyattks** [comment]
scanning function now works with handheld scanner at all locations.
