### ISSUE TITLE
Alpha Testing - Dashboard Draft for IHCS Project Managers

### ISSUE THREAD

**Issue by FrogGirl1123** [episphere/connect#26]
The draft for the IHCS project manager's dashboard is here https://nih.app.box.com/file/506145134411

**Comment by meganstead** [comment]
From [11/6 Alpha Tester](https://app.box.com/file/552256467704?sb=/activity) meeting - Could the count of created/shared tokens be included as a metric on the dashboard?

**Comment by meganstead** [comment]
From [11/6 Alpha Tester](https://app.box.com/file/552256467704?sb=/activity) meeting - will Sites send status of recruitment via API: refusals, those who have exhausted the contact attempts and no-response, etc. On an individual level or in aggregate? We will need this info to generate recruitment stats. Would be ideal to have it at individual level.
