### ISSUE TITLE
Biospec - Dshbrd - Error Pop ups

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#261]
Can the Error pop ups be moved into the middle of the screen?  Currently they are situated to the right hand of the screen and on tablets the entire message does not show unless you scroll over.  In their current location it is easy to miss that it popped up.  We want them more noticeable so having them pop up in the middle of the screen would be helpful.

This applies to any error that needs to pop up on both the clinical and research dashboards.

**Comment by bhaumik55231** [comment]
All pop-ups would appear in the middle of the screen, try it out, and re-open the issue if needed.
