### ISSUE TITLE
Biospec - Dshbrd - Mouthwash Bag ID entry

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#263]
On the research Collect/Process screen, when the mouthwash container is not collected, a Full Specimen ID is still required to be entered into the system for the Biohazard bag mouthwash.  You cannot save the information without entering this ID. Please change this so the Full Specimen ID is only required for the Biohazard bag mouthwash when the Mouthwash Container has been marked as collected.

**Comment by bhaumik55231** [comment]
It has been fixed. Please try it out and re-open the issue if needed.
