### ISSUE TITLE
New Opt-Out Variable

### ISSUE THREAD

**Issue by sarah-hague** [episphere/connect#267]
Could you please consider adding a new opt-out variable "Declined via MyChart" or something to denote individuals who opt out or decline participation following a MyChart recruitment message.
Thanks!

**Comment by FrogGirl1123** [comment]
Hi Sarah,
I have added it on my list of updates for the Recruitment dictionary.  I'll post to Gitter when the next round of updates are ready.

**Comment by Davinkjohnson** [comment]
implemented
