### ISSUE TITLE
BioSpec Research Dashboard - Shipping Tracking Information

### ISSUE THREAD

**Issue by amandamensing** [episphere/connect#270]
When I try to pack boxes, the "Shipping Tracking Information" screen will not load. The screen shows a circle that it's loading, but even after 30-45 minutes nothing happens. Using Chrome for the internet browser.

**Comment by StephanieWeinstein** [comment]
Hi Amanda,
Have you tried logging out and back in again?  If it still does not work, please enter the problem into the Excel feedback document in Box that NORC sent out.  If you continue having trouble, or have other issues, please enter into the Excel document or email NORC if its a more urgent issue (we will not be using gitter for testing feedback for now).  Thank you!

**Comment by naiyume** [comment]
Hi, I changed a few things, could you try again and see if you come across the same problem? If it doesn't load within a minute or two, then please let me know.

**Comment by amandamensing** [comment]
Hello - 
It works great now. 
Thank you!
