### ISSUE TITLE
biospec- dashboard - Blank when I try to get on

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#273]
When I select the biospecimen dashboard website I am getting a blank screen with connect up in the left hand corner.  I am not even getting an option to login.  The link I am using is: https://episphere.github.io/biospecimen/#dashboard

Mandy also tried and had the same result.

**Comment by bhaumik55231** [comment]
It should be working now.

**Comment by bhaumik55231** [comment]
Closing the issue.
