### ISSUE TITLE
Biospec - Dshbrd - Case Sensitivity

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#274]
Allow all manual entry areas in both the clinical and research dashboards to accept lower case entries in addition to the upper case entries.  Manual entries are located on the following pages:
Clinical - Participant Search: Scan in Full Specimen ID    
Clinical - Labeling and Receipt page: Scan Full specimen ID        
Clinical - Specimen Link page: Scan in Accession ID and Scan Collection ID                                                                                 Research - Participant Search: Scan in Full Specimen ID 
Research - Specimen Link Page: Scan Collection ID                  
Research - Process: Scan Full Specimen ID                 
 Shipping -  Packaging: Scan Specimen Bag ID or Full Specimen ID                                                                                    
Shipping - Shipment Tracking Information: Scan Tracking Number                                                                                     
Shipping - Summary and Receipt: Sign off pop-up

**Comment by bhaumik55231** [comment]
Hi Kathleen @wyattks, Our database doesn't support case insensitive search, So for example, if someone searches for **cxa123456** it will not return anything even if we have a record for **CXA123456**. One hack we can do is we can allow lower case inputs but convert them to uppercase before we perform any search or store them.

**Comment by wyattks** [comment]
Allowing lower case inputs and converting them to upper case would work. This was a common feedback from all the site testing.

**Comment by anthonypetersen** [comment]
Clinical - Participant Search: Scan in Full Specimen ID

Not required anymore, option to search for participant by Full Specimen ID no longer on Clinical Search

**Comment by anthonypetersen** [comment]
Clinical - Labeling and Receipt page: Scan Full specimen ID
Research - Process: Scan Full Specimen ID

Seems like we are already allowing non-capitalized entries and storing them in an uppercase format

**Comment by anthonypetersen** [comment]
Clinical - Specimen Link page: Scan in Accession ID

Accession Number Format will not include letters, don't need to worry about case sensitivity

**Comment by anthonypetersen** [comment]
Clinical - Specimen Link Page: Scan in Collection ID 
Research - Specimen Link Page: Scan Collection ID

Already capitalizing manually entered Collection IDs in code

**Comment by anthonypetersen** [comment]
Shipping - Packaging: Scan Specimen Bag ID or Full Specimen ID 
Shipping - Shipment Tracking Information: Scan Tracking Number 
Shipping - Summary and Receipt: Sign off pop-up

Added calls to convert text fields to uppercase before comparisons are made in code.

**Comment by HopkinsDC** [comment]
I'm getting an "Not Found" message when I enter an ID with lowercase letters, but when I use uppercase letters, it find the sample bag. (See attached photos of both instances
![Screen Shot 2021-11-23 at 1 36 18 PM](https://user-images.githubusercontent.com/85250133/143084468-a82a6942-5fd2-48f3-90ef-3f2689ccc0cd.png)
![Screen Shot 2021-11-23 at 1 40 02 PM](https://user-images.githubusercontent.com/85250133/143084478-d5b4918c-1815-49b4-9baf-6e540953482b.png)
).
