### ISSUE TITLE
Biospec - Dshbrd - Scanning Function

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#275]
Want to switch off of using the camera function on the iPads/computers to using a hand held scanner to scan IDs into the dashboards.  Below is a list of all the scan areas on the clinical and research dashboards:

Clinical   - Participant Search: Scan in Full Specimen ID    
Clinical - Labeling and Receipt page:   Scan Full specimen ID        
Clinical -   Specimen Link page: Scan in Accession ID and Scan Collection ID                                                                                   Research - Participant Search: Scan in Full Specimen ID 
Research -   Specimen Link Page: Scan Collection ID                  
Research - Process: Scan   Full Specimen ID                    
Shipping -  Packaging: Scan   Specimen Bag ID or Full Specimen ID                                                                                    
Shipping - Shipment Tracking Information: Scan Tracking Number

**Comment by wyattks** [comment]
Issue #250 is related

**Comment by Davinkjohnson** [comment]
"XS" effort (Assuming fix to 250 is working)

**Comment by wyattks** [comment]
I updated issue #250 with a comment about the specimen link page not allowing for scanning.  Will close this issue and keep 250 open to continue tracking.
