### ISSUE TITLE
Biospec - Dshbrd - Module Statuses on Checkout screen

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#277]
On the Research Checkout screen, show Statuses of all Modules not just the incomplete modules and update in real-time.  If a participant completes a module during the visit and before they are checked-out, have the system update the module status as soon as it has been completed.

**Comment by wyattks** [comment]
This issue will rely on PWA changes being complete.

**Comment by brotzmanmj** [comment]
On hold until we have all the surveys in the MyConnect app and the flags functional
