### ISSUE TITLE
Participant requested delay to a later time

### ISSUE THREAD

**Issue by meganstead** [episphere/connect#28]
Define option for invitee to indicate they would like to delay participation to a later time

**Comment by danielruss** [comment]
@brotzmanmj  ok to close?  Is this is the Recruitment workflow?

**Comment by hzhao392** [comment]
@brotzmanmj is this something on the site's side or ours

**Comment by hzhao392** [comment]
Pending site decision, if used we will need a flag

**Comment by Davinkjohnson** [comment]
Maybe re-visit this. (Not sure if this falls within the current refuse/withdrawal with return option.)
