### ISSUE TITLE
Biospec - Dshbrd - Search by date of birth on ipad

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#284]
On both the clinical and research dashboards "Participant Search" screen, enable to user to manually enter in the date of birth when they are using an iPad/tablet.  Currently on the iPad/tablet, users don’t have a choice to type in the birthdate, only option is to use the calendar function which the sites found to be inefficient.  Users are able to manually type this information in when using a computer.

**Comment by wyattks** [comment]
On my iPad air2, I'm still getting the calendar popup and am unable to type the birthdate in.

**Comment by iqbal-singh** [comment]
Hi @wyattks,

You may have to clear your history and website data on your iPad in order to see the new changes on episphere.github.io/biospecimen

**Comment by wyattks** [comment]
Thanks I will try

**Comment by wyattks** [comment]
I put this back in the to do list.  I just tried and the iPad is still forcing me to use the calendar and I can't type in the birthdate.

**Comment by wyattks** [comment]
I am able to type in the birthdate now but it does not bring back any results.  I get the participant with entered search criteria not found.  But when I search for the same participant using their last name results are returned.  I used Isabell Intersex 03/08/1980 for the search.
 
I tried with one of my other participants with the same result.

**Comment by iqbal-singh** [comment]
> I am able to type in the birthdate now but it does not bring back any results. I get the participant with entered search criteria not found. But when I search for the same participant using their last name results are returned. I used Isabell Intersex 03/08/1980 for the search.
> 
> I tried with one of my other participants with the same result.

Hi Kathleen,
This issue should be fixed now. The bug was caused because the month and day values were being reversed.
