### ISSUE TITLE
Biospec - Dshbrd - Research - Combine Check-In with Check-Out and add Screen Headers

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#290]
On the Research dashboard, combine the Check-In and Check-Out screens, add headers above the boxes to explain what is being viewed.  

Add the following headers:
1- Add "Confirm participant has consented, been verified and has not withdrawn. " above the Consent and Verified boxes.  
            - As part of this, we need to have a box added to the screen showing participation status. Show what the status is in words.
2 - Add ""Has SSN been entered?" placed above the SSN Entered box
3 - Add "Are Initial Surveys complete? " above the Baseline Module Boxes  
4 - Add "Baseline sample status" above the baseline sample boxes 
5- Add "Incentives" along with ax Incentive eligibility box showing if the participant is eligible to receive incentives. Green check for yes and red X for no.

Below the Baseline sample status boxes, we need to add two buttons and change the wording of one button:
1 - Change the "Exit" button to "Cancel" This will take the user back to the Participant Search screen without saving any information.
2 - Change the "Check-In And Continue" button to "Check-In", this would complete check in thereby triggering the biospecimen questionnaires, 
           -  When the Check-In button is pressed, add a pop up notifying the user "Success! Participant has been checked in.  Select Option" with the options being "Return to Participant Search" or "Continue to Specimen Link".  Make sure the navigation matches the buttons.
           
3 - Add an "End Visit" - Press if person decides not to continue with any collection once they arrive.

Below the Incentives eligibility box, add a "Check-Out Complete" button.  This button will take the user back to the participant Search screen.

See attached Mock-up for all changes to be made to the screen.

[Research Combine Check-In Screen and Check-Out Screens.docx](https://github.com/episphere/connect/files/7281164/Research.Combine.Check-In.Screen.and.Check-Out.Screens.docx)

**Comment by Davinkjohnson** [comment]
Likely "Medium/Large" (Need more info from Kathleen on the 2nd part of this)

**Comment by wyattks** [comment]
Make sure all status boxes listed above are updated in real-time.  Issue #276 Mentions this for the Check-Out screen.

**Comment by Davinkjohnson** [comment]
@iqbal-singh Please see the original requirements to ensure these sub-headers are updated on the Check-in/out screen. If you need some further clarity reach out to @wyattks (today preferably). 

@wyattks Can you also confirm the Font sizes? (I believe we said make the "sub headers" the same size/font as the new "Login method" text)
