### ISSUE TITLE
Biospec - Dshbrd - add samples not collected reasons

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#293]
On the research Review screen,  add the optional details for why samples were not collected.   Currently just the dropdown selections are shown, the sites would like the optional details to be displayed on the screen as well.

**Comment by wyattks** [comment]
Duplicate of issue #286

**Comment by anthonypetersen** [comment]
@Davinkjohnson does this need to be back here for some reason? looks like it was closed as a duplicate
