### ISSUE TITLE
Shpg - Dshbrd - Add Enter Button for search bar

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#295]
On the Packaging screen, add an "Enter" button for the Search Bar.
[Shipping Packaging Enter Button Addition.docx](https://github.com/episphere/connect/files/6338946/Shipping.Packaging.Enter.Button.Addition.docx)

**Comment by Davinkjohnson** [comment]
Size: S

**Comment by Gbarra9** [comment]
https://user-images.githubusercontent.com/33293205/144920868-68d2d5e7-cefd-4e8b-b0d1-76d388a253a9.mov

@wyattks @HopkinsDC  
I haven't merged this change to dev yet. Please let me know if any changes are needed for the enter button. Thank you.
