### ISSUE TITLE
Shpg - Dshbrd - add Error warning for review Ship

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#296]
On the Shipping Packaging screen, add a pop-up error if the Review/Ship button has been selected without a box or boxes having been selected from the "Boxes in Process" section.  The pop-up error should say "Please select Box(es) to review and ship."  Currently the system will proceed to the next page without any data present.
See attachment.

[Shipping Packaging Warning for reveiw ship button.docx](https://github.com/episphere/connect/files/6338993/Shipping.Packaging.Warning.for.reveiw.ship.button.docx)

**Comment by anthonypetersen** [comment]
Size: S

**Comment by Gbarra9** [comment]
<img width="649" alt="Screen Shot 2021-12-29 at 10 37 49 PM" src="https://user-images.githubusercontent.com/33293205/147720791-1febbc49-7b85-473b-a612-d184bf5ae425.png">
