### ISSUE TITLE
Shpg - Dshbrd - Change pop-up Title

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#298]
On the shipping packaging screen, change the pop-up title when a bag ID has been scanned in from "Add Specimens" to "Specimen Verification".
See attachment

[Shipping Packaging Change pop-up Title.docx](https://github.com/episphere/connect/files/6339059/Shipping.Packaging.Change.pop-up.Title.docx)

**Comment by anthonypetersen** [comment]
Size: XS
