### ISSUE TITLE
Shpg - Dshbrd - Order Specimens by tube type and not Full Specimen ID

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#299]
On the shipping packaging screen, when a bag ID has been scanned in, have the Specimens in order by Type/Color and not by the Full Specimen ID.  Sites would like all tubes from one tube type listed next to each other.  Currently on  the dashboard the tubes are listed by their Full Specimen IDs so similar tubes types will not show up next to each other. 
See attachment.

[Shipping Packaging Order by tube type and not Full Specimen ID.docx](https://github.com/episphere/connect/files/6339098/Shipping.Packaging.Order.by.tube.type.and.not.Full.Specimen.ID.docx)

**Comment by anthonypetersen** [comment]
@wyattks would we want a secondary sort on Full Specimen ID after we have sorted by Type / Color? Also is there a preferred order you would like to see for Type / Color?

**Comment by anthonypetersen** [comment]
Size: S

**Comment by wyattks** [comment]
Yes a secondary sort would be a good idea.  We need the tubes in the following order:
SST
Heparin
EDTA
ACD
Urine

**Comment by Gbarra9** [comment]
This issue may be resolved from a previous code change.
<img width="614" alt="Screen Shot 2021-12-22 at 1 16 03 PM" src="https://user-images.githubusercontent.com/33293205/147137568-0df930b4-ade7-49a5-8125-c0793e3d3e10.png">

**Comment by Gbarra9** [comment]
An Image of the sort by tube type.
<img width="619" alt="Screen Shot 2021-12-22 at 6 02 26 PM" src="https://user-images.githubusercontent.com/33293205/147189647-11c9f87c-4fad-4902-8582-356cfad906a5.png">

**Comment by wyattks** [comment]
Yes that is perfect. Thank you

**Comment by wyattks** [comment]
Linked to issue #421
