### ISSUE TITLE
API status

### ISSUE THREAD

**Issue by jonasalmeida** [episphere/connect#3]
It would be nice to have a method that just checks if the key is valid. It could be a call to something like https://episphere-connect.herokuapp.com/key that would return something like {"msg":"valid key"}

**Comment by theEIC** [comment]
Resolved by [3ef8d7](https://github.com/episphere/connect/commit/3ef8d79bbd01d3482c1f242baf0bf1613251281b). Please test and confirm!

**Comment by jonasalmeida** [comment]
The error message comes back as text, so the type is still associated with the response content (error type is now text type). What you say we have something generic, say  https://episphere-connect.herokuapp.com/status, that returns a json object with information about the API endpoint, including the validity of the bearer token, if submitted. This way we'd have complete decoupling between type and content and have a convenient place to ping our APIs. Whatever you come up with would set precedent for other APIs we expose in the future so it may be worth a look at how other Cloud hosted services format it. I looked around and found https://api.gdc.cancer.gov/status. Maybe something along the same lines but checking token if provided?

**Comment by bhaumik55231** [comment]
@jonasalmeida I have updated the response body data type to JSON, Now it will return {"message": "Valid Key"}. I'm not including any token validity because we are using temporary bearer tokens and they don't have any expiration. I will keep this issue open, so that it reminds us in the future to include token validity.

**Comment by danielruss** [comment]
OK to close this issue?  It appears stale.
