### ISSUE TITLE
Shpg - Dshbrd - Summary and Review Confirmation Pop-up

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#304]
On the Summary and Review screen, please add a confirmation pop up once “Sign” is selected to show the box has been shipped.  Confirmation should say “This shipment is now finalized; no other changes can be made”

See Attachment

[Shipping Summary and Review confirmation pop-up.docx](https://github.com/episphere/connect/files/6339268/Shipping.Summary.and.Review.confirmation.pop-up.docx)

**Comment by anthonypetersen** [comment]
@wyattks Is something similar to the attached image what you're thinking?
<img width="570" alt="Screen Shot 2021-12-03 at 9 36 16 AM" src="https://user-images.githubusercontent.com/18222069/144629630-f2593d05-1b77-4304-b7c8-40c3e7d47f0b.png">

**Comment by anthonypetersen** [comment]
Size: S

**Comment by wyattks** [comment]
Yes!  Thank you

**Comment by Gbarra9** [comment]
Please try to press the Review/Ship Button with no checked boxes.
<img width="649" alt="Screen Shot 2021-12-29 at 10 37 49 PM" src="https://user-images.githubusercontent.com/33293205/147719996-532f2bc8-2cbc-4ec1-b1e5-5f30665c1658.png">
