### ISSUE TITLE
Shpg - Dshbrd - Add a default for temperature monitor on the shipping manifest

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#305]
On the Shipping Manifest screen, add a default to the temperature monitor drop down selection.  Default the temperature monitor placement to the first box listed but allow for a change in the dropdown menu.
See attachment

[Shipping Manifest default Temperature monitor.docx](https://github.com/episphere/connect/files/6339299/Shipping.Manifest.default.Temperature.monitor.docx)

**Comment by anthonypetersen** [comment]
Size: S

**Comment by wyattks** [comment]
When I check the box next to 'Temperature Monitor is included in this shipment' on the Packaging screen, a default does not show up in the drop down of the 'Select the box that contains the temperature monitor'.
However, if I don't check the box on the packaging screen a default box number shows up in the dropdown.
This should be reversed.
