### ISSUE TITLE
Shpg - Dshbrd - Shipping Manifest Print Reminder

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#306]
On the Shipping Manifest screen, add a pop-up reminder to print the manifest before continuing.  When "Continue" is clicked, have a pop-up asking if the manifest has been printed with a "Yes" button to continue and  a "No" button to return to the shipping manifest page so it can be printed.

See Attachment

[Shipping Manifest Print reminder.docx](https://github.com/episphere/connect/files/6339322/Shipping.Manifest.Print.reminder.docx)

**Comment by anthonypetersen** [comment]
@wyattks should the code be tracking a print event and having this pop up appear conditionally? or should this always pop-up?

**Comment by anthonypetersen** [comment]
Size: S/M

**Comment by wyattks** [comment]
Would like to have it pop up conditionally but if that is more complicated then having it pop up always is fine.
