### ISSUE TITLE
Shpg - Dshbrd - Spell out Temperature on packaging screen

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#308]
At the bottom of the Packaging screen, spell out Temperature.  Currently it states "Temp Monitor is included in this shipment"

See attached

[Shipping Packaging spell out Temperature.docx](https://github.com/episphere/connect/files/6339388/Shipping.Packaging.spell.out.Temperature.docx)

**Comment by anthonypetersen** [comment]
Size: XS
