### ISSUE TITLE
Shpg - Dshbrd - Make the Box manifest a pop-up

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#309]
We would like to box manifest to be a pop up from the Shipping Packaging screen instead of it being a separate screen.  When the user clicks on the "Box Manifest" button located on the Shipping Packaging screen, the box manifest should be in a pop up.   The Box Manifest Screen would no longer be necessary.  Keep the ability to print the box manifest.

**Comment by anthonypetersen** [comment]
Size: L

**Comment by anthonypetersen** [comment]
No longer needed
