### ISSUE TITLE
Delay participation trajectory

### ISSUE THREAD

**Issue by meganstead** [episphere/connect#31]
Requested trajectory from Hackathon meeting.

"what if a participant begins the R->C workflow, doesn't complete, but indicates they'd like to return at a much later date"

On hold pending review of the R->C workflow.

DECISION NEEDED -> Does this trajectory exist within the Connect system hosted by DCEG or is it native to the Sites recruitment systems?

**Comment by danielruss** [comment]
Has this question been answered?

**Comment by hzhao392** [comment]
Pending site decision, if used we will need a flag

**Comment by Davinkjohnson** [comment]
Looks like a dup.
