### ISSUE TITLE
Biospec - Dshbrd - Add tube colors to deviation screen

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#314]
On the Research Deviation page, add the tube colors next to the tube type.  The colors will be specific to the collection sites.
See attachment

[Add tube colors to Deviation page.docx](https://github.com/episphere/connect/files/6345483/Add.tube.colors.to.Deviation.page.docx)

**Comment by Davinkjohnson** [comment]
"small"

**Comment by wyattks** [comment]
Verified
