### ISSUE TITLE
Biospec - Dshbrd - Specimen Link Change wording in pop-up

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#315]
On the Clinical and Research Specimen Link screens, in the pop-up that appears when the save and exit or continue button along the bottom of the screen are selected, change the wording from "Is the Collection ID - CXA###### correct for the Participant?" to 
"Collection ID is CXA######, confirm ID is correct for participant NAME."
NAME is the name of the participant being linked to the Collection ID.
See attachment

[Specimen Link Pop-up Word Change.docx](https://github.com/episphere/connect/files/6345595/Specimen.Link.Pop-up.Word.Change.docx)

**Comment by Davinkjohnson** [comment]
"Small" (Iqbal to check if this is actually a dupe)

**Comment by anthonypetersen** [comment]
@wyattks it looks like this change is in Dev already, can you confirm?

**Comment by wyattks** [comment]
Yes when we have verified participants I will enter test data and verify.

**Comment by wyattks** [comment]
Yes change is verified
