### ISSUE TITLE
Biospec - Dshbrd - Add an additional Accession ID and QC check to Specimen Link Page for KP sites

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#318]
Please add a page in between the participant search results screen and the specimen link screen on the Clinical Dashboard for the KP sites. The user would get to this screen by clicking on go to Specimen Link on the participant results screen.

The new screen should include a drop down for the visit selection, a place to scan in the Blood Accession ID and a place to scan in the Urine Accession ID.   There should be two boxes each for the Accession IDs where the user is instructed to scan or type the Accession ID.  We want them to have to each ID in twice.  We will not be capturing if the IDs are manually entered.

The screen should also contain a button stating "Return to Participant Search" which would take the user back to the participant search screen. Another button should be "Next". When this button is selected, a QC check should be performed on the Blood Accession ID. The check should see if the Blood Accession ID already exists in the system. If the Accession ID is already in the system, a modal should appear stating what Collection ID the Accession ID has been linked to and offer two choices. The first choice should be "Add Specimens to existing Collection ID". If this is selected, the user should be taken to the data entry screen for that Collection ID. The second choice should be "Close". If Close is selected, the modal should disappear and the user will remain on the current screen. If the Accession ID does not exist in the system the user should be taken directly to the Specimen Link screen.

If a Urine Accession ID was the only Accession ID entered, a QC check does not need to be performed. A modal should appear stating "You have not entered a Blood Accession ID, do you want to continue?" With a "Yes" or "No" selection. If "Yes" is selected the user should be taken directly to the Specimen Link screen. If "No" is selected, modal should disappear and the user will remain on the current screen.

The Specimen Link screen should display the visit that was selected and the Accession IDs entered. The remainder of the screen should be the same as the Research Specimen Link screen and include the same QC check of the Collection ID.

Please see attachment below in the comments.  I had trouble re=attaching the updated version here.

**Comment by wyattks** [comment]
Adding in the Accession ID formats confirmed on 7/18/2022
Below are the formats for the Accession IDs from each KP site.
KPHI: 3-21-112-123456
KPCO: 3-21-112-12345
KPGA: 3-21-112-12345
KPNW: 21-112-12345

Basic example explanation: 3-21-112-00001
• 3 is a regional identifier for the Georgia Region (KPNW does not include the regional number in their Accession ID)
• 21 reflects the year
• 112 reflects the julian date
• The last portion is the consecutive daily accession number Cerner assigns when the order is processed in Cerner. These begin with 00001 or 000001 each morning and continue until midnight as each order comes into Cerner. Some sites have 6 digits and some have 5 digits for this last set of numbers.

**Comment by wyattks** [comment]
Hendrick- As scanning the Accession IDs removes the dashes and we need to strip the letter at the end, how do we handle manual entries for this?
Should we add a note to tell people if they are hand entering to include numbers only, no dashes and no letters or can we automatically strip out dashes and letters when doing the QC check?  Any other ideas?

**Comment by wyattks** [comment]
Having trouble adding the attachment above
[Clinical Accession ID Search July 19 2022.pptx](https://github.com/episphere/connect/files/9337785/Clinical.Accession.ID.Search.July.19.2022.pptx)

**Comment by geniosys** [comment]
> Hendrick- As scanning the Accession IDs removes the dashes and we need to strip the letter at the end, how do we handle manual entries for this?
> Should we add a note to tell people if they are hand entering to include numbers only, no dashes and no letters or can we automatically strip out dashes and letters when doing the QC check? Any other ideas?

@wyattks it's really up to you. For now, I stripped the last character when the user scanned the label since the - is already removed based on what I see in the xls file you shared with me last week. For data entry, I was planning to show all characters with last char stripped like shown in the xls file, example: 321112123456

**Comment by StephanieWeinstein** [comment]
per our discussion today (8/16) we will add a note to tell people if they are hand entering the accession ID, to only include numbers, no dashes.  We will also add a QC check so if they add dashes they will get a warning to take them out.

**Comment by wyattks** [comment]
It did not strip off the end letter when I scanned in the accession IDs.  Is it capturing it in the backend with out the end letter?

**Comment by HopkinsDC** [comment]
@geniosys The error message for the Accession ID scanning field should be "**This entry can only contain numbers.**" This message should apply to the presence of dashes as well.

**Comment by wyattks** [comment]
Confirmed - ready for stage

**Comment by wyattks** [comment]
Just tested and a modal does not exist yet if the Accession ID has already been linked: 
If the Accession ID is already in the system, a modal should appear stating what Collection ID the Accession ID has been linked to and offer two choices. The first choice should be "Add Specimens to existing Collection ID". If this is selected, the user should be taken to the data entry screen for that Collection ID. The second choice should be "Close". If Close is selected, the modal should disappear and the user will remain on the current screen.

**Comment by geniosys** [comment]
@wyattks The modal does exist for Blood accession id only. I think it was specifically written that way in the pptx file and I think Michelle or Stephanie provided a rationale for it, but I don't remember now. See screenshot for Blood Accession ID in Teams

**Comment by wyattks** [comment]
that's the one I entered in Dev.  Connect ID: 6007672745  Collection ID assigned: CXA000128  Blood Accession ID: 422196000725
I am not getting the modal when entering the Blood Accession ID again.

**Comment by StephanieWeinstein** [comment]
I think this basically repeats what Kathleen has already posted above, but just as a recap (the quotes are from above):

> When this button is selected, a QC check should be performed on the Blood Accession ID. The check should see if the Blood Accession ID already exists in the system.
I TYPED IN 321112123456 WHICH IS ONE I USED BEFORE BUT IT IS NOT DOING A QC CHECK.  I TYPED IN ANOTHER ONE WE USED BEFORE AND ALSO NO QC CHECK, IT JUST BRINGS ME TO THE SPECIMEN LINK PAGE.  DOES IT ONLY DO QC CHECK OF ACCESSION IDS ENTERED ON THE SAME DAY?  

> If the Accession ID is already in the system, a modal should appear stating what Collection ID the Accession ID has been linked to and offer two choices. The first choice should be "Add Specimens to existing Collection ID". If this is selected, the user should be taken to the data entry screen for that Collection ID.
 
UNABLE TO TEST SINCE NO MODAL COMES UP

> The second choice should be "Close". If Close is selected, the modal should disappear and the user will remain on the current screen. 

UNABLE TO TEST SINCE NO MODAL COMES UP


> per our discussion today (8/16) we will add a note to tell people if they are hand entering the accession ID, to only include numbers, no dashes. We will also add a QC check so if they add dashes they will get a warning to take them out.

I DO NOT HAVE ACCESSION LABELS SO CANNOT CHECK THAT THEY SCAN PROPERLY.  HOWEVER, IF I PASTE OR TRY TO TYPE A DASH, THE DASHES ARE REMOVED AND LETTERS ARE NOT ACCEPTED, SO THAT IS GOOD.  BEFORE WE HAD A BIT OF TEXT UNDER THE BOXES THAT SAID “THIS ENTRY CAN ONLY CONTAIN NUMBERS” BUT THAT IS NO LONGER THERE.  WAS IT FELT THIS WAS NOT NEEDED GIVEN THAT THE BOX DOES NOT ALLOW YOU TO TYPE A DASH OR LETTER?

**Comment by wyattks** [comment]
Hendrick and I just discussed what is going on.  He is going to put the wording below the boxes.  He was looking into why the modal was no longer appearing.  I was able to show him what was going on.

**Comment by wyattks** [comment]
Modal pop up for existing Accession ID link verified.  Ready for stage.
![image](https://user-images.githubusercontent.com/64605220/189206217-2cc23790-9b7f-46ad-82ef-3a072e980d7b.png)
