### ISSUE TITLE
Connect API - IHCS Site Use -  ingestSiteParticipantData 

### ISSUE THREAD

**Issue by dbakumar** [episphere/connect#32]
IHCS sites send study participant information include StudyId, Unique Encrypted Validation Text (etextkey) for registering the study participant to NCI system.  
Example : 
-- inbound API Request Payload: 
{
  "participant": [
    {
      "studyid": "XYZ2424342",
      "etextkey": "asdgb2341123vnbstwe"
    },
    {
      "studyid": "XYZ2424334",
      "etextkey": "242343ndfhgsfh4bstwe"
    }
  ]
}

-- outbound API Response Payload :   
For Success 
{
   "code" : "200"
   "message" : "success"
}

For Error 
{
   "code" : "4XX"
   "message" : "error message"
}

Note : The "etextkey" used to verify the URL legitimately generated by the ICHS Site when the participant comes to NCI system to start the enrollment process.  Please refer to the detailed workflow document developed by HP for etextkey (encrypted text key ).

**Comment by danielruss** [comment]
@bhaumik55231 isn't this done in the getParticipantToken API call?

**Comment by bhaumik55231** [comment]
@danielruss we discussed this and concluded that we don't need to encrypt tokens as they are Universally Unique Identifiers. @dbakumar feel free to open this issue if you think we need any more discussion on it.
