### ISSUE TITLE
Shpg - Dshbrd - SST Tube color update

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#320]
On the packaging screen, in the Specimen pop-up, and on the box manifest, the SST tube is currently listed as SST/Gold.  Please change it from "SST/Gold" to SST/Gold or Red".  Both Clinical and Research sites will be using the same shipping dashboard.  There is a color difference in the SST tubes they use so we need to include both colors on the shipping screens and manifests.

See attachment
[Change from “SST Gold” to “SST Gold or Red”.docx](https://github.com/episphere/connect/files/6360061/Change.from.SST.Gold.to.SST.Gold.or.Red.docx)

**Comment by anthonypetersen** [comment]
Size: XS

**Comment by brotzmanmj** [comment]
There may be an update to this requirement momentarily, please hold

**Comment by brotzmanmj** [comment]
Requirement will remain the same, you can proceed with this change as requested.
