### ISSUE TITLE
Add querying capabilities to the dashboard

### ISSUE THREAD

**Issue by paulzakin** [episphere/connect#322]
So, currently, when searching for a participant on the dashboard, it's kinda hard once you have a bunch of participants. It would be great to have the ability to search for a participant, say by the token. This is a pretty standard feature in a CRM, so I think it's a good fit here!

**Comment by brotzmanmj** [comment]
Hi Paul, are you referring to the Study Manager Dashboard? If so, I'm going to move this issue over to where we're tracking those https://github.com/episphere/dashboard/issues. 
We recently discussed adding the Study ID to the participant search fields but can also discuss adding the token and PIN.

**Comment by paulzakin** [comment]
Yup! And that's fine with me (moving the ticket). Basically, the more querying power you can give the sites, the better honestly. Like if Bob Johnson shows up, ideally we want to be able to search by name, as Bob Johnson is going to know his pin - we could look in our CRM for bob johnson and then find the pin that way, but that seems like an unnecessary extra step...

**Comment by brotzmanmj** [comment]
Closed issue, created issue in the other github for the study manager dashboard
