### ISSUE TITLE
Biospec - Dshbrd - Remove Accession ID on Research Specimen Link Screen

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#325]
On the Research Dashboard's specimen Link screen, remove the accession ID column from the Participant Collections table.
See attachment

[Research dashboard - Remove Accession ID Column.docx](https://github.com/episphere/connect/files/6442586/Research.dashboard.-.Remove.Accession.ID.Column.docx)

**Comment by brotzmanmj** [comment]
@wyattks Since we're getting rid of the whole Participant Collections on the research screen, this is no longer relevant? Can we delete?
