### ISSUE TITLE
Biospec - Dshbrd - Research Navigation from Participant Search Results screen

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#326]
On the research participant search results page, update the navigation along the bottom to include "Go to Specimen Link".  The user should be able to go to any of those pages from the search results page.  We don't want them to have to go through Check-In to get to the Specimen Link page.    This will be a big change in how the data is saved.

See attachment.

[Research Specimen Link Navigation Button Updates.docx](https://github.com/episphere/connect/files/7278184/Research.Specimen.Link.Navigation.Button.Updates.docx)

**Comment by Davinkjohnson** [comment]
"Large" (Need some more clarity from Kathleen)

**Comment by Davinkjohnson** [comment]
This includes the changes from our 12/13 meeting:
- Ensure the "go to specimen link" selection is not an option (@wyattks just on the Pt Search or also the Spci Search?) if the Pt is not yet checked in.
- The current "go to specimen link" seems to automatically check-in a participant by way of removing this button when not checked-in this should no longer be an issue.

**Comment by wyattks** [comment]
Selection should only be on the participant search screen.  If the participant has not checked-In then a Collection ID will not have been assigned yet so the user will not be able to use the specimen search screen.
