### ISSUE TITLE
Connect API - IHCS Site Use - createSiteParticipantToken

### ISSUE THREAD

**Issue by dbakumar** [episphere/connect#33]
IHCS site will send a list of study-ids is to generate a unique token for each one of them to use in URL generation. 
Example 
Inbound Request API payload : 
{
  "participant": [
    {
      "studyid": "XYZ2424342"
    },
    {
      "studyid": "PQR23425656",
    }
  ]
}

Outbound Response Payload : 
For success
{
  "participant": [
    {
      "studyid": "XYZ2424342",
      "ptoken" : "0abce6c4-d98c-11e9-8a34-2a2ae2dbcce4"
    },
    {
      "studyid": "PQR23425656",
      "ptoken" : "0abce6c4-d98c-11e9-8a34-2a2ae2dbff323"
    }
  ]
}
For Error 
{
  "code" : "4XX",
   "message" : "Error message"
}

Note : using this method IHCS site never expose studyId to public and participant token (unique) can be used for communication between IHCS system & NCI system.

**Comment by Eusuf2000** [comment]
The updated GetParticipantToken API function assumes that the sites will provide PIN. There is no issue with sending PIN to DCEG. However, the following questions come to mind:

1. Can Study_ID and PIN be the same thing?
2. How can we ensure that PIN is globally unique - that's no two sites using the same PIN?
3. Won't it be better if the PIN is generated by NCI along with Token and sent to the sites?

**Comment by danielruss** [comment]
The GetParticipantToken API has been updated to accept a StudyId and returns a token and a pin generated by NCI.  The StudyId and the PIN are different and globally unique.
