### ISSUE TITLE
Biospec - Dshbrd - Restricting changes once specimen information has been entered, Big Picture Item

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#333]
Basic request:  Add an Edit button and Grey out entered data once saved

On both the Research and Clinical dashboards, we need to restrict the user making changes to previously entered information.  Currently once biospecimen information is added to the collect/Process and labeling and receipt screens, the user can easily make changes  Some of the feedback we received from testing stated the user was confused and unchecked previously checked items thinking they only needed to check the tubes they were adding.  The unchecking caused them to mistakenly list the biospecimens as not collected.  
To prevent this, we would like the system to "lock" the information saved for tubes but allow edits, if needed, through an edit button on the screens.  Also, we would like the information previously entered to be greyed out once it is saved.  If an edit is made, we would like a pop-up asking the user to confirm they changes. 

See attachments

[Clinical Consolidate Labeling and Receipt Screen with Greyed out portion.docx](https://github.com/episphere/connect/files/6555555/Clinical.Consolidate.Labeling.and.Receipt.Screen.with.Greyed.out.portion.docx)
[Research Collect and Process Screens with greyed out portion.docx](https://github.com/episphere/connect/files/6555556/Research.Collect.and.Process.Screens.with.greyed.out.portion.docx)

**Comment by Davinkjohnson** [comment]
closed by accident, re-opening.

**Comment by wyattks** [comment]
Works great!
