### ISSUE TITLE
Biospec - Dshbrd - Change wording on "Tube Type" and "Comment"

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#335]
On the Clinical and Research Dashboards, there are several locations where "Tube Type" is listed.  "Tube Type" needs to be changed to "Specimen Type". 
"Tube Type" Locations:
Research dashboard: Collect/Process screens, Deviation pop-up, and review screen                                                                                                          Clinical dashboard: Labeling and Scanning and Summary Screen

Also on the Receipt Summary and Review Screens, "Comment" needs to be changed to "Deviation Type".  Deviation Type reflects what is in the column.

See Attachment

[Clinical and Research Tube Type and Comment Word Change.docx](https://github.com/episphere/connect/files/6556627/Clinical.and.Research.Tube.Type.and.Comment.Word.Change.docx)

**Comment by Davinkjohnson** [comment]
"Small"
