### ISSUE TITLE
Shpg - Dshbrd - Handling Missing Tubes 

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#341]
On the shipping dashboard, suggestions are needed regarding how to handle specimens marked as "Missing".   These are the tubes listed under the "Location Unknown" area.  We do not want to create a never ending list on this page.

**Comment by HopkinsDC** [comment]
It would be beneficial to the site to be able to know how long each sample is in the "Location Unknown" column; adding a section for days-in-counting. Additionally, the ability to print this list of samples may aid in tracking and issue resolution.

**Comment by wyattks** [comment]
After our discussion today (12/7/2021), we will no longer have a stray tube table located on the Packaging screen but we will need a report comparing what was marked as collected to what was shipped.  We will add to the SOP, that if the physical count is different from the # listed, the user should cancel and double check the collection before adding it to a shipping box,
