### ISSUE TITLE
Biospec- Dshbrd- Clinical and Research Participant Search Results add Participant Statuses to table

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#342]
On the Clinical and Research search results table, add in a Verification status and Participation Status,

Only consented participants should be returned.

Verification Status should show one of the following:
Verified
Not Yet Verified
Outreach Maxed Out
Cannot Be Verified

Exclude verification status = Duplicate from the search results.

Participant Status 
Show  a green check if one of the following is true:
No Refusal
Refused Some Activities
Refused all Future Activities
Show a red X if the following is true:
Revoked HIPAA Only
Destroy Data
Withdrew Consent

See attachment.

[Clinical Participant Search Results screen with Statuses.docx](https://github.com/episphere/connect/files/7475300/Clinical.Participant.Search.Results.screen.with.Statuses.docx)

If the green check or red X are difficult to do, another idea was to have either Proceed or Do Not Proceed.
So it would be to following.
Participant Status of Proceed if one of the following is true:
No Refusal
Refused Some Activities
Refused all Future Activities
Participant Status of Do Not Proceed if one of the following is true:
Revoked HIPAA Only
Destroy Data
Withdrew Consent

**Comment by wyattks** [comment]
This issue will need to pull data from the backend

**Comment by anthonypetersen** [comment]
Merged change into nav-changes branch. When that branch is merged into the dev branch it will be ready for acceptance testing.

**Comment by anthonypetersen** [comment]
Does this still need to be open?
