### ISSUE TITLE
Biospec- Dshbrd- Research Checkin screen hide Contact information 

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#345]
On the Research Checkin screen, we have the "Verify Contact Information" with a button to pull up that information.  Currently we do no have the ability to edit the contact information even from the study manager's dashboard.  We would like to "hide" the "Verify Contact Information" and button until the ability to edit is at least on the study managers dashboard.  Is it possible to just not display it at this point?

**Comment by wyattks** [comment]
Issue #292 is related and can also be held for now

**Comment by Davinkjohnson** [comment]
"Small"
