### ISSUE TITLE
Response variables added to Master Data Dictionary

### ISSUE THREAD

**Issue by FrogGirl1123** [episphere/connect#346]
Added additional categories, Not Active recruit signed in as an Active recruit and Passive signed in as Active to RcrtV_DuplicateType_v1r0
Added 88   = "None of the Above" as a category for RcrtSI_CampaignType_v1r0, see notes in dictionary and Special Codes tab for usage, here https://nih.app.box.com/file/773986697713?s=wbl3omsyzenarermrspsk8dkoxku6hq4

The additional responses need Concept IDs and should be included if appropriate in the SM dashboard.  Once Concept IDs have been added the new variables will be shared with the sites.

For some reason I was not able to assign Abhinav to this issue, but he should be assigned to it as well.

**Comment by brotzmanmj** [comment]
Hi Nicole, I added this issue to the Github project board that we have for the Study Manage Dashboard and will assign it to Abhinav there. https://github.com/episphere/dashboard/issues/213

**Comment by brotzmanmj** [comment]
Closing the issue here since it is now being followed on the SM Dashboard github.
