### ISSUE TITLE
Biospec - Dshbrd - Navigation tabs across the top of Clinical and research Dashboards

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#347]
Currently across the top of the clinical and research dashboards we have the below navigation tabs that are not functional. We would like all of the tabs to be removed except the Participant Search and Specimen Search Tabs. These two tabs should be present on every screen and allow the user to click on them to return to the searches.

Clinical Dashboard:
Participant Search, Specimen Search, Specimen Link, Labeling and Scanning, Receipt Summary

Research Dashboard:
Participant Search, Specimen Search, Participant Check-In, Specimen Link, Collect/Process, Review, Participant Check-Out

**Comment by brotzmanmj** [comment]
The tabs that are to be removed will instead be nagivated to from elsewhere on other pages, that will be indicated in other github issues. The content on those pages should not be deleted.
