### ISSUE TITLE
Biospec- Dshbrd- Research change Visit selection screen location and add QC check

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#348]
On the Research dashboard Check-In screen, a participant can only be checked-in once for a baseline visit. Please move the field 'Select Visit' from the Specimen Link page to the Check-In page. The user will select 'Baseline' for the visit and then click Check-In. Upon Check In, the system needs to store the Check-In flag and check-in date/time stamp (currently there are placeholders for these variables but they are not being stored). Upon clicking check-in, the system needs to see if Check-In has already been recorded for baseline visit. If not, display a modal that says 'Success'. If a check in has already been occurred for baseline visit, display a modal that says "Participant has already been checked-in for a baseline visit" and do not overwrite the check-in data.

**Comment by Davinkjohnson** [comment]
Per 12/13 review - 

- Ensure the Check-in logic is happening on the check-in button itself (not in the "go to specimen link" button on the modal)
- Update button on "success" Modal to say "Close" instead of cancel. (use the Search Tab at top to go back to search)
