### ISSUE TITLE
Site Training Video - Clinical Tubes

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#350]
*Ask Norma for address*

Ask one of sites to send all the tubes they would use for participant collection for training video use. (Clinical) - NW or CO

we may need two sets of supplies as two sets fit in one canister - Stephanie

**Comment by StephanieWeinstein** [comment]
Let's confirm with Norma that she has received these tubes, then we could close this issue

**Comment by HopkinsDC** [comment]
Norma confirmed tubes were received (11/9).
