### ISSUE TITLE
SOP Loose-ends Spreadsheet

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#370]
Address the research SOP corrections in the SOP review spreadsheet sent by Stephanie

**Comment by HopkinsDC** [comment]
Language has been added to the Labeling SOP template to place the tubes in order before applying the labels. I will apply to site SOPs once addition is ok'ed.

**Comment by HopkinsDC** [comment]
Ok, I think I misunderstood that it was suppose to be added to the Research SOP. I will delete from research and add to clinical.

**Comment by StephanieWeinstein** [comment]
check out the clinical SOP. I had actually added some suggested wording already (I had forgotten that!)
