### ISSUE TITLE
Research SOPs - Keep Samples Cold

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#372]
Throughout all the SOPs where we say to keep samples cold from collection to receipt at NCI/FNL, we can instead just say "Keep samples cold (include the degree range)". Confirm temp is 2-8

**Comment by StephanieWeinstein** [comment]
on the clinical SOP template, we added one phrase that the serum tubes should not be kept cold when they are clotting at room temperature.  see page 3.  Please add this to all four clinical SOPs and check the research SOP templates to see if this needs to be added to any of the research SOPs.

**Comment by HopkinsDC** [comment]
Phrase had been added to all 4 clinical SOPs. Language for leaving the serum tubes at room temp as they are clotting and then placing them at 2-8 degrees is already present in all Research Blood SOPs.
