### ISSUE TITLE
Biospec - Dshbrd - Need ability to add tubes after collection has been moved to shipping dashboard

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#377]
This is for both the Clinical and Research dashboards.

After a collection has been submitted on the research or collection dashboards and moved onto the shipping dashboards, users will need the ability to go back to the collection data entry screens to add tubes. The user should not have the ability to make any changes to the other tubes that were previously marked as collected.  They can only add tubes and not remove tubes at this point.

Functions needed:
The user will need the ability to mark as collected a tube the was previously not marked as having been collected. 
         For the research dashboard, the reason not collected should be deleted.
The user should have the ability to enter in the Full Specimen ID and if there are any deviations associated with that specific tube.

The tube being added should show up on the shipping dashboard under the Stray Tube table.

**Comment by wyattks** [comment]
We would need the user to be able to search by Collection ID with finalized collections.

**Comment by wyattks** [comment]
After our discussion today, we will no longer have a stray tube table.  The above mentioned tube should be added to the "# Specimens in Bag" count under the Available Collections Box on the Shipping Dashboard's Packaging screen.  We will add to the SOP, that if the physical count is different from the # listed, the user should cancel and double check the collection before adding it to a shipping box,

**Comment by anthonypetersen** [comment]
Added missing "Save and Continue" button on Explanation form where Deviations and Tube Reasons are entered. Tubes can be added after the Collection has been Finalized. Specimen Search logic has been modified to allow access to the Collection through the Search Specimen path unless the following are ALL true:
1) All tubes have been collected
2) Collection is finalized
3) Participant is Checked Out for the Collection
