### ISSUE TITLE
Collection Screen Deviation Updates

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/connect#390]
On the Collection screen:

- Remove the "Select all" box for deviations (behavior shouldn't be to allow a deviation on every tube)
- Make the check boxes for deviations larger (easily click-able) and ensure these and "reason missing" are same size

**Comment by anthonypetersen** [comment]
I'll take care of this when I populate collection process screen

**Comment by anthonypetersen** [comment]
code is done, including in same branch as #391
