### ISSUE TITLE
Biospec - Dshbrd - Specimen Search Error after Check-Out

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#393]
On the Research dashboard, after you check-out the participant, if you conduct a specimen search you get an error stating "Research Collections cannot be viewed on Clinical Dashboard".  This error appeared on the research dashboard see attachment).  We need the same search results logic for a checked-out participant that we have for a checked-In participant.

[Check-Out Specimen Search error.docx](https://github.com/episphere/connect/files/7758049/Check-Out.Specimen.Search.error.docx)

**Comment by anthonypetersen** [comment]
Found the "why" for this bug.. thinking hard about a fix

**Comment by anthonypetersen** [comment]
* on line 1813 of events.js we are calling window.location.reload()
* this is causing document.getElementById('contentBody').dataset.workflow to get cleared
* that variable is where we store the workflow

Need to discuss this logic with @iqbal-singh when he is back in the office

**Comment by wyattks** [comment]
From issue 407: Michelle came across the Incorrect dashboard error when conducting a specimen search. The error she received was "Clinical Collections cannot be viewed on Research Dashboard". It is not related to a session timeout because her session was never idle. Her workflow was the following: checked the participant in, made the Collection ID link, added Collection information, returned to participant search and checked the participant out. She then performed a specimen search to go back to the collection data screen but received the error.
