### ISSUE TITLE
Biospec - Dshbrd - Update Connect Logo

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#394]
The logo on display in the Connect Dashboards is Red and Black.  The logo needs to be updated to the blue and yellow logo.  
Deanna DePietro can supply the correct file for the logo.

I am adding this issue so we do not forget about it!

**Comment by anthonypetersen** [comment]
@wyattks is this the logo you're referring to?
![ConnectLogo](https://user-images.githubusercontent.com/18222069/147276745-316c6b45-5a3d-4747-a2ef-9005b47d7164.png)

**Comment by anthonypetersen** [comment]
this is the logo being used on the Connect PWA.. This logo doesn't contain any blue in it, the only reason it appears to have blue on the PWA is because it has a transparent background and is on a blue page.

**Comment by anthonypetersen** [comment]
Deanna provided logo we should be using, changes have been pushed to dev.
