### ISSUE TITLE
Biospec - Dshbrd - Allow for multiple Specimen IDs to be linked

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#395]
On the research specimen link page, currently you can add additional Collection IDs even if a Collection ID has already been assigned to a participant for a baseline visit, with no notification that another Collection ID has already been linked.  While we will allow multiple Collection IDs to be linked to one visit, there should be some kind of modal warning if an additional Collection ID is being linked.  

 

For example: “Collection ID CXA###### has already been linked to this visit. Do you wish to continue with linking an additional Collection ID? Yes No"

 

So workflow:
1 check-In with 1 Visit associated to the check in
1st Collection ID linked - accept with current workflow
2nd Collection ID linked - modal with warning

**Comment by anthonypetersen** [comment]
after discussion it might be best to wait until #387 is resolved as those changes might affect how these ones are implemented

**Comment by wyattks** [comment]
not needed - will add a new issue for what is neeeded.
