### ISSUE TITLE
Biospec - Dshbrd - Select Collection Location Disappears

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#399]
When Checking-in a participant for a second time, previously they have been checked in and out, the Select Collection Location dropdown disappears on the Specimen Link page.  The drop down is present the first time you go to the Specimen Link page but if you check out the participant, check the participant back in and then go to the specimen link page, the drop down is no longer there.

[Select Collection Location Issue.docx](https://github.com/episphere/connect/files/7764712/Select.Collection.Location.Issue.docx)

**Comment by wyattks** [comment]
Ok so I just went back into Isabelle's Specimen Link and the drop down is present again.  Not really sure what is going on.  Maybe a timing issue?

**Comment by anthonypetersen** [comment]
@wyattks I think I've seen this happen to me before, but I believe it was due to my session basically timing out. Any chance this may have happened for you? If not, if you could figure out how to reproduce the issue that would make my job super easy :)

**Comment by wyattks** [comment]
I will try an reproduce.  I don't think I timed out but may have.

**Comment by wyattks** [comment]
Ok I was able to recreate this.  What I did was Check-In a participant and then closed. I conducted a search for the same participant and went to the Check-out screen checking them out.  Searched again for that participant Checked them in again and from that screen went to the Specimen Link screen.  When I did it that way the Collection Location option is not listed.

**Comment by anthonypetersen** [comment]
* it looks like this issue stems from the same core bug as #393 
* when we do a check-out we are clearing data that stores the dashboard type we are using
* the HTML code that populates the Collection Location is dependent on the variable that is getting cleared on check-out

**Comment by anthonypetersen** [comment]
will review with @iqbal-singh when he returns

**Comment by wyattks** [comment]
I just checked this and it is still happening.
