### ISSUE TITLE
Specimen search not working after 'Confirm and Exit' on specimen link

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#400]
I entered a specimen link CXA123435 for Henry Wallace. After submit I clicked 'Confirm and Exit'. I then went to Specimen Search and tried to search for the specimen but it did not respond when I clicked 'Search'.

**Comment by anthonypetersen** [comment]
pushed to dev

**Comment by StephanieWeinstein** [comment]
sorry, I clicked on the wrong thing and closed this by accident!
