### ISSUE TITLE
Specimen Search navigation after review and submit

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#401]
After finalizing specimen data (submitting the Review and Submit), and then searching the Specimen ID again, the search function doesn't work. It just stays on the search page and doesn't respond. 

Kathleen and Tony have this currently: If all tubes are collected, the collection has been finalized, but the participant isn't checked out then go to the checkout page. If all tubes are collected, the collection is finalized, and the participant is checked out then show a notification saying such and return to the search form.

I think instead the Specimen Search should always take you to the Specimen Data, even after it has been submitted. We need a team decision on this.

**Comment by anthonypetersen** [comment]
Decision is made that we will just default to go to the Collection Process screen no matter what

**Comment by anthonypetersen** [comment]
pushed changes to dev
