### ISSUE TITLE
Biospec - Dshbrd - Session Timeout discussion

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#406]
With testing we are seeing issues that are happening due to the session timing out.  Can we discuss on how long a session has to be idle before it times out?  Also there is no notification that the session has timed out so a user may continue entering data not realizing they have timed out.  Can we put in a modal or something similar saying their session has timed out?

**Comment by anthonypetersen** [comment]
will discuss with @naiyume next week, apparently we are doing something similar on the PWA

**Comment by anthonypetersen** [comment]
pushed to dev

**Comment by anthonypetersen** [comment]
similar to PWA, popup arrives after 20 min of inactivity and auto logout happens after 5 minutes of inactivity on popup
