### ISSUE TITLE
Biospec - Dshbrd - Specimen Search Incorrect dashboard error

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#407]
Michelle came across the Incorrect dashboard error when conducting a specimen search. The error she received was "Clinical Collections cannot be viewed on Research Dashboard".   It is not related to a session timeout because her session was never idle.  Her workflow was the following: checked the participant in, made the Collection ID link, added Collection information, returned to participant search and checked the participant out.  She then performed a specimen search to go back to the collection data screen but received the error.

**Comment by anthonypetersen** [comment]
I could be wrong, but I'm guessing this might be the same core bug as described in #393

**Comment by wyattks** [comment]
Yes it is!  Sorry I thought I had entered in one for this but didn't see it so I entered in a second one!
