### ISSUE TITLE
Biospec - Dshbrd - Optional notes not appearing on Review screen

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#408]
When Optional notes were added to the bottom of the collect/process screen on the research dashboard, they did not appear on the review screen.

**Comment by anthonypetersen** [comment]
Decision was made that we only need to be using Concept ID 338570265. We will be able to edit this field on the Collection Process screen and view this field on the Finalize and Review screen

**Comment by anthonypetersen** [comment]
pushed to dev
