### ISSUE TITLE
Shpg - Dshbrd - Packaging screen, changes to the "Shipping Box contents" titles

### ISSUE THREAD

**Issue by StephanieWeinstein** [episphere/connect#413]
On the Shipping Dashboard, packaging screen

Rename "Shipping Box Contents" to "View Shipping Box Contents"
Remove the "Create new box" button
Move the Box# drop down to the right of the words "View Shipping Box Contents" (where the "Create new box
 button was.)

**Comment by Gbarra9** [comment]
Screenshot of the updated change
<img width="683" alt="Screen Shot 2021-12-27 at 10 35 09 AM" src="https://user-images.githubusercontent.com/33293205/147487180-cba36a73-5c94-400c-9afd-0dcf2bd9d51f.png">

**Comment by StephanieWeinstein** [comment]
Looks great, thank you!
