### ISSUE TITLE
Shpg - Dshbrd - saving issue for shipment tracking information

### ISSUE THREAD

**Issue by StephanieWeinstein** [episphere/connect#418]
on the shipping dashboard, "Shipment Tracking Information" tab (which will be renamed to "Assign Tracking Number")

Change the "Continue" button to "Save and Continue"

Note that currently if you click that button, it does not save the data, so the save function needs to be added here.

Also, we are not 100% sure the "Save" button is saving the data either.  I think sometimes it works and sometimes it did not.  We will keep an eye on this as we continue teting

**Comment by Gbarra9** [comment]
**Tracking Number Saving Explanation**
Saved Data is Reset when:

- Box Id is finalized at last step of Summary and Review
- Box Id is saved during Assign Tracking Information but user goes back to Packaging Step and chooses a Box Id or Group of Box Ids that do not include the previous Box Id

Scenario:

1. User selects Box1 from Packaging. 
2. User enters Box1's tracking number and presses the save button or the save and continue button. 
3. User goes back to Packaging and selects Box2 and Box3. 
4. User makes it to Assign Tracking Information with Box2 and Box3. The previous Box1 data that persisted/saved will be gone and not displayed in the input fields.
5. User selects Box1 again and goes to Assign Tracking Information. The previously entered data for Box1 will be gone and the input fields for Box1 will be blank.

Let me know if you have any questions.
