### ISSUE TITLE
Delete Account - Participant Request

### ISSUE THREAD

**Issue by meganstead** [episphere/connect#42]
Source - Hackathon feedback - KPCO:  Should users be allowed to delete their account and profile, perhaps a process that is associated with the opt-out process?  We would keep some data so that we know the participant did opt-out.

Notes from @brotzmanmj - 
Can a participant delete their account? 
Can anyone else (at site or at NCI) delete a participant’s account? 
Will the PWA have an ‘Uninstall’ option, and if so, would the Uninstall action delete the participant’s account? 
If deleting an account is technically possible, what are the implications if this is done pre-consent vs post-consent? A pre-consent deletion of account by a participant should trigger a notification to the site study manager to be factored in to the recruitment process. A post-consent deletion of account needs action by NCI and an alert to the site study manager as this would not be considered a formal withdrawal from the study but will indicate that we can no longer communicate with them through the PWA. 

Intentionally not related to other opt-out tickets

**Comment by hzhao392** [comment]
Follow withdraw SOP
