### ISSUE TITLE
Shpg - Dshbrd - duplicate samples in bag/box

### ISSUE THREAD

**Issue by StephanieWeinstein** [episphere/connect#421]
On the shipping dashboard, on the packaging screen, we have seen a few instances where data are duplicated, listing multiples of the same ID in a bag/box.  I know Gene is looking into this, we just wanted to add an issue for it.  If it happens to anyone again, please take notes of what you were doing when it happened and take a screen shot and enter the notes and attach the screen shot here.

**Comment by wyattks** [comment]
Linked to issue #299 

Not sure what is causing the duplication yet.

**Comment by Davinkjohnson** [comment]
Davin to check with Warren on this.
