### ISSUE TITLE
Shpg - Dshbrd - Temperature monitor flag in the data dictionary?

### ISSUE THREAD

**Issue by StephanieWeinstein** [episphere/connect#422]
is the temperature monitor flag in the data dictionary?  If not, we will need to add it.  We will need to show which boxes have the temperature monitor on the BPTL dashboard, I will enter that issue separately.

**Comment by Gbarra9** [comment]
I believe the data dictionary includes the temperature monitor.
The concept id is [429634576](https://episphere.github.io/conceptGithubActions/web/#429634576) and the variable name is "Shipping - Temp Probe"

**Comment by brotzmanmj** [comment]
@Gbarra9 Hi Gene, Is it possible to tell if the data for the temp monitor is actually being stored?

**Comment by brotzmanmj** [comment]
@Gbarra9 Actually, there should be a flag that indicates if there is a temp monitor in the shipment, and then later on in the shipping dashboard before the shipment is finalized there is a place to select which box in the shipment the temp monitor is in. Can you check the Master Data Dictionary and see if you can locate both, and confirm that the data are actually being stored?

**Comment by Gbarra9** [comment]
> @Gbarra9 Hi Gene, Is it possible to tell if the data for the temp monitor is actually being stored?

Let me check and get back to you.

> @Gbarra9 Actually, there should be a flag that indicates if there is a temp monitor in the shipment, and then later on in the shipping dashboard before the shipment is finalized there is a place to select which box in the shipment the temp monitor is in. Can you check the Master Data Dictionary and see if you can locate both, and confirm that the data are actually being stored?

I believe there is a flag that indicates if the temp monitor is included in the shipment. I'm not sure if the data is stored, I'll message back when I find out whether it is being stored.
<img width="1377" alt="Screen Shot 2021-12-27 at 12 09 06 PM" src="https://user-images.githubusercontent.com/33293205/147493246-53dec30a-169c-4677-9dcc-6cd6193ced74.png">
<img width="1378" alt="Screen Shot 2021-12-27 at 12 08 52 PM" src="https://user-images.githubusercontent.com/33293205/147493227-d2c23757-9e6d-4a2e-bc7b-26e08797b871.png">

Correct me if I am wrong, but this is what occurs after selecting 2 different boxes and checking "Temp Monitor is included in this shipment" and finally pressing "Review/Ship" button on Shipping page. The second screenshot is from the shipping manifest page. From the below screenshots, I can only assign a temp monitor to one box. Isn't there a possibility that each box can have its own separate temp monitor? 
<img width="836" alt="Screen Shot 2021-12-27 at 12 17 19 PM" src="https://user-images.githubusercontent.com/33293205/147493643-7c3870d4-e40c-400d-9535-5f181ca8cc0e.png">

<img width="877" alt="Screen Shot 2021-12-27 at 12 17 42 PM" src="https://user-images.githubusercontent.com/33293205/147493655-f5709ae3-f63d-43cd-8343-a4e0ee1453bd.png">

**Comment by brotzmanmj** [comment]
@StephanieWeinstein Per Gene's question, it is possible Norma will ever want a temp monitor in more than one box in a shipment?

**Comment by StephanieWeinstein** [comment]
currently we are only planning to put a temperature monitor in one box per shipment.  I suppose if we end up having lots of problems we may decide in the future that we would want to put a temperature monitor in all boxes.

**Comment by Gbarra9** [comment]
> @StephanieWeinstein Per Gene's question, it is possible Norma will ever want a temp monitor in more than one box in a shipment?
> currently we are only planning to put a temperature monitor in one box per shipment. I suppose if we end up having lots of problems we may decide in the future that we would want to put a temperature monitor in all boxes.

Thank you for the response to my question.


> @Gbarra9 Actually, there should be a flag that indicates if there is a temp monitor in the shipment, and then later on in the shipping dashboard before the shipment is finalized there is a place to select which box in the shipment the temp monitor is in. Can you check the Master Data Dictionary and see if you can locate both, and confirm that the data are actually being stored?

Good news, I went through the process of finalizing a collection for shipping with a temperature monitor. I can confirm that the temp monitor's data is being stored in the database and its status can be retrieved.

@StephanieWeinstein On BPTL's Packages in Transit I was able to retrieve the temp monitor status for multiple shipments. The comment I made about the temp probe's concept Id was a mistake. The concept id is actually [105891443](https://episphere.github.io/conceptGithubActions/web/#105891443).

<img width="798" alt="Screen Shot 2021-12-28 at 12 29 26 AM" src="https://user-images.githubusercontent.com/33293205/147532374-4a2e2a3b-0e05-4897-816c-49454d38dedc.png">
