### ISSUE TITLE
Inconsistency in Biospecimen Variable Format

### ISSUE THREAD

**Issue by FrogGirl1123** [episphere/connect#423]
Variables associated with tube attributes and deviations are not being collected in formats consistent with the Master data dictionary.   If a value is collected as a concept ID it should be an integer, if the value contains text it should be a string.  d_299553921_248868659 is showing up as a string when it's null and as a integer when it's populated, it should always be an integer.  It is possible to submit multiple deviations (which I didn't see in the test data), which should be collected as an array and handled the way Bhaumik handles the select all that apply questions (such as how did you hear about this study) in the recruitment workflow.

I'm linking issue #387, as nesting of tube attributes will be part of the overall repeated measures nested structure.

**Comment by anthonypetersen** [comment]
Hi @FrogGirl1123 I think I see the issue with Concept ID 248868659. Could you please post any other Concept IDs you see the issue with and I'll try to find others in our code as well?

**Comment by anthonypetersen** [comment]
Concept IDs associated with Tube Concepts should be either a number or a null value, not an empty string
