### ISSUE TITLE
Biospec - Dshbrd - Word Change on Collection ID Confirmation Modal

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#424]
On the Research screen's modal that appears when a Collection ID is entered, please make the following word changes:

"Confirm Changes" to "Confirm Collection ID"
"Close" to "Cancel"
[Collection ID Confirmation Modal Word Change.docx](https://github.com/episphere/connect/files/7793169/Collection.ID.Confirmation.Modal.Word.Change.docx)

**Comment by anthonypetersen** [comment]
ezpz

**Comment by anthonypetersen** [comment]
pushed to dev
