### ISSUE TITLE
System time out

### ISSUE THREAD

**Issue by StephanieWeinstein** [episphere/connect#429]
We need to caution that the system times out after a certain period of inactivity, and then if you try to continue it gets stuck/spinning. Users should close browser and log back in/start again.

Also, we may need to include links to instructions on clearing the cache. Not sure if that is an issue in testing only or could be an issue in Production.  There are slightly different instructions based on the brower.  For example, here is the chrome one:  https://support.google.com/accounts/answer/32050?hl=en&co=GENIE.Platform%3DDesktop

We have also found that for testing it works better to use an incognito window. Not sure if that matters for production but we might at least suggest it for testing.

**Comment by HopkinsDC** [comment]
Time-out instructions are in the Manual. 

I would like to wait until we receive feedback from the sites on any issues with getting stuck/spinning to determine if troubleshooting solutions for this is needed.

**Comment by sonyekere** [comment]
@HopkinsDC Hi, Can this issue be closed?

**Comment by Davinkjohnson** [comment]
stale
