### ISSUE TITLE
Account creation- Prevent duplicate accounts

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#43]
Ensure that participants who create an account do not create a different account with a different email address or a different method (e.g. phone or Google) when they sign in again.

**Comment by danielruss** [comment]
Deduplication of accounts should they occur

**Comment by danielruss** [comment]
duplicate of #2

**Comment by hzhao392** [comment]
Handled by sites in verification SOP

**Comment by hzhao392** [comment]
We will need to test this from the sites

**Comment by anthonypetersen** [comment]
being referenced in other issues
