### ISSUE TITLE
Stuck at sign off - add hints to the manual

### ISSUE THREAD

**Issue by StephanieWeinstein** [episphere/connect#431]
if the sites gets stuck where the sign off is needed at the very end, some options are to log out and start over, clear the cache and start over, have someone else log in and finish the process

**Comment by HopkinsDC** [comment]
I feel like this issue is similar to #429. I'm going to close this one and keep 429 open. Also, I think we should wait until we receive feedback from the sites on any issues with getting stuck/spinning to determine if troubleshooting solutions for this is needed.
