### ISSUE TITLE
Word Change on Finalize Collection Data Entry Screen

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#439]
On the  Finalize Collection Data Entry Screen, the back button says 'Return to Process' can that be changed to read 'Return to Tube Collection'

**Comment by anthonypetersen** [comment]
Currently we have conditional wording on the button mentioned.. If we are in the research dashboard we display "Return to Process" and if we are on the clinical dashboard we display "Return to Labeling and Scanning".

@wyattks do we want these changes to be uniform or do we want to keep the conditional wording?

**Comment by wyattks** [comment]
We want the conditional wording.  In the Research dashboard, the process page has a Tube Collection label at the top that is why we want to change.  We don't want to confuse the user with different terms.
