### ISSUE TITLE
Alpha Testing - HP Feedback - Sign-in to Consent Workflow

### ISSUE THREAD

**Issue by dbakumar** [episphere/connect#44]
1. -	The email verification message should include information that Internet Explorer (as Enterprise setting still using IE 11) is not a valid browser. Also include instructions to copy and paste the link into one of the other acceptable browsers for those that might not know how.
2. -	After completing the email verification and going back to Chrome, the Connect page seemed to be stuck. The message appeared that the email had been verified but there were no further instructions on how to actually sign in. Suggestions: include instructions to refresh the page or direct them to the User tab, which also seemed to work for some
3. -	Might be best to rename “User” tab to something like “My forms” or “My actions”
4. -	Every time sign out and then sign in occurs, you are able to click “sign in using email” but then the page goes blank. You have to hit refresh and then sign in again to have the process work properly and present the fields to enter the email and password.
5. -	When entering phone number if you use dashes between numbers a message pops up to use the suggested format, this format should be displayed.
6. -	Error messaging seems vague and should be specific to each field where information is entered incorrectly.
7. -	If you accidently skip answering the question about sex at birth you cannot submit the profile page, but the question did not appear to be highlighted in any way indicating that it was the reason the form was not complete. If information is missed that must be completed it should be highlighted so the participant can easily see what they missed. 
8. -	Avalow selected multiple sources from which she heard about the study, hit submit and nothing happened. Submit changed to ‘saving’ but appeared to just be circling, she could not move forward to the profile.
9. -	After entering Phone 1, Phone 2, Email 1, Email 2 you are asked what is the preferred method of contact, people might not remember what they had entered for each of those fields. It should say something like: “Contact me by email at”: and have dropdown of the email address options previously filled in by the participant.
10. -	If NCI requires that the secondary contact have a different phone number than the participant this should be stated on the form. Also, if NCI allows the secondary contact to be somebody who lives with the participant there should be a button to click saying “use same address as above” or something to that effect to save the participant some time. 
11. -	In general, the page seems convoluted and does not appear to be ordered well.

**Comment by Eusuf2000** [comment]
1. Works for me on Chrome and Edge. Doesn't work for me on IE11 and Firefox.

2. Every token is associated with a healthcare provider. Asking users about their healthcare provider may not be necessary if they are required to have tokens to sign up. 

3. Tells me to follow the format for phone but doesn't display what the format is.

4. Displays red asterisk (*) for required fields which is informative.

5.  Page appears to be straight forward to me.

**Comment by dbakumar** [comment]
Few more testing comments from HP 
1.	Here I would provide some instruction – something like, please provide an email address (or phone number) that you can access now to verify your identity. This email (or phone number) will not be used to… 
![image](https://user-images.githubusercontent.com/4921186/71925382-89f98100-3156-11ea-8228-689516f9881c.png)

2.	Also generally it seems like there needs to be more orienting language on the first page. Something that reminds the person what they are creating an account for, for example.
3.	Can the verification email be more friendly and better connect to the study? Is any info needed about how long this link is good for or who to contact w questions? Right now the highlighting is all that appears study specific. Can this change just to “Connect Study” or something like that?
![image](https://user-images.githubusercontent.com/4921186/71925464-b8775c00-3156-11ea-80d6-0765471a174e.png)

4.	When I click on the verification link I am taken back to IE and get this message – my first thought was that I needed to open old connect page and reenter my email and password, then I realized that I needed to go back to chrome. I cut and paste the link from email into chrome. But then I am told that the link no longer works. I definitely would give up by now.

![image](https://user-images.githubusercontent.com/4921186/71925488-c9c06880-3156-11ea-8da0-116f44a2d9fe.png)

5.	I could not navigate from the Chrome website how to go back and try the whole thing with a text message.

**Comment by Eusuf2000** [comment]
Tested on firefox version 72. Works fine. Below are our observations which we went over on yesterday's call:

![image](https://user-images.githubusercontent.com/57463904/72075026-eed0ea80-32c0-11ea-83fc-da77004ecdf7.png)

**Comment by strennr** [comment]
Comments from testing:

1. On the contact information page, it allows user to select "Email 2" as the preferred contact, even though a second email was not provided.  Presumably, the same issue with "Phone 2".

**Comment by Eusuf2000** [comment]
Used token to sign up. Still prompted for PIN. Entered PIN. Then prompted to select site... Ideally it'd be better to automatically skip PIN question if token is used and skip site selection question if either token or PIN is provided. Assuming token/pin is always unique and belongs to a specific site.
