### ISSUE TITLE
Access issues to Biospecimen dashboard

### ISSUE THREAD

**Issue by dwitt116** [episphere/connect#440]
I recently added our coordinator as a user in our biospecimen dashboard but she is unable to sign in.  Keeps getting message "Authorization failed, you lack permissions to use this dashboard".  Is there something I need to do on our end to fix this?  Thanks.

**Comment by Davinkjohnson** [comment]
@dwitt116 Is this still an issue for your team? (I thought we may have figured this out via a different channel, but wanted to be sure.)

**Comment by dwitt116** [comment]
@Davinkjohnson This issue has been resolved, thank you for following up!

**Comment by Davinkjohnson** [comment]
solved!
