### ISSUE TITLE
Activate comments section on Tube Collection screen for reasons not collected

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#444]
Currently on the Tube Collection screen, you can only put in comments that are directly linked to a tube if the full specimen ID is entered.  Sites would like to ability to enter a comment here even if a tube is not collected or before the Specimen ID has been entered.

**Comment by anthonypetersen** [comment]
@wyattks I think this may have been recently implemented with a different issue, let me know if it's working as expected.
