### ISSUE TITLE
Script pop ups on check-in/check-out screen

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#446]
We need more discussion on what we want with this.

On the check-In/check-out screen, if one of the boxes has a red X, be able to hover over it and have a script pop up.  For example, the SSN entered has a red X.  If they hover over it have the script appear on what they should tell the participant.  Same with incentive- have text stating what would make then eligible.

If the hovering won't work, can we add an information tab next to the boxes and if the user clicks that a modal will appear with the text?

We still need to supply text.

**Comment by StephanieWeinstein** [comment]
No longer necessary
