### ISSUE TITLE
Collection ID scan fixes on Specimen Link screen

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#447]
Two issues came up when sites were scanning in the Collection IDs on the Specimen Link screen.

1 - the scan box was allowing for free text to be entered.  User should only be allowed to scan into the box and not manually enter the IDs.

2 - If the scan was in lower case, an error appeared even if the full ID was correct.  Please fix so even is lower case is entered the ID will be accepted.  Issue #274 previously addressed this case sensitivity.

**Comment by wyattks** [comment]
For issue #1 above, please add a second scan box under the first and label as "Re-enter Collection ID"
Please put the same QC checks in for the scan boxes that exist for the manual entry boxes.

**Comment by brotzmanmj** [comment]
Issue #2 resolved, Issue #1 on hold for later

**Comment by wyattks** [comment]
Adding a new issue for #1 as we are changing the request. Issue #563
