### ISSUE TITLE
Add Collection Date/Time to Tube Collection Screen

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#448]
Add Collection Date/Time to top of the Tube Collection Page, label it as Collection ID Link Date/Time.

We want it labeled as Collection ID Link Date/Time so it is clear to the sites what the date/time represent.  There was some confusion with the sites on what the collection date/time mean.

**Comment by wyattks** [comment]
please have it 2/17/2022 12:12 PM est

Can we do that?

**Comment by anthonypetersen** [comment]
@wyattks so always display the time as the EST equivalent?

**Comment by wyattks** [comment]
Yes.  I believe that would be easiest correct?

**Comment by anthonypetersen** [comment]
it would

**Comment by StephanieWeinstein** [comment]
by the way, this is already displayed on the summary review page, so the format should look the same here.  (there are reasons for displaying it in both places)

**Comment by wyattks** [comment]
Yes, the sites indicated it would be helpful to have it displayed in both locations.  The way it appears on the review page will work for the collection page.
