### ISSUE TITLE
unverify user:

### ISSUE THREAD

**Issue by danielruss** [episphere/connect#45]
Who has the authority to do this, how do they do it, what happens to data and specimens already collected for this person?

**Comment by danielruss** [comment]
This is a management issue.  Not a developer issue.

**Comment by Eusuf2000** [comment]
These are what we plan to do:

•  If the participant is not verified automatically then the participant information will be sent to the manual review queue (in our CRM application) where the field staff/coordinator looks at the queue. 
 
 •	CRA will search the cohort population (in CRM application) for matching. If it is matched then the CRA will update our CRM application with the info and the NCI will be updated by the nightly API push as ‘verified manually.’
 
 •	If the CRA is unable to search the participant in the CRM application then they will reach out to the potential participant via email, phone call etc. to investigate and/or process it further. 

 •	If the participant is still unverified then the CRA will flag it as unverified in the CRM and a secondary review will be done by the PM/PC. Once PM/PC confirms that the participant is unverified then the unverified status will be pushed to NCI in a nightly API call.
 
 •	Any information sent to us by NCI for verification will remain in our CRM application with unverified status flag and the record will be inactivated. 

•	Most of the information that has been collected on the Active Participants will be with the NCI (profile, consent, questionnaire, etc.). We will not be able to collect any specimens if the participant is unverified.
