### ISSUE TITLE
Tube Collection screen will not save if deviation = "Other"

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#452]
If "Other" is picked for the deviation on the Tube Collection screen, the "Save" and "Save and Continue" functions do not work.  You just remain ion the screen with nothing happening.

**Comment by anthonypetersen** [comment]
Going to make the Comments text box required if "Other" is selected for Reason Not Collected OR Deviation Type

**Comment by anthonypetersen** [comment]
Another issue was found as we used to have two different types of explanation boxes, one for Reason Not Collected (338286049) and one for Deviations (536710547). We might need to combine the two in the Data Dictionary to reflect the fact that we only have one comments box now per tube.

**Comment by anthonypetersen** [comment]
The reason the issue is happening though is because I was dumb and kept some old code when refactoring and we are referencing something that doesn't exist anymore.

**Comment by anthonypetersen** [comment]
Decision was made to keep both concepts and populate them based what happens on the form
