### ISSUE TITLE
Check-in Modal requested for repeated check-in on same day

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#453]
It was requested to have a modal if someone is attempting to check-In a participant for a repeat visit type.  They would like to modal to confirm you do want to check-in the participant again.  
Wording would be "Participant [NAME] was previously Checked In on [Date/Time].  Do you wish to check them in again? " The modal would have a yes which would take the user to the check-in screen or cancel which returns the user to the participant search results screen.

**Comment by wyattks** [comment]
Putting on hold as needs more discussion.  

If Tony makes us the back door way into specimen link to link an additional collection ID, then we may not need this one.

**Comment by wyattks** [comment]
We do want multiple Collection IDs for a visit type but not for multiple Collection IDs linked to the same visit instance.

We will allow a second visit of the same type but will only link a new Collection ID if the repeat visit is NOT on the same day.  We will need a pop-up on the dashboard saying "Participant [NAME] was previously Checked In on [Date/Time]. Do you wish to check them in again?"  when a visit type is repeated.

Coming back in on the same day (same day means same date, not 24 hours from original check-in) do not check them back in, use the previously linked Collection ID.  Do not check a person in more than once in a day. 

If the participant comes back on another day, check them in again and link a new Collection ID.  Only collect the specimens not previously collected.

**Comment by anthonypetersen** [comment]
@wyattks Need some input on the following...

* Text for the Title of the pop-up
* Buttons on pop-up, the text on the buttons, and what should happen if each is clicked

**Comment by wyattks** [comment]
Text for the Title of the pop-up:  "Warning - Participant Previously Checked In"
Buttons:
"Cancel" - Stay on Search Results Page
"Continue" - Proceeds to Check-in Screen


Can we have in the Modal what the Collection ID was?  We are worried there is no way for the sites to know what was previously assigned to the Collection on that day. 
Something like:
“Participant [NAME] was previously Checked In on [Date/Time] with Collection ID 'CXA######"."

**Comment by anthonypetersen** [comment]
@wyattks also this modal would be popping up when they were already on the Check-In screen, does that affect what we want the buttons to say?

**Comment by anthonypetersen** [comment]
do you want [NAME] to be [last, first] or [first last]

**Comment by wyattks** [comment]
@anthonypetersen I'm not getting the pop up for this.  I am in incognito mode and am trying to check One BiospecTestOne in again today.  It just allowed me to without any pop-ups except for the success one.

**Comment by wyattks** [comment]
It appears when a new visit type is selected.  As Tony stated- because the participant had been checked in previously (a month before) and all the baseline specimens collected, the system was allowing for the check-in.  Once I switched to a different visit type and tried to check the participant in for that visit type twice in a day, I was getting the modal.
