### ISSUE TITLE
Rename Tube Collection Screen

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#457]
To help clarify some confusion by the sites, please change 'Tube Collection' to 'Collection Data Entry' in the following locations:

On the tab in the navigation bar which can be seen when you are on the Tube Collection screen or on the Summary/Review screen.

'Return to Tube Collection' button on the Summary/review screen.

**Comment by we-ai** [comment]
Tony resolved this issue in commit 5b4b7b8 on Feb 9, 2022.
