### ISSUE TITLE
Do not allow same Collection IDs across multiple sites

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#465]
Marshfield sent a list of 5 IDs they were using during testing.  
CXA123555
CXA123999
CXA666666
CXA987654
CXA123446

To make sure we could not use the same Collection IDs across sites, Erin from Health Partners and I tested with those IDs as well.  We were both able to link them to our own participants.  We feel the occurrence of having duplicate Collection IDs being sent to multiple sites will be low we want to make sure that if the rare occurrence does happen the system has a QC check in place.

See attached file for all of Erin's comments.

 
[Same Collection ID across multiple sites.docx](https://github.com/episphere/connect/files/7945834/Same.Collection.ID.across.multiple.sites.docx)

**Comment by anthonypetersen** [comment]
Found the issue.. Filtering is done on the backend based on Site, so code doesn't think specimen "exists" when we check for duplicates. But then we overwrite the specimen that actually exists. Waiting on feedback for how a fix should be applied.

**Comment by wyattks** [comment]
After recent data wipe Erin entered 2 Collection IDs and linked them to a Health Partner's participant.  I tried to link the same Collection IDs and received errors.
CXA000041 - received error
CXA000048 - Received Error

**Comment by wyattks** [comment]
It was an expected error saying the Collection ID was already used.
