### ISSUE TITLE
Increase font size and Bold Box on Box Manifest screen

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#469]
On the box manifest screen, increase and Bold "Box## Manifest".

**Comment by Gbarra9** [comment]
Let me know if the font size needs to be adjusted for "Box## Manifest"
<img width="1193" alt="Screen Shot 2022-01-31 at 2 00 38 PM" src="https://user-images.githubusercontent.com/33293205/151859578-89c6d79a-f8f1-4318-bab4-8d945f07f709.png">
