### ISSUE TITLE
Design of the app

### ISSUE THREAD

**Issue by danielruss** [episphere/connect#47]
design, layout, headers, language needed for every screen and message the participant sees that is within the nci portion of the recruitment workflow. Who is designing this and when?

**Comment by danielruss** [comment]
design, layout, headers, language needed for every screen and message the participant sees that is within the nci portion of the recruitment workflow. Who is designing this and when?

**Comment by strennr** [comment]
Other threads have addressed some of these issues as well, but we (Marshfield) noted that there are several usability issues that need to be addressed in the design, including but not limited to:

1). The user sign in/out options are not where a user would typically expect. Most websites show these in upper right hand corner of website.
2). Some drop down options do not appear in alphabetical order (example: Healthcare provider).
3). Readability issues - some text appears too small.
4). No option to delete second options for alternative contact information (email and phone).
5). Options to download signed consent form or other material.
