### ISSUE TITLE
Add an auto advance on Assign Tracking Number screen

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#476]
When entering the tracking numbers, if enter is hit, add an auto advance to the next box.

**Comment by Davinkjohnson** [comment]
@Gbarra9 look into code in the collections form for where we're using an event listener to do this

**Comment by wyattks** [comment]
Ready for Stage

**Comment by Davinkjohnson** [comment]
@wyattks @HopkinsDC reach out to a site to confirm whether this is in PROD

**Comment by HopkinsDC** [comment]
HP confirms this is in production and is working as expected.
