### ISSUE TITLE
Connect messaging format

### ISSUE THREAD

**Issue by danielruss** [episphere/connect#48]
how do sites want to receive notification of actions happening in our system (e.g. if someone consents or completes a user profile)? Who should be notified and how? What data do they need to receive?

**Comment by Eusuf2000** [comment]
We’ll fetch data from NCI using API call on a regular basis. We only want information on those who completed user profile. Without user profile, there isn’t much information on the participant to verify. However, we will need all the statuses displayed on the NCI dashboard for the participant, where they are in the process: login, consented, profile created, questionnaire, etc. for manual review.
