### ISSUE TITLE
SSO requirements for Biospecimen Dashboard

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#482]
@abhinavjonnada82 Hi Abhinav, Here are the SSO requirements for the Biospecimen Dashboard:

Site users: Should have access to all components of the Biospecimen Dashboard EXCEPT the BPTL section. And of course limited only to participants and specimens from their site.
As with the Site Manager Dashboard, each site will have a Site Admin who is responsible to assigning and revoking SSO access to the Biospecimen Dashboard at their site.

BPTL users (Norma and her team): Should have access ONLY to the BPTL section of the Biospecimen Dashboard, nothing else.

NCI users: In Dev environment, should have access to all parts of the Biospecimen Dashboard. In Stage and Prod, since NCI is not a real site, we should only have access to the 'Reports' section of the Biospecimen Dashboard.

Please let us know if you have any questions.

**Comment by Davinkjohnson** [comment]
@abhinavjonnada82 to verify that NCI is a "master" site which can see all sites/participant data.
