### ISSUE TITLE
Formatted Biospecimen Table - Deviation - Mislabeled not needed on tabl

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#490]
Deviation - Mislabeled (806820884) is showing up on the Data report.  This Concept ID is not being used in the dashboard anymore but a column for it has shown up on the Data table.

**Comment by StephanieWeinstein** [comment]
and while this variable it is mostly empty for all tube types, there are some participants with "No" for this variable for all tube types.

**Comment by anthonypetersen** [comment]
![image](https://user-images.githubusercontent.com/18222069/156844885-d230032f-1529-43bd-a7a5-3f586b99157f.png)

**Comment by anthonypetersen** [comment]
is this an example of the issue?

**Comment by StephanieWeinstein** [comment]
yes, exactly

**Comment by anthonypetersen** [comment]
If so, affected Collections appear to be: 

* CXA123422
* CXA000048
* CXA000041
* CXA123421
* CXA123433
* CXA876876 (this one was entered by me)

**Comment by anthonypetersen** [comment]
So my initial thought on this one is that these collections were entered using old code... Would we be against deleting these Collections from dev and re-entering them then having Madhuri re-run this data table?

**Comment by wyattks** [comment]
We could re-enter.  We wanted to redo some tests anyway.

**Comment by anthonypetersen** [comment]
Let's circle back to this Monday morning

**Comment by wyattks** [comment]
Sounds good

**Comment by brotzmanmj** [comment]
Just adding: This issue is linked to #487

**Comment by mnataraj92** [comment]
I haven't removed the mislabeled variable from the dictionary yet since we were waiting on the gold standard file, but I have removed it from my formatting code.
