### ISSUE TITLE
Formatted Biospecimen Table - Missing Column for Not Collected details

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#492]
The data file is missing the variable for 'not collected details' (concept ID 338286049).  An example of data we entered where this should exist is:
CXA123438 where reason not collected entered in Comments for all the blood tubes was this text: 'second baseline visit'
CXA123432 for EDTA tubes, not collected details was this text: 'ran out of EDTA tubes'

**Comment by mnataraj92** [comment]
I didn't see this variable in the biospecimen table that was pulled from BQ. The way I wrote my code was I took all of the concept IDs present in the biospecimen table and translated them. Is it possible this variable was added later? I can try pulling the biospecimen table again and running the format code.

**Comment by zly2021** [comment]
Hi, I just added concept_ids d_299553921_d_338286049, d_652357376_d_338286049, d_838567176_d_338286049, d_454453939_d_338286049, d_143615646_d_338286049, d_973670172_d_338286049, d_703954371_d_338286049 to the bigquery flat table.

**Comment by zly2021** [comment]
When I check with Madhuri together today, the value changed from No to Yes for the collection flag already
