### ISSUE TITLE
Formatted Biospecimen Table - Empty Deviation Cells for CXA123421

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#493]
CXA123421 has a lot of empty deviation cells.  Most of the newly added deviations do not have data associated starting from the ACD Tube.  The cells under the new deviations do not have a yes or no.  File is attached.   Is there a reason some of the cells for a collection will have yes/no and others are completely blank?

The specific columns I am looking at are:
BX5 - CC5 (ACD Tube)
CL5 - CQ5 (Heparin Tube)
CZ5 - DE5 (EDTA Tube)
DN5 -DQ5, DV5 (Mouthwash Tube)
DX5 - EA5 (Urine Tube)
[CXA123421 Data issues.xlsx](https://github.com/episphere/connect/files/8188736/CXA123421.Data.issues.xlsx)

**Comment by anthonypetersen** [comment]
I believe that might be a case of Incognito as well. For that collection, all of the deviations we would expect to be there weren't initialized but I just created a new Collection and everything was there. Should be something to just keep an eye on, but I don't believe this will be an issue going forward.

**Comment by zly2021** [comment]
We check above tube deviation for the connect id in the CXA123421.data.issues spreadsheet and there is no information in the original table of Bigquery for this person
