### ISSUE TITLE
Check-In/Check-Out add Baseline CXA #s and dates

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#496]
On the Check-In and Check-out screen under the Baseline visit boxes, if there is a green check in the box add the CXA # and Date/time of collection associated with the baseline collection.

**Comment by anthonypetersen** [comment]
is this still an issue?

**Comment by StephanieWeinstein** [comment]
Hi Tony,
I just checked and this has not been completed yet. We would still like it if its not too hard.
thanks!
Stephanie

**Comment by Davinkjohnson** [comment]
Want date for every specimen collected

**Comment by anthonypetersen** [comment]
pushed to dev

**Comment by wyattks** [comment]
Tested and looks good.

**Comment by HopkinsDC** [comment]
HP confirms change in stage. Ready for deployment.
