### ISSUE TITLE
Discard Flag not set to Yes correctly

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#497]
For the SST2 tube collected for participant Issue Issue, Collection ID CXA123457, a deviation of Mislabeled- discard was selected.   As this is a discard deviation, the discard flag for CXA123457 0002 should be set to "yes" instead it is set to 'No".

The Mislabeled- discard deviation is one of the ones not showing up in the data file.
[CXA123457 0002 discard flag Issue.xlsx](https://github.com/episphere/connect/files/8199932/CXA123457.0002.discard.flag.Issue.xlsx)

**Comment by wyattks** [comment]
Below are a list of the deviations that should change the discard flag to Yes.

Discard (record in comments)     Concept ID: 810960823
Broken (discard do not ship)       Concept ID: 472864016
Mislabeled- discard                     Concept ID: 684617815
Insufficient volume, discard         Concept ID: 956345366

**Comment by anthonypetersen** [comment]
@wyattks issue here is on our end, our code needs small update to set Discard flag for these concepts

**Comment by anthonypetersen** [comment]
updates pushed to dev

**Comment by wyattks** [comment]
CXA775533 0006 had a discard deviation and discard flag was set to yes.
