### ISSUE TITLE
Recruitment data from sites

### ISSUE THREAD

**Issue by danielruss** [episphere/connect#50]
recruitment data that we need to receive from the sites- need list and format of all data elements, when we will receive it, how and when it will be qc'd.

**Comment by Eusuf2000** [comment]
•	If NCI has an API available we can send excel or flat file

•	We will send aggregate level recruitment data to NCI.

**Comment by bhaumik55231** [comment]
**Submit participant data** would fulfill the requirement of sending participant data.
