### ISSUE TITLE
Incognito Windows

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#500]
I'm opening this issue so we do not forget to revisit and figure out directions for the sites and participants.

1 - do the sites need to input all their data through incognito windows?  
2 - do the participants need to use an incognito window when filling out their surveys?

**Comment by brotzmanmj** [comment]
2- Participants using a shared tablet or other shared device at the sites to complete questionnaires must use an incognito window. This should be in the Check-In SOP; the site staff will open and incognito window, hand them a tablet to complete the survey(s) and close out the incognito window when the participant is done completing the survey(s).

**Comment by wyattks** [comment]
Yes we have that in the SOP.  I should have been more clear.  This is if they are using their own devices and updates have been made to the dashboard.  We are not sure if participants using their own devices would have to clear their caches if they had previously logged in to make sure they are responding to the most up to date code.

**Comment by StephanieWeinstein** [comment]
that is our question, is this relevant to participants who are filling out surveys?  If not relevant, then we can drop it.  It came up in our discussions today about the check-in SOP where we direct users of shared tablets to use the incognito window - do we also need to direct participants using their own devices to use incognito windows?

**Comment by brotzmanmj** [comment]
Nope :)
The purpose of having them do so on the shared devices is not because of changes pushed by our team as in the dashboards; it's because not using an incognito window means that there is potential that someone using the tablet next could see their data (stored in the cache, etc)

**Comment by StephanieWeinstein** [comment]
yeah, we knew it was so that the next person could not see their data, but we wondered if there would also be issues with changes pushed out. But if its not an issue then we won't worry about it!

we still need to determine whether sites need to use incognito, or if they clear their cache every time changes are pushed, would that take care of things? So this github issue is so we don't forget to address this!
