### ISSUE TITLE
Change Red X to Green check for two participant statuses

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#502]
On the check-in/check-out screen, please change the red X to a green check for the following two participant statuses.
Refused some activities
Refused all future activities

The green check should be for No Refusal, Refused Some Activities, Refused all Future Activities. The red X for the other statuses.

After discussion we feel if the participant actually shows up to give specimens, then we will allow them to.  The participant status on the check-in/check-out screen should now match the participant status on the search results screen. 

Thanks

**Comment by brotzmanmj** [comment]
@anthonypetersen Yes, this looks like the same issue. I though the earlier one was closed so I submitted a new one.

**Comment by brotzmanmj** [comment]
I tested this today. Participation Status look correct and consistent except for these two:
Participation Status = 'Refused all future activities' is correctly showing as green checks in both places, but on the Check In/Out page it displays as 'undefined'
Participation Status = 'Deceased' is showing correctly as red X in both places but on the Check In/Out page it displays as 'undefined'
We checked the underlying data and the participation status for both is correct so we're not sure why it's not showing.
Here are two examples of the participants we checked:
Refused all future activities - Connect ID 60836898773 
Deceased- Connect ID 4500622597

**Comment by geniosys** [comment]
I updated the concept ids per our discussion. Everything should be good to go now. Thanks

**Comment by brotzmanmj** [comment]
Participation status for those two statuses is now correct, but I'm getting odd instances now where the whole check in/out screen shows only as 'undefined' and otherwise blank. Search Connect ID 60836898773 (participation status = refused all future activities) or Connect ID 36593441425  (participation status = withdrew consent)

**Comment by HopkinsDC** [comment]
Changes made successfully. Confirmed with:
- Connect ID# 4592691088 = Refused All (green check present)
- Connect ID# 9355242353 = Refused Some (green check present)
- Connect ID# 4242162341 = No Refusal (green check present)
