### ISSUE TITLE
Bag/Sleeve Collection ID remaining in Available Collections Section

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#508]
On the Packaging screen of the shipping dashboard, we noticed the Bag/Sleeve Collection ID remains in Available Collections Section after a tube is marked as not in the bag/sleeve and the remainder of the tubes are assigned to a box.
This happens when a bag/sleeve Collection ID is scanned into the Enter/Scan and the Sample Present box unchecked for a tube in the Specimen Verification modal.  The specimens that are present are added to a shipping box and correctly appear in the View Shipping Box Contents section.  But the Specimen Bag ID also shows back up in the Available Collections section.    
The Specimen Bag ID still being in the Available Collections is not correct.   If a tube is marked as not present in the bag and the remainder of the tubes assigned to a shipping box, we do not want the Specimen Bag ID to show back up in the available collections.  For all purposes that bag is now in a box.  Please remove having a Specimen Bag ID in the Available Collections when it has already been placed in a box.

Please let me know if you have questions.

**Comment by Davinkjohnson** [comment]
Leaving this on hold until post go-live stabilization. (close if no new issues/occurrences appear)
