### ISSUE TITLE
Sanford prod issue with recruit type=Connect ID

### ISSUE THREAD

**Issue by robertsamm** [episphere/connect#511]
For one of the records that had their recruit type manually updated from passive to active for the triple duplicate issue, the recruit type was updated to the participants Connect ID instead of the correct recruit type variable. This is for participant with Connect ID: 2980632837.

This issue is also messing up the prod metrics.

**Comment by bhaumik55231** [comment]
Hi Amelia, sorry for the inconvenience, I have fixed it. Looks like the correct recruit type concept Id was not copied properly and instead previously copied Connect ID got pasted.
