### ISSUE TITLE
SSN variables

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#514]
SSN variable for not started, started, submitted to be set as default (exists from the start).  That variable and date/time SSN module started and date/time submitted need to established an set based on activity on the app. CIDs exist but variables were never implemented. Add these variables to the biospecimen dashboard check in/out screen and the SM dashboard participant summary screen.

The existing variables for full SSN digits given (and date/time given) and partial SSN digits given (and date/time given) are currently being set when someone enters the SSN into quest, regardless of whether the module was submitted, and the variables do not change back to 'No' if the person backs out their data in quest. Change this to function such that those four variables are set only upon submitted status of the module.

**Comment by brotzmanmj** [comment]
Linked to issue https://github.com/episphere/connect/issues/504

**Comment by anthonypetersen** [comment]
CIDs have been updated / added in dev

**Comment by brotzmanmj** [comment]
Michelle confirmed the new variable for SSN not started, started, submitted and date started and submitted are working as expected. 
Remaining part of issue is to change the Full SSN received and Partial SSN Received to only set to yes if the SSN module is Submitted (not if they entered data and didn't submit the module).
