### ISSUE TITLE
Add a second collection site for HF

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#515]
Henry Ford currently has one collection location of 'HFHS Research Clinic (Main Campus)'.
We need to add a second collection location in the drop down (Select Collection Location) on the specimen link page of 'HFH Cancer Pavilion Research Clinic'
HF will still only have one shipment location.

Madhuri - we will need to have a new Collection Location Concept ID created for this location. Collection Location Concept ID is 951355211.  So it would need to be nested under here.

**Comment by anthonypetersen** [comment]
@wyattks do we need a new collection location or a new site? There's the concept ID you mentioned, but I'm also looking at CID 560975149 where we are storing multiple HF sites at the moment. Just want to make sure we make these changes in the correct spot.

**Comment by anthonypetersen** [comment]
@wyattks correct

**Comment by wyattks** [comment]
Ok.  Then we only need 'HFH Cancer Pavilion Research Clinic' for concept ID 951355211.  It will be a collection location only and not a shipping location.

**Comment by mnataraj92** [comment]
I have made this addition to the dictionary

**Comment by brotzmanmj** [comment]
Kirsti at HF confirmed that both collection locations appear.
