### ISSUE TITLE
Source of Deceased Report to be removed as a default variable

### ISSUE THREAD

**Issue by FrogGirl1123** [episphere/connect#517]
Source of Deceased Report (CID 764403541) is currently a default variable (set when we receive the studyId for active recruits or at sign-in for passive recruits) in the Prod environment, but should not be.  The prod environment needs to be updated such that 764403541 is not set as a default for new recruits.  For past recruits, 764403541 will need to be deleted, as the format for the response CID is a string instead of a integer.  @Davinkjohnson and @anthonypetersen please confirm that I have interpreted our conversation correctly.

**Comment by Davinkjohnson** [comment]
@FrogGirl1123 This is in production now. 

Can we close this issue now?

**Comment by sonyekere** [comment]
Closing issue. Last update 05/22
