### ISSUE TITLE
Bug with Entering Full Specimen ID on the Collection Data Entry Screen

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#519]
On the Collection Data Entry screen, when I am entering in the Full Specimen ID, if I hit enter after entering in the ID the screen is going to the check-out screen instead of going to the next data entry line.  We only want to go to the Check-out screen if the Go To Check-Out button is selected.

This happens for manual entry and scanning of the IDs.
Happened for:
Connect ID 8787519057, CXA777125 Manual Entry
Connect ID 6630532769, CXA000126 Scanning

**Comment by anthonypetersen** [comment]
@wyattks let's meet when you're back in the office, I can't seem to replicate this manually or with a scanner

**Comment by brotzmanmj** [comment]
More info on this: HP says this is not happening in stage today but they did encounter this in dev recently, and to get around it they had to manually enter each tube ID and NOT hit enter….had to click into the next field manually.

**Comment by anthonypetersen** [comment]
Issue should be fixed... One thing I thought of though, when this button is clicked I don't think we saved any unsaved changes.. Do we need to warn the sites about that?

**Comment by StephanieWeinstein** [comment]
Hi Tony, thanks for fixing the bug so quickly and thanks for noticing that data that have been entered on the page are not saved if someone clicks the "go to check out" page.  As we discussed, it would be preferable to just disable the "go to checkout" button for now so that no one enters data and then looses the data by accident.  We can certainly launch without that button.

**Comment by brotzmanmj** [comment]
If disabling it but leaving it visible is too confusing to users, it might be preferable to hide it entirely or remove it.

**Comment by we-ai** [comment]
We can use ' display: none ' to hide the button, so that it doesn't confuse users. After more thorough implementation and testing, we may put it back.

**Comment by anthonypetersen** [comment]
Code has been pushed into stage

**Comment by brotzmanmj** [comment]
Bug is fixed. Button is hidden, code is there for later. Also wasn't saving entered data before took users to next screen.
