### ISSUE TITLE
Report Creation Tracking

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#520]
This issue is to track the progress of the report creation on the Biospecimen Dashboard.
Gene- if you need specifics please let me know and I will add them onto the issue.

**Comment by Gbarra9** [comment]
Reference:

[Modify getBoxesPagination and getNumBoxesShipped endpoints on connectFaas ](https://github.com/episphere/connectFaas/pull/162)

Styling Filter and Manifest Buttons 
![Screen Shot 2022-05-17 at 9 06 30 AM](https://user-images.githubusercontent.com/33293205/168861568-6bccdf1d-1297-4136-a599-24086c6efea3.png)

![Screen Shot 2022-05-17 at 9 17 18 AM](https://user-images.githubusercontent.com/33293205/168861604-1b013908-af93-40fe-9d05-159c17d26708.png)
