### ISSUE TITLE
Update Connect logo and flavicon

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#523]
Mia noticed that the biospecimen dashboard has the old red and black Connect logo and flavicon. Please update to the current ones. Deanna can provide them.

**Comment by anthonypetersen** [comment]
Should be resolved now that stage has been updated

**Comment by brotzmanmj** [comment]
Connect logo looks right but flavicon is the old red and black one. Can we swap that out for the current blue one that appears on the SM dashboard?
