### ISSUE TITLE
Remove extra menu items from stage and prod dashboards

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#524]
The menu items: Report Issue, Github Projects, and Chat With Us should only be on the dev dashboard. Please remove them from the stage and prod dashboard.

**Comment by Davinkjohnson** [comment]
Remove theses in Dev as well. (They aren't used)

**Comment by Davinkjohnson** [comment]
@HopkinsDC to check today

**Comment by HopkinsDC** [comment]
Menu items removed successfully.
