### ISSUE TITLE
Remove Sign in With Email from stage and prod

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#525]
Suggest we remove the Sign In With Email from the stage and prod dashboards as this will not be functional.

**Comment by geniosys** [comment]
Done - in dev

**Comment by anthonypetersen** [comment]
@brotzmanmj whenever you want

**Comment by brotzmanmj** [comment]
good to go anytime from my perspective

**Comment by anthonypetersen** [comment]
done.. we can move this to prod when we move the rest of our code
