### ISSUE TITLE
Error on Clinical vs Research dashboard assumption in Stage

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#528]
Erin from Health Partners came across an error when performing a specimen search on CXA000186 Yesterday and CXA000183 today.
They get an "Incorrect Dashboard  Research Collections cannot be views on Clinical Dashboard."
When some one else searched they were able to pull up the participant.
I have attached a screen shot.
[HP Search Error.docx](https://github.com/episphere/connect/files/8771927/HP.Search.Error.docx)

They just tried CXA000186 and was able to pull up the information this morning.
CXA000183 was assigned to Connect ID 5361119820

**Comment by anthonypetersen** [comment]
@wyattks one thing I notice right away... I don't think they should be adding the specimen ID to the end of the search?

**Comment by anthonypetersen** [comment]
@wyattks could you ask them to try this when they notice the issue? click on the Home button, then go back into the Specimen Search and try again.

**Comment by anthonypetersen** [comment]
ah, yeah that might not cause any issues, just something I wasn't used to seeing.

**Comment by wyattks** [comment]
From Erin:
I have just tried the steps listed below for CXA000183 and got the same error message both times---initially and after hitting close, clicking Home button and searching again. 

Our research specialist scanned the label with CXA000183 in to make the specimen link. The page started thinking (loading circle showed up), so she refreshed the browser.  Then, she went back into the participant and Specimen Link page and a message appeared that the collection ID was already in use. She searched for the specimen ID and got the error message we have been discussing today. At that point, we abandoned this test participant and moved on to the others.

**Comment by brotzmanmj** [comment]
Warren looking into why the system thought one of the HP RA's was in the clinical dashboard rather than the research dashboard

**Comment by brotzmanmj** [comment]
Davin says Warren has identified the issue of why the dashboard thought the RA was in the clinical dashboard and not the research dashboard and may be able to push the fix tonight.

**Comment by anthonypetersen** [comment]
fix pushed to dev

**Comment by brotzmanmj** [comment]
@anthonypetersen Is there any way you can think of that we can test this in dev or should we just move on and push it to stage? Not sure how to try to recreate the issue.

**Comment by anthonypetersen** [comment]
@brotzmanmj so the only way I was able to think to re-create the issue was the webpage reloading

**Comment by Davinkjohnson** [comment]
@HopkinsDC  to test today. Update us once Dev test is complete and @anthonypetersen to check Firestore.
