### ISSUE TITLE
Change Save and review Button

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#529]
On the Collection Data Entry screen, when save and review was used, the data entered was not saved. 
This was feedback from one of the sites.  They had entered in all the information, used the save and review button.  When they went back later the data fields on the Collection Data Entry screen were empty.
I have not tried it myself yet in the Dev environment.

**Comment by anthonypetersen** [comment]
Stage or Dev?

**Comment by wyattks** [comment]
Stage

**Comment by anthonypetersen** [comment]
Do we know who it was as well as the approximate time?

**Comment by Davinkjohnson** [comment]
@anthonypetersen Warren and I saw this with Erin. (she demo'd the issue for us around 1:50 CT today).

**Comment by brotzmanmj** [comment]
Rename Save and Review button to 'Go to Review'. Update user manual to instruct them to always Save before they leave the page. The 'Go to Review' button will do what it does now which is to QC the data, retrun any errors, and the save and move them to finalize.

**Comment by geniosys** [comment]
Done

**Comment by StephanieWeinstein** [comment]
Thank you.  Can you guys change the color of the save button from yellow to blue or green (whichever color you think is better).  The yellow tends to indicate optional things, and we really want them to be clicking this save button to avoid any data loss.  Thank you!!

**Comment by anthonypetersen** [comment]
@geniosys can you take a look into Stephanie's request when you get a chance?

**Comment by geniosys** [comment]
'Save' Button color changed.

**Comment by Davinkjohnson** [comment]
@HopkinsDC to check this in Dev today

**Comment by HopkinsDC** [comment]
"save" button color changed
