### ISSUE TITLE
Change to modal conditionality on Specimen Link

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#534]
Change to modal requested on Specimen Link page. When a collection ID is assigned, the system should check and see if a Collection ID for that visit type already exists for that participant, if so, display the existing collection ID and ask if they want to proceed or cancel. The existing modal works slightly differently, we think it only displays if the person was already checked in on that same day. 
This is not MVP for launch, but would like to discuss complexity and when to work on this.

**Comment by wyattks** [comment]
Go ahead and push to Dev
