### ISSUE TITLE
small changes needed to BPTL csv file

### ISSUE THREAD

**Issue by StephanieWeinstein** [episphere/connect#536]
Abhinav,
BPTL is testing the csv file and found two small items that need to be updated.

1. under Additive/Preservative where it says "EDTA" please change that to "EDTA = K2"
2. under Sample Collection Center where is says "HealthPartners" change that to "HealthPartners Research Clinic"

everything has to match exactly with what BSI is expecting.
Thank you!
Stephanie

ps - I don't have access to the BPTL dashboard so I'm putting it under shipping.

**Comment by abhinavjonnada82** [comment]
Changes addressed.

**Comment by Davinkjohnson** [comment]
Test these in dev with HF shipped packages today
