### ISSUE TITLE
Add Shipping Location for Lake Hallie

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#537]
Need to add a shipping location for Lake Hallie, associated with Marshfield. We have a CID for this as a Collection Location but not as a Shipping Location.  For reference, the Collection Location variable CID is 951355211 and the Lake Hallie CID response code within that is 698283667.  The Shipping Location variable CID is 560975149.  Can we add the same Lake Hallie CID response code to that and add it to the dashboard drop down for shipping location?

**Comment by Gbarra9** [comment]
Linked with [Issue#535](https://github.com/episphere/connect/issues/535)

**Comment by Gbarra9** [comment]
Merged changes to Dev. To check if dropdown was correctly added and implemented, Marshfield will need to test Lake Hallie dropdown and manifest Information for Review Shipping Contents manifest, reports query manifest and individual box manifest .

**Comment by brotzmanmj** [comment]
@Gbarra9 From the demo just now with Marshfield it looked like this was in stage and working fine. Can we close this?

**Comment by brotzmanmj** [comment]
@mnataraj92 Can you make sure this is updated in the Master DD? Thanks.

**Comment by Gbarra9** [comment]
> @Gbarra9 From the demo just now with Marshfield it looked like this was in stage and working fine. Can we close this?

Yes, this issue was in stage and can be closed.
