### ISSUE TITLE
Update the Master DD to add Lake Hallie shipping location

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#538]
Add to the Master Data Dictionary a shipping location for Lake Hallie, associated with Marshfield. We previously had a CID for Lake Hallie as a Collection Location but not as a Shipping Location. Gene added the same CID as a shipping location on the biospecimen dashboard. 

For reference, the Collection Location variable CID is 951355211 and the Lake Hallie CID response code within that is 698283667. The Shipping Location variable CID is 560975149.

**Comment by mnataraj92** [comment]
Sure, I'll make this update once Nicole gives me the green light to make dictionary changes.

**Comment by mnataraj92** [comment]
This change has been updated in the dictionary

**Comment by brotzmanmj** [comment]
Thanks! Closing the issue
