### ISSUE TITLE
Frequency, content, and type of reminders

### ISSUE THREAD

**Issue by hannahem** [episphere/connect#54]
Action Item from 2/5/2020 Feedback and Review Meeting: 

DCEG to determine the frequency, content, and type of reminders/communications from Connect.

Daniel shared that if the Connect system sends all reminders, we can have them on a timer and have reminders sent at intervals in the workflow. We also need to be sure to contact participants in the way that they asked us to contact them.

**Comment by danielruss** [comment]
Currently, this is more of a management decision and less of development issue.  I'll keep reminding the oversight committee that a decision needs to be made.

**Comment by brotzmanmj** [comment]
Hi Daniel, This will depend upon a better understanding of the app notifications in the PWA and also the case management system upon which successful coordinated use depends. Please let me know when we can discuss. Thanks.

**Comment by hzhao392** [comment]
Will be handled in spreadsheet
