### ISSUE TITLE
DD update for 2 variables Question Texts, Labels and Names

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#540]
Please change the following 2 variables' Question Text, Variable Label and Variable Name in the Data Dictionary

CID 410912345 
Question Text From: Autogenerated flag when review complete - go to shipping 
Question Text To: Autogenerated flag when collection entry finalized
Label From: Go to shipping   To: Collection Entry Finalized
Name From: BioRec_ShipFlag_v1r0    To: BioRec_CollectFinal_v1r0

CID 556788178 
Question Text From: Autogenerated date/time when go to shipping
Question Text To: Autogenerated date/time when collection entry finalized
Label From: Date/Time go to shipping   To: Date/Time Collection Entry Finalized
Name From: BioRec_ShipTime_v1r0    To: BioRec_CollectFinalTime_v1r0

**Comment by mnataraj92** [comment]
I have made these changes

**Comment by brotzmanmj** [comment]
@mnataraj92 Hi Madhuri, Just a quick note on the Master DD you probably also want to update the 'Required' note that still references the old variable name 'Yes if BioRec_ShipFlag_v1r0 equals 1'

**Comment by mnataraj92** [comment]
updated!
