### ISSUE TITLE
Chicago Shipping Issue with 2 straggler SST tubes

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#542]
Chicago is having issues with straggler tubes.  While performing a run through on shipping, they removed SST tubes CXA002227 0001 and CXA002227 0002 from the bag and virtually shipped the rest of the samples from that collection.

When they went to virtually ship the straggler tubes, CXA002227 0001 was giving an error of not being found and CXA002227 0002 would just churning when trying to add the tube to a box.

Chicago tried switching from the Edge browser to Chrome but that did not work.  They also tried logging out and back in, that also did not work.

**Comment by wyattks** [comment]
Shifting this information from issue #229. I was testing the new error modals and came across 1 issue. I removed tubes CXA000132 0001 and CXA000132 0002 from the "bag" and shipped the remainder of the samples from CXA000132. I went to add these two tubes into a new box, box 14, CXA000132 0001 showed up as expected. CXA000132 0002 is giving me an error stating item not found, item not reported as collected. If you go back to the collection screen the tube is marked as collected. Can you take a look? All the other errors are working as expected.

**Comment by wyattks** [comment]
@Gbarra9 In testing the clinical dashboard we are finding this same issue.

**Comment by wyattks** [comment]
This happened in the Dev dashboard 9/6/2022.  Abhinav had asked me to create an Orphan tube for testing with the csv file date/time stamp.  I created a collection for CXA000130, collected and shipped all but the Urine tube.  I went back and collected CXA000130 0006 and moved it to shipping.  When I tried to put CXA000130 0006 in a box I received an error stating it hadn't been collected.  If you go back to the collection screen it shows as having been collected.

**Comment by HopkinsDC** [comment]
Straggler tube issue tested in dev using the following biospecimen data:
Connect ID: 8062798612
Blood Accession ID:42115401234
Urine Accession ID:42115401235
Collection ID: CXA222010

SST tubes individually appear when the tube’s Full Specimen ID (CXA222010 0001, CXA222010 0002, CXA222010 0011, CXA222010 0012) is searched, but the dashboard buffers when “Add to Box” is clicked.

![Screen Shot 2022-10-03 at 2 05 19 PM](https://user-images.githubusercontent.com/85250133/193647537-736f23ed-6f3e-414d-9b35-20e5b2eb6257.png)

![Screen Shot 2022-10-03 at 2 05 49 PM](https://user-images.githubusercontent.com/85250133/193647540-333b7f14-15f3-44a4-9cce-974eb3cfb098.png)

**Comment by HopkinsDC** [comment]
SST straggler tubes were successfully added to box and shipped.

![Screen Shot 2022-10-03 at 4 10 57 PM](https://user-images.githubusercontent.com/85250133/193672219-7d019108-7d61-464a-ba06-b5bc11c8709d.png)

Tubes are still not showing in CSV file after being received.

[10_3_2022-BSI-data-export (2).pdf](https://github.com/episphere/connect/files/9700654/10_3_2022-BSI-data-export.2.pdf)

**Comment by Davinkjohnson** [comment]
related to issue #561 Straggler tube issue seems to be resolved.
