### ISSUE TITLE
Add actual login email/phone number to Check-in/out screen

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#543]
Please add the actual email or phone number a participant used for login to the Check0in/Check-Out screen on the Research dashboard. 

This is in case the person doesn't remember or has a duplicate account

**Comment by brotzmanmj** [comment]
@anthonypetersen  Has this been pushed to stage and prod?

**Comment by anthonypetersen** [comment]
@brotzmanmj no it has not

**Comment by brotzmanmj** [comment]
@anthonypetersen Do we have a deployment schedule for this? And would you like us to track it in github, maybe by moving it to a 'ready for deployment' column rather than just close it and mark it Done?

**Comment by anthonypetersen** [comment]
@brotzmanmj we can throw one together
