### ISSUE TITLE
Collection and Shipping Location Selection Defaults

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#544]
We had a situation with the soft launch where Marshfield Lake Hallie did not remember to re-select Lake Hallie under the Collection Center Location when making the Specimen Link.  They linked the first participant correctly, but when they linked the second participant they forgot to select the correct collection location.

For the location selection on the Specimen Link Page and on the Shipping packaging, can we have the default be Select one and have an error pop up if a location is not selected?  We are thinking this way the sites would be forced to pick a location and have more chance for that to be correct.

Let us know if you have other ideas for this.

**Comment by wyattks** [comment]
The Specimen Link Drop down is complete.

@geniosys Can we also have the same change made to the Shipping Location Dropdown on the packaging screen of the shipping dashboard?

**Comment by geniosys** [comment]
@wyattks just added the logic to shipping location dropdown.
