### ISSUE TITLE
Health Partner's Bag error on shipping dashboard

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#546]
During Health Partner's soft launch, an error was received upon first bag search in shipping dashboard that indicated it was not found because was affiliated with clinical and not research. We have seen and resolved that message before in the context of Collections rather than Shipping. Please look for source of error.

**Comment by anthonypetersen** [comment]
@wyattks did the error message say "Research Collections cannot be viewed on Clinical Dashboard" or was it something else?

**Comment by wyattks** [comment]
Yes, I believe it was the "Research Collections cannot be viewed on Clinical Dashboard" error

**Comment by wyattks** [comment]
@brotzmanmj 
Can you clarify when the error occurred?

**Comment by brotzmanmj** [comment]
@anthonypetersen It occurred when they tried to scan the first bag into the search box on the Shipping dashboard
