### ISSUE TITLE
Biospec- Dshbrd- QC Check for Assigned FedEx Tracking Numbers

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#549]
FedEx tracking numbers scanned into the 'Assign Tracking Information' page in the Shipping dashboard needs to be QC'ed against all previously assigned FedEx tracking numbers.

A QC check already exists for tracking numbers scanned for two different boxes on the same page if more than one box is being assigned a tracking number at once (see image below of pop-up message), but not for tracking numbers already assigned. A tracking number should never be repeated.
![Screen Shot 2022-07-06 at 3 58 54 PM](https://user-images.githubusercontent.com/85250133/177635507-5ffaeb8e-0994-4aab-a76e-2777c2ff3bd6.png)

**Comment by geniosys** [comment]
@wyattks 2 updates have been made and are in dev:
https://github.com/episphere/biospecimen/commit/683445b6b99f134c08a5dfad647232279da86885
https://github.com/episphere/biospecimen/commit/1b8d7a8c45f418d07b069f76be1b23c0e2422891
