### ISSUE TITLE
Connect sign up using e-mail no longer works

### ISSUE THREAD

**Issue by danielruss** [episphere/connect#55]
Cannot sign up for connect using the email option.  The webpage just spins.

**Comment by danielruss** [comment]
Correction.  You store something in indexDB that prevented me from logging in as a new user.  Not sure if this is a bug or a feature.

**Comment by strennr** [comment]
Marshfield noted this in workflow testing as well.  This could be an issue when multiple users (same household) are attempting to sign up on a shared computer.
