### ISSUE TITLE
Clinical Collection ID Link Date/Time Storage

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#551]
For The KP Clinical sites, the Date/Time the Specimen Link is made in the dashboard needs to be stored in the backend under:
conceptId: 915838974.  
Question Text: Autogenerated date/time when scanned at regional lab
 Variable Name: BioReg_ArRegTime_v1r0

**Comment by wyattks** [comment]
On the research dashboard the Specimen Link Date/Time is stored under the Collection Date/Time
Concept ID: 678166505
Variable Name: BioCol_ColTime_v1r0

On the Clinical Dashboard, this variable will be filled from data pushed from EPIC (KP's data system)

**Comment by wyattks** [comment]
@anthonypetersen Can you check backend data for me?  I ran a test today on Connect ID 8502122714, Collection ID CXA002644.  Can you see if the collection Data and time is not populated but the scanned at regional lab is?

**Comment by anthonypetersen** [comment]
@wyattks likely bug found.. I'll reach out to @geniosys

**Comment by Davinkjohnson** [comment]
Hendrick to verify he fixed this.
