### ISSUE TITLE
NCI Custom Clinical Tube list for Dev Dashboard

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#557]
Attached is a basic list of the tubes for the NCI Clinical site in dev and also a mock-up of what the data entry screen would look like for those tubes.  Let me know if you need anything else.

[NCI Clinical Tube Types.xlsx](https://github.com/episphere/connect/files/9184845/NCI.Clinical.Tube.Types.xlsx)

[NCI Clinical Collection Page.docx](https://github.com/episphere/connect/files/9184846/NCI.Clinical.Collection.Page.docx)

**Comment by wyattks** [comment]
Confirmed - ready for stage

**Comment by StephanieWeinstein** [comment]
9/7/22 - I concur this looks correct.
