### ISSUE TITLE
CSV File Bug - Date Received for Orphan Sample

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#561]
The urine tube for CXA000197 in prod was shipped a few days after the blood and mouthwash tubes by Sanford. The blood tubes were received at BPTL on 7/27. The urine tube (CXA000197 0006) was sent in a box by itself on 7/29 and received at BPTL on 7/30. The urine tube was shipped as an orphan in an unlabelled bag.
 
In the Biospecimen data table: The overall date received for the collection is 7/27 and all the blood tubes and the mouthwash tubes individually also have a date received of 7/27 at the tube level.
The urine tube does not have a date received at the tube level (the date received field for the tube is blank). It should have a date received of 7/30 at the tube level. The urine tube also does not appear on the CSV file from 7/30 (maybe that’s because the system is looking for the date received at the tube level, but it is blank).

**Comment by wyattks** [comment]
Ran a test in research and clinical. Stragglers showed up correctly in csv file for both dashboards.
[Straggler test 10-13-2022.docx](https://github.com/episphere/connect/files/9780716/Straggler.test.10-13-2022.docx)
[CSV testing 10-13-2022.csv](https://github.com/episphere/connect/files/9780717/CSV.testing.10-13-2022.csv)

**Comment by wyattks** [comment]
Need to test if they come in on a different day.

**Comment by wyattks** [comment]
Tested on 10/14/2022.  Tubes showed up correctly in csv file
