### ISSUE TITLE
Reports: Date Shipped vs Date Received

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#562]
UChicago reported that packages on their Reports section of the dashboard in prod display the same date for both Date Shipped and Date Received. Date Received should be at least 1 day after Date Shipped. 

Michelle checked the data report and confirmed both dates look fine, so this may be a dashboard UI issue.

**Comment by brotzmanmj** [comment]
Hi, just checking on status of this issue? We saw a screenshot of HP's dashboard today and the Date Received on their Report in prod is also not displaying correctly (Chicago reported the same issue).  Thanks.

**Comment by wyattks** [comment]
This works in Dev.  It is ready to be pushed to Stage for testing.

**Comment by HopkinsDC** [comment]
HealthPartners tested and confirms this works in stage. Approved in stage and is ready for deployment.
