### ISSUE TITLE
Add a second scan box for Collection ID on Specimen Link Screen

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#563]
On the Specimen Link screen where the Collection ID is entered, add a second scan box under the first and label as "Re-enter Collection ID".   Allow for the user to scan or manually enter into these two boxes and remove the manual entry boxes for the Collection ID. As there is no way to restrict users from manually entering in the scan box, we feel it would be easier to force them to fill in twice no matter if it is manually entered or scanned.
This is for both Clinical and Research.
See mock up for the research screen.
[Update Specimen Link Screen August 2022.pptx](https://github.com/episphere/connect/files/9311884/Update.Specimen.Link.Screen.August.2022.pptx)

**Comment by wyattks** [comment]
Confirmed this is working in Dev

**Comment by wyattks** [comment]
Ready for stage

**Comment by FrogGirl1123** [comment]
@wyattks @StephanieWeinstein  does the double entry also apply to the accession IDs?  The email thread from Aug. 12th was on accession IDs, but Stephanie mentioned this issue.

**Comment by wyattks** [comment]
Yes  we want them to double enter the Accession IDs.  But we won't be able to distinguish between a scan and manual entry.

**Comment by FrogGirl1123** [comment]
@geniosys  Hi Hendrick, for the double entry of the Accession IDs for blood and urine, we need an open text box for each entry.  Your code should confirm that the two entries match each other and if not then request they enter again.  We will not need to store the Accession ID twice, so we don't need a second Concept ID for the second entry.  Davin and I discussed this briefly and he thinks this is how you already have it coded.  Please confirm in the comments and then you can close this issue.
