### ISSUE TITLE
Collection ID Link - Truncate the Sequence Number

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#568]
On the Specimen Link page where the Collection ID is scanned twice to link to the participant's Accession IDs, the last 4 digits (the sequence number) should be removed when a Collection ID label is scanned into the fields. The format for these fields should be "CXA######". See the image below for reference. 

![image](https://user-images.githubusercontent.com/85250133/186732333-63c71a7d-441e-434a-b555-7e2ad9336698.png)

**Comment by wyattks** [comment]
Confirmed in Dev.  Ready to be moved to Stage
