### ISSUE TITLE
Urine Accession ID Not Showing on Specimen Link

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#569]
On the Specimen Link page where the Collection ID is scanned twice to link to the participant's Accession IDs, the urine Accession ID is displaying as "N/A" even if a urine Accession ID is entered. The ID should be displayed like the blood Accession ID. (if no Accession ID is entered, for either blood or urine, it is ok to display "N/A".) See image below for reference.

![image](https://user-images.githubusercontent.com/85250133/186736393-5b03aa95-9498-4879-bf58-b27cabe14425.png)

**Comment by HopkinsDC** [comment]
Confirmed this is working in dev. Ready for stage.

**Comment by wyattks** [comment]
Confirmed in Dev.  Ready for deployment in Stage
