### ISSUE TITLE
Deviations for Discard Flag

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#570]
There are 5 deviations that should have a discard flag:

472864016: Broken (discard, do not ship)
982885431: Not Found
684617815: Mislabeled – discard
956345366: Insufficient Volume
810960823: Discard (record in comments)

The Discard Flag was marked as YES for “Broken (discard, do not ship)”, “Mislabeled – discard”, “Insufficient Volume” and “Discard (record in comments)” in Scenario 3 of our clinical dashboard test (see attachment). “Not Found” is the only one that says NO.
 
SST 1
* Deviations -> 472864016
* Deviation Notes -> Empty
* Collected -> YES
* Deviations Present -> YES
* Discard Flag -> YES
* Object ID -> CXA000333 0001
 
HT 1
* Deviations -> 684617815
* Deviation Notes -> Empty
* Collected -> YES
* Deviations Present -> YES
* Discard Flag -> YES
* Object ID -> CXA000333 0003
 
EDTA 1
* Deviations -> 810960823
* Deviation Notes -> TEST - discard comment
* Collected -> YES
* Deviations Present -> YES
* Discard Flag -> YES
* Object ID -> CXA000333 0004
 
Urine
* Deviations -> 956345366
* Collected -> YES
* Deviations Present -> YES
* Discard Flag -> YES
* Object ID -> CXA000333 0006

The deviation on the ACD tube was "Not Found" which should be a discard deviation, but the txt file says there was not a discard flag: 
 
ACD 1
* Deviations -> 982885431
* Deviation Notes -> Empty
* Collected -> YES
* Deviations Present -> YES
* Discard Flag -> NO
* Object ID -> CXA000333 0005

Please confirm that Discard Flag is located to all the deviations listed.

[Scenario 3.txt](https://github.com/episphere/connect/files/9434459/Scenario.3.txt)

**Comment by Davinkjohnson** [comment]
Update so 982885431: Not Found will flag the discard flag to "Yes"

**Comment by HopkinsDC** [comment]
Confirmed this is working in Dev. Ready for Stage.
