### ISSUE TITLE
Gray out mouthwash bag if mouthwash sample not collected

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#572]
On the Collection data entry screen, keep the mouthwash bag data entry field grayed out (unable to enter data) until a Collection ID is scanned into the Mouthwash container field.   Even if the check box next to the bag is selected keep it from having data entered.

**Comment by wyattks** [comment]
The Bag data entry field is gray when the box is checked but it remained gray after I entered in an ID for the mouthwash.  Can we make it that as soon as the ID is entered into the mouthwash data entry field it allows for the Bag ID to be entered or do we have to save it first?

**Comment by StephanieWeinstein** [comment]
It still does not look like this works.  here is a screen shot showing that I have entered all the tubes including the mouthwash container, but the mouthwash bag is still grayed out.

![image](https://user-images.githubusercontent.com/64600223/188972502-8b4948a3-3ec6-4de0-bb35-b988ee274b38.png)

**Comment by wyattks** [comment]
This one is going to include a small process change.  They need to wait to select the mouthwash bag until after they have entered the mouthwash container ID.  If they do that the field opens up.  Otherwise they have to save and then enter the bag ID.

**Comment by wyattks** [comment]
@geniosys can you make it so when the Check All box at the top is selected the box for the Mouthwash Bag is not marked?

**Comment by geniosys** [comment]
Done

**Comment by wyattks** [comment]
The wrong bag is left unchecked. You have it so the Blood/Urine bag (0008) remains unchecked but we need the Mouthwash bag to remain unchecked (0009).

**Comment by geniosys** [comment]
Good catch. It's been updated now :)

**Comment by wyattks** [comment]
Great Thank you.  Confirmed it works in Dev.  Ready for Stage
![image](https://user-images.githubusercontent.com/64605220/189204312-d58909de-7895-4202-bdb2-c577dd9bd4d0.png)
