### ISSUE TITLE
If blood and Urine are marked as collected force the bag to be marked as well

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#574]
On both the clinical and research dashboards, if any blood or urine tubes are marked as collected and any Full Specimen IDs have been entered, the user should be forced to also mark the blood/urine biohazard bag (0008) as collected and enter in the Full Specimen ID for that bag. The check should happen when hitting either the "Save" or the "Go to Review" button. If the bag does not have its Full Specimen ID entered, include a pop up that says "Enter the Full Specimen ID for the Biohazard bag blood/urine (0008)"

For the research dashboard, if the mouthwash is marked as collected and Full Specimen ID has been entered, the user should be forced to mark the mouthwash biohazard bag (0009) as collected and enter in the Full Specimen ID for that bag.

**Comment by HopkinsDC** [comment]
This is working correctly in dev. Ready for stage.
