### ISSUE TITLE
Receive date not being captured in firestore

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#577]
During the clinical testing, when we created shipping scenarios with straggler tubes, the receipt date at BPTL is not being captured in firestore.  

Examples:

Ship Scenario B using CXA002654
The ACD and Urine tubes were collected after the remainder of the collection was sent to shipping and added to Box 3.  Once both tubes were "collected" they were added to the same shipping box.  In firestore, all of the samples have a receipt date of 9/12/2022 except the ACD tube (CXA002654 0005).  There is no receipt date listed for the ACD tube in firestore.

Ship Scenario C using CXA123423
The SST tubes were all placed in a box (Box 2) and shipped separately from the remainder of the collection (Box 1).   All the tubes shipped in Box 1 have a BPTL receipt date in firestore of 9/12/2022.  The SST tubes do not have a BPTL receipt date listed in firestore.

Ship Scenario F using CXA123422
The Heparin tubes were marked as missing when the collection was added to Box 5.  They were later added to Box 6 and shipped separately.  All tubes in Box 5 have a BPTL receipt date in firestore of 9/9/2022.  The Heparin tubes were receipted in the dashboard on 9/12/2022 but  do not have a BPTL receipt date listed in firestore.

**Comment by HopkinsDC** [comment]
Ship scenarios B, C, and F tested again on 10/5-10/6. Scenario data for second test in document below. 

[GH.Issue.577.docx](https://github.com/episphere/connect/files/9724353/GH.Issue.577.docx)

**Ready for check in firestore.**

**Comment by we-ai** [comment]
The data look correct.

**Comment by HopkinsDC** [comment]
Please check the ship date and BPTL received date in Firestore (production) for the SST tubes (0001, 0002, 0011, & 0012) in KPCO collection CXA003803. 

SSTs were separated from the other tubes but were found later and shipped as straggler tubes.

- Other tubes were shipped on 2/27/23 in Box 23 and received at BPTL on 2/28/23

**Comment by we-ai** [comment]
In collection CXA003803 tubes 0001, 0002, 0011 and 0012 have no receipt dates. Below are details:
- CXA003803 level dates: CID926457119="2023-02-28T00:00:00.000Z", CID915838974="2023-02-27T20:22:17.778Z", CID556788178="2023-02-28T18:48:47.713Z"
- In other tubes (eg 0004, 0014 etc): CID926457119="2023-02-28T00:00:00.000Z"

**Comment by Davinkjohnson** [comment]
Need Norma or Kari to accept the tubes so we can verify the data are corrected. (Domonique reached out via email earlier today.)

**Comment by HopkinsDC** [comment]
Please recheck the ship date, Box ID, and BPTL received date in Firestore (production) for the SST tubes (0001, 0002, 0011, & 0012) in KPCO collection CXA003803. Firestore should reflect:

1. Shipped **5/16/2**
2. Box ID **216**
3. FedEx Tracking #**511600000000**
4. BPTL received **5/19/23**

**Comment by we-ai** [comment]
Checked Firestore on 5-24-2023.
Collection CXA003803:
- Tubes 0001, 0002, 0011 and 0012 have received date (CID926457119) '2023-05-19T00:00:00.000Z'
- First level CID926457119 updated to  '2023-05-19T00:00:00.000Z'

KPCO Box216:
- CID656548982='2023-05-16T15:13:45.990Z'
- CID926457119='2023-05-19T00:00:00.000Z'
- CID959708259='511600000000'
