### ISSUE TITLE
Remove manual entry flags from Clinical Biospecimen DB

### ISSUE THREAD

**Issue by FrogGirl1123** [episphere/connect#578]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/GERLAN~1/AppData/Local/Temp/1/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/GERLAN~1/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Bld Acc   Manul | Needs to be deleted | d_148996099
-- | -- | --

</body>

</html>
and 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/GERLAN~1/AppData/Local/Temp/1/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/GERLAN~1/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Collection   ID Manually Entered | This flag should be removed | d_387108065
-- | -- | --

</body>

</html>

Should be removed from the Clinical Biospecimen DB.

**Comment by anthonypetersen** [comment]
387108065 is being tracked in research dashboard currently, is that fine? @FrogGirl1123

**Comment by FrogGirl1123** [comment]
The CIDs have been removed per additional teams chat.
