### ISSUE TITLE
Site customization in the Connect App

### ISSUE THREAD

**Issue by strennr** [episphere/connect#58]
Has there been any thought to allowing some customization (data specific) in the recruitment workflow within the Connect app?

For example, in the "How did you hear about this study?" question, one of the options is "MyChart".  Marshfield does not (currently) use Epic so is not applicable.  It would be nice if this option only showed up for healthcare providers using Epic.

**Comment by danielruss** [comment]
Waiting for questionnaire to handle input from user profile and earlier modules.
