### ISSUE TITLE
Push all NCI Clinical features to all Clinical dashboards in Dev

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#580]
During the test with KPNW today, it became apparent that all the clinical changes made in Dev were only activated (Correct term?) for the NCI site.  All clinical requirements and changes implemented for the NCI Clinical dashboard need to be pushed to all of the clinical sites in the dev environment.

For example, we asked for a modal to appear on the Accession ID link page if the user only enters in the Accession ID for blood and not urine. The modal points this out and asks the user if they wish to continue.  On the NCI instance, this modal appears and the user can move on to the specimen link page without entering in the urine Accession ID.  When KPNW was testing this, there was a hard stop. The modal did not appear and the dashboard was looking for the urine Accession ID in order for them to continue forward.  Please see the screen shot below.  Tony was on the call and said the code looks like the modal was only active for the NCI "site".

![image](https://user-images.githubusercontent.com/64605220/191095105-26c9e361-e387-488d-b64b-5eb586e8b7d6.png)

**Comment by HopkinsDC** [comment]
Another example is the cursor auto-tab on Accession ID page. After scanning the Blood Accession ID into the first field, the cursor moves to the first Urine Accession ID field instead of the second Blood Accession ID field.

**Comment by HopkinsDC** [comment]
KPCO confirms these issues are working in dev. Ready for stage.

![Screen Shot 2022-10-07 at 11 07 14 AM](https://user-images.githubusercontent.com/85250133/194586386-7997958c-1bb0-495e-bb5f-fa390be16767.png)

![Screen Shot 2022-10-07 at 11 07 28 AM](https://user-images.githubusercontent.com/85250133/194586428-e873bc8a-2cc1-4dc9-a555-770ce7b13e67.png)

**Comment by anthonypetersen** [comment]
@HopkinsDC can this be closed?

**Comment by HopkinsDC** [comment]
@anthonypetersen Yes, this can be closed.
