### ISSUE TITLE
Updates to Shipping and Box Manifests

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#582]
MANIFEST UPDATES

In the shipping dashboard please update the site contact information in the box and shipping manifests.

**KPGA** - Remove name and info for Brandi Robinson and replace with the following contact info:
-Name: Laura Gonzalez Paz
-Email: Laura.M.Gonzalezpaz@kp.org
-Phone: 561-860-6240

**Sanford** - Remove name and info for DeAnn Witte (**leave info for Kimberly (Kay) Spellmeyer**) and replace with the following contact info:
-Name: Madison (Maddi) Mayer
-Email: Madison.mayer@sanfordhealth.org
-Phone: 701-234-6718

**Comment by Davinkjohnson** [comment]
@geniosys is taking over the Biospecimens dashboard (which encompasses both Clinical and Research workflows). He'll be back next week so I'll assign it to him.

**Comment by HopkinsDC** [comment]
Please rename “SF Cancer Center LL” to “Imagenetics Building” for Sanford's Collection Location, Shipping Location, and the manifest.

**Comment by HopkinsDC** [comment]
This issue will only be for manifest updates.
