### ISSUE TITLE
Create Clinical Survey Flag Derivations

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#587]
The following variables need to be derived for the Clinical Surveys.

CID 253883960 (Blood/urine survey completion, SrvBlU_BaseComplete_v1r0)
CID 534669573 (Date/time Status of Start of blood/urine survey, SrvBlU_TmStart_v1r0)
CID 764863765 (Date/Time blood/urine survey completed, SrvBlU_TmComplete_v1r0)

**Comment by HopkinsDC** [comment]
Aileen tested the clinical survey flags, and they don't seem to be working as they should. Please see her comments below.
![Screen Shot 2022-10-19 at 8 07 56 AM](https://user-images.githubusercontent.com/85250133/196688707-5dcc5b12-2577-4147-a61f-f2b4735d57d9.png)
