### ISSUE TITLE
Add Report Tabs and Check-Out Report to Reports Page

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#588]
The Reports page will need two enhancements. 
1. The addition of tabs on the left-hand side that can be selected to display a different reports table
2. The addition of a Check-Out Report table that displays participants that have been checked into their appointment but have not been checked out.

- The only tabs that will be functional are "Shipping Report" and "Check-Out Report" for now. Placeholders for additional tabs can be added and grayed out.
- "Shipping Report" will be the default tab anytime someone navigates to the Reports page. The contents of the current Shipping Report table will remain unchanged.

- Check-Out Report table should display records with a status of **YES** for the Check-In Complete Flag.
**Variable**: BioChk_Complete_v1r0 (CID: 135591601)
**Value**: 1=Yes (CID: 353358909)
**Other Relevant CIDs:**
  •	Last Name – 996038075
  •	First Name – 399159511
  •	Check-In Date/Time – 840048338
- The "Go to Check-Out" buttons on each row must navigate directly to the participant's check-out page.
- Participants should be removed from the Check-Out Report table when there is a value for Check-Out Time Complete 
**Variable**: BioFin_CheckOutTime_v1r0 (CID: 343048998)
 
**Mock-Up 1** - Reports Tabs on left, Shipping Report tab selected (the default tab), Shipping Report table showing
![Reports Page Mock-Up_1](https://user-images.githubusercontent.com/85250133/195432441-8190d1a4-ecd1-49cc-bb3d-5b68943b98e0.png)

**Mock-Up 2** - Reports Tabs on left, Check-Out Report tab selected, Check-Out Report table showing 
![Screen Shot 2022-10-13 at 10 06 43 AM](https://user-images.githubusercontent.com/85250133/195619653-97448ea7-84a2-4910-844a-00739ce0555b.png)

**Comment by abhinavjonnada82** [comment]
Landing Page:
![Screenshot 2023-06-22 at 11 31 37 AM](https://github.com/episphere/biospecimen/assets/30497847/dca1b9ee-bf88-4896-9f67-46f08bffcd1a)

Check-Out Report Page:
![Screenshot 2023-06-22 at 11 33 15 AM](https://github.com/episphere/biospecimen/assets/30497847/7d67181d-43df-4e01-838a-5116f0bfc1dd)

**Comment by abhinavjonnada82** [comment]
Test Cases available here:
https://github.com/episphere/biospecimen/pull/545#issue-1769962914

**Comment by abhinavjonnada82** [comment]
Ready for DEV testing.

**Comment by wyattks** [comment]
Reports are in Dev.  The reports look good.  However if you navigate to a participant's Check-Out page from the report, it does not allow you to check the participant out.

**Comment by wyattks** [comment]
Report is working as expected: 
Participants that don't have specimen collection in the biospecimen table will have check-out button disabled. 
Participants that do have specimen collection in the biospecimen table can perform check-out action

Ready for Stage

**Comment by anthonypetersen** [comment]
is this fine to close now? @HopkinsDC @wyattks

**Comment by abhinavjonnada82** [comment]
Deployed to prod!
