### ISSUE TITLE
Add Accession ID information to Clinical Data Collection and Collection Summary screens - (Biospecimen)

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#589]
Please add the Accession IDs, Blood (BioClin_DBBloodID_v1r0, 646899796) and Urine (BioClin_DBUrineID_v1r0, 611091485) to the Collection Data Entry screen and Collection Summary screen of the clinical dashboard.

@Davinkjohnson Please assign accordingly.

**Comment by Davinkjohnson** [comment]
I've assigned this to Tony as he is currently working on the bio specimen dashboards

**Comment by anthonypetersen** [comment]
@Davinkjohnson @wyattks can this be closed?

**Comment by anthonypetersen** [comment]
* Add informational fields to the top of Collection and Finalization Screens
* Always show both Accession fields, using N/A if not entered
* @wyattks and @HopkinsDC to confirm if this is already implemented

**Comment by HopkinsDC** [comment]
Accession IDs are **not** present on the Collection Data Entry review page. 

Please add the blood and urine accession IDs on the Collection Data Entry page and the Collection Data Entry review page. The Accession IDs can be added to the top portion of the pages between the Connect ID and the Collection ID. 

![Screenshot 2023-04-26 at 11 26 17 AM](https://user-images.githubusercontent.com/85250133/234625247-581cab5e-c9c5-431b-a47c-570e8b8b6620.png)

**Comment by JoeArmani** [comment]
reviewed and approved the PR

**Comment by Gbarra9** [comment]
Merged PR to dev and ready to test

PR: 
- https://github.com/episphere/biospecimen/pull/634

**Comment by wyattks** [comment]
Tested in Dev- both locations now show the accession ID.
Ready for Stage.

**Comment by Gbarra9** [comment]
Confirming that this is now in stage and ready for stage testing.

**Comment by wyattks** [comment]
Erin tested and Accesson IDs showed up in both locations:


![Image](https://github.com/episphere/connect/assets/64605220/c0d603e8-b8f5-4f69-93ce-b769d4458635)



![Image](https://github.com/episphere/connect/assets/64605220/02c181eb-5cab-4575-8b11-e587ad0721e8)

Ready for production

**Comment by Gbarra9** [comment]
This is in prod. I am going to close the issue.
