### ISSUE TITLE
Keep Biohazard Bag (0008) Checked When Another Tube is Unchecked

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#590]
On the Collection Data Entry page, the biohazard bag (0008) should remain checked when the "Check All" box is checked, and any other tube is unchecked. This change should only apply to the clinical Collection Data Entry page.

The video below shows what is happening currently.

https://user-images.githubusercontent.com/85250133/196973308-793abbab-8d3c-463d-bcdb-c505ec75a04c.mov

**Comment by wyattks** [comment]
Tested and it is working in Dev.  Can be moved to Stage.

**Comment by Davinkjohnson** [comment]
Not necessary to test in stage

**Comment by HopkinsDC** [comment]
KPGA confirms this is working in stage. **Ready for deployment.**

**Comment by Davinkjohnson** [comment]
This is in Prod.
