### ISSUE TITLE
Make Collection Data Entry Page Fully Editable 

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#595]
Please make the collection data entry page fully editable up until the data is finalized (once "Confirm" is clicked in "Confirm Collection" modal).

Currently, the "Samples Collected" column and the "Reason Not Collected" column are not editable after the "Edit All" or individual "Edit" button is clicked. (See video below)

https://user-images.githubusercontent.com/85250133/201675866-5353cad5-2fef-4942-8d50-1e8f7019aa4b.mov

**Comment by anthonypetersen** [comment]
* Original rules were put in place for QC purposes but they are causing more problems than preventing

**Comment by Davinkjohnson** [comment]
Only want this editable up until collection is confirmed. (Do not allow it to be edited once it's in shipping.)

**Comment by Davinkjohnson** [comment]
Gene and Joe continuing to work on this

**Comment by wyattks** [comment]
Function is working.  I was able to edit collection (CXA441336) and add/remove.  Once I finalized and sent the samples to shipping I was unable to change anything for the samples already marked as collected.  
This is ready for Stage.

**Comment by brotzmanmj** [comment]
@wyattks  Just to make sure the later part of the workflow still works as expected, can  you also check that if the sample is finalized it appears on the shipping dashboard as available for shipping and if not finalized it does not appear? There's no reason that should have broken but just want to be sure before it gets deployed. Thanks.

**Comment by wyattks** [comment]
Collection (CXA112233) appears in shipping as expected after Edit All was used on it.  Tube I removed from shipping does not appear as expected.

**Comment by brotzmanmj** [comment]
Thank you for checking!
