### ISSUE TITLE
Add Free-Text Box to Collection Data Entry Page for Phlebotomist Initials (Research Only)

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#599]
Please add a free-text box section to the Collection Data Entry page, under the participant information and above the collection data on the research dashboard (see mock-up below). This free-text box needs to be required a required field to continue to the review page. 

![Picture1](https://user-images.githubusercontent.com/85250133/206537338-f0a06f0d-dd02-48d6-bc54-d9468b9ce95f.png)

If the "Save and Review" button is clicked and the phlebotomist initials have not been entered, the warning phrase "This field is required. Please enter the phlebotomist’s initials." should show up under the field in red. (See mock-up below).

![Picture2](https://user-images.githubusercontent.com/85250133/206537947-3d8b019b-e831-46d8-813d-fcc920b25cdf.png)

A new variable must be created and added to the data dictionary (Nicole).

**Comment by HopkinsDC** [comment]
@FrogGirl1123 I added a request for this new variable to the Data Dictionary Change Log: https://nih.app.box.com/file/1033495332436

**Comment by anthonypetersen** [comment]
* CID has been created (719427591)
* Will be implemented as a required field on the Collection Data Entry page near the top of the page
* All capitalized letters
* Free text, let sites determine what they enter
* Allow letters and numbers

**Comment by anthonypetersen** [comment]
pushed to dev

**Comment by HopkinsDC** [comment]
@anthonypetersen Initial box is showing correctly on the Collection Data Entry page in dev. Please display the field entry on the collection data review page as well.

![Picture1](https://user-images.githubusercontent.com/85250133/221648751-0849b689-46f1-4063-b0d5-76dfabc07063.png)

**Comment by anthonypetersen** [comment]
@HopkinsDC updates pushed to dev

**Comment by HopkinsDC** [comment]
Changes made successfully in dev. Ready for stage.

**Comment by HopkinsDC** [comment]
HP confirms change in stage. Ready for deployment.
