### ISSUE TITLE
recruit dashboard

### ISSUE THREAD

**Issue by jonasalmeida** [episphere/connect#6]
Testing API for support of user interaction at https://github.com/episphere/dashboard (let me know if you want to be added). Example of test UI at https://episphere.github.io/dashboard/recruitConnect_1

**Comment by geetajoshi2019** [comment]
Team - any update on Dashboard? 
I am looking at https://episphere.github.io/dashboard/recruitConnect_1/ and not seeing much activity. 
Am I looking in wrong place? 

Do you need any requirements defined for this? Please let me know.

**Comment by danielruss** [comment]
9) participant dashboard needs to be designed. Who is doing this and when?
