### ISSUE TITLE
Consent page: add asterisk to the read/consent statement

### ISSUE THREAD

**Issue by miagaudet** [episphere/connect#60]
Add an asterisk at the end of this statement: "I have read the explanation about this study and have been given the opportunity to discuss it and ask questions. I consent to participate in this study.*" While it is obvious (to nearly everyone), the addition of the asterisk will be consistent with the other mandatory items on the page.

**Comment by danielruss** [comment]
The consent section is simply a place holder.  There needs to be a connect approved module.  When the consent team defines that process, we'll implement it.
