### ISSUE TITLE
Add New Collection & Shipping Locations for UChicago, Marshfield, and Sanford

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#600]
Please add new Collection Locations (BioSpm_Location_v1r0 - CID: 951355211) **AND** Shipping Locations (BioShip_LocalID_v1r0 - CID: 560975149) for UChicago (3), Marshfield (5), and Sanford (1).

The UChicago location names are:
1. Ingalls Harvey
2. River East
3. South Loop

The Marshfield location names are:
1. Rice Lake 
2. Wisconsin Rapids 
3. Colby Abbotsford 
4. Minocqua 
5. Merrill 

The Sanford location name is:
1. Fargo South University

We need them added in the following places:

CID creation and Data Dictionary labels update (Nicole's team)
Biospecimen Dashboard Specimen Link Drop Down (Davin to assign)
Biospecimen Dashboard Shipping Drop Down (Davin to assign)
Biospecimen BPTL CSV (Abhinav)
BSI (Kathleen) - This needs to be done when the CSV is complete and pushed to production
Metrics format Code (Jing)

**Comment by HopkinsDC** [comment]
@FrogGirl1123 @mnataraj92 This request has been added to the data dictionary change log: https://nih.app.box.com/file/1033495332436

**Comment by HopkinsDC** [comment]
@Davinkjohnson @abhinavjonnada82 

Sanford and UChicago report that they are unable to create a new box under the new shipping added to the shipping dashboard. They also report that this is not happing for their pre-existing shipping location, only the new ones. 

Please refer to the video from UChicago for reference.

https://user-images.githubusercontent.com/85250133/212400223-060ff075-101c-4250-be19-6c7bb2f0ca99.mov

**Comment by wyattks** [comment]
All new sites listed above have been added to BSI

**Comment by HopkinsDC** [comment]
See the screen recording below for inspection console errors while attempting to create a new box (UChicago).

https://user-images.githubusercontent.com/85250133/212982679-5573e685-9568-4b9c-9e12-f812da513591.mov

**Comment by HopkinsDC** [comment]
Sanford's test in dev looked good in the CSV file. Still waiting for Marshfield to finish.

**Comment by HopkinsDC** [comment]
Marshfield has completed their test, which looks good in the CSV file. This issue is ready for stage.

**Comment by HopkinsDC** [comment]
Chicago completed their stage testing for their new locations, which looks correct in the CSV file. **This issue is ready for deployment**.

**Comment by Davinkjohnson** [comment]
This is in Prod
