### ISSUE TITLE
Remove ACD Tube from Clinical Biospecimen Dashboard

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#602]
Clinical collections will no longer include ACD tubes. Please remove the ACD tube from the data entry page in the clinical biospecimen dashboard. The ACD tube is to be removed from the clinical biospecimen dashboard **ONLY**. See the annotated screenshot below for reference.

-Davin to assign this issue

![Screen Shot 2022-09-13 at 4 20 59 PM](https://user-images.githubusercontent.com/85250133/208975527-d2c8d441-2160-4073-b4d9-277892022c87.png)

**Comment by HopkinsDC** [comment]
Placing this issue on hold until a final internal decision is made on the ACD tube presence on the clinical Collection Data Entry page for Hybrid Collections.

**Comment by Davinkjohnson** [comment]
Closing this for now, given changing needs.
