### ISSUE TITLE
Baseline Collection Flag - Data Discrepancy for UChicago Participant

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#603]
UChicago submitted a research collection (CXA002464) for the participant with Connect ID #5312274299 after accidentally using the clinical dashboard first.

All of the individual specimens have a value of "Yes" for being collected (**SSTube1_BioCol_TubeColl**, **SSTube2_BioCol_TubeCollected**, **EDTATube1_BioCol_TubeCollected**, **ACDTube1_BioCol_TubeCollected**, **HepTube1_BioCol_TubeCollected**, **UrineTube1_BioCol_TubeCollected**, and **MWTube1_BioCol_TubeCollected**), but the flags for the baseline blood, urine, and mouthwash collected (**BioFin_BaseBloodCol_v1r0**, **BioFin_BaseUrineCol_v1r0**, and **BioFin_BaseMouthCol_v1r0**) all have a value of "No".

The baseline flags should have a value of "Yes" since all specimens were collected.

**Comment by anthonypetersen** [comment]
@HopkinsDC I'm looking in Firestore and see all three of those CIDs have a value of "YES"

**Comment by HopkinsDC** [comment]
I've reviewed the participant table from 1/23 for **CXA002464,** and the three CIDs (BioFin_BaseBloodCol_v1r0, BioFin_BaseUrineCol_v1r0, and BioFin_BaseMouthCol_v1r0) now has a value of "YES". 

The participant is eligible for their incentive.

This issue is resolved.
