### ISSUE TITLE
Baseline Completion Flag not updating properly

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/connect#605]
We have seen 2 instances in the last week (and a total of 4 in the last 1-2months) where participants complete all 4 baseline modules but do not have their completion flag set correctly. 

Need to add Connect IDs (only connect IDs) for the most recent 2 cases for investigation.

**Comment by mnataraj92** [comment]
These are the Connect IDs for the 2 most recent cases from UC: 
5587247277
7092571820

**Comment by anthonypetersen** [comment]
Will need to keep an eye on this, upcoming production code push will hopefully resolve this by moving this derivation to the backend instead of being calculated on PWA side.

**Comment by Davinkjohnson** [comment]
Fixed with 2023 release
