### ISSUE TITLE
Multiple Clinical Survey email Issue

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/connect#608]
When completing a collection at the RRL the possibility exists that participants will receive multiple emails at once, reminding them to complete their sample survey.

**Comment by Davinkjohnson** [comment]
Test Scenario:
- put in data once (partial completion)
- put in remaining data for same Accession ID

**Comment by HopkinsDC** [comment]
This issue was tested in dev, and DeAnna confirms that only one email was sent. **Ready for stage**.

**Comment by HopkinsDC** [comment]
KPNW completed the test, and I confirm that only one survey email was sent (via the stage study manager dashboard). This issue is ready for deployment.

**Comment by Davinkjohnson** [comment]
This is in PROD
