### ISSUE TITLE
Consistency check for name: consent vs. user profile

### ISSUE THREAD

**Issue by miagaudet** [episphere/connect#61]
I set up a user profile using a name that differed from the name used on the consent and name from the sign in page, yet I was still allowed to move on to the questionnaire page.

**Comment by danielruss** [comment]
That is definitely not the expected behavior.

**Comment by sarah-hague** [comment]
Similar but slightly different issue that might be taken care of, but I was able to type numerics into the first and last name fields of the user profile (not matching the name on consent).

**Comment by miagaudet** [comment]
@bhaumik55231, sorry for the delay. we reached out for advice. we have come down to the following: we would like to carry the first and last name from the consent to pre-populate the user profile and have a box to ask them to verify that the name is correct. So that they actually LOOK at the spelling of their name, I would have them check a box indicating it’s correct. Is that doable?

**Comment by bhaumik55231** [comment]
@sarah-hague We have made the modifications now participant would not be able to type in numeric values and special characters in the user profile.

@miagaudet Consistency check for the name is implemented, please try it out and let me know your thoughts :)
