### ISSUE TITLE
Sign-in date/time stamp issue

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/connect#610]
One of the things we discovered as we worked on metrics with Jing last week was that the date/time stamp for Sign-In (CID 335767902) defined as Time Sign-In Occurred isn’t making sense the way we thought it would.
 
The time sign-in occurred is slightly later than the time consent was signed, in a large majority of instances. Could someone look into when our system is capturing time sign-in occurred? Is it articifially delayed for some reason?

**Comment by Davinkjohnson** [comment]
The consented date to look at is: 454445267
A Previous consented date had been used but should be ignored as it is deprecated: 982402227

The verification Time variable is: 914594314

Notes on Workflow:
- User creates account for first time (signs in) then completes consent.
- Once account is created/consented the site will verify the participant
- The issue causing concern is that the verification status time is (in 8 cases) being set before the consented time, which shouldn’t be possible

**Comment by brotzmanmj** [comment]
And to add, the User Profile time variable is: 430551721. 

The order these should logically occur in time is:
first sign-in > consent > user profile > verification

**Comment by Davinkjohnson** [comment]
Ready for STAGE as of 2/8

**Comment by Davinkjohnson** [comment]
This is in PROD
