### ISSUE TITLE
Hybrid Collections - distinguish between Research and Clinical dashboards

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#611]
For discussion

**Comment by Davinkjohnson** [comment]
Just After Participant Search or Specimen Search add logic to distinguish Colors (and add a banner) for this.

**Comment by anthonypetersen** [comment]
@wyattks @StephanieWeinstein any initial thoughts on what general color we'd like use to represent Clinical and Research dashboards?

**Comment by StephanieWeinstein** [comment]
I don't have strong feelings. What if you leave the research as is, and for the clinical make a  blue background, like one of the colors in the Connect logo?  Would that work?  Open to other suggestions!

**Comment by anthonypetersen** [comment]
We could do that! I'll try to keep it in the same color family as the Connect logo, but the only thing I will suggest is that it's a very dull version of the color so that it isn't contrasting too much with the form elements.

**Comment by Davinkjohnson** [comment]
If we're going to start assessing 508 compliance inside the dashboard (not just the login page) we're going to have to reserve a lot more time for this. To my knowledge, we haven't done an assessment of this dashboard.

**Comment by Davinkjohnson** [comment]
Warren hoping to begin work on this next week

**Comment by wyattks** [comment]
Changes look good.  Please push to Stage.

**Comment by HopkinsDC** [comment]
This issue is working in stage. Ready for prod.

**Comment by HopkinsDC** [comment]
Henry Ford confirms the color schemes for clinical and research are working correctly in stage.
