### ISSUE TITLE
Correct backlog of sign-in date/time

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#612]
Fix existing sign-in date/time. We are working during the week of 2/3/23 to fix the system to capture accurate date/time of first sign-in but once implemented, we will need to correct those that were in the prod data before the fix was pushed.

**Comment by brotzmanmj** [comment]
Hi, The prod correction to capture accurate date/time of first sign in went to prod on 2/16. We are circling back to correct those that were in prod data before the fix was pushed. There are some with dates that are later than expected and some with no sign in date.

**Comment by we-ai** [comment]
Some of above missing dates occurred 1 year ago or earlier (eg: "4460c192-d082-4e86-a193-8e0b367dd8bc", "c1d5dc66-21ed-4b59-bc6e-5bff0ccfc148") @mnataraj92

**Comment by mnataraj92** [comment]
@brotzmanmj, @we-ai has implemented a fix for the sign-in time. I will confirm in dev tomorrow that the sign-in time occurs before the consent time. 

However, for the errors where recruitment type time (RcrtSI_TypeTime_v1r0) is happening after sign-in time, if this is still occurring, this may be an issue with the recruitment type time. I will check the data for this tomorrow as well when BQ updates to make sure that the recruitment type time is happening before sign in time.

**Comment by we-ai** [comment]
There should be an issue causing incorrect recruitment type time.

**Comment by we-ai** [comment]
I agree. If a timestamp is not captured and saved, there's no way we can retrieve it later.

**Comment by we-ai** [comment]
Yes, the issues are clear. I suggest we use two terms to refer to these two separate issues/tasks:
- Code update(s) in PWA.  This task target *future* participants data, to make sure the missing/incorrect sign-in timestamp won't occur in the future.  The updated code is in dev now. 
- Sign-in timestamp recovery. This task targets *existing* participants data, to put back a correct sign-in timestamp in each participant record, whether the CID 335767902 is missing or incorrect. The code direct talks to Firebase/Firestore and does data updates. Yesterday (4-11-2023) I recovered sign-in timestamps for dev data, and I'm working on recovering timestamps in stage data.

Hope above info is clear enough.

**Comment by brotzmanmj** [comment]
Perfect, thank you!

**Comment by mnataraj92** [comment]
This has been implemented in prod and the majority of the sign-in times are now prior to the consent times!

There are 6 Connect IDs that for some reason still have a sign-in time after consent time:
1426516915
3156900613
4539494079
6329432822
6661084316
8260740208

It could be that these participants had account changes/merges before?

@brotzmanmj
