### ISSUE TITLE
KPHI Date incorrect in dashboard shipping report 

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#616]
KPHI discovered the incorrect date is showed up for a package they shipped on 2/14/2023.
The ship date in the dashboard report shows as 2/15/2023.  The ship date on the received csv file show 2/14/2023.  The package was shipped on 2/14/202 between 2 and 3 pm HST.

Warren believes the error is occurring because of an incorrect time conversion in the app.

Please correct so the correct ship date is appearing in the report for KPHI.

[KPHI incorrect date on shipping report.docx](https://github.com/episphere/connect/files/10808094/KPHI.incorrect.date.on.shipping.report.docx)

**Comment by Davinkjohnson** [comment]
largest concern date/time is Needle to Freezer time (Collection date/time based on API data for clinical and check-in time for research, processed time is in BSI from CSV. CSV time is UTC)
Kathleen did Excel comparison for this previously. 

Look at Fedex dates for shipped pick up times

Example:
KPHI ships box 8pm local on 2/28 
Date on shipment report should be 2/28

**Comment by wyattks** [comment]
I believe this has been fixed.  They have not commented again on this.  reopen if issue happens again.
