### ISSUE TITLE
Update Tokenized MyConnect login to new login workflow

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/connect#617]
Currently, the tokenized login for participants joining MyConnect leads to the generic (essentially the old) version of the MyConnect Sign-in/Sign-up page. The tokenized link should use the updated login workflow. 

example tokenized link from prod (do NOT use to sign up) https://myconnect.cancer.gov/?token=c3861a7d-49c7-4bda-8915-a2336f396cd5

Resulting page:
<img width="891" alt="image" src="https://user-images.githubusercontent.com/87718852/221979785-04c2edbe-1b6b-4188-926d-c1bb0d7d1133.png">

Desired login page:
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/87718852/221979893-afc281c7-aa44-409b-84b3-ddb817e0f2cc.png">

**Comment by we-ai** [comment]
Tokenized login was not requested when implementing the new sign-in/sign-up UIs. More details (validate token, show sign-in or sign-up UI, etc) are needed to implement this request.

**Comment by Davinkjohnson** [comment]
Per Deanna (3/20) this is good in STAGE
