### ISSUE TITLE
Shipping dashboard slow loading

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#619]
HP reports that shipping dashboard is slow loading. Warren said he will explore what is causing this.

**Comment by Davinkjohnson** [comment]
Related issue: https://github.com/episphere/biospecimen/issues/548

**Comment by JoeArmani** [comment]
Related: https://github.com/episphere/connect/issues/650

**Comment by JoeArmani** [comment]
This is live in dev and ready for testing.

**Comment by JoeArmani** [comment]
This is tested in dev and ready for stage.

**Comment by JoeArmani** [comment]
Approved in stage, ready for prod.

**Comment by JoeArmani** [comment]
Closing - this is in production.
