### ISSUE TITLE
User profile: error message for birth year 

### ISSUE THREAD

**Issue by miagaudet** [episphere/connect#62]
Suggest replacing current error message for birth year with information about age eligibility.

**Comment by danielruss** [comment]
I believe you are referring to the user profile.  This will be handled in the questionnaire tool, so the error message will be different.  Not closing, but putting this on hold for when the questionnaire comes on line.

**Comment by bhaumik55231** [comment]
Now user profile is part of connect PWA and is finalized. So closing this issue.
