### ISSUE TITLE
Add Streck Tube to Research and Clinical Dashboards

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#620]
A new liquid biopsy tube needs to be added to the dashboards.  
HP and HFH will be collecting Streck tubes as part of their clinical collections as well. 

1. Add Streck tube to: Research and Clinical Dashboards - Collection Data Entry (sequence number 0060)
2. Add Streck tube specific deviation(s) (Same deviations as ACD tube plus hemolysis) to collection data entry page: Research and Clinical Dashboards - Collection Data Entry 
3. Add Streck tube to Review list: Research and Clinical Dashboards - Review Collection Data Entry
4. Add Streck tube to Shipping Dashboard Modal list for Specimen Bag (in 0008 bag): Shipping Dashboard – Packaging Screen
5. Add Streck tube to Manifests: Shipping Dashboard- Box & Shipping Manifest
6. Add Streck tube to In Transit csv file: BPTL Dashboard
7. Add Streck tube to Receipt CSV file: BPTL Dashboard
8. Allow for Streck Tube to be an Orphan Tube
9. in terms of tube ordering, tube will be added after the ACD tube

**Comment by wyattks** [comment]
Streck Tube Deviations: 
•	BioCol_Dev_v1r0_Broken (472864016)
•	BioCol_Dev_v1r0_Hemo (242307474)
•	BioCol_Dev_v1r0_TempL (550088682)
•	BioCol_Dev_v1r0_TempH (690540566)
•	BioCol_Dev_v1r0_Leak (757246707)
•	BioCol_Dev_v1r0_LowVol (728366619)
•	BioCol_Dev_v1r0_Other (453343022)
•	BioCol_Dev_v1r0_TubeSz (777486216)
•	BioCol_Dev_v1r0_Discard (810960823)
•	BioCol_Dev_v1r0_MislabelD (684617815)
•	BioCol_Dev_v1r0_MislabelR (283900611)
•	BioCol_Dev_v1r0_NotFound (982885431)
•	BioCol_Dev_v1r0_OutContam (313097539)

**Comment by wyattks** [comment]
BPTL CSV file information added to the Tube Mapping file: https://nih.app.box.com/file/1306346523951

**Comment by Davinkjohnson** [comment]
This tube should also interact with the "blood collected" and "incentive eligible" derived variables.

**Comment by wyattks** [comment]
attached is a picture of the Streck tube to use on the dashboard.
[Streck Tube Labeled.docx](https://github.com/episphere/connect/files/12918438/Streck.Tube.Labeled.docx)

**Comment by bransteitterbr** [comment]
PR created https://github.com/episphere/biospecimen/pull/600

**Comment by brotzmanmj** [comment]
@bransteitterbr  has the PR been approved and this moved to dev for our testing to begin? Maybe this isn't ready for us yet?

**Comment by Davinkjohnson** [comment]
This code was reviewed and approved, all the open changes have been merged to Dev. So, everything should be working as expected. 

@HopkinsDC was this in a private/incognito window? (if you're seeing the Streck tube I'd assume you have the latest code but I'm not sure if Brian had to do 2 merges to get the image added.) 

Brian is out sick today, but should be back tomorrow to troubleshoot further, if needed.

**Comment by HopkinsDC** [comment]
@Davinkjohnson Yes, the screenshot is from the dashboard on an incognito window. The image of the streak tube was showing earlier this week.

**Comment by Davinkjohnson** [comment]
This was tested in stage. Ready for prod.

**Comment by bransteitterbr** [comment]
Pushed to Prod
