### ISSUE TITLE
Box data not finalized after signing the shipment

### ISSUE THREAD

**Issue by we-ai** [episphere/connect#625]
Box data were not finalized after shipper signed the shipment in dashboard, and information related to the shipment (shipment time, shipment courier, shipper' email, tracking number, etc) were not added to the box data in Firestore. This issue occurred 2 times in the past 2 weeks.

**Comment by Davinkjohnson** [comment]
this is in PROD

**Comment by Davinkjohnson** [comment]
Continue monitoring

**Comment by Davinkjohnson** [comment]
This is in Prod

**Comment by StephanieWeinstein** [comment]
sadly this is still a problem.  I happened to two packages that Health Partners finalized yesterday and which were received today at FNL. The original FedEx numbers were   6352 1365 7697 and 6352 1362 0093 (Boxes 585 and 589).  New fake numbers were assigned so that they could be receipted

Box585: 123213657890
Box589: 567213620890

**Comment by StephanieWeinstein** [comment]
@JoeArmani - I'm tagging you on this!

**Comment by JoeArmani** [comment]
Notes - initial discovery:

There are a few points where this could be intermittently failing.
(1) BSD Error handling: Error handling is incomplete, so there would be no way for the user to see when something goes wrong. If errors aren't caught, the user’s navigation pattern continues on the successful path even when the database operation fails.
(2) BSD Event Listeners: It’s possible that duplicate event listeners are being created in the BSD shipping panel based on the navigation pattern in the app. This could lead to unexpected behavior and empty data being sent.
(3) ConnectFaas shipBatchBoxes() order of operations: If a get() operation (or an update() operation) returns an unexpected snapshot/value, the function will trigger a ‘false’ response (failure), but this wouldn’t be caught on the BSD site.

Actions:
•Add error handling and error messaging to the BSD shipping page to break the 'success' navigation cycle and notify a user when a db write (ship operation) fails.
•Rearrange event listener setup to ensure duplicate event listeners aren’t created. Remove the existing listeners before creating the new ones.
•Update the server side to handle this as a Firestore ‘transaction’. This is an atomic operation that disallows access to the specific docs requested during the fetch and writing processes (the specific box docs in this case) to rule out concurrent updating (highly unlikely that this was the problem _unless_ event listeners were duplicated and firing multiple events). It also includes automatic retries in the event of failure prior to returning the failure notification to the user.

These steps should tighten up the 'ship' process throughout the event chain. It will provide error messaging to the end user and hopefully eliminate the next-day 'surprises' related to shipping on both the site and BPTL sides.

**Comment by JoeArmani** [comment]
Update: PRs are under review for both client-side and server-side handling (BSD & ConnectFaaS) of shipment finalization.

Once merged:
•Users will receive error messaging on a failure. The dashboard will no longer refresh or show success messaging until the operation succeeds. This error messaging will be helpful in tracking down future issues.
•The new server-side implementation locks access to documents during the read/write process (~400-2000ms) and uses automatic retries, so fewer failures are expected in case of a short-term error on the firebase side.
•Warren was helpful in relaying the information that the ship() function wasn't being called in certain circumstances (this was hard to reproduce), so the code structure of the shipment finalization section of the shipping dashboard has also been updated for robustness.

**Comment by Davinkjohnson** [comment]
This will be tested along with the Phase 2 changes.

**Comment by JoeArmani** [comment]
This is in production - closing.
