### ISSUE TITLE
Resolve false errors from Get Specimen / User Collections

### ISSUE THREAD

**Issue by anthonypetersen** [episphere/connect#628]
API call for getting a participant's biospecimen collections returns a 404 code if no collections have been submitted yet. Change this to a 200 code with an empty data return object, currently errors are being thrown on the console unnecessarily and will eventually be picked up by Datadog.

Also if we can clean up how this API is accessed from two different sources, that would be cool too.

**Comment by Davinkjohnson** [comment]
per Tony this can be closed
