### ISSUE TITLE
Collection Data Entry Review Page Text Overlap

### ISSUE THREAD

**Issue by Gbarra9** [episphere/connect#629]
The box manifest in the shipping dashboard looks good, but the collection data entry review page seems to have a formatting issue in the deviations column (see image below)

![Screenshot 2023-03-31 at 8 39 12 AM](https://user-images.githubusercontent.com/85250133/229123559-1a5f65e0-6b29-4321-abf4-1c65ad2be898.png)

_Originally posted by @HopkinsDC in https://github.com/episphere/connect/issues/609#issuecomment-1491873464_

**Comment by HopkinsDC** [comment]
Bug successfully fixed in dev. Ready for stage.

**Comment by Gbarra9** [comment]
Image from Erin's feedback in stage testing:

<img width="395" alt="Screenshot 2023-04-28 at 10 43 29 AM" src="https://user-images.githubusercontent.com/33293205/235182815-72e84f8c-6b2b-4845-b134-95ed6c75851b.png">

**Comment by Davinkjohnson** [comment]
Approved in Stage, ready for PROD

**Comment by HopkinsDC** [comment]
Pushed to prod (5/25)
