### ISSUE TITLE
PIN issue

### ISSUE THREAD

**Issue by Eusuf2000** [episphere/connect#63]
The current PIN format is SITE-######, for example HFHS-674426. It is simple. Participant can mistype digits and still end up having a valid PIN. The PIN should be a little bit more complex, random, and alpha-numeric. For example, F1HD16AE. It'll be difficult for anyone to guess a PIN like this. Even if the participant mistypes, it is highly unlikely to match another existing PIN.

Token is alpha-numeric and over 30 characters long. PIN could be a token which is 8 characters long containing numbers and upper case letters only.

**Comment by bhaumik55231** [comment]
Modified the API, now it returns 6 characters alpha-numeric PIN. Eg: 8SBH6S

**Comment by danielruss** [comment]
I have run the NCI workflow and generated pins.  Looks good.
