### ISSUE TITLE
Add Daily Report to Research Reports Page

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#631]
*Davin to assign this issue

Add a Daily Report table that displays all records with a status of _YES_ for the Check-In Complete Flag at any of the site locations (135591601=YES)

The table columns should include:
1. Collection Location (951355211)
2. Connect ID (Connect_ID)
3. Last Name (996038075)
4. First Name (399159511)
5. Check-In (840048338)
6. Collection ID (820476880)
7. Collection Finalized (556788178)
8. Check-Out (343048998)

- Column data should be updated in real-time
- Records are to be removed from the Daily Report table 2 days following the calendar day of check-in (or 48 hours from the check-in timestamp, whichever is easiest to implement)
- Add filter function for Collection Location with "Apply" and "Clear" buttons. Filter should include all collection locations for the site.
- "Shipping Report" will remain the default tab anytime someone navigates to the Reports page. The contents of the current Shipping Report table will remain unchanged.

**Mock-Up**
(1) Daily Report selected tab on the left (below Shipping Report and Check-Out Report) with table displayed and missing data for some participants
![Mock-Up 1_Daily Report](https://user-images.githubusercontent.com/85250133/230129806-edf40001-4f24-4f81-959f-33a0bd1ee7b1.jpg)

(2) Daily Report table displayed with all data entered for participants
![Mock-Up 2_Daily Report](https://user-images.githubusercontent.com/85250133/230129992-71035511-88d3-4cfb-96b3-d29fddcdf4c5.jpg)

**Comment by Davinkjohnson** [comment]
@wyattks to start testing this today (verify end date is correct prior to EOW)

**Comment by wyattks** [comment]
Connect ID 9763644172
Collection ID CXA225588
Connect ID not showing up on report right after check-In and collection. 
Will wait for a few and try the report again to see if it shows up before checking out the participant.

**Comment by abhinavjonnada82** [comment]
@wyattks can you checkn dev once I released a fix.
<img width="1692" alt="Screenshot 2023-08-23 at 9 25 22 AM" src="https://github.com/episphere/connect/assets/30497847/8a33d1b4-0696-41fd-9070-cb2058dbbc2e">

**Comment by wyattks** [comment]
Yes I can check.  Just let me know when.

**Comment by Davinkjohnson** [comment]
Tested in Dev, Ready for Stage. 

MF and HF to test in Stage.

**Comment by HopkinsDC** [comment]
Marshfield reports buffering on attempting to load the daily reports after linking a Collection ID to a participant in stage.

![Screenshot 2023-09-28 at 2 10 23 PM](https://github.com/episphere/connect/assets/85250133/331cfd94-440d-45c3-83bf-156683553f23)
