### ISSUE TITLE
Update Response Code of Get User Profile API Call

### ISSUE THREAD

**Issue by anthonypetersen** [episphere/connect#638]
API call for getting a participant record returns a 500 code if participant is signing up in PWA. Change this to a 200 code with an empty data return object, currently errors are being thrown on the console unnecessarily and will eventually be picked up by Datadog.

Also if we can clean up how this API is accessed from two different sources, that would be cool too.

**Comment by Davinkjohnson** [comment]
Per Tony this can be closed
