### ISSUE TITLE
Add a question for participants about biospecimen

### ISSUE THREAD

**Issue by Eusuf2000** [episphere/connect#64]
Can you please add a question for Henry Ford (or any/all other sites) participants and ask them where do they want to go to give bio-specimens? We'd like you to provide them two choices - Clinic Lab or Research Lab. Based on the selection, we'd like you to display additional information about these choices. We'd like to get the answer to this question through API call.

Thanks.

**Comment by brotzmanmj** [comment]
Hi Eusuf, This needs greater discussion in the context of the biospecimen workflow. I suggest for this issue to be put on hold until we begin to tackle that so we have a better sense of where and when to ask this. Thanks.

**Comment by Eusuf2000** [comment]
OK, sure.

**Comment by brotzmanmj** [comment]
The plan for the initial phase of the study (first year of enrollment) is to start at each IHCS with either clinical collections or research collections but not both at the same IHCS. That would eliminate the need for a workflow that determines which route paritcipants will take at each site. If funds become available to expand beyond this, we will need to plan how to amend the workflow to this issue.

**Comment by brotzmanmj** [comment]
This will be a topic of discussion on the monthly contract calls with each site next week. Thanks.

**Comment by Eusuf2000** [comment]
Thanks.

**Comment by Davinkjohnson** [comment]
Conversation of this is currently ongoing, include this when we enable collections at both research and clinical sites. (timing TBD)

**Comment by brotzmanmj** [comment]
We told the sites we won't begin discussing this at least until early 2023, after the clinical biospecimens and the home mouthwash collections are launched.

**Comment by Davinkjohnson** [comment]
@brotzmanmj We manage this through the scheduling tools the sites use, correct? (this is the case for Hybrid and Clinical sites, it seems.)

**Comment by brotzmanmj** [comment]
Yes, this is a function of the sites scheduling systems, not our system
