### ISSUE TITLE
Implement initial Data Destruction SOP

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/connect#640]
Initial MVP scope for data destruction from DevOps

1. Create a service which runs daily to see if any participants are flagged with Data Destruction (831041022) = yes
> If destroy data categorical (883668444) = requested and signed (704529432) OR date data destroy requested >60 old (269050420) then continue with destroy data

2. Remove all data from Firestore except for identified "stub record" data. (section 3.1.2)

Because we aren't worried about published data, I think that's all we need to get started... 

SOP for the requirements lives here: https://nih.box.com/s/xys7j67pbliwaw4tpn4g7drn5hnmkmj7

**Comment by sonyekere** [comment]
Hi @brotzmanmj . For awareness, I think Jessica may be pending the add'l variables in order to push the development forward. Thanks!

**Comment by brotzmanmj** [comment]
Hi, thanks for the reminder. I need to crosscheck the list from Amelia and will update this issue before the end of the day.

**Comment by brotzmanmj** [comment]
HI @jhflorey Can you confirm Data Has Been Destroyed flag: yes/no (861639549)  is saved as part of the stub record? I would assume yes but just wanted to check since it wasn't on the SOP.

The one additional variable we need to retain in stub record is NORC Case Number (320023644) which is nested under Payment Round. This is what currently helps us distinguish payment issued by NORC vs Chicago so for invoicing purposes, we need to keep it.

Another question: Will the additional variables and tables we have added since when we last tested this will get deleted automatically? For example, Kit Assembly Table, just to name one?

**Comment by jhflorey** [comment]
Hi @brotzmanmj, 

- #1: You're correct. The default value of `861639549` is no, after the data is destroyed,  its value will be changed to yes.
- #2: The  Payment Round (130371375) is a part of the stub record so the NORC Case Number (320023644) will still be retained. We do not need to update code.
- #2: Yup, the related data in "bioSurvey_v1", "clinicalBioSurvey_v1", "covid19Survey_v1", "menstrualSurvey_v1", "module1_v1", "module1_v2", "module2_v1", "module2_v2", "module3_v1", "module4_v1", "biospecimen", "notifications" will get deleted automatically.

**Comment by jhflorey** [comment]
@brotzmanmj yup.  If we want to delete data automatically in `KitAssembly` and `CancerOccurrence`, we have to add these table. Do you want to add these tables for deleting data automatically? Please help confirm.

**Comment by JoeArmani** [comment]
> @brotzmanmj yup. If we want to delete data automatically in `KitAssembly` and `CancerOccurrence`, we have to add these tables. Do you want to delete data automatically in 2 tables? Please help confirm.

reviewed and approved - add kitAssembly & cancerOccurrence to data destruction list

**Comment by brotzmanmj** [comment]
@JoeArmani Not yet, still under discussion with leads as to whether these get retained or destroyed

**Comment by brotzmanmj** [comment]
@jhflorey @JoeArmani We have a decision that the CancerOccurrences will get destroyed if the participant requests data destruction. No decision yet on KitAssembly data.

**Comment by sonyekere** [comment]
Hi @robertsamm and @brotzmanmj  Per priority list, this issue would address Data destruction: Data + SMDB - add stub vars in the March release. If this is the case, is there an update to requirements for @jhflorey to note ? Thanks!

**Comment by robertsamm** [comment]
Hi @sonyekere the Ops team is meeting this Thursday to finalize the list of additional stub variables and then will share this list with Jessica once final.

**Comment by mnataraj92** [comment]
@jhflorey The participation status variable (912301837) has an option "Data Destroyed" (884452262) that should be set when HdWd_DataHasBnDestroyed_v1r0 (861639549) = 353358909 (yes). Could you please program this?

**Comment by jhflorey** [comment]
@mnataraj92 let me check it.

**Comment by mnataraj92** [comment]
Hi @jhflorey here is the link to the SOP that has all of the variables to be retained or deleted https://nih.app.box.com/file/839951579186. The participants table variables where we are selectively keeping/deleting variables is the first table. The second table has the other data tables where we are either keeping the whole table or deleting the whole table (not selectively). For the data destruction of the Send Grid variables, that table will be merged with the notifications table in the next month and we will be deleting both notifications table and send grid table data. Please let me know if you have any questions or need additional information.

**Comment by brotzmanmj** [comment]
@jhflorey @mnataraj92 New SOP uploaded, same link as the old one https://nih.app.box.com/file/839951579186

**Comment by jhflorey** [comment]
Hi @brotzmanmj @mnataraj92, after checking code and new document.

- I found we are missing these fields as image below. I will add them.
<img width="1123" alt="image" src="https://github.com/episphere/connect/assets/24559107/17366a7a-fd7e-4be7-bdc3-2e7b5a070ba9">

- This list table will be deleted are "bioSurvey_v1", "clinicalBioSurvey_v1", "covid19Survey_v1", "menstrualSurvey_v1", "module1_v1", "module1_v2", "module2_v1", "module2_v2", "module3_v1", "module4_v1", "notifications", "promis_v1", "mouthwash_v1", "ssn" 

- After doing the data destruction, will update the value of variables
   912301837=884452262
   861639549=353358909

Please correct me if i was wrong.

**Comment by mnataraj92** [comment]
@jhflorey yes, please add all of the variables as stated in the SOP. The variables you listed in the image are part of the participants table and should be retained as indicated in the SOP. 

Regarding the participation status variable (912301837), the participation status variable has an option "Data Destroyed" (884452262) that should be set when HdWd_DataHasBnDestroyed_v1r0 (861639549) = 353358909 (yes).

**Comment by jhflorey** [comment]
@brotzmanmj @mnataraj92  have you tried test in dev?

**Comment by mnataraj92** [comment]
@jeannewu is finishing up the code to check the data. I finished the test plan and Amelia reviewed. Once Michelle approves it should be good to go. I have asked Aileen to create test participants.

**Comment by mnataraj92** [comment]
Tested in dev, stub record variables retained as expected. There were a couple issues with the SMDB where there were errors with the participant summary page not showing the correct statuses and the participation status 'data destroyed' is showing as 'error' in the bubble field: https://github.com/episphere/connect/issues/937.

**Comment by sonyekere** [comment]
Thanks Madhuri. Confirming that SMDB fixes https://github.com/episphere/connect/issues/937 will occur in the April release.

**Comment by mnataraj92** [comment]
This is ready for stage testing

**Comment by mnataraj92** [comment]
ready for prod
