### ISSUE TITLE
Remove extra spacing for deviation type manifest rows

### ISSUE THREAD

**Issue by Gbarra9** [episphere/connect#643]
Problem
> Norma noticed that the manifests the sites print out are now all double-spaced, even when there aren't any deviations recorded, making the manifest longer. Is it possible to make the manifests single-spaced except for the rows that have deviations?

Current Manifest
![Screenshot 2023-05-30 at 9 54 12 AM](https://github.com/episphere/connect/assets/33293205/2780d830-0dee-4fcb-8f3a-5efcb2732114)

Desired Manifest Change
<img width="1162" alt="Screenshot 2023-05-30 at 9 58 11 AM" src="https://github.com/episphere/connect/assets/33293205/06cf96f9-d7cf-4a16-8a06-2043f7527483">

**Update (Title Change):** 
Changed original title `Make manifest rows single spaced except for rows with deviations` to `Remove extra spacing for deviation type manifest rows`

**Comment by Gbarra9** [comment]
Information for deviation row spacing on manifests:

- The double spaced rows will occur if the `Full Specimen ID` is associated with more than one Deviation Type and the `Full Specimen ID` is not the last Specimen ID in the Specimen Bag ID
- Spacing may occur for rows regardless if a `Full Specimen ID` is associated  with more than one `Deviation Type`. This may occur from the amount of content or characters from the `Comments` table cells or if the `Full Specimen ID` extends to **two rows**

**Comment by Gbarra9** [comment]
**BPTL**

Current (BPTL)
<img width="1032" alt="Screenshot 2023-06-07 at 4 55 51 PM" src="https://github.com/episphere/connect/assets/33293205/de048704-fff8-4b04-abbc-2ebf6672d194">

New Row Spacing Rules (BPTL)
<img width="1032" alt="Screenshot 2023-06-07 at 4 55 58 PM" src="https://github.com/episphere/connect/assets/33293205/1e4ddafb-db91-435f-98ef-f296cdac223b">

**Shipping Dashboard Page**

Current (Ship Dashboard)
<img width="1032" alt="Screenshot 2023-06-07 at 5 01 26 PM" src="https://github.com/episphere/connect/assets/33293205/92dae2bc-2ed2-49d2-b492-952acb826225">

New Row Spacing Rules (Ship Dashboard)
<img width="1032" alt="Screenshot 2023-06-07 at 5 01 37 PM" src="https://github.com/episphere/connect/assets/33293205/2862a5a9-4aca-473c-b95c-15e26dfd76d4">

Shipping Reports 

Current (Ship Reports)
<img width="1235" alt="Screenshot 2023-06-07 at 5 04 27 PM" src="https://github.com/episphere/connect/assets/33293205/09270b0d-23f1-45ed-b190-d4ee3b8f33a7">

New Row Spacing Rules (Ship Reports)
<img width="1276" alt="Screenshot 2023-06-07 at 5 04 18 PM" src="https://github.com/episphere/connect/assets/33293205/33bad013-8a90-4fb6-a8ce-8d497d100edc">

**Comment by Gbarra9** [comment]
> Hi Gene, I am just curious why there is still double spacing for the first one (tube 0001) but not the urine tube (0006). both have multiple deviations. Can the 0001 also be single spaced? Thanks, Stephanie

Hi Stephanie the first tube can have no spacing. The important thing to note is that spacing may occur due to the amount of characters in the Comments column cells or area. This will affect the spacing in the other columns and will create an extra space between rows. Reference `Box Manifest 43` Full Specimen ID's CXA440660 0002. CXA440660 0002 is not on one line due to character size length in the Comments Column. 

**Below are examples of how the manifest will appear without Deviation Type Spacing:**

<img width="1206" alt="Screenshot 2023-06-08 at 11 52 17 AM" src="https://github.com/episphere/connect/assets/33293205/b03af5be-12a6-4be1-9bba-435277477df8">

<img width="1198" alt="Screenshot 2023-06-08 at 11 32 47 AM" src="https://github.com/episphere/connect/assets/33293205/974154a4-4dd8-4648-ac95-16a216b89bfb">

<img width="1216" alt="Screenshot 2023-06-08 at 11 32 32 AM" src="https://github.com/episphere/connect/assets/33293205/fd650c10-3267-4ee6-9acc-6e9386fc2345">

**Comment by Gbarra9** [comment]
I also changed the logic to experiment and see how the deviations would appear with minimal amount of spacing. I believe we are leaning towards the **no spacing** option from the [comment above](https://github.com/episphere/connect/issues/643#issuecomment-1582992992). If I recall correctly the objective here is to reduce the printed manifest sizes that the sites print and deliver to Norma's team.

The logic is as follows:
- Full specimen ID has more than one deviation type, except reference third bullet point
- Given the `Full Specimen ID` has more than one `Deviation Type`, the last deviation type (associated with the Full Specimen ID) row will have an extra line break (more spacing)
- A Full Specimen ID with more than one Deviation Type will not have spacing if it's the last `Full Specimen ID` in the `Specimen Bag ID`
<img width="1217" alt="Screenshot 2023-06-08 at 11 47 40 AM" src="https://github.com/episphere/connect/assets/33293205/cf49d529-ff3b-434b-9acc-1c88a36a1992">
<img width="1205" alt="Screenshot 2023-06-08 at 11 47 56 AM" src="https://github.com/episphere/connect/assets/33293205/5e363d97-fa73-4d15-b802-ac484aff1f45">
<img width="1187" alt="Screenshot 2023-06-08 at 11 48 07 AM" src="https://github.com/episphere/connect/assets/33293205/12a81955-e559-4e4b-a07e-1fecf27fa0b3">

**Comment by StephanieWeinstein** [comment]
Hi Gene,
yes the objective is to reduce the printed manifest length that the sites print and deliver to Norma's team.  Fewer pages is better.

Why is this included? "Given the Full Specimen ID has more than one Deviation Type, the last deviation type (associated with the Full Specimen ID) row will have an extra line break (more spacing)"  I don't think we need an extra line break here?
Thank you!

**Comment by StephanieWeinstein** [comment]
ah, sorry there was a miscommunication here regarding this:  "Is it possible to make the manifests single-spaced except for the rows that have deviations?" This was just to acknowledge that if there are deviations then those might take up more than one line.  So we do want everything single spaced, and some items may use more than one line if there are a lot of deviations or if the CXAID column wraps over two lines.

**Comment by Gbarra9** [comment]
> So we do want everything single spaced, and some items may use more than one line if there are a lot of deviations or if the CXAID column wraps over two lines. So as you indicated above, this would work well: `https://github.com/episphere/connect/issues/643#issuecomment-1582992992.`


Yes that is correct. There will be spacing but its comparable to the spacing you see in the first image. If content for columns will wrap more than one line, the appearance will be the second image.
<img width="800px" alt="Screenshot 2023-06-09 at 12 57 54 PM" src="https://github.com/episphere/connect/assets/33293205/a7b46283-9e6d-4ce8-b7e8-811458639f54">

Column Content Wrapping More than one line 
<img width="800px" alt="Screenshot 2023-06-08 at 11 32 47 AM" src="https://github.com/episphere/connect/assets/33293205/974154a4-4dd8-4648-ac95-16a216b89bfb">

**Comment by StephanieWeinstein** [comment]
ok, thank you!

**Comment by Davinkjohnson** [comment]
@wyattks to test in DEV

**Comment by wyattks** [comment]
Spacing looks good.  Ready for stage.

**Comment by Davinkjohnson** [comment]
Good in Prod
