### ISSUE TITLE
Change in Using MRN for Kaiser Identify Verification

### ISSUE THREAD

**Issue by aMaloneKPCO** [episphere/connect#65]
The Kaiser Project Leadership has decided not to use Kaiser MRNs for recruit identity validation in the first year.   We would also like the option to add it back to the recruit profile after the trial period depending on our ID verification algorithm's auto-pass rate.     The request is to suppress the MRN field for Kaiser profile screens.

**Comment by aMaloneKPCO** [comment]
As I am checking the profile section on the KPGA site, I do not see the MRN field.   Has the MRN field already been removed for all KP sites?

**Comment by bhaumik55231** [comment]
Yes @aMaloneKPCO MRN field has already been removed from the user profile for all KP sites.

**Comment by aMaloneKPCO** [comment]
@bhaumik55231, Thanks.  I should have checked first. I confirmed MRN is no longer visible for each KP site.  We can close this issue.
