### ISSUE TITLE
Make specimen search faster

### ISSUE THREAD

**Issue by we-ai** [episphere/connect#650]
Our `searchSpecimen` function in backend does below steps to get searched collection:
1. Query `biospecimen` collection in Firestore using a collection ID.  If a document is found, get token value from the document. 
2. Query `participants` using the token in step 1. If a document is found, get site code from it. If this site code matches the site code passed in to `searchSpecimen` function, return the document data in step 1.

Above steps can be simplified. If we add a `siteCode` key in each document of `biospecimen` collection, `searchSpecimen` function will only use 1 query (with collection ID and site code) to get the result.

To achieve the faster search mentioned, below tasks are needed:
- Update each existing document of `biospecimen` in Firestore, to add `siteCode` value 
- Update frontend repo, to create `siteCode` as a required field when creating a new specimen data record
- Update `searchSpecimen` function in backend, to use `siteCode` and `collection ID` when searching a collection in `biospecimen` collection

**Comment by JoeArmani** [comment]
I just looked @ this structure for the first time. Here are some thoughts to add to @we-ai's insights:

Looking at the `siteDetails` collection -> `siteCode` and `siteAcronym` map to each other. So these comments assume a 1:1 mapping and are not valid if I'm mistaken about that mapping.

Mapping for new docs:
Maybe we can reference `siteAcronym` (already on the biospecimen doc) without updating the biospecimen docs.
Or to update the biospecimen docs with `siteCode`, we can use a mapping object `siteAcronymToSiteCode` where  `siteAcronym: siteCode`.
```javascript
const siteAcronymToSiteCode = {
   siteAcronym1: siteCode1,
   siteAcronym2: siteCode2,
   // etc...
};
```

If we need `siteCode` and can't just use `siteAcronym`, we can use the same mapping object to write `siteCode` to all new docs without frontend changes (assuming this 1:1 `siteAcronym`:`siteCode` mapping) when the initial write happens. This handles everything moving forward, but existing docs will need to be updated with a separate routine. We should handle the null `siteCode` property case in the meantime to prevent errors.

Updating existing docs:
If we need `siteCode`: The routine to update existing docs should be paginated by `docID` so we can track the last updated doc as the loop executes (batch limit 500). I don't think we can query a null property in Firestore, so we'll have to loop through all the docs, check for the `siteCode` property, and `update` when `!doc.hasOwnProperty('siteCode')`.

Search function - searchSpecimen:
// still need to look at this...

**Comment by we-ai** [comment]
Thanks @JoeArmani for suggestions. I think for each site, the siteCode and siteAcronym are exactly 1-to-1 map.

I just realized concept ID  827220437 (healthcare provider) in each biospecimen document might hold the siteCode we're talking about. If this is the case, only minor changes are needed in the Firestore query ( in `searchSpecimen`) to achieve faster searches.

**Comment by Davinkjohnson** [comment]
@JoeArmani to add further details on how the tubes and boxes are marked (status) depending on whether they were shipped. 

Will need a naming convention for leftover/remaining tubes.

**Comment by JoeArmani** [comment]
**Boxes:**
•We're adding a shipped (yes/no) and received (yes/no) property to all new boxes on creation. This is key to efficient firestore querying. These properties are currently only written when the 'yes' value exists. They are missing prior to a 'yes' value. Firestore does not allow querying on missing properties. We will be able to query 'no' values once these are in place.
This functionality is in the current BSD PR here: https://github.com/episphere/biospecimen/pull/568.

•We've written the routine to update all existing boxes with these flags here: https://gist.github.com/JoeArmani/39e8b5b2e053a26cc5773a253c8f50fc
This routine will run once the new box creation code from the current BSD PR is live. It will enable us to start querying boxes based on: 
-shipped or unshipped (using the shipped flag).
-received or not yet received (using the received flag).
-in transit (using a combination of the shipped and received flags).

•We've written the API endpoints to handle box numbering efficiently here: https://github.com/episphere/connectFaas/pull/396
Ideas discussed: 
-adding boxCreationTimestamp, then querying by site and box creation date (Joe).
-maintaining a counter for each site (Tony, Warren, Joe).
-The final decision was to maintain a counter for each site based on Warren's preference.
This counter is the `mostRecentBoxId` property in each site doc in the `'siteDetails'` collection (Firestore).
Process:
(1) Query the doc by `siteCode`, return `docId` and `mostRecentBoxId` properties.
(2) Increment the `boxId` client-side.
(3) Batch write (atomicity is critical here) the `new box` and the updated `mostRecentBoxId` properties. Note: The write operation double-checks that a box with that ID doesn't already exist for the site. This is important in case of multiple site users creating boxes at exactly the same time.


The above lays the groundwork for the new box-handling methods. Full implementation in the shipping dashboard requires coordination with the specimen data. Below is a rough estimate of work to complete. Other smaller details are expected to arise. These optimizations are key to the shipping dashboard's long-term optimal functionality and scalability. 


**Specimen Data:**
•Handling these same considerations related to items in the `biospecimen` collection: specimens, stray tubes, and shipped properties on the bags and tubes.
•Writing the cloud function routine to update existing specimens with the shipped/unshipped property.
•Updating the data structure in BSD for new specimen creation - to include the shipped property.
•Writing the in-app algorithm for handling stray tubes when bags are added to boxes.
•Writing the new API endpoint to handle stray tubes when bags are added to boxes.
•Writing the new API endpoints for:
(1) specimen search (querying with the shipped/unshipped property).
(2) box search (querying with the shipped/unshipped property).
•Writing the new algorithm that handles bags in the app's 'Available Collections' section.
•Rewriting the routine that separates specimens currently in boxes from unshipped specimens in the 'Available Collections' section.

**Comment by JoeArmani** [comment]
PR here: https://github.com/episphere/connectFaas/pull/440

This PR covers several issues. I only linked one so it didn't clutter up the board.

PR-specific notes:
(1) Add biospecimen shipping dashboard endpoints for optimized box and specimen loading.
(2) Increase Box capacity to 40 bags.
(3) Update tube types for new streck tube implementation.
(4) Update submitParticipantData.json and updateParticipantData.json for new & expanded API-access.

Related issues:
Shipping Dashboard slow loading: https://github.com/episphere/connect/issues/619
Make specimen search faster: https://github.com/episphere/connect/issues/650 &
https://github.com/episphere/connect/issues/746
Increase max bag capacity: https://github.com/episphere/connect/issues/746
Add streck tubes support (ConnectFaas): https://github.com/episphere/connect/issues/620
Add new variable to rules JSON: https://github.com/episphere/connect/issues/739
Age expansion updated CIDs https://github.com/episphere/connect/issues/761

**Comment by Gbarra9** [comment]
PR - being review

**Comment by bransteitterbr** [comment]
PR ready for leads review

**Comment by anthonypetersen** [comment]
reviewing...

**Comment by JoeArmani** [comment]
Merged into dev. I'll update when the Biospecimen PR that accompanies this one - https://github.com/episphere/connectFaas/pull/440 - is in dev and ready for testing.

**Comment by JoeArmani** [comment]
This is live in dev and ready for testing.

**Comment by JoeArmani** [comment]
This is tested & approved in dev, ready for stage.

**Comment by JoeArmani** [comment]
Approved in stage, ready for prod.

**Comment by JoeArmani** [comment]
Closing - this is in production.
