### ISSUE TITLE
Missing BPTL Received Dates in Biospecimen Table

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#653]
The following Connect IDs are missing the collection-level BPTL received date (BioBPTL_DateRec_v1r0 - 926457119) and/or tube-level BPTL received dates in the biospecimen table. The received dates _are_ present in the Boxes table.

**Missing BioBPTL_DateRec_v1r0**
- 9382576687 (Rec'd on 6/7)

**Missing SSTube1_BioBPTL_DateRec_v1r0**
- 9382576687 (Rec'd on 6/7)

**Missing SSTube2_BioBPTL_DateRec_v1r0**
- 9382576687 (Rec'd on 6/7)

**Missing HeparinTube1_BioBPTL_DateRec_v1r0**
- 9382576687 (Rec'd on 6/7)

**Missing HeparinTube2_BioBPTL_DateRec_v1r0**
-9382576687 (Rec'd on 6/7)

**Missing EDTATube1_BioBPTL_DateRec_v1r0**
- 9382576687 (Rec'd on 6/7)
- 9069102957 (Rec'd on 6/7)

**Missing UrineTube1_BioBPTL_DateRec_v1r0**
- 9382576687 (Rec'd on 6/7)
- 9069102957 (Rec'd on 6/7)

@Davinkjohnson to assign this issue.

**Comment by abhinavjonnada82** [comment]
Test plan:
Pick a package with multiple boxes (at least 2) from Packages In Transit then receipt & download CSV receipt file.
CSV file  should contain all the boxes with received date.

**Comment by HopkinsDC** [comment]
Issue tested in dev. Ready for stage.

**Comment by Davinkjohnson** [comment]
Close 1st week of November if this does not reoccur

**Comment by Davinkjohnson** [comment]
Closing this as it has not reoccured.
