### ISSUE TITLE
[Feature] Enhance participant search to return all available names (first + last)

### ISSUE THREAD

**Issue by abhinavjonnada82** [episphere/connect#654]
Description:
Allow the user to perform a search on consent, preferred first name, user profile & updated user profile F+L name in the Participant Lookup page. This enhancement will improve the search experience.

MVP:
- [x] In the query object of participant JSON response, change the key value pairs `firstName` & `lastName` from strings to arrays.[@JoeArmani ]
- [x] Ensure that this change is reflected in existing participants as well. [@abhinavjonnada82]
- [x] Extend this feature to the Biospecimen participant lookup as well. [By default gets extended to Biospecimen participant lookup]
- [x] Perform thorough testing to validate the accuracy and performance of the enhanced participant search feature.[@abhinavjonnada82 & @JoeArmani ]

Nice to haves:
- [ ] Consider integrating fuzzy search or partial name matching to accommodate variations in name spellings or formats.

Note:
Are we storing previously used names, email and phones or are we getting rid of them?
Resolution: 
Tracking consent  F+L name,  user profile F+L name (& updated), preferred first name

**Comment by abhinavjonnada82** [comment]
[Test Cases](https://github.com/episphere/connect/files/12084126/Search.Test.Cases.pdf)

**Comment by abhinavjonnada82** [comment]
Script to change F+L name from string to array in search query object
https://gist.github.com/abhinavjonnada82/7713cae834f51665f2e6cf3786d78066

**Comment by brotzmanmj** [comment]
Hi Abhinav, is this ready to test in dev?

**Comment by abhinavjonnada82** [comment]
> Hi Abhinav, is this ready to test in dev?

Yes ready for DEV testing.

**Comment by mnataraj92** [comment]
this looks good in dev and is ready for stage

**Comment by abhinavjonnada82** [comment]
Looks good in prod!
Search can be performed on consent, user profile F+L name & preferred name.
Ran a quick check on prod, all the participants search query data type changed from string to array.
