### ISSUE TITLE
HFH- Participant verified on NCI side but not in HFH records

### ISSUE THREAD

**Issue by mnataraj92** [episphere/connect#655]
Connect ID 3868997238 is showing up as verified. This pt signed in on 3/6/23, consented on 3/13, submitted user profile on 3/13, and was verified on 3/13 (according to BQ). They don’t have a verification method though (the automated/manual verification variables are null, in addition to the verification table variables). HFH said that this pt is not verified on their end and they don’t see any activity on their end for how this person was verified.

@Davinkjohnson, can you assign this to someone who can check the prod data? Would there be a record of the incoming API call or anything we can see? Or if you have any suggestions for next steps? Thanks so much!

**Comment by brotzmanmj** [comment]
Thanks Madhuri, and just to add, this person is eligible so HFH would like guidance on how they can process the verification to make the data complete on both sides.

**Comment by Davinkjohnson** [comment]
We can probably look into this this afternoon (once we've completed our stage push). I'm not certain how far back our API logs go, so no promises there but I think you're right that it's a good place to start.

**Comment by brotzmanmj** [comment]
HFH pushed the necessary verification information to complete the data so should we close this or is further insight available on the origin of this error?

**Comment by Davinkjohnson** [comment]
@brotzmanmj We didn't get a chance to look at this the other week (as we were tied up in release tasks). If you'd like we can take a look through the logs before closing the ticket, but the only updated that happen in prod are via manual change log requests or the API.

**Comment by brotzmanmj** [comment]
@Davinkjohnson I think it's not worth the effort to pursue for this one instance. We checked the prod manual change log and it was not there, and the site says they didn't push it in the API so it remains a mystery. However, we do have QC checks that can identify instances like this so we can open a new issue if it re-occurs.
