### ISSUE TITLE
Add Delete Functionality - SMDB Notifications

### ISSUE THREAD

**Issue by anthonypetersen** [episphere/connect#657]
Currently users can only add and edit notification specifications, add the ability to delete a specification.

**Comment by we-ai** [comment]
I see notification deletion functionality is rarely used. So I'm not sure whether we should implement it in SMDB or manually delete a spec when occasionally needed.
The only scenario using deletion functionality is quarterly newsletter specs. With the implemented draft functionality, the retired newsletter specs can be put in draft mode and deleted at appropriate time.

Please comment on this @brotzmanmj @depietrodeanna @anthonypetersen

**Comment by we-ai** [comment]
Agreed @depietrodeanna. Please comment on issue #893 for proposed editing condition functionality.

**Comment by brotzmanmj** [comment]
Agreed , we can do without the ability to delete an entire existing spec.
