### ISSUE TITLE
Implement 'duplicate' label check when a valid token/pin is used at the first time

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#659]
Set up system to check ‘duplicate’ label (CID 922622075) in verification status (CID 821247024) of an existing record when a valid token/pin is used for the first time, and block the participant from proceeding as early as when he/she sign in (token scenario) or click the “Submit” button (pin scenario) if the ‘duplicate’ label is found.

Deanna will confirm the wording for the message to be displayed.

**Comment by depietrodeanna** [comment]
New language, assuming we can pipe in redacted sign in info for the "correct" account:

Our records show that you already have an account with [redacted email or phone number of their verified account]. Please try signing in again. Contact the Connect Support Center by emailing [ConnectSupport@norc.org](mailto:ConnectSupport@norc.org) or calling 1-877-505-0253 if you need help accessing your account.

**Comment by we-ai** [comment]
Sounds good. We need to retrieve the correct account info to remind participants.
In the participant record marked as duplicate by the site, which concept ID holds information about the participant's correct account?

**Comment by depietrodeanna** [comment]
@mnataraj92 @FrogGirl1123 @anthonypetersen I don't have the answer to Warren's question but perhaps you do?

**Comment by we-ai** [comment]
I checked some records marked as 'duplicate', and couldn't find information about the correct accounts. Likely this piece of info is not saved in duplicate records.

**Comment by brotzmanmj** [comment]
In agree, I don't think there is anything in our system that indicates for a duplicate account what is the corresponding verified account.

**Comment by we-ai** [comment]
Since identifying a duplicate account involves lots of work, we may need to save some key information for later use. In the duplicate account case, we may consider adding a field (eg `state.verifiedConnectID` or something similar) in a duplicate record for easy access to the correct record.

**Comment by brotzmanmj** [comment]
We would need to get this information from the site. They are the ones that do the verification. We're not currently set up to do it but it would be worth discussion with our internal team leads.

**Comment by we-ai** [comment]
Since new code after next Friday (7-14) won't be included in July release, we may not be able to implement this functionality in full before July 14, because currently we don't have a reliable way to retrieve the correct account.

Without the information about correct account, the message to participants can be: 
`Our records show that you already have an account. Please try signing in again using the other account. Contact the Connect Support Center by emailing ConnectSupport@norc.org or calling 1-877-505-0253 if you need help accessing your account.`

Please suggest on above message to participants.

**Comment by brotzmanmj** [comment]
Since we can't retrieve the correct account, we should proceed for this release with doing the duplicate check earlier as we discussed (I think that's in another github issue) and display the message: Our records show that you already have an account. Please try signing in again using your other account. Contact the Connect Support Center by emailing ConnectSupport@norc.org or calling 1-877-505-0253 if you need help accessing your account.

**Comment by cunnaneaq** [comment]
Dev testing looks good - ready for stage

**Comment by cunnaneaq** [comment]
reached out to Vijay for stage accounts

**Comment by cunnaneaq** [comment]
Stage testing looks good!  Scenarios documented in Box - https://nih.app.box.com/file/1261189336655
