### ISSUE TITLE
Check valid address/phone/email on user profile

### ISSUE THREAD

**Issue by mgarciaclosas** [episphere/connect#66]
Can we  add an address/phone number/email validator on the user profile ? e.g. to check that a valid ZIP code is entered or other checks

**Comment by Davinkjohnson** [comment]
Depends on the level desired 
checking formatting (10-digit # for phone and 5-digit for zip) is viable
validating via API call to USPS that a zip code is valid is harder

**Comment by sonyekere** [comment]
Closing issue. Issue has not been revisited since 9/20/22.
