### ISSUE TITLE
Add basic validation to DOB in User Profile

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/connect#665]
In prod there is insufficient validation of the DOB. As an example a participant was recently able to mistakenly enter invalid DOB of 1062. We'll need direction from Ops on valid minimum date.

**Comment by bransteitterbr** [comment]
I found that there was an existing validation that was just incorrectly written that I updated the old regex was /[19|20]{2}[0-9]{2}/ that was actually validating for the first two characters could be 1 or 9 or | or 0 instead of the intended 19 or 20.  I changed it to /(19|20)[0-9]{2}/ to make it 19 or 20 followed by 2 digits.  That is why the absurd 1063 worked but if you tried 1863 it would have properly failed

**Comment by brotzmanmj** [comment]
That was fast! Thank you for finding this. Can that fix go in the July release?

**Comment by Davinkjohnson** [comment]
@brotzmanmj Brian has a PR for this and it's just waiting for an approval now. It should make it into the July release, provided approval and testing go as expected.

**Comment by Davinkjohnson** [comment]
Oldest date is 1900 newest date is 2099
Aileen to test

**Comment by cunnaneaq** [comment]
tested in dev - received error message when entering DOB in 1800s.  Newest year is 2023.  2024 also resulted in an error message.  The message currently states: 

<img width="684" alt="Screenshot 2023-07-18 at 2 43 07 PM" src="https://github.com/episphere/connect/assets/83971268/8df3ab34-dbaa-4e9e-aaaa-a10982b4c525">

**Comment by bransteitterbr** [comment]
So it looks like there is additional validation other than the regex that does prevent any years greater than the current year so 2024 and above should fail.  As far as the error message the code currently uses 1 error message for any validation error and it is not specific to the rule that failed.  If the error message is too confusing, we could draft a different message easily.  If we wanted different error messages per reason that the validation failed then we would need to do more work.

**Comment by cunnaneaq** [comment]
Thanks, Brian!  I defer to @brotzmanmj and @Davinkjohnson about updating the error message language

**Comment by brotzmanmj** [comment]
@bransteitterbr When you say we can just have 1 error message for any validation error, is this particular validation just for birth year or does it apply to other places where we ask for 'year'?

**Comment by bransteitterbr** [comment]
@brotzmanmj Each individual field can have its own error message but there is only 1 error message per field.  So DOB can have one message and a different year can have its own message too.

**Comment by brotzmanmj** [comment]
Thank you! @depietrodeanna can you advise on if/how we should this error message for year of birth? Should we change it to be more broad to encompass just to say it's 'out of the expected range' or something to that effect which would apply if they only entered three digits or if they put something that was not 19xx or 20xx. Thoughts?

**Comment by depietrodeanna** [comment]
Yes @brotzmanmj I think we should change it to make more sense given that a birth year like 2024 is still shooting the error message (and is in the YYYY format). What about, "The year you entered is outside of our expected range. Please check your entry." I think this encompasses both a year outside of our window (that fits the YYYY format) and also a 3 digit year error.

**Comment by brotzmanmj** [comment]
Sounds great, thank you. @bransteitterbr Does that work for you?

**Comment by bransteitterbr** [comment]
Yes, I can have a pull request for that change out shortly.

**Comment by cunnaneaq** [comment]
Confirmed in stage - DOB year range 1900-2023 in stage.  Error message language updated; message appeared for year outside of window (see screen shot below) and for a 3-digit year entry error

<img width="547" alt="Screenshot 2023-07-25 at 2 54 43 PM" src="https://github.com/episphere/connect/assets/83971268/d89a562c-b97b-425c-ae2d-f32802d57431">
