### ISSUE TITLE
multi-login cleanup and sign-in mechanism reporting

### ISSUE THREAD

**Issue by JoeArmani** [episphere/connect#666]
(1) Sign in mechanism is incorrectly reported for certain login combinations when participants have both email and password logins.
expected result: 995036844 is reported as
'password' for participants with email authentication only
'phone' for participants with phone authentication only
'passwordAndPhone' for participants with both email and phone authentication methods.

(2) verify email notification shows for logged-in participants with only phone validation method.

**Comment by JoeArmani** [comment]
Per Deanna: Here is the language for the update login info screen from NORC that you can add to the Github issue when it's created. For the language that appears on the MyProfile page when you click the “Update Login” button. Current language- “Need to update your sign-in information? Choose your preferred login method below:” and the buttons are labeled “Use email” and “Use mobile phone”. Change to- “Need to update your sign-in information? Add or update your information below:” and label the buttons as “Update email” and “Update mobile phone”.

**Comment by JoeArmani** [comment]
Here's the updated text, included in: https://github.com/episphere/connectApp/pull/600
<img width="851" alt="Screenshot 2023-07-12 at 1 40 52 PM" src="https://github.com/episphere/connect/assets/93854858/b77de11d-7e48-431e-9135-a67384c19e37">

**Comment by depietrodeanna** [comment]
Hi @JoeArmani The top part of this looks good. The language at the bottom "Update your login New Email Address" is awkward- could you change to: "Update your login email:" and then in the new email address field and confirm field you have "new" twice in a row for both lines. 

It's not clear to me and potentially the user if they have to "Remove this email address" or if they submit a new email if that would automatically replace the old. Could you clarify the flow? For the "Submit Email Update" button could you change this to, "Submit new login email"

**Comment by JoeArmani** [comment]
Hi @depietrodeanna would you like any other changes? Do you want additional text clarifying the flow?
<img width="847" alt="Screenshot 2023-07-12 at 2 39 46 PM" src="https://github.com/episphere/connect/assets/93854858/944e74e6-7ce4-4cb7-905f-ba32dee56f44">

**Comment by depietrodeanna** [comment]
This looks great @JoeArmani  Just a question for me- if someone adds a new email but doesn't remove the other email by clicking that button, is that a problem? Or will the new email just overwrite the old one?

**Comment by JoeArmani** [comment]
Perfect, thanks @depietrodeanna.

Here are a couple key points of the form behavior:
-If someone submits a new email and has an existing email login, it just overwrites the old one.
-if someone submits a new phone number and has an existing phone login, it just overwrites the old one. 
-The 'remove' buttons are only visible if both phone and email logins exist. They are not visible to the participant if only one login method exists since retaining a login method is required.

I'll get this added to the current PR, it should be in dev within the next couple days. Please let me know if you have any other questions/updates.

**Comment by depietrodeanna** [comment]
Thanks for clarifying @JoeArmani !

**Comment by depietrodeanna** [comment]
Hi @JoeArmani this is what I'm seeing in Dev which looks good except I don't see the "Remove this email address." Is there a reason this wouldn't show up?
<img width="736" alt="Screenshot 2023-07-17 at 10 42 37 AM" src="https://github.com/episphere/connect/assets/74061787/2f5da77a-396b-417c-8401-4c28616aa60a">

**Comment by JoeArmani** [comment]
Perfect. Glad to hear it.

**Comment by brotzmanmj** [comment]
Additional place login info displays: Check to make sure the multiple login information displays correctly on the Biospecimen Dashboard check-in/out page.

**Comment by HopkinsDC** [comment]
I confirm the multiple login info displayed on the check-in/check-out page are correct for email only, phone only, and both.

**Comment by depietrodeanna** [comment]
@Davinkjohnson Updates look good in stage. Ready for prod.

**Comment by JoeArmani** [comment]
Update: Reopened issue to solve for participants with the wrong sign-in mechanism between June and July releases.

@robertsamm and I tested the sign in mechanism update in dev. Ready for stage.

**Comment by robertsamm** [comment]
@JoeArmani and I tested the sign in mechanism update in stage and it also looked good there. Ready for prod.

**Comment by JoeArmani** [comment]
Ran the sign in mechanism update in prod yesterday. Closing.
