### ISSUE TITLE
Add new campaign type for Research Registry

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#669]
Need to add a new campaign type to variable 667474224 (RcrtSI_CampaignType_v1r0)
I already put this on the DD Change Request to request the addition of the response code and a CID for it.
Need to do whatever programming and testing is needed to enable the sites to send this code. Chicago will be the first ones using it.

**Comment by mnataraj92** [comment]
The concept ID for Research Registry is 208952854

**Comment by abhinavjonnada82** [comment]
Looks good & can move forward.
