### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by mgarciaclosas** [episphere/connect#67]
[Connect App User Profile.pdf](https://github.com/episphere/connect/files/4299722/Connect.App.User.Profile.pdf)

User profile is missing a question on cancer history. 

Final content needs to be approved by the ExCom, including deciding on mandatory/non-mandatory items.

**Comment by brotzmanmj** [comment]
Cancer history questions have been added back to the user profile document: https://nih.app.box.com/file/501193852134
Were removed erroneously on 3/3/2020 following discussion at the weekly prep meeting.

**Comment by mgarciaclosas** [comment]
@bhaumik55231 - did you use the cancer history questions on the user profile document that Michelle just shared?  Can this issue be closed?.

**Comment by bhaumik55231** [comment]
Done.
