### ISSUE TITLE
Missing Shipment Information in Dashboard - DataDog Troubleshoot

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#674]
Please investigate the following site occurrences of seemingly shipped boxes returning to the Available Collections queue and/or not appearing on BPTL's dashboard for receipt.

- KPGA
BOX 260
SAMPLES ENTERED: 7/17 @ 12PM
COLLECTION FINALIZED: ~2:30PM
SHIP: 7/17 @~4PM
COLLECTIONS INCLUDED: CXA008981, CXA008982
>- KPGA suspects there may have been an Internet signal error, as I have noticed the page often pausing (i.e., graying out, spinning circle) while assigning collections to particular boxes, assigning tracking numbers to the boxes, and finalizing the boxes.

- Henry Ford
BOX 283 
SHIP 7/12 @ ~3:30PM
FEDEX # 635213599392
COLLECTIONS INCLUDED: CXA009863, CXA009835, CXA006670, CXA009834
>- HFH reports slow loading times on the shipping dashboard when continuing to Review Shipment Contents

**Comment by we-ai** [comment]
Based on data in Firestore and BigQuery, HF Box 283 has CXA009863 in bag 2 (CID 136341211), and  CXA009835 in bag 3 (CID 503046679). There's no CXA009834 and CXA006670.

**Comment by StephanieWeinstein** [comment]
CXA006670 and CXA009834 were the collections that had to be shipped electronically after the fact using a fake Fed Ex number (6352 0000 0000).

can  you see any errors using datadog around the time that HF was shipping the samples?  SHIP 7/12 @ ~3:30PM

**Comment by we-ai** [comment]
After checking dozens of Datadog-saved sessions on 7-12, only one session matches time points of Box 283. In this session, the user started at 3:23pm (EST), and the "Sign" button was clicked at 4:15pm, matching shipment time (CID 656548982) 4:15:01 in Box 283 in Firestore.

There was no error in this session.

**Comment by we-ai** [comment]
For Box260 in KPGA, one session match can be found. 
In this session, 2 bags were added to a new box (should be box 259) and shipped. Then other 2 bags were added to another new box (should be box 260), but the Datadog record session stopped after user clicked "Continue to Assign Tracking Number". The "Save and Continue" button on tracking number input page had no chance to be clicked (or was not recorded by Datadog). There were no errors.

**Comment by HopkinsDC** [comment]
@brotzmanmj @StephanieWeinstein It doesn't seem like DataDog captured any errors for these occurrences.

HFH 
- CXA009863 and CXA009835 shipped in DB on 7/12 in Box 283 with tracking number 635213599392; received on 7/13
>- These data are correct in the new flatted boxes table, are correct in the BSI, and match the box manifest that HFH forwarded to us.
- CXA006670 and CXA009834 reshipped in DB on 7/14 in Box 286 with fake tracking number 635200000000; physically received on 7/13
>- These data are correct in the new flatted boxes table and match the box manifest that HFH forwarded to us; the data in BSI was updated to correct the received date to 7/13.

KPGA
- CXA008981 and CXA008982 shipped in DB on 7/20 in Box 260 using fake tracking number 123456789123; physically received on 7/18
>- These data are correct in the new flatted boxes table; the data in BSI was updated to correct the received date to 7/18


I recommend we close this issue since the data are correct in all areas and no errors were detected in DataDog; we will add new issues as they arise.

**Comment by StephanieWeinstein** [comment]
That sounds reasonable for now. thx.
