### ISSUE TITLE
Samples missing in received CSV file

### ISSUE THREAD

**Issue by we-ai** [episphere/connect#676]
This error occurred to Box 261 from Sanford.
In received in-transit file, Box 261 had all expected samples, while in received CSV file, most or all samples in CXA002223, CXA002225 and CXA010645 were missing.

**Comment by Davinkjohnson** [comment]
Abhinav is continuing to work on resolving this. Should have PR this week.

**Comment by Davinkjohnson** [comment]
@abhinavjonnada82 to create plan on how the issue occurs today (show how this can be reproduced) create test plan to show this is resolved.

**Comment by HopkinsDC** [comment]
Issue tested in dev using test plan, and all samples were present. Ready for stage.

**Comment by wyattks** [comment]
HP just had this same happen to them today. 
Box 539 were missing the following samples in the csv for today's receipt.
 CXA006003 0007
CXA006002 0007
CXA005995 0007
CXA005990 0007
Erin tried to scan them again and got the error message saying "Item reported as already shipped"
