### ISSUE TITLE
Preferred Name set on PWA user profile doesn't get stored on search query object

### ISSUE THREAD

**Issue by abhinavjonnada82** [episphere/connect#678]
As the tittle suggests, on PWA when the user sets preferred name on the user profile. It updates the preferred name CID but  the preferred name doesn't get updated on the search query object.

User can't perform a search on Preferred Name set on PWA user profile.

Related issue: https://github.com/episphere/connect/issues/654

**Comment by abhinavjonnada82** [comment]
@JoeArmani you missed including Preferred Name from PWA user profile.

**Comment by abhinavjonnada82** [comment]
Update: Looks like only consent name is set need to add user profile (F+L name) & preferred name on search query object

**Comment by cunnaneaq** [comment]
Successfully able to search for preferred name (in first name field) in SMDB and Biospecimen Dashboard in stage

**Comment by abhinavjonnada82** [comment]
Closing out this issue. Resolution deployed to stage & https://github.com/episphere/connect/issues/654 is ready for production.
