### ISSUE TITLE
Client side reminders to complete biospecimen surveys for clinical versions not being triggered

### ISSUE THREAD

**Issue by abhinavjonnada82** [episphere/connect#679]
As the title suggests, client side reminders to complete biospecimen surveys for clinical versions not being triggered.

Waiting confirmation from KP CO, if the email has been triggered for clinical versions

**Comment by anthonypetersen** [comment]
Do we have any additional information like the participant used?

**Comment by abhinavjonnada82** [comment]
[Samplestesting5@gmail.com](mailto:Samplestesting5@gmail.com)
Connect ID: 9183200893

**Comment by anthonypetersen** [comment]
Who tested this? I see that this API was called twice today and I found SendGrid receipts with a matching subject line at the same time as the API call.

**Comment by anthonypetersen** [comment]
Did they create a Collection ID? I'm not seeing a biospecimen Collection entry for that participant and that is required to send the client side email for a clinical participant. If it's a research participant they need to be checked in, and this participant isn't.

**Comment by abhinavjonnada82** [comment]
> Did they create a Collection ID? I'm not seeing a biospecimen Collection entry for that participant and that is required to send the client side email for a clinical participant. If it's a research participant they need to be checked in, and this participant isn't.

I'll check with Aileen & site testing about this.

**Comment by abhinavjonnada82** [comment]
No further action is required!
