### ISSUE TITLE
Recommend 2 Step IHCS Site Selection Process 

### ISSUE THREAD

**Issue by aMaloneKPCO** [episphere/connect#68]
The Kaiser recruitment Core Team is concerned about how passive recruits select their Health Plans.  The current method is a pull-down menu with a list of health plan names.  The concern is for recruits who accidentally choose the wrong health plan, and the effort it will take to correct their data to reflect the correct health plan.   This issue occurred in another project.  The attached process document was the solution for that study:
[Two Step IHCS Site Selection Process.docx](https://github.com/episphere/connect/files/4308137/Two.Step.IHCS.Site.Selection.Process.docx)

Direct Questions to the Kaiser Recruitment Core Team lead:  Charisma Jenkins (charisma.l.jenkins@kpchr.org), Kaiser Recruitment Team

**Comment by danielruss** [comment]
We are planning on moving the user profile to our questionnaire application, so the user profile will change a bit.

**Comment by Eusuf2000** [comment]
Participant provides his/her address on user profile. IHCS site could use it to pinpoint site, couldn't it?

**Comment by danielruss** [comment]
All agreed that second question (are you sure that your IHCS is <x>

**Comment by bhaumik55231** [comment]
Made required modification.
