### ISSUE TITLE
PWA Multiple Login - Feedback Updates

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/connect#682]
#### Current:
- Login Update button on MyProfile page
- Update says "Update email" and "Update phone" 
- Phone entry says "New phone" 
- Submit button says "Submit new phone number"

#### Future:
- Login update button on MyProfile page says "Update Sign in"
- Sign in Method buttons are Yellow (color adjusted based on active tab)
- Sign in Method buttons read "Update email" and "Add Phone number"
- Remove/hide the "update phone number" subheading text
- Keep phone entry saying "New phone number" and "Confirm new phone number"
- Replace all "login" and "log-in" and "sign-in" text to be "sign in"

#### Current: 
- Login Update button on MyProfile page
- Update says "Update email" and "Update phone" 
- Email entry says "New phone" 
- Submit button says "Submit new email"

#### Future:
- Sign in Method buttons read "Add email" and "Update Phone number"
- Remove/hide the "update email" subheading text
- Keep email entry saying "New email" and "Confirm new email"

## For Participant with Both methods
- Sign in Method buttons read "Update email" and "Update Phone number"
- Keep "Remove this phone number" and "Remove this email" in respective Method tabs
- Keep "Update your sign in mobile number" and "Update your sign in email" sub heading text

## Follow up questions
@brotzmanmj @depietrodeanna  I didn't capture this in my notes... should the "Submit" button have dynamic language or is "Submit new sign in <xyz>" sufficient since whether it's net new or just an updated number their both "new"?

@bransteitterbr Please review the above and add any other requirements you captured that I missed.

**Comment by bransteitterbr** [comment]
- Update instances of sign-in to sign in
- Update instances of login to sign in
- Update the active and inactive tab colors to use the yellow and blue color scheme

**Comment by depietrodeanna** [comment]
@Davinkjohnson If @brotzmanmj agrees, I don't think the Submit button needs to be dynamic based on whether it's a new method or updated email/phone; it can just say, "Submit new sign in details"

**Comment by bransteitterbr** [comment]
![Screenshot (6)](https://github.com/episphere/connect/assets/135354377/b6f1e280-c0ac-412a-9273-1cf9f07eed3d)

Here is the updated language. I still need to update the tab colors but I wanted to post the current progress

**Comment by depietrodeanna** [comment]
@bransteitterbr This looks good! Also, I noticed that if you enter a phone number that's already associated with another account, you get an error message that says the following:
<img width="652" alt="image" src="https://github.com/episphere/connect/assets/74061787/6bb887af-fdb9-4675-97fc-335d5c80915f">

Could you edit the red error message to make it, "This phone number (or email if that shoots an error) is already linked to a MyConnect account. Please check your entry. If you think this is a mistake, please contact the Connect Support Center at 1-877-505-0253 or ConnectSupport@norc.org"

**Comment by bransteitterbr** [comment]
@depietrodeanna I was able to track down how that error message is generated, and I should be able to update it to your preferred message.  I will update it in my dev environment and get that screen shot out for review

**Comment by depietrodeanna** [comment]
Thanks @bransteitterbr this looks good. To confirm, this is also the error message that shows up if someone enters an email already associated with a MyConnect account (except it just says "email" instead of "phone number")?

**Comment by bransteitterbr** [comment]
@depietrodeanna Yes, the error message for email is updated as well:
![Screenshot (10)](https://github.com/episphere/connect/assets/135354377/6db2aec2-ea3e-4a2b-a93c-aa109627e061)

**Comment by depietrodeanna** [comment]
Thanks @bransteitterbr !

**Comment by bransteitterbr** [comment]
@depietrodeanna Here are the final screen shots with the updated tab colors and the different configurations email/phone/both
![Screenshot (17)](https://github.com/episphere/connect/assets/135354377/0c1dcb30-a22a-4f4e-993c-b59339b9fa96)
![Screenshot (18)](https://github.com/episphere/connect/assets/135354377/5cf6bfa4-2aeb-4db9-8df3-24dfdaa434c3)
![Screenshot (20)](https://github.com/episphere/connect/assets/135354377/d76df184-3864-471f-8327-bb53c6761dbd)

**Comment by depietrodeanna** [comment]
@bransteitterbr  Great! One question on the colors- is there any way the text in the buttons for "Update mobile phone" and "Add email sign in" etc. could be darker blue like the other text buttons?
<img width="273" alt="Screenshot 2023-08-17 at 1 14 57 PM" src="https://github.com/episphere/connect/assets/74061787/c21919c3-2c91-4076-bb15-48a19ef57be9">

**Comment by bransteitterbr** [comment]
@depietrodeanna Technically they were already that color but it is probably hard to tell.  I set the font weight to bold to match the other buttons.  Let me know which you prefer:
![Screenshot (22)](https://github.com/episphere/connect/assets/135354377/89053c37-7b56-4900-88fb-2ae29e829604)

**Comment by depietrodeanna** [comment]
Ah, I suspected the bolding might be it. This looks good. Thanks for updating @bransteitterbr

**Comment by bransteitterbr** [comment]
@depietrodeanna and @robertsamm This has been pushed to dev and is ready for testing

**Comment by depietrodeanna** [comment]
@bransteitterbr I am testing various options and see an error code that I haven't seen before (I incorrectly entered the verification code sent to my phone): 
<img width="640" alt="Screenshot 2023-08-23 at 9 22 24 AM" src="https://github.com/episphere/connect/assets/74061787/12017cb9-d341-470c-8cbc-cca688584c6a">

could you confirm when this error message displays? And if it only shows up when someone inputs an invalid verification code, please update this error message language to: "The verification code you entered does not match what we sent. Please check the code we sent to your mobile device and enter the verification code again. If you didn't get a code, click "Submit new sign in phone number" again to receive a new code."

**Comment by depietrodeanna** [comment]
I found another odd error message after inputting an email address (that is definitely valid):

<img width="637" alt="Screenshot 2023-08-23 at 9 32 21 AM" src="https://github.com/episphere/connect/assets/74061787/0e395251-3f75-4934-9b36-3d6623c4f0b3">

Could you confirm when this error message is supposed to show up so I can appropriately craft a message that is clearer?

**Comment by bransteitterbr** [comment]
@depietrodeanna I was able to confirm that the 5 minute timeout is indeed the cause of the error and I have updated the two error messages.  Here are the screen shots for your approval.
![Screenshot (26)](https://github.com/episphere/connect/assets/135354377/740b8bed-0eba-46bb-bc37-3995ff998105)
![Screenshot (27)](https://github.com/episphere/connect/assets/135354377/f8170e4e-5569-4271-8f47-cdba1ce2db96)

**Comment by depietrodeanna** [comment]
@bransteitterbr thanks, these look good. also, I realize when I enter an email that is already associated with a MyConnect account and get this error message: 
<img width="705" alt="Screenshot 2023-08-23 at 4 47 22 PM" src="https://github.com/episphere/connect/assets/74061787/499e69fc-2855-4cf1-a794-925fcad07ef5">

It should go away if I decide to add a phone/update my phone login, but when I click on "Add phone" the message still displays. It should ideally go away:
<img width="764" alt="Screenshot 2023-08-23 at 4 48 14 PM" src="https://github.com/episphere/connect/assets/74061787/76b53694-99ea-4fd3-aa1e-d13f12af5745">

The issue happens in reverse (the phone error message pops up even when I toggle to email add/update). If this is a quick adjust, it should be updated before we push this to stage.

**Comment by depietrodeanna** [comment]
Confirming that in dev, the new format looks good with improved language and color updates. I think the odd error codes popping up from Google are beyond the scope of this issue. @Davinkjohnson, if you agree, we can leave out further investigation. Just wanted to make you aware that these may require further investigation separate from the Aug release. **Since they suggested the initial improvements, should we ask NORC to review the flow briefly in dev before we push to stage?** If yes, I can send them an email on Monday.

**Comment by depietrodeanna** [comment]
Updates look good in stage. ready for prod.

**Comment by Davinkjohnson** [comment]
Now related to #709

**Comment by anthonypetersen** [comment]
can this be closed?

**Comment by depietrodeanna** [comment]
Yes, separate issue covers outstanding work from @bransteitterbr.
