### ISSUE TITLE
August - HFH MySamples Updates

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/connect#686]
Requirements and progress tracked here

**Comment by depietrodeanna** [comment]
Edits tracked here: https://app.box.com/s/svun4hooetuqp3d179ou5tr26k4gkuaq

**Comment by bransteitterbr** [comment]
@depietrodeanna This has been pushed to dev and is ready for testing

**Comment by depietrodeanna** [comment]
@bransteitterbr Kirsti from HFH has confirmed the changes look good in dev. Ready for stage.

**Comment by depietrodeanna** [comment]
Reviewed in stage. Ready for prod.
