### ISSUE TITLE
multiple login display in emails

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#689]
Need to check the code for how multiple logins display in emails. There is code that we refer to in the email message specs that Deanna enters that makes this line appear in the emails that are sent to participants (this is an example):

Please log into the MyConnect app using m*******@yahoo.com. It is important to use this account every time you access the MyConnect app.

If their account access is a phone number, it will display the phone number instead of the email.
We are not sure how this appears now that people can have multiple logins.

Please check the underlying code and see if it needs to be updated. Please reach out to Aleah for any testing needs in dev.

**Comment by Davinkjohnson** [comment]
@abhinavjonnada82  When you have a little time can you please check the code Michelle references so we can best understand whether testing or code changes will be needed?

**Comment by abhinavjonnada82** [comment]
Upon Deanna's suggestion, these 2 a/c's Aleah created 
iD: 4958929565
ID: 8186923759
they should be receiving a post verification email in like 3 days. That should most likely have redacted login email/phone.
Once we see an email in these 2 accounts, we can move forward from there.

**Comment by depietrodeanna** [comment]
@abhinavjonnada82 and @Davinkjohnson- I asked Kelsey to check BigQuery for Connect IDs associated with two login modalities (email and phone) in prod. These two Connect IDs came up and there is some weirdness with one of them; it's still unclear to me how the emails from our system are inputting redacted login info and thus requires further testing. I am assuming, from one of the below examples, that the first method (the one the person originally used to sign in) is the one that the email redacts and inserts into the reminders we send.

Prod participants:
Connect ID 8140165381 (has both email and phone login). Emails in June use redacted **email** login in reminders, but in late July, reminder to complete research sample survey contains “undefined” as the redacted login info. Why?
Connect ID 9967314103 (has both email and phone login). All email reminders from us (including reminder to complete research sample survey) contain the redacted **email** login. 

Could you look into the "undefined" info for participant with ID 8140165381? This is from the client side reminder that Tony programmed (the first reminder to complete research sample survey, triggered upon check in for research collection).

**Comment by depietrodeanna** [comment]
Summarizing dev testing:

We've tested post-verification survey reminders and the 1st (client side) biospecimen survey reminder for research collection for someone who has both a phone and email login. The login information in the emails includes both redacted phone and email now for these cases. Abhinav is working to update the loginDetails code to plug in just the redacted login information (currently the code inputs additional language that is repetitive to the language in the email templates themselves). 

Next step, once the code is fixed, is to test and make sure things work properly for all cases (just phone, just email, and both), and check to be sure the code adjusts if a login method is removed from an account that has both options (someone removes phone login option from their account that had both phone and email)

**Comment by depietrodeanna** [comment]
Reviewed in stage- the 1st client side reminder for biospecimen survey completion was the only thing that I was unable to coordinate checking for a test account today. I can check this on Monday next week. Emails sent server side are showing up as expected. I think we are still OK to push to prod.

**Comment by depietrodeanna** [comment]
Reviewed client side email for research collection sample survey with updated display of multiple login in stage- login details for someone with phone and email are populating correctly. ready for prod.

**Comment by Davinkjohnson** [comment]
Now related to #709
