### ISSUE TITLE
Notification Handler Overhaul

### ISSUE THREAD

**Issue by anthonypetersen** [episphere/connect#692]
Pagination appears to have broken with notifications that pull in larger numbers of participants.

**Comment by we-ai** [comment]
To reduce participant data pulled in, we'll need to add information about emails sent to each participant. I suggest adding a new field in `participants` document, for example `query.emailSpecIdsSent` (array type). This way, participants data fitting each email spec can be retrieved in one query, and it'll run faster and cost less.

**Comment by brotzmanmj** [comment]
This is just a question... I think I understand that we currently have the data about the emails (who qualified for what email to get sent and when?) in a separate table in Firestore. Is that right? And are you suggesting that we store that information in the participants table instead or in addition to?

**Comment by we-ai** [comment]
For email sending, currently we need to search 3 separate data: `notificationSpecifications`, `participants` and `notifications`. 

`notificationSpecifications` stores conditions and template for each email type. For each email spec (eg welcome email), we search `participants` data to get a list of participants matching the conditions. But we don't know whether they've received the email or not. So we search `notifications` (notification records) to check whether a email matching participant ID and email spec ID has been sent or not. If not, we send the email and store email info in `notifications`.

Adding email template ID information to `participants` data will enable us retrieving participants for each email template in one search. There'll be no need to search email records (`notifications`) to know whether a email (eg welcome email) has been sent or not.

**Comment by brotzmanmj** [comment]
Thank you! So would the email records ('notifications') still exist and just the email spec ID will be added to the participants table, or will all the information currently in 'notifications' be added to 'participants'?

**Comment by we-ai** [comment]
Email records should still exist as usual. Just the email spec IDs used will be stored in `participants` to speed up search.

**Comment by we-ai** [comment]
Previously, our old code handling notifications (at 3 PM in prod) needed 800~900 seconds to run, but still wasn't able to send out all notifications needed. Based on current data size, sending out daily welcome emails alone need more than 1600 seconds when handled by old code.
In comparison, the updated code now only needs 7 seconds to finish all notifications (at 3 PM in prod). So we achieved >200x speedup in notification handling in this update.

**Comment by anthonypetersen** [comment]
rockstar!! @we-ai

**Comment by brotzmanmj** [comment]
Woo hoo! Thank you so much!
