### ISSUE TITLE
Add New Locations for UChicago & Marshfield

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#693]
Please add new Collection Locations (BioSpm_Location_v1r0 - CID: 951355211) and/or Shipping Locations (BioShip_LocalID_v1r0 - CID: 560975149) for UChicago & Marshfield. 

UChicago locations:
- _Orland Park_ (Collection and Shipping location)
- _UCM Pop-Up_ (Collection location ONLY)

Marshfield locations:
- _MF Pop-Up_ (Collection location ONLY)

The following areas need to be updated:
- CID creation and Data Dictionary labels update (Nicole's team)
- Biospecimen Dashboard Specimen Link Drop Down (Davin to assign)
- Biospecimen Dashboard Shipping Drop Down (Davin to assign)
- Biospecimen BPTL CSV (Abhinav)
- BSI (Kathleen) - This needs to be done when the CSV is complete and pushed to production
- Metrics format Code (Kelsey)

**Comment by brotzmanmj** [comment]
Abhinav created a document where he listed every step that needs to be done to add a new collection location. Would recommend the DevOps team refer to that for this issue.

**Comment by HopkinsDC** [comment]
Sanford, Henry Ford, and HealthPartners all confirm they have no plans for additional locations within the next 6 months.

**Comment by HopkinsDC** [comment]
@FrogGirl1123 New locations added to data dictionary change log: https://nih.app.box.com/file/1033495332436

**Comment by Gbarra9** [comment]
New Concept Ids assigned for

UChicago locations:
  "UCM Pop-Up": "319518299"
  "Orland Park": "940329442"

Marshfield locations:
  "MF Pop-Up": "567969985"

**Comment by HopkinsDC** [comment]
@Gbarra9 Per Stephanie, UChicago will need a third collection location, "Mobile Van". 

@FrogGirl1123 I have added this location to the data dictionary change log: https://nih.app.box.com/file/1033495332436

**Comment by abhinavjonnada82** [comment]
Are we still waiting on UC Mobile Van CID?

**Comment by brotzmanmj** [comment]
"UCM Pop-Up": "319518299" is the same thing as UC Mobile Van

**Comment by HopkinsDC** [comment]
@brotzmanmj "UCM Pop-Up" CID is ready to go, so should the "Mobile Van" be removed from the data dictionary change log?

**Comment by wyattks** [comment]
BSI has been updated for the added locations.

**Comment by brotzmanmj** [comment]
Hi, I see Dev - Stage sync noted above. Is this ready for testing in dev?

**Comment by Davinkjohnson** [comment]
Domonique to reach out to sites to test in Dev and stage.

**Comment by HopkinsDC** [comment]
UChicago completed testing for "UCM Pop-Up" and "Orland Park" in dev. Locations were correct in BPTL in-transit and receipts csv files.
<img width="1223" alt="Screen Shot 2023-09-27 at 8 59 59 AM" src="https://github.com/episphere/connect/assets/85250133/3fbdaeef-b1a0-41ee-b17b-3de430414235">
<img width="1223" alt="Screen Shot 2023-09-27 at 9 03 34 AM" src="https://github.com/episphere/connect/assets/85250133/af4e165b-880e-49cc-a3ba-1c79c868fd70">

**Comment by brotzmanmj** [comment]
Great. Can someone check behind the scenes in Firestore and make sure the CID for the new locations came through correctly?

**Comment by HopkinsDC** [comment]
Marshfield completed testing for "MF Pop-Up" and "Orland Park" in dev. Location was correct in BPTL in-transit and receipts csv files. 
![Picture1](https://github.com/episphere/connect/assets/85250133/e5037614-2983-4ea2-bc30-811303927f37)

**Ready for stage**

**Comment by brotzmanmj** [comment]
As soon as someone checks the data on the back end, we'll be ready for stage. Thanks everyone.

**Comment by Gbarra9** [comment]
I'll message back when I finish checking the CID site locations in Firestore.

**Comment by Gbarra9** [comment]
**Repeated Message Sent on MS Teams**

Firestore Backend Data Check - (DEV)

Data on Firestore appears to be correct.

One thing to confirm. Did UChicago select "Orland Park" via the collection process? I was unable to find a document for "Orland Park" in the biospecimen collection. However, a box had "Orland Park" as a site location selected in the shipping process in the boxes collection. 

From checking firestore, it appears UChicago selected "UCM- Pop-Up" as a collection location on the Biospecimen Dashboard and selected "Orland Park" as a site location for a Box (Box8) in the Shipping Dashboard.

Biospecimen's Document (1) - UCM

- Healthcare Provider (827220437) - University of Chicago Medicine (809703864)
- Collection Location (951355211) -  "UCM- Pop-Up" (319518299)
- Collection ID (820476880) - CXA000002

Biospecimen's Document (2) - Marshfield

- Healthcare Provider (827220437) - Marshfield Clinic Health System (303349821)
- Collection Location (951355211) -  "MF Pop-Up" (567969985)
- Collection ID (820476880) - CXA333444

Biospecimen's Document (3) - Marshfield

- Healthcare Provider (827220437) - Marshfield Clinic Health System (303349821)
- Collection Location (951355211) -  "MF Pop-Up" (567969985)
- Collection ID (820476880) - CXA333446

Boxes's Document (1) - UCM

- Location ID, site specific (560975149) - "Orland Park" (940329442)
- Login Site (809703864) -  University of Chicago Medicine (809703864)
- Box ID (132929440) - Box8

**Comment by Gbarra9** [comment]
> **Repeated Message Sent on MS Teams**
> 
> ### **[Firestore Backend Data Check - (DEV)]**
> Data on Firestore appears to be correct.
> 
> One thing to confirm. Did UChicago select "Orland Park" via the collection process? I was unable to find a document for "Orland Park" in the biospecimen collection. However, a box had "Orland Park" as a site location selected in the shipping process in the boxes collection.
> 
> From checking firestore, it appears UChicago selected "UCM- Pop-Up" as a collection location on the Biospecimen Dashboard and selected "Orland Park" as a site location for a Box (Box8) in the Shipping Dashboard.
> 
> Biospecimen's Document (1) - UCM
> 
> * Healthcare Provider (827220437) - University of Chicago Medicine (809703864)
> * Collection Location (951355211) -  "UCM- Pop-Up" (319518299)
> * Collection ID (820476880) - CXA000002
> 
> Biospecimen's Document (2) - Marshfield
> 
> * Healthcare Provider (827220437) - Marshfield Clinic Health System (303349821)
> * Collection Location (951355211) -  "MF Pop-Up" (567969985)
> * Collection ID (820476880) - CXA333444
> 
> Biospecimen's Document (3) - Marshfield
> 
> * Healthcare Provider (827220437) - Marshfield Clinic Health System (303349821)
> * Collection Location (951355211) -  "MF Pop-Up" (567969985)
> * Collection ID (820476880) - CXA333446
> 
> Boxes's Document (1) - UCM
> 
> * Location ID, site specific (560975149) - "Orland Park" (940329442)
> * Login Site (809703864) -  University of Chicago Medicine (809703864)
> * Box ID (132929440) - Box8

Note: UCM will make a "Orland Park" collection in stage testing. 
Ready to move dev updates for this issue to stage.

**Comment by HopkinsDC** [comment]
UChicago and Marshfield completed stage testing successfully. Locations were correct in BPTL in-transit and receipts csv files.

UChicago:
<img width="1170" alt="Stage-Specimen-Link-Page-UC" src="https://github.com/episphere/connect/assets/85250133/e583d5ed-46dd-468a-a06a-74dbeb97144e">
<img width="1170" alt="Stage-Shipping-Page-UC-1" src="https://github.com/episphere/connect/assets/85250133/d43ec20c-be47-4195-8a76-437768a7b885">


Marshfield:
![Screenshot 2023-09-28 at 2 07 48 PM](https://github.com/episphere/connect/assets/85250133/7cc92acf-2981-46c6-8c61-cdded8470a78)
![Screenshot 2023-09-28 at 2 08 00 PM](https://github.com/episphere/connect/assets/85250133/08de9f61-3756-4747-a497-eeb285d3538d)


@Gbarra9 Ready for Firestore check (and then prod).

**Comment by Gbarra9** [comment]
### Stage Testing Data Check

@HopkinsDC -->  Data checked and appears as expected. Stage updates ready for Prod.

-----
**UChicago***

Biospecimen's Document (1) 

- Healthcare Provider (827220437) - University of Chicago Medicine (809703864)

- Collection Location (951355211) -  Orland Park (940329442)

- Collection ID (820476880) - CXA000004

Boxes's Document (1) 

- Location ID, site specific (560975149) - Orland Park (940329442)

- Login Site (789843387) -  University of Chicago Medicine (809703864)

- Box ID (132929440) - Box20


----
**Marshfield***

Biospecimen's Document (1)
- Healthcare Provider (827220437) - Marshfield Clinic Health System (303349821)

- Collection Location (951355211) -  MF Pop-Up (567969985)

- Collection ID (820476880) - CXA111666

Boxes's Document (1) 

- Location ID, site specific (560975149) - Marshfield (940329442) 

- Login Site (789843387) -  Marshfield Clinic Health System (303349821) 

- Box ID (132929440) - Box20
