### ISSUE TITLE
Include notifications collection as table in BQ backup

### ISSUE THREAD

**Issue by jacobmpeters** [episphere/connect#695]
@FrogGirl1123 would like for the Analytics Team have access to the "notifications" collection as a new table in BigQuery so that we can better understand the notifications workflow and detect issues as they arise. I'm not sure if the "notificationSpecifications" collection would also be required for this purpose, so this will need some discussion. 

My understanding is that Nicole, @brotzmanmj and @Davinkjohnson discussed this in a recent meeting, so they might have more details.

Note that this is a separate issue from the _Notification Handler Overhaul_ #692 issue that @we-ai has been working on. We would like to use the "notifications" collection, rather than the "query.notificationSpecIdsUsed" object that has been added to the participants table to resolve that issue.

**Comment by we-ai** [comment]
I had a discussion with other leads in Dev team. Due to large volume of notifications data (125,393 documents in prod at 3pm on 8-25), we may consider backing up the whole data once per day.
In future, after we create pipelines to do more efficient (incremental) backups, we can do frequent backups.
Please provide suggestions. @jacobmpeters @brotzmanmj .

**Comment by jacobmpeters** [comment]
Thanks, Warren. I think it is likely sufficient to have less frequent backups for now so that we can do some initial QC/metrics while we discern the most efficient way to do this.

I will defer to @brotzmanmj though.

**Comment by we-ai** [comment]
After participant data destroy, notifications records in BQ may also need to be removed, as the case in [records in Firestore](https://github.com/episphere/connectFaas/pull/410).

**Comment by brotzmanmj** [comment]
@we-ai @jacobmpeters  I think the backup frequency is a decision for Nicole rather than me

**Comment by jacobmpeters** [comment]
The notifications table looks good in BQ2 in DEV, STG, and PROD. I'll close this issue now. Thank you!
