### ISSUE TITLE
Replace link for Certificates of Confidentiality in eConsent screens

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connect#696]
On screen four of eConsent (Your Privacy), edit the hyperlink on "Certificates of Confidentiality" to the updated page: https://grants.nih.gov/policy/humansubjects/coc.htm

old link: https://grants.nih.gov/policy/humansubjects/coc/what-is.htm

<img width="925" alt="Screenshot 2023-08-18 at 4 46 32 PM" src="https://github.com/episphere/connect/assets/74061787/28acbf3e-4c40-429e-a30c-e24e0c700db5">

**Comment by robertsamm** [comment]
Tested the [Certificate of Confidentiality](https://grants.nih.gov/policy/humansubjects/coc.htm) link in dev for Deanna. This link looks correct in dev.

I did notice that on the same eConsent screen the link for the [Privacy Act](https://www.justice.gov/archives/opcl/overview-privacy-act-1974-2015-edition) is outdated. It leads to the 2015 version not the [2020 version](https://www.justice.gov/opcl/overview-privacy-act-1974-2020-edition). However, what we have linked does provide a new link on that page to get to the most recent version. We should update this link next, but does not need to hold up this release. @Davinkjohnson should this be added as a new github issue?

![image](https://github.com/episphere/connect/assets/67074735/baf2667b-54e0-498c-b25c-7b0c9667e421)

**Comment by robertsamm** [comment]
@bransteitterbr confidentiality link in PWA tested in stage, looks good. Ready for prod.

**Comment by anthonypetersen** [comment]
Can this be closed now? @bransteitterbr

**Comment by anthonypetersen** [comment]
no response - closing
