### ISSUE TITLE
Error Caught via DataDog: Cannot read properties of undefined (reading '699625233')

### ISSUE THREAD

**Issue by anthonypetersen** [episphere/connect#698]
![image](https://github.com/episphere/connect/assets/18222069/86b89415-8c2c-477c-971c-45c835096a95)

**Comment by JoeArmani** [comment]
in the `renderSettingsPage()` if block:
•`hasUserData` is false.
•Then we check `userData[699623233]` in `buildPageTemplate()`, but `userData` is `undefined`.

Proposed solution: check `userData` for truthiness in the `buildPageTemplate` conditional.

**Comment by JoeArmani** [comment]
This will be moving to stage in the upcoming sync. It is not testable because it's an intermittent issue.

**Comment by JoeArmani** [comment]
This will be moving to prod in the upcoming sync. It is not testable because it's an intermittent issue.

**Comment by JoeArmani** [comment]
This is in production - closing.
