### ISSUE TITLE
My Profile Div Stacking Error

### ISSUE THREAD

**Issue by anthonypetersen** [episphere/connect#699]
Prior to user profile being complete, if you continue to go back a forth to and from the `My Profile` tab you get a stacking of divs saying the profile hasn't been completed. Each trip back to the tab adds one div, see below:

![image](https://github.com/episphere/connect/assets/18222069/760c58e3-2fa2-4ca2-b4e8-2bf6587b4dc7)

**Comment by JoeArmani** [comment]
`template` has global scope, so this div is being appended each time we navigate to the page. Proposed solution: `template = ''` at the beginning of `renderSettingsPage()` to reset `template` on each new render.

**Comment by JoeArmani** [comment]
This has been tested and approved in dev.

**Comment by JoeArmani** [comment]
This has been tested and approved in stage.

**Comment by JoeArmani** [comment]
This is in production - closing.
