### ISSUE TITLE
"What type of cancer did you have?" field accepts only 4 characters

### ISSUE THREAD

**Issue by aMaloneKPCO** [episphere/connect#70]
Using Chrome browser, after entering profile data, the "...Have you ever been diagnosed" question was answered as "yes".  The field used to describe the cancer, "What type of cancer did you have?", only accepts 4 characters.
![cancer diag description field bug](https://user-images.githubusercontent.com/42878488/76988085-d0631d00-6909-11ea-8fed-7ddb34640b3d.png)

**Comment by bhaumik55231** [comment]
Thank you @aMaloneKPCO for pointing this out. I have fixed the issue.
