### ISSUE TITLE
Error Caught in DataDog: Cannot read properties of undefined (reading 'sha')

### ISSUE THREAD

**Issue by anthonypetersen** [episphere/connect#703]
<img width="878" alt="image" src="https://github.com/episphere/connect/assets/18222069/cc3a20d2-53d8-470f-83ac-01e46e190779">

<img width="499" alt="image" src="https://github.com/episphere/connect/assets/18222069/d9f28c8f-3a94-4d1b-99eb-4739649b20d8">

**Comment by anthonypetersen** [comment]
This appears to be a surface level issue that occurs when a participant tries to continue with an SSN survey that they previously started. Because the SSN survey is not currently incorporated into our module submitting logic I'm proposing the following changes in a refactor:

* Enable SSN module to utilize existing logic for submitting module data
* Update SSN Firestore collection to utilize the same fields being used in other collections (i.e. sha, uid, Connect_ID)
* Split out the `submit()` function - currently this function is being used to submit data meant for the participant collection and data meant for module specific collections, it would be beneficial to have these features be contained in their own backend function.

**Comment by bransteitterbr** [comment]
Regarding the refactoring of submit I started it but was concerned that it introduced too much room for error at this point.

**Comment by bransteitterbr** [comment]
Tested in Dev and ready for stage push
