### ISSUE TITLE
Biospecimen/Shipping Performance Enhancements - Phase2

### ISSUE THREAD

**Issue by JoeArmani** [episphere/connect#708]
Focal points for this optimization stage will be BPTL functionality and API enhancements related to BPTL. There will be some crossover in shipping dashboard functionality.

This is a placeholder while we await a list of BPTL items that need improvement.

Related (Shipping): Shipment data not added to shipped box - https://github.com/episphere/connect/issues/625
Related (BPTL): Box manifests - slow loading - https://github.com/episphere/biospecimen/issues/548
Related (ConnectFaas API): Shipping dashboard - slow loading - https://github.com/episphere/connect/issues/619
Related (Shipping Dashboard + ConnectFaas API) - slow specimen search - https://github.com/episphere/connect/issues/650

Related (Completed, in production): Biospecimen/Shipping Performance Enhancements - Phase1 https://github.com/episphere/connect/issues/685

**Comment by JoeArmani** [comment]
Here's a detailed list of what has changed in this release:
*As of now (9/26), this is still under PR review. I'll update this message when everything is in dev and ready for testing.

**New box creation**
This is now handled server-side, so there shouldn’t be any issues with users creating boxes concurrently (both users should succeed and receive unique box IDs.
Box numbering is handled based on site (so all BoxIds are unique for the provider), and new box creation rules are based on the contents (empty or not empty) of the location's most recent box.

The following should be tested:
•New box number is accurate.
•Box creation is allowed when the location's most recent box has at least one item.
•Box creation is not allowed when the location's most recent box is empty.
•Two users trying to create a box simultaneously should now be successful and receive unique box IDs.

**Shipment finalization**
We’ve updated the shipment flow client-side and server-side. User experience should be mostly the same. The differences:
•Error handling and a more robust operation server-side are implemented. The user will receive an error message if there’s an issue. This will be difficult to test on your end.
•Please confirm boxes are found ‘in transit’ after being shipped.
•As soon as shipment success is registered from the server, the shipping dashboard will begin reloading while a success message is visible. Previously, the success message alert blocked reloading until it was clicked. 

**BPTL**
Packages in transit
We’ve updated how the app interacts with the server when fetching this data. It is a more direct method with significantly less data in transit. It should be faster and should continue to be performant as data scales.
•Please test & confirm the accuracy of data in the _in-transit box list and manifests_.

Create CSV files (In transit and Receipted CSV files):
Similarly, we’ve updated these operations to be significantly more direct in their approach.
•Please test & confirm accuracy of _‘in transit’_ and _‘receipted csv’_ files.


**Caveats to speed: Recency and authentication/authorization.**
Recency:
Recency impacts the cloud function speed on the server side. If a function hasn't been called in a while, it must be loaded in GCP and executed. This can make the first operation (such as a click on a manifest) slower. Then, the function stays in GCP memory for a time, and the operation is quicker. Google Cloud docs refer to this as 'warm' and 'cool' states.
Authentication/Authorization:
When the user sits idle for a while and then uses the dashboard, the authorization function takes several seconds to execute. The time to complete this auth function is anywhere from 300ms to 7.5s. This is intermittent, and we haven't had a chance to look into it yet.

**Comment by Davinkjohnson** [comment]
Kathleen and Domonique to test all above in Dev
Kathleen to reach out to sites to test creation and shipping components in stage

**Comment by wyattks** [comment]
**Dev Testing:**
**New box creation**
•New box number is accurate. - Works Fine
•Box creation is allowed when the location's most recent box has at least one item.  - Works Fine
•Box creation is not allowed when the location's most recent box is empty.  - Works Fine
•Two users trying to create a box simultaneously should now be successful and receive unique box IDs.  - Works Fine (I got 91 immediately and Domonique got 92 immediately)

**Shipment finalization**
•Please confirm boxes are found ‘in transit’ after being shipped.  - Works Fine

**BPTL
Packages in transit**
•Please test & confirm the accuracy of data in the in-transit box list and manifests.   - Works Fine

**Create CSV files (In transit and Receipted CSV files):**
•Please test & confirm accuracy of ‘in transit’ and ‘receipted csv’ files.   - Works Fine, all samples were present in both files immediately.

**Comment by JoeArmani** [comment]
Testing has been completed in stage. This is approved and ready for prod.

**Comment by JoeArmani** [comment]
This is in production. Closing.
