### ISSUE TITLE
Login Refresh for updating authentication data

### ISSUE THREAD

**Issue by bransteitterbr** [episphere/connect#709]
Firebase requires the session to be less than 5 minutes old to update authentication information such as login email or phone number.

Proposed update:  When the edit button is clicked to edit authentication information we present a login dialog and have the user re-authenticate at that time so it restarts the timer and in most cases the user should complete the task in the window allotted.

**Comment by sonyekere** [comment]
https://github.com/episphere/connectApp/tree/reauth-settings

**Comment by Davinkjohnson** [comment]
Jessica will resolve/finalize the code Brian started. Brian's branch is here. https://github.com/episphere/connectApp/tree/reauth-settings

**Comment by sonyekere** [comment]
Noting for visibility, Deanna will be leading the dev and stage testing.

**Comment by Gbarra9** [comment]
PR review status - Reviewing

-  [#709] Reauth settings

**Comment by Gbarra9** [comment]
PR review status - Approved

- https://github.com/episphere/connectApp/pull/667

**Comment by sonyekere** [comment]
Ready for Prod pending language update

**Comment by anthonypetersen** [comment]
Can this be closed?
