### ISSUE TITLE
Participants All Dashboard should have option to display IHCS STUDYID field

### ISSUE THREAD

**Issue by aMaloneKPCO** [episphere/connect#71]
https://episphere.github.io/dashboard/siteManagerDashboard/#participants/all

The StudyId field is an important method for the IHCS to identify data in the Connect app.

**Comment by bhaumik55231** [comment]
Hi, @aMaloneKPCO to see studyId and other sensitive data that we don't want the participant to read/update are store in a flag named **state**(please see screenshot below).

![image](https://user-images.githubusercontent.com/26577910/77020642-d2090100-695a-11ea-8125-906a4e25f1f1.png)

**Comment by danielruss** [comment]
@aMaloneKPCO Bhaumik answered the question.  If there is follow up feel free to re-open the question.
