### ISSUE TITLE
Change functionality of SSN Survey

### ISSUE THREAD

**Issue by cusackjm** [episphere/connect#712]
SSN survey stays open/available on dashboard until participant enters either a full or partial SSN

ADDED REQUIREMENTS FROM PREVIOUS ISSUE (https://github.com/episphere/connect/issues/514):

The existing variables for full SSN digits given (and date/time given) and partial SSN digits given (and date/time given) are currently being set when someone enters the SSN into quest, regardless of whether the module was submitted, and the variables do not change back to 'No' if the person backs out their data in quest. Change this to function such that those four variables are set only upon submitted status of the module.

**Comment by brotzmanmj** [comment]
Just to note, this issue has to remain on hold until we get IRB approval of the changes.

**Comment by brotzmanmj** [comment]
@anthonypetersen  The final clean version of the IRB approved SSN survey that we are scheduled to implement in January is here: https://nih.app.box.com/file/1348670927498

**Comment by Davinkjohnson** [comment]
Please also address this comment https://github.com/episphere/connect/issues/715#issuecomment-1785878192

**Comment by Davinkjohnson** [comment]
This is the latest, IRB approved doc. 
https://app.box.com/s/vgtla8c82pl3rj6feschs7ez0zzmmmpv

**Comment by Davinkjohnson** [comment]
survey placement logic should remain as-is (within to-do box and at the bottom of the list). Existing appearance on to-do list should remain the same (existing description text and continue button, etc.). 

Once participant starts the survey the started status/time should remain. 

Having the survey display as a multiple page form, in line with the surveys on the dashboard is OK. 

"hash" the entry so all 9, or 4, digits are not visible when entered.

Need to ensure the survey, once complete, shows up on the "completed" tab of the participant's dashboard. 

On submit/close the survey moves to completed tab, but the participant remains on the to-do tab.

**Comment by Gbarra9** [comment]
PR Review Status - Approved

**Comment by sonyekere** [comment]
Tested in Dev and ready for stage.
