### ISSUE TITLE
Reproduced CSC issue - no response available in SSN4d

### ISSUE THREAD

**Issue by cusackjm** [episphere/connect#713]
Replicated CS0013157 on 9/12/23 in Stage under ccctesting3@mailinator.com
Skipped the 1st question
Second question does not have a response entry:
![image](https://github.com/episphere/questionnaire/assets/85582895/2bb40452-9ca6-4e7b-842c-57da92254597)

@anthonypetersen is aware and going to reproduce/look into it later today

**Comment by anthonypetersen** [comment]
This should be resolved now
<img width="1452" alt="image" src="https://github.com/episphere/connect/assets/18222069/90bba4a8-9cb1-4863-89a0-dc852c0574bb">

**Comment by anthonypetersen** [comment]
One thing to note... Any participants this has already affected won't be able to continue the survey due to the other SSN bug we are working on at the moment.

**Comment by cusackjm** [comment]
Ok, I will wait to update the CSC issues until that is fixed
