### ISSUE TITLE
[ON HOLD] Add response checks to SSN survey - QUEST changes for 1/2024 prod push

### ISSUE THREAD

**Issue by cusackjm** [episphere/connect#714]
response checks are being added to the SSN Survey FOR JANUARY PROD PUSH: https://nih.app.box.com/file/772342375528?s=4ih3qinmaio8r4x5wt81doe32mncsv0n

1. Response Mis-match
- only applies to 2nd response entry (if 2nd response does not match 1st)
- Hard error pop up message, can't move on without changing response

Deanna is still reviewing error message jargon **I will update this issue when it is ready for programming**

**Comment by cusackjm** [comment]
Update: This will be ready once the IRB approves the changes and IMS has programmed https://github.com/episphere/questionnaire/issues/287

**Comment by Davinkjohnson** [comment]
This is tracked in a newer version of a tracked document on Box. closing as duplicate.
