### ISSUE TITLE
SSN - add QUEST invalid response checks 

### ISSUE THREAD

**Issue by cusackjm** [episphere/connect#715]
CURRENT ERROR MESSAGES (revisions to the error messages are in **bold**)
- HARD ERROR- RED LINE MESSAGE: “Please enter a **valid** Social Security Number in this format: 999-99-9999.” 
- SOFT ERROR- POP-UP MESSAGE: “There is 1 question unanswered on this page. Would you like to continue?” 

[SrvSS_SSN_v1r0] Invalid response checks (new response checks are in **bold**)
    1. Must be 9 digits. [HARD ERROR- RED LINE] 
   2. Must be numeric [HARD ERROR- RED LINE] 
   3. No-response [SOFT ERROR- POP UP] 
**4. Cannot start with 000, 666 or 900-999 [HARD ERROR- RED LINE]** 
**5. Cannot be 111111111, 333333333, 078-05-1120, 219-09-9999 [HARD ERROR- RED LINE]** 
**6. Middle digits cannot be 00 [HARD ERROR- RED LINE]** 
**7. Last digits cannot be 0000 [HARD ERROR- RED LINE]**

[SrvSS_SSN4d_v1r0] Invalid response checks (new response checks are in **bold**)
    1. Must be 4 digits. [HARD ERROR- RED LINE] 
   2. Must be numeric [HARD ERROR- RED LINE] 
   3. No-response [SOFT ERROR- POP UP] 
**4. Last digits cannot be 0000 [HARD ERROR- RED LINE]**

**Comment by danielruss** [comment]
@cusackjm  with the last push of quest SSN validation works (1->7).  I just update the SSNsm validation to avoid 0000.  Should push to prod in a few hours...

**Comment by brotzmanmj** [comment]
@danielruss  will they also be in Dev and Stage so Julie can test them?

**Comment by danielruss** [comment]
yes they are

**Comment by cusackjm** [comment]
@danielruss I was still able to enter 078-05-1120 and 219-09-9999 without seeing an error message

**Comment by danielruss** [comment]
updated quest validation to mark those two SSNs as invalid.  (you're making my code ugly!!)

**Comment by cusackjm** [comment]
it's still allowing those in dev :( @danielruss

**Comment by danielruss** [comment]
@cusackjm  are you using the myconnect app or the quest dev tool?

**Comment by cusackjm** [comment]
@danielruss myconnect app

**Comment by anthonypetersen** [comment]
just tested in dev 
<img width="887" alt="image" src="https://github.com/episphere/connect/assets/18222069/c4dd1d51-885f-4ab3-bb13-0aba3a7217d0">

**Comment by cusackjm** [comment]
![image](https://github.com/episphere/connect/assets/85582895/9a36f648-0ad5-4d07-b227-af12100e2770)
Can you insert "valid" before Social Security Number?

**Comment by Davinkjohnson** [comment]
This is all in the tracked version document on Box. Closing as a duplicate.
