### ISSUE TITLE
Update HFH My Samples page

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connect#716]
Tracked changes here: https://app.box.com/s/svun4hooetuqp3d179ou5tr26k4gkuaq

Addition of HFH Hospital as a clinical collection location (under Option 2).

**Comment by depietrodeanna** [comment]
Looks good in dev. Ready for stage @ramavavi

**Comment by robertsamm** [comment]
Kirsti at HFH tested in stage and confirmed this looks good. Ready for prod.

**Comment by anthonypetersen** [comment]
can this be closed?
