### ISSUE TITLE
Upgrade Node and other packages

### ISSUE THREAD

**Issue by we-ai** [episphere/connect#718]
Currently Node version 14 is running our backend services. 
With Node 14 maintenance ended on [4-30-2023](https://github.com/nodejs/release#release-schedule), and Node 16 maintenance ended on 9-11-2023, continue using these versions might have risks.
If we don't want to use the newest version, Node 18 might be good for us. It is maintained until 2025.

**Comment by anthonypetersen** [comment]
is there anything we need to do besides update the Node version being utilized for our Cloud Functions?

**Comment by abhinavjonnada82** [comment]
Highly suggest for Node & Firebase upgrade across our ecosystem.
https://github.com/episphere/connectFaas/pull/430#discussion_r1337661509

We could leverage new features in Firebase & Node for faster performance.

**Comment by jhflorey** [comment]
Approved PR https://github.com/episphere/connectFaas/pull/498
