### ISSUE TITLE
Gray buttons in profile page don't indicate selected option 

### ISSUE THREAD

**Issue by aMaloneKPCO** [episphere/connect#72]
The buttons for gender, phone type, and preferred method of contact, do not indicate which option was selected.    The testing team feels clearly showing the selected option will reduce confusion for the recruit.

**Comment by danielruss** [comment]
Thank you @aMaloneKPCO I'll check it out and add it to the list of Things to Do.....

**Comment by bhaumik55231** [comment]
Now the option selected shows with more contrast focus color.
