### ISSUE TITLE
Design and style fixes

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connect#722]
Note the design, style, and formatting changes defined in this document: https://nih.box.com/s/9fw5zwb5i8n90qg0afx5nuu914bk31mk

**Comment by depietrodeanna** [comment]
@anthonypetersen nope. Some of these suggestions may no longer be relevant but most could be incorporated when time permits.

**Comment by JoeArmani** [comment]
Reviewed and approved https://github.com/episphere/connectApp/pull/692 for the following changes:
•Survey icon under the Messages tab.
•Increased padding for the next button.
•Added the hover effect to the Previous button.

**Comment by ramavavi** [comment]
Tested in dev and Ready for stage.

**Comment by sonyekere** [comment]
Ready for Prod.

Minor change requested : the text on the yellow buttons (e.g. submit) looking like Times New Roman; however Times New Roman was not used.

**Comment by JoeArmani** [comment]
This has been given the green light despite minor changes requested - confirmed in teams chat.
Ready for prod.

**Comment by JoeArmani** [comment]
Closing. This is in production.
