### ISSUE TITLE
prod - Issue with first survey - health conditions under a sub-set type

### ISSUE THREAD

**Issue by dbakumar** [episphere/connect#724]
The below issue raised by one of the study participant. 

health conditions under a sub-set type:
When you answer that you have been told by a doctor that you have that condition...it then moves to a screen where you can choose either how old you were when you were diagnosed, or the year of the diagnosis.   at this point - no response to entering answer and hitting the next button. 

a) tried changing from selecting the year, to inputting my age instead - no luck. 
b) chose the back button and started again, no luck.  
c) cannot continue past the point where  stuck.

**Comment by Davinkjohnson** [comment]
stale
