### ISSUE TITLE
Magic Link Issue - Safari Can't Open the Page

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connect#725]
After clicking on the magic link in an email while using Safari, I received this error message

<img width="1435" alt="Screen Shot 2022-02-24 at 9 50 31 AM" src="https://user-images.githubusercontent.com/83971268/155547505-e0827bc6-628f-495d-b3e4-2021aaee4329.png">

I tried the same process using Safari on my personal phone and laptop and NCI tablet and it worked as it should on those other devices.  I also tried with a yahoo mail and an outlook test account and the issue occurred in the same way.

@depietrodeanna has been able to replicate this issue.

**Comment by Davinkjohnson** [comment]
implemented new magic linkz
