### ISSUE TITLE
Phone number log in issue - loop when responding to 'not a robot' questions

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connect#726]
HP participant tried logging in using a phone number.  After entering the verification code and completing the "not a robot" questions, they were looped back to the initial screen to enter their phone number.

They eventually received a message that they had attempted to log in with that phone number too many times.

Participant was using Safari on her phone and then tried using an incognito chrome window on an HP iPad

**Comment by cusackjm** [comment]
@cunnaneaq is this still an issue?

**Comment by cunnaneaq** [comment]
Just tested in Safari on my iPhone in stage and worked well
