### ISSUE TITLE
about connect not displaying well in mobile

### ISSUE THREAD

**Issue by jonasalmeida** [episphere/connect#727]
The subpages of myconnect, such as https://myconnect.cancer.gov/#about, don't respond to form factor. The parent page, https://myconnect.cancer.gov, is fine.

![Screen Shot 2022-09-30 at 9 30 35 AM](https://user-images.githubusercontent.com/204769/193281348-059351bf-3f6c-4329-9313-c4cee7225948.png)

**Comment by robertsamm** [comment]
Tested on dev on iPhone and and Android phones and looks good. Pictures, links, and content all look good. Ready for stage.

**Comment by robertsamm** [comment]
@ramavavi syndicated content tested in stage, looks good. Ready for prod.

**Comment by anthonypetersen** [comment]
can this be closed?
