### ISSUE TITLE
Home mouthwash collection survey

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#737]
Requirements for the baseline home mouthwash collection survey: 

The baseline home mouthwash collection survey will trigger upon a baseline home mouthwash collection kit being sent to a participant. The variables for this will be Kit Status changing to 'shipped', for Kit Type = Mouthwash and timepoint = Baseline. @abhinavjonnada82 will update this with the variables when the Concept IDs are available.

The survey will appear on the To Do list @depietrodeanna please provide information on where it should appear on the ToDo list (I'm thinking at the top of the list?) and what the description should say. We will add the estimated time after testing.

The survey has been programmed but needs to be tested.

The variables to store the flag, time started and time submitted for the home mouthwash survey are in the data dictionary.

**Comment by depietrodeanna** [comment]
Placement of survey on dashboard: at top of the To Do list

Description on dashboard:
Title: At-Home Mouthwash Sample Survey
Questions about your oral health and hygiene practices. 
_Estimated time:_TBD based on testing, use placeholder

**Comment by cusackjm** [comment]
Mouthwash delivery https://nih.app.box.com/folder/211732448362

**Comment by anthonypetersen** [comment]
survey ready to be pushed to dev

**Comment by cusackjm** [comment]
Mock survey passed Dev testing

**Comment by jhflorey** [comment]
Approved https://github.com/episphere/connectApp/pull/665

**Comment by sonyekere** [comment]
Noting for visibility. Kathleen/Julie/Hana/Deanna will be leading Dev and Stage testing.

**Comment by sonyekere** [comment]
IMS is working on error, to follow up w/ Julie.

**Comment by anthonypetersen** [comment]
Can this be closed?
