### ISSUE TITLE
Add New Variable to the Rules JSON

### ISSUE THREAD

**Issue by mnataraj92** [episphere/connect#739]
CID 811353546 for "Letter Variant" needs to be added to the rules JSON so it can be updated by the API. 

711757828 | 0 = Control X
943427992 | 1 = Variant A
648219696 | 2 = Variant B
798915634 | 3 = Variant C
896010519 | 4 = Variant D

**Comment by JoeArmani** [comment]
These "Letter Variant" variables are included in a ConnectFaas PR under review.

**Comment by brotzmanmj** [comment]
@mnataraj92  When Joe indicates this is in dev, please send an email to one site (HP or MF would be a good option) to ask them to test this for us in dev, and to be prepared to test is in stage (we're aiming for 10/27 or 10/30 for stage test). They will need to send 5 people, each with one of the response codes to make sure they all work. We don't need a formal test plan. Just ask them to tell you which Connect ID they send with each response code so our team can check the data on the back end. Thanks.

**Comment by mnataraj92** [comment]
sounds good!

**Comment by JoeArmani** [comment]
@mnataraj92 This is now in dev and ready for your next steps. Thanks!

**Comment by mnataraj92** [comment]
Just emailed Marshfield to help test this!

**Comment by JoeArmani** [comment]
Passed testing in dev, ready for stage.

**Comment by JoeArmani** [comment]
Passed testing in stage, ready for prod.

**Comment by JoeArmani** [comment]
Closing - this is in production.v
