### ISSUE TITLE
NULL field select allowed for "What is your preferred method of contact?" 

### ISSUE THREAD

**Issue by aMaloneKPCO** [episphere/connect#74]
In the Profile Page, I was allowed to choose a "... preferred method of contact?" that did not exist.  The profile contained one email and one phone number.  My selection was "Phone 2" which did not exist.

**Comment by Davinkjohnson** [comment]
@cusackjm to test

**Comment by danielruss** [comment]
@cusackjm  I was not expecting this question.  The user profile is in a javascript function: 
https://github.com/episphere/connectApp/blob/master/js/components/form.js#L24
preferred email/phone is:
https://github.com/episphere/connectApp/blob/master/js/components/form.js#L203

**Comment by cusackjm** [comment]
This is not a function in the pwa anymore
