### ISSUE TITLE
NORC incentives for Chicago participants with Research Collections

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#740]
We would like to make the option of NORC incentives available to Chicago participants. 

-Change derivation of 'NORC Incentive Eligible' at baseline to remove the exclusion of Chicago participants. 
-Ask NORC to change the time of their daily API call to a time outside of business hours, like 3am

For their own internal tracking, Chicago will add a 'deferred' option to ERMS payments but will not send those data to us.

For explanation: The NORC Incentive Eligible API looks for verified participants that are marked as NORC incentive eligible, haven't refused payment, and haven't received payment.

**Comment by ramavavi** [comment]
Approved the PR's.

**Comment by JoeArmani** [comment]
reviewing...

**Comment by Gbarra9** [comment]
Moved to Dev with PR's 
- https://github.com/episphere/connectFaas/pull/439
- https://github.com/episphere/biospecimen/pull/599

This will need another PR for NORC API test where previous incentive eligible test participant was not found.

**Comment by Gbarra9** [comment]
Created an issue in response to NORC not being able to get one of the two University of Chicago participants from the Get Participants Eligible for Incentive API Endpoint. Added PR that is currently under team review.

New Issue: 
- https://github.com/episphere/connect/issues/806

New PR
- https://github.com/episphere/connectFaas/pull/449

**Comment by Gbarra9** [comment]
In response to the email screenshot below. Current code changes in October release in stage can be moved to production.
<img width="1221" alt="Screenshot 2023-11-01 at 3 52 04 PM" src="https://github.com/episphere/connect/assets/33293205/c41c1364-e733-4e02-b4f5-c34cc185991a">

The interim items are referenced below:

> Created an issue in response to NORC not being able to get one of the two University of Chicago participants from the Get Participants Eligible for Incentive API Endpoint. Added PR that is currently under team review.
> 
> New Issue:
> 
> * [NORC unable to pull University of Chicago Incentive Eligible Participants #806](https://github.com/episphere/connect/issues/806)
> 
> New PR
> 
> * [Add University of Chicago Incentive Eligible Participants to appear for NORC connectFaas#449](https://github.com/episphere/connectFaas/pull/449)

**Comment by Gbarra9** [comment]
PR Merged to Dev and ready for NORC to retest participants eligible for incentive API endpoint
- https://github.com/episphere/connectFaas/pull/449

**Comment by Gbarra9** [comment]
NORC restested:
https://github.com/episphere/connect/issues/806#issuecomment-1800827494

I am in the process of merging changes to stage.

**Comment by Gbarra9** [comment]
Cherry PickPR  merged to stage
- https://github.com/episphere/connectFaas/pull/454

NORC restesting in stage
