### ISSUE TITLE
Add Collection Location to Available Collections List on Packaging screen (biospecimen) (September release) 

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#741]
In the list for available collections on the packaging screen, add a column showing the Collection Location for the bag.  This request is mainly for the research sites that have many collection locations and shipping locations.

For research sites, use the locations selected at the time of Specimen Link
For clinical sites, use the overall site. 

[Collection Loction to Available list.pptx](https://github.com/episphere/connect/files/12729596/Collection.Loction.to.Available.list.pptx)

**Comment by wyattks** [comment]
Alternate idea was to add a filter for selecting the collection location and only showing the available collections for that selected location in the available collections box.  Would also have an "All" choice to show all collections across the site.  We felt it would be easier to add in a column for the Collection location instead of adding in a filter.

**Comment by wyattks** [comment]
August or September Release?

**Comment by erincschwartz** [comment]
Upon further discussion, we would like to move forward with adding the filter vs adding a column with collection location.

**Comment by amber-emmes** [comment]
Just to be clear, what are the concept ID flags which I would be looking for on these specimens in each case, and are the options to be made available in the collection location list the same as in "Choose your shipping location" or taken from somewhere else? If so, what would the list of collection locations be expected to be? Thanks!

**Comment by erincschwartz** [comment]
@amber-emmes As we just discussed, it makes more sense to add the Collection Location column (vs. adding a drop down). For Research collections, the collection locations are selected by site team members on the Specimen Link page. Any collections that are from the Clinical Collection setting, should have a collection location of "Clinical"

**Comment by amber-emmes** [comment]
Merged into dev and ready for review.

**Comment by wyattks** [comment]
Checked in Dev. Ready for Stage

**Comment by amber-emmes** [comment]
Please re-review this and test the box shipping process to ensure there are no issues. The previous fix to this introduced an issue in the shipping workflow which should now be resolved.

**Comment by wyattks** [comment]
Hi Amber,  I tested a couple of scenarios on this.  I was able to add a bag to a box but if I remove that bag from the box and try to add that same bag back into a box, I am unable to do so unless I go back to the home screen and then back into the shipping dashboard.  

Also after removing a bag, sometimes the number of collections listed in the avaiable collections feild is reduced even when I haven't added those bags to a box.

**Comment by amber-emmes** [comment]
Looking into this, but while I do that, can you confirm whether or not this issue also exists in stage? It doesn't sound immediately related to my changes, so it seems worth double-checking if this is an existing issue.

**Comment by wyattks** [comment]
I'm not able to check this in the Stage environment.  Most who can are traveling home today.

**Comment by erincschwartz** [comment]
I am in Stage on my HP computer. I can add a bag to a box, remove it and then add it back again. This issue does not seem to exist in Stage.

**Comment by amber-emmes** [comment]
A new implementation of this has been released to dev. Please re-test and confirm the box shipping process is working as expected now.

**Comment by wyattks** [comment]
This is functioning as xpected now.  Ready for Stage

**Comment by erincschwartz** [comment]
Tested in Stage, ready for Prod. 

New addition of Collection Location looks as expected. I added 2 new collections (1 at each HP site) and the locations showed up as correctly in the Available Collections box of the Shipping page. 

Added, then removed a bag from the box. Was able to add it back without any issue.
