### ISSUE TITLE
Increase Specimen Bag ID Max Per Box

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#746]
Currently, up to 15 specimen bag IDs can be assigned to a single box in the shipping dashboard. This is an issue for sites conducting research collections and using larger shippers.

Please increase the max number of specimen bag IDs that can be assigned to a single box.

@wyattks to provide the new max number per allowable box when she returns next week (10/2).

**Comment by JoeArmani** [comment]
Initial notes:

After a quick review, we'll need to do the following:
(1) Determine new capacity. A good guideline capacity is slightly above the max number of bags the site can fit in a single large shipping box. That's the best balance between removing limitations for the shipper and ensuring max efficiency in the shipping dashboard.
(2) Generate new bag conceptIds.
(3) Update implementations:
-3 places in ConnectFaas.
-2 places in Biospecimen.
(4) We might consider notifying the user when capacity is reached, or implementing a counter that shows current bag count and capacity.
(5) It would also make sense to disallow adding bags when the box is at capacity and notify the user in the shipping dashboard. That would eliminate confusing situations like the one Erin @ HP dealt with yesterday.

Current bag concept ID list:
```javascript
bagContainerCids: {
        bag1: 650224161,
        bag2: 136341211,
        bag3: 503046679,
        bag4: 313341808,
        bag5: 668816010,
        bag6: 754614551,
        bag7: 174264982,
        bag8: 550020510,
        bag9: 673090642,
        bag10: 492881559,
        bag11: 536728814,
        bag12: 309413330,
        bag13: 357218702,
        bag14: 945294744,
        bag15: 741697447,
},
```

**Comment by wyattks** [comment]
Please go to 40 bags.

**Comment by JoeArmani** [comment]
This PR is under review. The system accepts max 40 bags. It starts warning the user about bag capacity at 37 bags, then disallows the add operation if the user attempts to add bag 41.

Screenshots: 37 bags - 41 bags

add bag 37
<img width="983" alt="Screenshot 2023-10-24 at 10 40 48 AM" src="https://github.com/episphere/connect/assets/93854858/41be744d-0d12-46d9-bbaf-1b65c78dbe10">
add bag 38
<img width="419" alt="Screenshot 2023-10-24 at 10 41 27 AM" src="https://github.com/episphere/connect/assets/93854858/aed2492f-fb9b-45c4-bccb-50a154cd3168">
add bag 39
<img width="415" alt="Screenshot 2023-10-24 at 10 41 50 AM" src="https://github.com/episphere/connect/assets/93854858/680b230b-fe7c-4595-a34f-dff4298b04d5">
add bag 40
<img width="428" alt="Screenshot 2023-10-24 at 10 42 18 AM" src="https://github.com/episphere/connect/assets/93854858/56e33763-026b-43b2-8e62-7721fe976825">
add bag 41 (not allowed)
<img width="417" alt="Screenshot 2023-10-24 at 10 43 20 AM" src="https://github.com/episphere/connect/assets/93854858/89085e77-0444-426d-a9f5-d45539be1cf1">

**Comment by JoeArmani** [comment]
This is live in dev and ready for testing.

**Comment by JoeArmani** [comment]
This is tested in dev and ready for stage.

**Comment by JoeArmani** [comment]
Closing - this is in production.
