### ISSUE TITLE
Home mouthwash- SMDB updates

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#747]
For home mouthwash collections we need to make these updates to the SMDB. 

On the Participant Summary page:

1) Update the existing row for Baseline/Survey/Home Mouthwash to reflect the actual variables:
Mouthwash survey flag CID 547363263 (not started, started, submitted)
'Date' should show either Home mouthwash survey time started CID 286191859 or Home mouthwash survey time submitted CID 195145666, depending on the mouthwash survey flag

2) Check the existing row for Baseline/Sample/Mouthwash to also capture the home collection mouthwash. It should be based on the derived variable BioFin_BaseMouthCol_v1r0 CID 684635302 which should update to 'yes' when the home mouthwash tube is received and entered by BPTL. The 'Date' in that row should update to the derived variable BioFin_BMTimeBL_v1r0 CID 448660695 (derived variable that will now include the date collected from the collection card). And the 'Setting' BioSpm_MWSettingBL_v1r0 CID 915179629 should update to 'Home' (103209024).

3) The metrics on the home page should update in two places: Metric in the upper right corner Number and percentage of 'Verified Participants who Completed Baseline Survey and Samples' needs to take into account the home mouthwash collection. And in the bottom right corner, metric on Baseline biospecimens collected among verified participants' needs to take into account the home mouthwash collections.

**Comment by robertsamm** [comment]
For the Baseline/Sample/Mouthwash row on the participant summary page, please also add the variable 'Kit Status' (BioKit_KitStatus_v1r0) under 'Extra'.

**Comment by Davinkjohnson** [comment]
Need to meet with Michelle Kelsey and Amelia to define requirements for the percentage metric: 
Metric in the upper right corner Number and percentage of 'Verified Participants who Completed Baseline Survey and Samples' needs to take into account the home mouthwash collection.

**Comment by brotzmanmj** [comment]
In the issue description at the top, clarified which variables need to appear on the Participant Summary page to include the home collection.

Clarified by email the requirements for the metric at the top right corner of the home screen should be changed to the definition of 'complete' that we use in the Weekly Log (verified, all survey modules 1-4 submitted, any blood collected). Coordinate with Kelsey to make sure your code matches.

The requirements for the Biospecimens metric at the bottom left corner, update to include the home collections. If you have already updated the derived variables, this should capture the home collections too.

**Comment by sonyekere** [comment]
Noting for visibility, Amelia and Kathleen will be leading the dev and stage testing.

**Comment by we-ai** [comment]
Just want to double check with @brotzmanmj , since Kelsey and I have different opinions on 'completion' count in top right card in home page. To get the count, should participants be filtered based on 4 completed baseline surveys and blood collection only (this is count requested in metrics report), or based on 4 completed baseline surveys as well as blood, urine and mouthwash collections (this is count we currently have in card)?

**Comment by brotzmanmj** [comment]
4 completed baseline surveys and blood collection only

**Comment by we-ai** [comment]
Tentative text changes:
- In card description: "Verified Participants who Completed Baseline Surveys and Blood Samples" (old text: "Verified Participants who Completed Baseline Survey and Samples"). 
- Hover text: "All 4 Initial Survey Sections + Blood Collection" (old text: "All 4 Initial Survey Sections + All 3 Specimen Collections").

Any suggestions on changed text?

**Comment by brotzmanmj** [comment]
Small change to card description:  "Verified Participants who Completed Baseline Survey and Blood Sample"
Hover text sounds good, thanks

**Comment by jhflorey** [comment]
Approved - https://github.com/episphere/dashboard/pull/580

**Comment by brotzmanmj** [comment]
Tested in dev. Ready for stage.

**Comment by anthonypetersen** [comment]
Can this be closed?
