### ISSUE TITLE
SMDB errors caught in DataDog

### ISSUE THREAD

**Issue by we-ai** [episphere/connect#748]
<img width="494" alt="image" src="https://github.com/episphere/connect/assets/47251797/223318f3-47fb-487c-be00-9e72082de4d5">

**Comment by anthonypetersen** [comment]
Decision was made to postpone this PR until next release since Warren was OOO leading up to review cycle

**Comment by Gbarra9** [comment]
PR Review Status - Approved

**Comment by jhflorey** [comment]
Left 1 comment on PR

**Comment by jhflorey** [comment]
PR Review Status - Approved

**Comment by anthonypetersen** [comment]
reviewed & approved

**Comment by we-ai** [comment]
<img width="972" alt="image" src="https://github.com/episphere/connect/assets/47251797/b1922560-cc33-4800-bdb7-06b4d67687a4">

**Comment by we-ai** [comment]
<img width="971" alt="image" src="https://github.com/episphere/connect/assets/47251797/eb5ef516-4382-428d-838c-118391dc2ff2">

**Comment by jhflorey** [comment]
Approved - https://github.com/episphere/dashboard/pull/581

**Comment by sonyekere** [comment]
Ready for Prod

**Comment by we-ai** [comment]
Recent error:
<img width="784" alt="image" src="https://github.com/episphere/connect/assets/47251797/eb62927a-4f6f-4031-bd15-ff5a97cbc2e2">

**Comment by we-ai** [comment]
<img width="852" alt="image" src="https://github.com/episphere/connect/assets/47251797/2bb79d66-6289-40d8-8eea-a070ef6f2e09">

**Comment by anthonypetersen** [comment]
@we-ai can this be closed? if new SMDB errors pop-up in DataDog that we want to fix we can always open a new Issue.

**Comment by we-ai** [comment]
> @we-ai can this be closed? if new SMDB errors pop-up in DataDog that we want to fix we can always open a new Issue.

This can be closed. 
There're very few SMDB errors reported in DataDog. They can can be easily fixed.
