### ISSUE TITLE
PWA consent name issue

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/connect#753]
Recently a participant encountered an error where they could only enter 2 characters of their last name on the consent form. We'd like to ensure this isn't a broader issue.

**Comment by brotzmanmj** [comment]
We have a second instance of this reported today. Both so far are from KPNW.

**Comment by robertsamm** [comment]
Hi @Davinkjohnson has your team been able to look into this more? I am also going to respond to the email thread with KPNW and see if they have had any more instances of this happening besides the first 2

**Comment by anthonypetersen** [comment]
Queried our database and there only seem to be a few instances of this possibly occurring across the entire study. I'm not sure if this is a potential issue between the device and our front end code, but we really don't have much to go off of on our end.

**Comment by Davinkjohnson** [comment]
We've also been performing testing in Dev for our various code updates and have not seen this issue occur in our testing.
