### ISSUE TITLE
Slow loading time for Reports (Biospecimen)

### ISSUE THREAD

**Issue by JoeArmani** [episphere/connect#755]
I'm taking this issue from the slow manifest issue where it was initially reported.

**Previous Conversation:**

From @wyattks:
@JoeArmani Not sure if this instance of slowness is connect to the above report, but Chicago is experiencing slowness when trying to view the manifest from the Shipping Report.

From @JoeArmani:
@wyattks Thank you for documenting this.

We have not looked into the 'reports' section yet, so I will mark it for exploration this coming week. I just took a cursory look - some of the same data-handling methods we found in the first shipping dashboard update (and in the current BTPL update) are also used in the reports section.

These can be adapted as we optimize specimen and box handling (the target of the upcoming dev cycle). So, improvement is almost a certainty, I'm just not sure of the time to complete it since I haven't been able to take a deep dive into how this section of the app is constructed yet.

**Comment by Gbarra9** [comment]
PR Review Status - Approved
- https://github.com/episphere/connectFaas/pull/538
- https://github.com/episphere/biospecimen/pull/663

**Comment by wyattks** [comment]
Reports are running smoothly in Dev.  Ready for Stage.

**Comment by wyattks** [comment]
Running smoothly.  Ready for Prod.

**Comment by JoeArmani** [comment]
Closing - in production.
