### ISSUE TITLE
Biospecimen/Shipping Performance Enhancements – Phase3

### ISSUE THREAD

**Issue by JoeArmani** [episphere/connect#756]
### This update will tie together previous improvements to ensure the shipping dashboard's data handling methods are scalable as the Connect study grows.

**Items covered:**

**Specimen Bag IDs – increase max capacity:**
Related: https://github.com/episphere/connect/issues/746
The current implementation allows for 15 bags. New, larger shipping boxes have been introduced. We’re raising the implementation’s capacity to 40 bags to accommodate the new larger boxes.
Updates to BSD & ConnectFaas are required for implementation.

**Shipping dashboard data initialization:**
Related: https://github.com/episphere/connect/issues/619 & https://github.com/episphere/connect/issues/650
Cloud function to update specimens: https://github.com/episphere/connect/issues/764
Some of this groundwork has been laid in previous updates, but the heavy lifting will be done here.
Boxes – fetch unshipped boxes only.
Specimens – direct fetching and organization of unboxed, stray, and boxed but unshipped specimens.
This is highly detailed due to specimen handling intricacies around the ‘add to box’ and ‘remove bag’ operations.
These updates will result in fetching a small fraction of the data currently being fetched, so loading and refresh times will be greatly reduced.
Updates to BSD & ConnectFaas are required for implementation.

**Reports section:**
Update: ConnectFaas functions are implemented. BSD (frontend) updates are pushed to the next release.
Related: https://github.com/episphere/connect/issues/755
We’ve received feedback about slowness in the ‘reports’ section of the app. Initial discovery leads us to believe data optimization is required (similar to issues with manifests).
Updates to BSD & ConnectFaas are required for implementation.

**Other related items (in production):**
Biospecimen/Shipping Performance Enhancements – Phase2: https://github.com/episphere/connect/issues/708
Biospecimen/Shipping Performance Enhancements – Phase1: https://github.com/episphere/connect/issues/685

**Comment by Gbarra9** [comment]
PR Review Status - under review

**Comment by Davinkjohnson** [comment]
@jhflorey will review this

**Comment by jhflorey** [comment]
Already reviewed and approved PR https://github.com/episphere/biospecimen/pull/602

**Comment by Gbarra9** [comment]
PR Review Status - Approved

**Comment by JoeArmani** [comment]
This is live in dev and ready for testing.

**Comment by JoeArmani** [comment]
This is approved in stage and ready for prod.

**Comment by JoeArmani** [comment]
Closing - this is in production.
