### ISSUE TITLE
Update UC My Samples page for Oct release

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connect#757]
Changes tracked here: https://app.box.com/s/mkipmbpsdz36hgrjuk8iev564gkpr2v0
Addition of Orland Park location, removal of days/hours for all locations

**Comment by ramavavi** [comment]
The link for the PR is https://github.com/episphere/connectApp/pull/656

**Comment by Gbarra9** [comment]
PR reviewed - suggested changes

**Comment by ramavavi** [comment]
I am almost done with the changes, just trying to commit. Thanks

**Comment by Gbarra9** [comment]
PR reviewed - approved

**Comment by anthonypetersen** [comment]
reviewing

**Comment by depietrodeanna** [comment]
@ramavavi reviewed dev and looks good. ready for stage.

**Comment by ramavavi** [comment]
reviewed dev and looks good. ready for stage.

**Comment by anthonypetersen** [comment]
can this be closed?

**Comment by ramavavi** [comment]
Yes Tony, I will close the issue.
