### ISSUE TITLE
 "Other" option in 'How you heard about use' Section needs free form text field

### ISSUE THREAD

**Issue by aMaloneKPCO** [episphere/connect#76]
The "How did you hear about this study" section needs a free form text field to for the "Other" option that prompts the user to describe how they heard about the study.

**Comment by brotzmanmj** [comment]
Hi Allen, We considered this request. We have a good range of actionable responses for  “How did you hear about this study?” and don’t think we will get enough additional information from adding “specify” to merit the effort it would take to clean the open ended data. Our preference is to examine how often “other” is selected and then determine if it’s frequent enough that we need to add a “specify”.

**Comment by Davinkjohnson** [comment]
Determined we do not need this functionality at this time.
