### ISSUE TITLE
Remove Sentry Logic

### ISSUE THREAD

**Issue by anthonypetersen** [episphere/connect#760]
Now that we have started using DataDog to collect information about runtime sessions on the client-side, we no longer need to initialize our Sentry instance in the PWA.

We need to remove the block of code that initializes Sentry.

**Comment by JoeArmani** [comment]
reviewed - approved

**Comment by anthonypetersen** [comment]
tested and confirmed in dev

**Comment by anthonypetersen** [comment]
tested and confirmed in stage - ready for prod
