### ISSUE TITLE
Update SMDB age metric on homepage

### ISSUE THREAD

**Issue by robertsamm** [episphere/connect#762]
With the age expansion updates, will also need to update the 'Age of Verified Participants' pie chart that displays on the home page of the SMDB with the 3 new responses for 30-34, 35-39, 66-70.

The CIDs are still being generated. @mnataraj92 can you update this issue with the CIDs once they are done?
![image](https://github.com/episphere/connect/assets/67074735/cde6e643-da2f-43c4-8368-b407153c69fd)

**Comment by mnataraj92** [comment]
These are the CIDs for the new age ranges:

"30-34": "713781738",
"35-39": "631272782",
"66-70": "722846087",
