### ISSUE TITLE
Specimens in 'biospecimen' collection need 'boxedStatus' and 'strayTubeArray' properties for optimized shipping dashboard data management system

### ISSUE THREAD

**Issue by JoeArmani** [episphere/connect#764]
Specimens need 'boxedStatus' and 'strayTubeArray' properties to optimize data pulled on initial load and refresh in the shipping dashboard.

Need cloud function to:
(1) Pull all box and specimen data for each site.
(2) Compare specimens in boxes vs unboxed specimens and identify stray tubes (Note: do not include discard deviations in calculation).
(3) Label each specimen doc with boxedStatus (771580890) and strayTubesList (742186726).

Available boxed status options:
notBoxed (657483796)
partiallyBoxed (775512390)
boxed (210720511)

**Comment by JoeArmani** [comment]
GitHub Gist for review (this is a one-off cloud function, not going in a repo): https://gist.github.com/JoeArmani/74b1a76091bd2abbe66e0a8f801d6063

**Log output (successful dev run):**
All boxes data fetched for site: 452412599
All biospecimen data fetched for site: 452412599
discard flag (skip):  CXA002710 0012
specimenDifferences [ 'CXA002704 0004' ]
Committed batch starting from index 0 to 500
All boxes data fetched for site: 531629870
All biospecimen data fetched for site: 531629870
discard flag (skip):  CXA013298 0001
Committed batch starting from index 0 to 500
All boxes data fetched for site: 657167265
All biospecimen data fetched for site: 657167265
Committed batch starting from index 0 to 500
All boxes data fetched for site: 548392715
All biospecimen data fetched for site: 548392715
Committed batch starting from index 0 to 500
All boxes data fetched for site: 303349821
All biospecimen data fetched for site: 303349821
Committed batch starting from index 0 to 500
All boxes data fetched for site: 125001209
All biospecimen data fetched for site: 125001209
specimenDifferences [ 'CXA002665 0004' ]
Committed batch starting from index 0 to 500
All boxes data fetched for site: 809703864
All biospecimen data fetched for site: 809703864
Committed batch starting from index 0 to 500
All boxes data fetched for site: 13
All biospecimen data fetched for site: 13
discard flag (skip):  CXA441336 0050
discard flag (skip):  CXA357951 0001
discard flag (skip):  CXA000789 0003
discard flag (skip):  CXA166177 0005
discard flag (skip):  CXA112233 0001
discard flag (skip):  CXA050500 0006
discard flag (skip):  CXA151510 0005
discard flag (skip):  CXA114477 0003
discard flag (skip):  CXA114477 0006
discard flag (skip):  CXA800789 0001
discard flag (skip):  CXA557844 0003
discard flag (skip):  CXA557844 0006
specimenDifferences [ 'CXA441336 0054', 'CXA441336 0051', 'CXA441336 0053' ]
specimenDifferences [ 'CXA123424 0005' ]
specimenDifferences [ 'CXA050519 0054' ]
specimenDifferences [ 'CXA444444 0005' ]
specimenDifferences [ 'CXA333222 0024' ]
specimenDifferences [ 'CXA741368 0002', 'CXA741368 0006' ]
specimenDifferences [ 'CXA959595 0006' ]
specimenDifferences [ 'CXA112233 0050', 'CXA112233 0002' ]
specimenDifferences [ 'CXA900600 0050', 'CXA900600 0051' ]
Committed batch starting from index 0 to 500
All boxes data fetched for site: 300267574
All biospecimen data fetched for site: 300267574
discard flag (skip):  CXA002728 0012
Committed batch starting from index 0 to 500
All boxes data fetched for site: 327912200
All biospecimen data fetched for site: 327912200
discard flag (skip):  CXA002726 0012
Committed batch starting from index 0 to 500
finished running updateSpecimenBoxedProperty()
updateSpecimenBoxedProperty: 4.415s

**Comment by Davinkjohnson** [comment]
@jhflorey and @abhinavjonnada82  will review this

**Comment by jhflorey** [comment]
the syntax looks good to me. the minor i would like to suggest is the jsdoc of function buildQuery (line 292).

**Comment by JoeArmani** [comment]
Updated per Abhinav and Jessica, ready for leads review.

**Comment by anthonypetersen** [comment]
reviewing...

**Comment by JoeArmani** [comment]
This is ready for stage. I'll run it when dev -> stage sync is executed to update the biospecimen docs with the needed properties.

**Comment by JoeArmani** [comment]
This is ready for prod. I'll run it at the same time the prod push is built.

**Comment by JoeArmani** [comment]
Closing - this is in production.
