### ISSUE TITLE
Move data from SendGrid to Firestore

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/connect#766]
We would like to have certain data in SendGrid get shared back to Firestore (either Webhook or API is fine). The data for the first integration should be the following.

For Each Message:
- Who the message was sent to (ideally, Connect_ID or token, but email could suffice)
- What is the status of the message (delivered, not delivered, etc.)
- Click through status (did they click on any link we may have sent and navigate to our site?)
- Any error code or non-delivery message (incorrect email, marked as spam, etc.)

**Comment by jhflorey** [comment]
the event will be send from sendgrid https://docs.sendgrid.com/for-developers/tracking-events/event

**Comment by jhflorey** [comment]
@Davinkjohnson @depietrodeanna @brotzmanmj  Feel free to let me know your thoughts.

**Comment by Davinkjohnson** [comment]
@jhflorey Deanna and Hana agreed that we should remove the items under "notification" (so "body", "time", and "title"). These are kept in the notifications collection in Firestore and would therefore be duplicates if kept in this new table. 

Otherwise, this looks great!

**Comment by brotzmanmj** [comment]
This looks great. I'm curious what is the definition of 'processed date'?

**Comment by Davinkjohnson** [comment]
> This looks great. I'm curious what is the definition of 'processed date, processed status, and processed timestamp', as opposed to 'delivered' and 'opened'?

@brotzmanmj SendGrid's definition is below. basically, it's the time they successfully received our API call to send a the message. 
_"Message has been received and is ready to be delivered."_

**Comment by brotzmanmj** [comment]
got it, thank you!

**Comment by Gbarra9** [comment]
PR Review status - Approved

**Comment by sonyekere** [comment]
Noting for visibility. If needed, Hana will be leading Dev and stage testing.

**Comment by JoeArmani** [comment]
reviewing

**Comment by FrogGirl1123** [comment]
Is this data also being pushed to BQ?  If so, what table (Participants or New)?  If so, should Kelsey be checking BQ during he Stage testing?

**Comment by brotzmanmj** [comment]
Just a heads up that the Ops team isn't involved in any testing for this. To my thinking, it would be good for Kelsey to be able to check BQ if that is possible.

**Comment by jhflorey** [comment]
@brotzmanmj @FrogGirl1123 the data is stored collection `sendgrdiTracking` in firestore. I guess the data do not exist in BQ yet.
