### ISSUE TITLE
Site listed as undefined on manifest

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#769]
BPTL has received some manifests where the site is listed as undefined.  I have attached an example.

[Manifest example no site defined.pdf](https://github.com/episphere/connect/files/13025086/Manifest.example.no.site.defined.pdf)

**Comment by JoeArmani** [comment]
This update is in a Biospecimen PR under review.

**Comment by JoeArmani** [comment]
This is live in dev and ready for testing.

**Comment by JoeArmani** [comment]
This update is in the October release, moving to prod 11/1. It was only visible in prod. Continue monitoring.
Note: the update uses the logged-in user's authenticated site as a fallback. If this issue persists, consider making a call to the 'siteDetails' doc to get siteAcronym.
