### ISSUE TITLE
"Cancer Diagnoses" response should be required.

### ISSUE THREAD

**Issue by JAusiello** [episphere/connect#77]
The Cancer diagnoses question should be a required field since it is an important piece of information for enrollment.

**Comment by brotzmanmj** [comment]
Agreed. The cancer diagnosis lead question has been updated to a required field on the user profile criteria document (pg 5): https://nih.app.box.com/file/501193852134

**Comment by Davinkjohnson** [comment]
Davin to follow up with testers on this. (is it required now)

**Comment by Davinkjohnson** [comment]
@cusackjm next time you create a participant for testing can you please see whether the cancer diagnoses question on the User Profile is **required**?

**Comment by cusackjm** [comment]
@Davinkjohnson its required in stage 
![image](https://user-images.githubusercontent.com/85582895/191297883-d4091fcc-00e4-4088-8faa-9d62eaa3d4cd.png)
