### ISSUE TITLE
Give Health Partners Clinical Dashboard Access in Stage Environment

### ISSUE THREAD

**Issue by Gbarra9** [episphere/connect#770]
Health Partners(HP) currently has access to the Research and Clinical dashboard in the dev environment. We need to give HP access to the Clinical Dashboard in stage environment. 

Related Issue:
- https://github.com/episphere/connect/issues/796

**Comment by ramavavi** [comment]
Reviewed and approved.

**Comment by JoeArmani** [comment]
reviewing...

**Comment by Gbarra9** [comment]
[Biospecimen PR#601](https://github.com/episphere/biospecimen/pull/601) - Merged to Dev
- This does NOT need to be tested in dev since the changes made were for stage environment
- Awaiting dev to stage sync to have this tested in stage

**Comment by Gbarra9** [comment]
Ready for Stage Testing

**Comment by Davinkjohnson** [comment]
Davin to talk with @JoeArmani  @Gbarra9  @anthonypetersen  about timing for the prod launch

**Comment by Gbarra9** [comment]
Code for stage access was merged in prod environment. I am going to close this issue and make another issue called "Give Health Partners Clinical Dashboard Access in Stage Environment"
