### ISSUE TITLE
[Feature] Add home collection to BPTL dashboard

### ISSUE THREAD

**Issue by abhinavjonnada82** [episphere/connect#771]
Description:
Allow the user to perform assemble & assign kits for home collection process.

MVP:
- [x] Integrate designs provided in reference document 
- [x] Add newly created CIDs & update APIs accordingly
- [x] Introduce two pane window UI into the dashboard
- [x] Integrate QC check into forms

Reference:
[UI design](https://github.com/episphere/connect/files/13047801/HomeMouthwashUI_Wireframe.pptx)

CIDs: https://nih.app.box.com/file/1306274192476?sb=/activity

**Comment by Davinkjohnson** [comment]
@brotzmanmj @wyattks Please provide the requirements (filter and sort order) for participants to receive these kits.

**Comment by Davinkjohnson** [comment]
Kathleen and Madhuri meeting tomorrow to review/finalize CIDs for home collections.

**Comment by wyattks** [comment]
Hi @abhinavjonnada82 

Criteria for generating the kit list is located here: https://nih.app.box.com/file/1338886830047

**Comment by brotzmanmj** [comment]
@abhinavjonnada82  I added one thing to the Criteria for generating the kit list that Kathleen linked above, to exclude people who are deceased. Thanks.

**Comment by Gbarra9** [comment]
PR Review Status - Currently reviewing for both #609 and #448

**Comment by Davinkjohnson** [comment]
@jhflorey to review

**Comment by jhflorey** [comment]
Already left some minor comments for both PR and Approved.

**Comment by jhflorey** [comment]
Approved for both PRs

**Comment by Gbarra9** [comment]
PR Review Status - Approved for both https://github.com/episphere/connect/issues/609 and https://github.com/episphere/connect/issues/448

**Comment by anthonypetersen** [comment]
reviewing Part 1

**Comment by anthonypetersen** [comment]
@abhinavjonnada82 please link Part 2 PRs to this issue

**Comment by anthonypetersen** [comment]
reviewed & suggested changes for Biospecimen Part 2

**Comment by JoeArmani** [comment]
reviewing #453 shortly

**Comment by sonyekere** [comment]
Home collection testing in dev occurred Thursday Nov 9th. Biospecimen team created a kit and put it all the way through all the steps of the process. Dev testing found fixes.

**-Update Error Messages on BPTL page** i.e. The user did not receive an error message that the kit receipt did not go through.

**-Error on Print Label Page** i.e. Counter error when printing the number assigned

**-Update to error on Print Label Page** i.e. Add "No labels to Print" 

**-Error on Kit Shipment Page**  i.e. Tracking number is not being displayed when entered in the "Scan barcode"

**-Update QC Items** i.e. Unique check for Supply ID, Kit ID, Collection ID

**-Add** on  i.e Make the Kit Assembly to have a requirement that the user has to select a mouthwash on Kit assembly page before continuing 

Kathleen and Domonique will be be leading testing scenarios in dev and stage.

**Comment by jhflorey** [comment]
Approved and left a minor comment on https://github.com/episphere/connectFaas/pull/463

**Comment by jhflorey** [comment]
Approved on https://github.com/episphere/biospecimen/pull/621

**Comment by Gbarra9** [comment]
PR review status - Approved

- https://github.com/episphere/connectFaas/pull/466
- https://github.com/episphere/biospecimen/pull/622

**Comment by jhflorey** [comment]
Approved: https://github.com/episphere/connectFaas/pull/467

**Comment by sonyekere** [comment]
Pending final check in Dev for all fixes. Once DevOps gets go from Ops, please move all changes to stage. @abhinavjonnada82 @brotzmanmj

**Comment by wyattks** [comment]
Pushed to Prod 12/4/23
