### ISSUE TITLE
Contact Information Form Needs Disclaimer.

### ISSUE THREAD

**Issue by ghost** [episphere/connect#79]
The Kaiser NW IRB recommends the Contact Information Form have a disclaimer explaining the recruit's identify needs to be verified before they are officially enrolled in the study.

**Comment by brotzmanmj** [comment]
Language has been added to the user profile criteria document on Box, in the introduction text on page 2
https://nih.app.box.com/file/501193852134

**Comment by brotzmanmj** [comment]
Accidentally closed issue. Issue is still open.

**Comment by Davinkjohnson** [comment]
@cusackjm Can you also check this one next time you're creating test participants?

**Comment by cusackjm** [comment]
![image](https://user-images.githubusercontent.com/85582895/191300256-0bc550c4-6339-4f1c-ad9f-9a73e6b60af0.png)
@Davinkjohnson is this what they are referring to? I'm otherwise unsure what I should be looking for

**Comment by Davinkjohnson** [comment]
I think we'll need some input from @brotzmanmj or Deanna as to whether this captures what's needed, but it looks like (unless the disclaimer is on a different page) that we either don't need this anymore or it wasn't added.

**Comment by sonyekere** [comment]
Closing issue. The account owner of issue no longer exist. Last update 9/21/22
