### ISSUE TITLE
Back button from participant details to all participants page

### ISSUE THREAD

**Issue by robertsamm** [episphere/connect#790]
When I go to the all 'participants page' > select a participant > select 'participant details' > then click 'back to search', it only shows me that one participant's details on the screen. If I click 'back to search' a second time it takes me to the participant search screen. I feel like the back button in this instance should go back to the 'all participants' page as that was the last page I visited before selecting the participant details page.

**Comment by sonyekere** [comment]
@robertsamm Should this be revisited or can we close issue?

**Comment by Davinkjohnson** [comment]
stale
