### ISSUE TITLE
Update "EDTA = K2" on csv files to "EDTA" (Biospecimen)

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#791]
BSI had an update and the code for "EDTA = K2" has been changed to "EDTA"
Please change this in the Receipt csv file.
I have updated the mapping file to reflect this change.
https://nih.app.box.com/file/1306346523951

**Comment by JoeArmani** [comment]
From @wyattks:
"BPTL brought an issue with the mapping in the receipt csv file to our attention late yesterday.  For KPGA and KPGA the urine tube had a vial type of 15ml Nalgene jar and not 10ml Vacutainer (this is the correct type)."

-TODO: add this to the list of receipted csv updates.

**Comment by wyattks** [comment]
Urine tube type should be the 10ml Vacutainer.  I corrected it in the file as well.

**Comment by sonyekere** [comment]
Noting for visibility. Kathleen will be leading dev and stage testing.

**Comment by JoeArmani** [comment]
PR ready for review: https://github.com/episphere/biospecimen/pull/620

**Comment by Gbarra9** [comment]
PR Review Status - Approved
- https://github.com/episphere/biospecimen/pull/620

**Comment by JoeArmani** [comment]
Approvals: Gene, Warren, Jessica - thank you.

Merged to dev, ready for testing.

**Comment by wyattks** [comment]
Testing complete.  Ready for Stage

**Comment by JoeArmani** [comment]
This is tested in stage, ready for prod.
