### ISSUE TITLE
Update Box Manifest Site Contact Information (Biospecimen)

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#794]
Update the contact information on the box manifest for all sites.

1. Replace "Full Name:..." with the site name plus "Connect Study Team" (i.e., KPNW Connect Study Team, HealthPartners Connect Study Team, Marshfield Connect Study Team, etc.).

2. Update the email address for each site to the following:
- KPNW = CHR_Connect_KPNW_Bio@kpchr.org
- KPCO = Connect-Study-KPCO@kp.org
- KPHI = ConnectBioKPHI@KaiserPermanente.onmicrosoft.com
- KPGA = KPGAConnectBio@kp.org
- HealthPartners = communityresearchdepartment@healthpartners.com
- UChicago = connectbiospecimen@bsd.uchicago.edu
- Sanford = connectstudy@sanfordhealth.org
- Henry Ford = ConnectBioHFH@hfhs.org
- Marshfield = connectstudy@marshfieldresearch.org

3. Remove the contact phone number for all sites; a phone number will no longer be listed on the box manifest.

**Comment by Gbarra9** [comment]
### Screenshots Box Manifest's Site Contact Information Section

Note: The other sites will have their respective contact information

**Reports Page (Shipping Report Tab)**

![Screenshot 2023-11-07 at 8 17 28 PM](https://github.com/episphere/biospecimen/assets/33293205/fbdee768-a656-49c9-b0c7-f2084e17cdd0)
![Screenshot 2023-11-07 at 8 17 50 PM](https://github.com/episphere/biospecimen/assets/33293205/4ac160d0-d56a-4808-8dc4-d0249ecc821a)

**Shipping Dashboard (Box Manifest Tab)**

![Screenshot 2023-11-07 at 8 44 16 PM](https://github.com/episphere/biospecimen/assets/33293205/49ae7d2c-a416-43ac-a96e-f254c3f674f0)
![Screenshot 2023-11-07 at 8 44 28 PM](https://github.com/episphere/biospecimen/assets/33293205/29c0fe19-80ab-4e94-bc61-8b7f66ecfa3a)


**Shipping Dashboard (Review Shipping Contents Tab)**

![Screenshot 2023-11-07 at 8 39 30 PM](https://github.com/episphere/biospecimen/assets/33293205/be1797ca-12db-4585-9297-7399d660a4b2)
![Screenshot 2023-11-07 at 8 40 14 PM](https://github.com/episphere/biospecimen/assets/33293205/2d905229-16eb-4316-a6e8-857a4f974bd9)

**Comment by Gbarra9** [comment]
Made PR and is awaiting team review

- https://github.com/episphere/biospecimen/pull/613

**Comment by jhflorey** [comment]
Approved https://github.com/episphere/biospecimen/pull/613

**Comment by sonyekere** [comment]
Noting for visibility, Domonique will be leading dev and stage testing.

**Comment by Gbarra9** [comment]
Merged to dev and ready for testing.
- https://github.com/episphere/biospecimen/pull/613

**Comment by HopkinsDC** [comment]
Changes successfully made in dev. Ready for stage.

**Comment by sonyekere** [comment]
Check in stage 11/28 - Domonique to follow up w/ MF.
