### ISSUE TITLE
Update Collection ID Search for Streck Tubes

### ISSUE THREAD

**Issue by JoeArmani** [episphere/connect#799]
Biospecimen Collection ID search needs null handling for streck tubes (existing data does not have this data point).

**Comment by JoeArmani** [comment]
PR here: https://github.com/episphere/biospecimen/pull/607

**Comment by anthonypetersen** [comment]
approved

**Comment by JoeArmani** [comment]
merged and ready for testing

**Comment by JoeArmani** [comment]
Tested and approved in dev, ready for stage.

**Comment by JoeArmani** [comment]
Approved in stage, ready for prod.

**Comment by JoeArmani** [comment]
Closing - this is in production.
