### ISSUE TITLE
API playground

### ISSUE THREAD

**Issue by jonasalmeida** [episphere/connect#8]
Multiple sites report difficulty in trying the API because of lack of a swagger-like environment.   The existence of a temporary key mechanism makes this very easy for us to address. Maybe the [new developments in Postman](https://sites.google.com/mathbiol.org/cloud4bio/2019/2019-06-05-jun#h.p_jLszD-rqnmBL) will allow us to not have to go all the way to swagger. In any case, this is now the main topic of the one-on-one meetings.

**Comment by theEIC** [comment]
Is the point of contention that the Sites have to _install_ Postman to try out our APIs? This seems like a valid concern from their point of view. From the Postman documentation, it seems like there is an option to import existing Postman schemas and convert them to a different spec. We should be able to convert the existing collection to swagger without too much trouble in that case, which I feel we should.

**Comment by danielruss** [comment]
@bhaumik55231 is this still an issue?  ok to close?
