### ISSUE TITLE
Recommend "Preferred Contact" information be a required.

### ISSUE THREAD

**Issue by ghost** [episphere/connect#80]
This information is important for consistent communication with the participant.  We feel the participant should select a contact method that does have a number or address in it.  Also, if the recruit enters a 3rd phone number, "Preferred Contact" does not provide a Phone 3 option.

**Comment by brotzmanmj** [comment]
The participant is required to enter either a mailing address and either an email or a mobile number.

'Preferred contact' will be a choice of any one of the emails or mobile numbers they provided. 

We would rather not require 'preferred contact' as a hard edit. We are trying to limit the number of required fields that prevent the participant from submitting the form. If the participant does not select a specific email or text as preferred, we can utilize any email or text as needed or can defer to their sign in email or mobile for communications. Participants will have the ability to update their preferred mode of contact in the PWA at any time.

**Comment by aMaloneKPCO** [comment]
There are a couple of components to this issue:  i) having a the preferred contact field as required;  ii) selecting a preferred contact that has a NULL value.   Our main concern is the second,   selecting a preferred contact that is NULL.

**Comment by FrogGirl1123** [comment]
The user profile will eventually rendered in the participant app through the Quest app that is being used for the questionnaire.  So some of the components as currently in the participant app my not be fully functional.  The options to be selected as a preferred contact will be populated from the contact information collected above, so if I have understood part 2 correctly, there should not be a problem of being able to select a NULL.

**Comment by aMaloneKPCO** [comment]
Sorry @FrogGirl1123.  I am not following the logic for why this is not an issue and that is OK.  Your perspective of the Connect app is definitely more informed than mine.  If you feel it's not an issue, I trust your judgement.

**Comment by danielruss** [comment]
We look at the user profile as a questionnaire. So we plan on moving the user profile into our questionnaire app (called quest).  We will address the logic (preventing no response or null values) within the user profile questionnaire.  The current user profile is just a place holder until the user profile questionnaire is available.

Did I make anything clearer?

**Comment by aMaloneKPCO** [comment]
Yes.  Thank you, Daniel.

**Comment by sonyekere** [comment]
Closing Issue. Last update 4/3/2020
