### ISSUE TITLE
Potential race condition in BPTL package receipt

### ISSUE THREAD

**Issue by JoeArmani** [episphere/connect#800]
We found a potential race condition in BPTL's existing package receipt function when testing the new bags and streck tube in the shipping dashboard.

Screenshot attached: The error is generic and intermittent.

Need to:
(1) Fix the async operations that get executed on the backend (ensure they happen sequentially instead of at the same time).
(2) Support status updates on tubes 0050-0054.

![Package Receipt error](https://github.com/episphere/connect/assets/93854858/0a518b64-8b46-4a12-bfc2-b928ba0fd465)

**Comment by JoeArmani** [comment]
1st approval: Brian - thank you.

**Comment by JoeArmani** [comment]
2nd approval: Gene - thank you.

**Comment by anthonypetersen** [comment]
reviewed & approved

**Comment by JoeArmani** [comment]
Additional approval: Warren - thank you.

This is merged to dev and ready for testing.

**Comment by JoeArmani** [comment]
This is tested in dev and ready for stage.

**Comment by JoeArmani** [comment]
Tested and approved in stage, ready for prod.

**Comment by JoeArmani** [comment]
Closing - this is in production.
