### ISSUE TITLE
QR code use - GCP Analytics

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/connect#807]
Please use these links to find the different codes in use.

https://app.box.com/s/a0xy5kac45uvm2ccpe4kjuq0diz1967e
https://app.box.com/s/j6nqpd4gn8aqr4c7y92is1oqvagde3zw

Once the distinct codes are determined, please look at our Prod GCP analytics environment to assess whether we can see if people are using these unique links. 

If the links are being used, we'd like to establish metrics/frequencies to determine how users in different geographic locations are engaging with the communications materials. (ex: How often are UChicago participants scanning the "static" materials vs KPGA participants?)

**Comment by brotzmanmj** [comment]
Can we add Hana to this issue?

**Comment by Davinkjohnson** [comment]
I couldn't see her in this repo. I'll work with her to get her added to the repo and then assigned.

**Comment by jhflorey** [comment]
Hello @brotzmanmj @depietrodeanna @Davinkjohnson after doing some research I found some interesting things. Please see that link https://nih.app.box.com/file/1354928566974 if you get a chance. Please let me know what you think.

**Comment by jhflorey** [comment]
Hi @brotzmanmj @depietrodeanna @Davinkjohnson , please let me know your thought after reading my docs. Thanks

**Comment by brotzmanmj** [comment]
@Davinkjohnson can you add Hana Shin to this item? She is best positioned to review this and provide feedback along with Deanna. Thanks.

**Comment by sonyekere** [comment]
Noting for visibility. Hana/Deanna will be leading dev and stage testing.

**Comment by jhflorey** [comment]
QR_static-passive-recruitment.eps
	- https://nih.app.box.com/file/1079375556202
	- https://myconnect.cancer.gov/?cid=qr_en_static
 
QR_takeaway-passive-recruitment.eps
	- https://nih.app.box.com/file/1079381019168
	- https://myconnect.cancer.gov/?cid=qr_en_takeawa
 
QR_snowball-recruiment.eps
	- https://nih.app.box.com/file/1079380452852
	- https://myconnect.cancer.gov/?cid=qr_en_snowball
 
QR_post-enrollment.eps
	- https://nih.app.box.com/file/1079376262745
	- https://myconnect.cancer.gov/?cid=qr_en_postenrollment

**Comment by sonyekere** [comment]
For visibility purposes. Jessica demonstrated walk through of QR code data via Google Analytics. Deanna and Hana are pending Google Analytics access for self-serve demo. Once access is provided and demo completed, issue can then be closed.
