### ISSUE TITLE
Identify Verification Dashboard "Not Yet Verified" should display cancer question.

### ISSUE THREAD

**Issue by JAusiello** [episphere/connect#81]
The Identify Verification screen for the list of "Not Yet Verified" recruits should display the Cancer Question in it's default view.  That information is important for the verification decision.

**Comment by brotzmanmj** [comment]
The user will have the ability to select any or all of the fields from the Contact Information Form to display in the dashboard. My suggestion would be to leave this to each user to set and save their preferences for their dashboard. 
Please note that the a 'Yes' answer to the cancer history question will not exclude someone from eligibility in the study. The EMR is considered the gold standard for cancer history for the purposes of eligibility determination.
We are not aware of any sites that are using self-reported cancer history as a means of identity verification (i.e. that the person signing up for the study is the person in the IHCS records). If this is so, please describe how you intend to use this variable in your site's Identity Verification SOP.

**Comment by aMaloneKPCO** [comment]
Kaiser is not using self-reported cancer data for our cohort eligibility.  However, we consider this information supplementary.  I will mention that to the Kaiser Recruitment team that the cancer question should not be considered in the manual verification process.  Feel free to close this issue.
