### ISSUE TITLE
Old Collections Listed in BPTL Received CSV File (Biospecimen)

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#811]
BPTL reported that tubes from 3 collections (CXA004636, CXA012919, and CXA012888) showed up on the 11/2 Received CSV file, but the tubes had already been received on 9/30. Images of CSV files from both dates are included below.

**9/30 CSV File**

![Image](https://github.com/episphere/connect/assets/85250133/d1e92854-0cc4-43ff-b011-9bf7bc14eaf8)

**11/2 CSV File**

![Image](https://github.com/episphere/connect/assets/85250133/0b965153-4ef5-45a2-854d-5929ec8aaf06)

**Comment by Davinkjohnson** [comment]
Believe this may be an issue with the FedEx numbers used (used incorrect/old labels) and that this was a process issue. 

Biospecimen team to investigate the process that occurred to create this issue. 

Create issue to ensure FedEx numbers cannot get reused in shipping and cannot be receipted twice.

**Comment by StephanieWeinstein** [comment]
all set.  closing
