### ISSUE TITLE
Update HP My Samples page

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connect#814]
HP My Samples page has updated to include self-scheduling info as well as hybrid infrastructure. Significant changes tracked here: https://app.box.com/s/2j1lxrrjtprstsshf0nzmlq7x4x0u23s
Clean copy for ease of programming: https://app.box.com/s/3po427g40hcw095qi6szfs4idji7ptn9

**Comment by Gbarra9** [comment]
PR Review Status - Reviewing right now

**Comment by Gbarra9** [comment]
PR Review Status - Reviewed and requested changes

**Comment by jhflorey** [comment]
Approved on https://github.com/episphere/connectApp/pull/666

**Comment by Gbarra9** [comment]
PR Review Status - Approved
- https://github.com/episphere/connectApp/pull/666

**Comment by ramavavi** [comment]
Dev testing done, looks good. Ready for stage.

**Comment by ramavavi** [comment]
Ready for Prod.
