### ISSUE TITLE
Scanner issue or Dashboard issue?

### ISSUE THREAD

**Issue by michelleodelberg** [episphere/connect#815]
Hello, 
 When attempting to scan the Collection ID into the dashboard from the labels, I continually get this error: 
![image](https://github.com/episphere/connect/assets/127787755/15c393c6-f1e5-4a47-babe-2f6d8dfe6dfb)
![image](https://github.com/episphere/connect/assets/127787755/20806e97-d4a6-4052-920c-b36cd1d9b84f)

I am able to get by typing in the IDs by hand, thankfully, so this has not completely halted the workflow .

I attempted this with multiple collection ID stickers and receive the same error. Our site has two scanners, so I tried it with the other one and did not get this error, so it may just be an issue with this scanner. However, I want to rule out any issues with the dashboard. Thank you for your time!

-Michelle O, KPCO team

**Comment by wyattks** [comment]
Hi @michelleodelberg 
please try canning the labels into a word document using the scanner that was causing issues yesterday.  Trying to see if it is a scanner issue.  Thanks!

**Comment by wyattks** [comment]
Hi @michelleodelberg I am closing this issue as it has been posted on Gitter.  In the future please add issues like this to Gitter: https://app.gitter.im/#/room/#episphere_Connect-AlphaTest-Private:gitter.im
