### ISSUE TITLE
sync kitAssembly collection with BigQuery

### ISSUE THREAD

**Issue by jacobmpeters** [episphere/connect#818]
There is a new `kitAssembly` collection in DEV in Firestore associated with the home mouthwash kits.

Please add this collection to the scheduled data transfer from Firestore to BigQuery so that it appears as a table in BigQuery.

**Comment by Gbarra9** [comment]
PR Review Status: Approved, left comments

**Comment by we-ai** [comment]
`kitAssembly` in dev was synced to BQ with success.

**Comment by jacobmpeters** [comment]
Great! Thanks, @we-ai. I'll work on flattening it and let you know if any issues arise on my end.
