### ISSUE TITLE
Streck tube data null in Firestore (intermittent) (Biospecimen) 

### ISSUE THREAD

**Issue by JoeArmani** [episphere/connect#820]
We have an intermittent issue with Streck tube data (the placeholder data that's added on collection creation) being null in Firestore. This leads to an issue where Biospecimen is expecting the data, throws an error, and users cannot save/finalize collections. Two sites have experienced this issue, two times each.

I haven't been able to reproduce this issue in dev.
I can reproduce the error when I go into Firestore dev and delete the streck tube data.

Fixes:
(1) Sanity check data in Biospecimen and add the missing placeholder data to unfinalized collections when needed.
(2) Make sure the Biospecimen 'save collection' process can handle the data.
(2) Sanity check the data in ConnectFaas and add the missing placeholder data when needed.
In combination, these two should eliminate the bugs we're seeing with users being unable to save data in prod.

**Comment by jhflorey** [comment]
Approved and left comment on https://github.com/episphere/biospecimen/pull/619

**Comment by jhflorey** [comment]
Approved and left a minor comment on https://github.com/episphere/connectFaas/pull/462

**Comment by JoeArmani** [comment]
Merged to dev, ready for testing: https://github.com/episphere/biospecimen/pull/619
Merged to dev, ready for testing: https://github.com/episphere/connectFaas/pull/462

**Comment by sonyekere** [comment]
Check in stage is occurring - Kathleen to follow up 11/28

**Comment by wyattks** [comment]
pushed to prod 12/4/23
