### ISSUE TITLE
Death Data received from Sites

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/connect#823]
Placeholder for the addition of death data to the updateParticipantAPI
Planned for December release
Should already have CIDs for this?

- Create two variables and get CIDs
- Add them to the API so they can be received
- ~~Exclude them from the birthday card ppts to NORC~~ (We determined that these will NOT be excluded in our API call. It's up to NORC to remove these on their side.)
- Test receipt from the sites

**Comment by mnataraj92** [comment]
857217152	EMR participant deceased			HdWd_EMRPartDec_v1r0
				
772354119	EMR participant deceased date/time	HdWd_EMRPartDecTm_v1r0

**Comment by JoeArmani** [comment]
Confirming these are top-level (not nested) variables in the participant profile.

**Comment by brotzmanmj** [comment]
@FrogGirl1123 upon receipt of these two variables from the sites, are we also updating the existing flag for deceased that NORC populates from the SMDB? Concept ID 987563196 HdWd_Deceased_v1r0

**Comment by brotzmanmj** [comment]
Hi @FrogGirl1123 do we have a decision on the above? The existing flag is what we use to exclude deceased participants from receiving study communications. I believe Davin mentioned that we should update that flag to include data sent from the sites so we won't need to proliferate another flag into the messaging specs. Do you agree?

**Comment by brotzmanmj** [comment]
@JoeArmani  please note this one additional requirement.
Nicole and I discussed and agree on adding this requirement: The existing flag for deceased (the one that NORC currently writes to from the SDMB interface which is CID 987563196, HdWd_Deceased_v1r0) should be updated to the CID for yes '353358909' when a site pushes us a '353358909' (yes) CID for their new variable indicated death based on EMR (variable 857217152).

**Comment by JoeArmani** [comment]
> @JoeArmani please note this one additional requirement. Nicole and I discussed and agree on adding this requirement: The existing flag for deceased (the one that NORC currently writes to from the SDMB interface which is CID 987563196, HdWd_Deceased_v1r0) should be updated to the CID for yes '353358909' when a site pushes us a '353358909' (yes) CID for their new variable indicated death based on EMR (variable 857217152).

Hi @brotzmanmj @FrogGirl1123, confirming 987563196: 353358909 when 857217152: 353358909. Thanks for the update.

**Comment by Gbarra9** [comment]
PR Review Status - Approved, left minor comments

**Comment by mnataraj92** [comment]
Thanks @JoeArmani! I'll reach out to the sites today.

**Comment by JoeArmani** [comment]
Thanks @mnataraj92! Here are some notes:

Two new variables have been added to the updateParticipantData API:
857217152: participant deceased
772354119 participant deceased ISO 8601 timestamp

Note for testing: when the two above variables are confirmed, 987563196 NORC participant deceased is also derived to ‘yes’.

Testing:
(1) If the participant deceased value is yes, the API confirms the timestamp value is included and well-formed. If it is, the NORC deceased timestamp is derived and the request is accepted.
(2) If either of the two data points are missing or badly formed, the system returns an error message to the user.
(3) If the values are included but 857217152 is ‘no’, the deceased data is ignored (deleted from the POST request) and the operation continues as normal.
(4) If neither of the variables are included, this functionality is passed entirely and the operation continues as normal.

Minimal example for site devs:
```javascript
{
  "data": [
    {
      "token": "<YOUR_PARTICIPANT_TOKEN>",
      "857217152": 353358909,
      "772354119": "2023-12-01T00:00:00.000Z"
    }
  ]
}
```

Additional functionality has also been added to the updateParticipantData API to match participant profile changes in ConnectApp and SMDB.

• User profile versioning
changes to participant first name, last name, suffix, preferred name, mobile/home/other phone, address, city, state, and zip can be recorded through this API. These changes will now update user history 569151507 consistent with how these updates are handled in ConnectApp and SMDB.
```javascript
firstName: 399159511
preferredName: 153211406
middleName: 231676651
lastName: 996038075
suffix: 506826178
homePhone: 438643922
cellPhone: 388711124
otherPhone: 793072415
prefEmail: 869588347
additionalEmail1: 849786503
additionalEmail2: 635101039
address1: 521824358
address2: 442166669
city: 703385619  
state: 634434746
zip: 892050548
canWeVoicemailMobile: 271757434
canWeTextMobile: 646873644
canWeVoicemailHome: 187894482
canWeVoicemailOther: 983278853
```

•Query array tracking: these are the data structures used for participant search in Biospecimen and SMDB.
Updates to these query arrays (firstName array, lastName array, allPhoneNo array, and allEmails array) are automatically handled by the API when that data is submitted normally. Requests to update participantData['query'] (where this data is stored) are automatically denied.

**Comment by JoeArmani** [comment]
Testing status update: dev testing has been requested from Sanford Health (thanks, @mnataraj92) I'll update this comment as test cases are processed.

**Comment by JoeArmani** [comment]
Update 12/14: change in requirements - Timestamp 772354119 is optional.

**Comment by mnataraj92** [comment]
A correction is being made to the EMR participant deceased date/time variable in order to make it not required. Once it is fixed, we will ask UC to retest to make sure that the EMR participant deceased flag can be sent without the date/time variable.

**Comment by JoeArmani** [comment]
Dev testing progress:
Confirmed in Firestore and BQ: HFHS, Sanford, HP.
Awaiting: UC, Marshfield.

**Comment by JoeArmani** [comment]
Stage testing progress:
Confirmed in Firestore and BQ: HP
Awaiting: HFHS, Sanford, UChicago, Marshfield.

**Comment by JoeArmani** [comment]
Tested in stage, ready for prod.

**Comment by JoeArmani** [comment]
Closing - this is in prod
