### ISSUE TITLE
sync mouthwash_v1 with BigQuery

### ISSUE THREAD

**Issue by jacobmpeters** [episphere/connect#825]
There is a new "mouthwash_v1" collection in Firestore. 

Please sync this collection with BigQuery so that it appears as a `Connect.mouthwash_v1` table.

We need this done before the data can be tested in DEV/STG. 

Listeners: @cusackjm @we-ai

**Comment by we-ai** [comment]
This needs a small update in code.

**Comment by Gbarra9** [comment]
PR Review Status - Approved

**Comment by we-ai** [comment]
"mouthwash_v1" collection in dev is synced to BQ.

**Comment by jacobmpeters** [comment]
Thank you, Warren. I'll begin adding this table to our flattening configuration in BQ.

**Comment by sonyekere** [comment]
Sandra to follow up .
