### ISSUE TITLE
SMS via Twilio: Technical Requirements for SMDB Build 

### ISSUE THREAD

**Issue by HanaShiho** [episphere/connect#827]
Additional resources for the technical build: DevOps

Programmable SMS API: https://www.twilio.com/docs/messaging/api
Segment counter for messages: https://twiliodeved.github.io/message-segment-calculator/
Quickstart Guide for messaging: https://www.twilio.com/docs/messaging/quickstart

**Comment by brotzmanmj** [comment]
Requirements using existing Notifications page in SMDB:

- Enable SMS to be sent concurrently with email (same conditions, same timing)
- Enable just Email and just SMS to be sent separately (under unique conditions and at separate times)
- Restrict SMS messages to only be sent if the user profile data has a mobile phone number AND permission to text that number.
- For email messages already programmed and sending in prod, be able to add a concurrent SMS message without resending to past participants who already received the email.
- The current interface is glitchy when using both SMS and email for the same message instance (I vaguely recall if you add SMS details, you lose email content and vice versa). It needs to be stable for both.
- Figure out how to format hyperlinks in SMS to direct people to MyConnect and to the CSC help desk.
- SMS messages will need to include first name in the same way that our emails do (preferred first name if exists, and if none then current user profile first name). Need syntax for that.


Other SMDB work:
- Display the SMS messages sent in the Participant Messages page on SMDB

STOP functionality:
- Figure out how 'STOP' works - how do we configure the required 'STOP' on the messages via the Notifications interface? We think Twilio will automatically stop messages to phone numbers that have indicated STOP, but are we also able to absorb the STOP back into our data?

Testing Needs:
- Figure out how we can test SMS messaging with fake phone numbers (we only have a few real phones among us)
-

**Comment by Davinkjohnson** [comment]
@HanaShiho and @brotzmanmj I'm hoping for some clarification on the following requirements mentioned above:

Enable just Email and just SMS to be sent separately (under unique conditions and at separate times)
- Is the meaning here that the notification schema could have ONLY email (like it does today) and then a separate schema for ONLY SMS? 
- The alternative I wasn't sure on is whether each schema should have the ability to have an email condition and an SMS condition? (I would recommend against this as it seems like it would get very tricky very fast.) 

Figure out how to format hyperlinks in SMS to direct people to MyConnect and to the CSC help desk.
- since SMS messages are only text there's no way to make a real hyperlink (like a "click _**here**_) but we could look into using a link shortener to make the links more useable in 160 character texts.

**As for the other questions**
Stop Functionality: I'm almost certain Twilio manages this on their end, and they should have something similar to what Jessica setup with SendGrid (where we can "listen" for Twilio to send us outcomes of the messages sent and load them back into Firestore).

Testing needs: There are a couple services we can use to do this. My understanding was that Twilio had some of this functionality built in. We'll look into it and find something better than using our team's own cell numbers.

**Comment by brotzmanmj** [comment]
HI Davin, I think the best thing would be for Deanna to demonstrate the current functionality for SMS in dev and the way that is set up, though we've only ever used it for email. Right now, you can select email and SMS for the same message.

**Comment by depietrodeanna** [comment]
@HanaShiho should we find some time for the four of us (and whomever else from the Dev team should be included) to meet and run through the current SMDB functionality as Michelle mentioned above?

**Comment by HanaShiho** [comment]
@brotzmanmj @Davinkjohnson I think we probably don't need to have capability to send email and SMS simultaneously to the same person. If it's easy to build then may as well, but if it imposes any delay, I think it's unlikely we'd use it based on our use case scenarios. I'd advise for the capability for the system to be able to trigger and send SMS and emails independently of each other. 

As for hyperlinks, yes, if we have more information to share than can fit in an SMS, then directing them to the app for the extra detail is great e.g. a link to the Connect app, which would then take them to the survey to complete. Additionally, if possible, we'd want the system to be able to send out not just pre-programmed SMS, but also give the functionality to be able to send a singular participant an adhoc manual message if needed. Not sure the use case for this yet or how often this may be needed, but having the functionality there gives a greater flexibility for nuanced cases. 

To Davin's point around phone number and email validation (you probably are already aware of this but just in case), Twilio has a Lookup API detail [HERE](https://www.twilio.com/blog/best-practices-phone-number-validation-user-enrollment) and Sendgrid and email validation API [HERE](https://sendgrid.com/en-us/solutions/email-api/email-address-validation-api), both that I believe we can programmatically plug into our app sign-up process. From memory, the Lookup API is free for a while and then costs after a certain amount, and the email verification again is part of our SendGrid package up to a certain number of verifications, and then it's additional $'s. 

Since there will be an element of testing and seeing where email engagement drops and if SMS is more effective, it could be interesting to see if any other trials have email data on perhaps the average number of reminders needed before action taken, and also if they have any data on open/click rates for those emails to see if they are being read? If that data was available it may help us build out the scenarios (e.g. have an SMS go out after 3 email reminders have gone out and still no action taken)but bringing in the SMS at a stage where it could have helped most in the past.

**Comment by HanaShiho** [comment]
Additional resources around [opt-out keywords ](https://www.twilio.com/docs/proxy/opt-out-keywords)and [customization ](https://www.twilio.com/docs/messaging/tutorials/advanced-opt-out)

**Comment by brotzmanmj** [comment]
Hi @HanaShiho @Davinkjohnson and @depietrodeanna , I think we need to discuss the requirements. I definitely think we want to send SMS and email to the same person at the same time. We need to think carefully about what are the MVP requirements and distinguish this from later enhancements, without coding ourselves into a corner.

**Comment by we-ai** [comment]
> Hi @HanaShiho @Davinkjohnson and @depietrodeanna , I think we need to discuss the requirements. I definitely think we want to send SMS and email to the same person at the same time. 

This is doable, since a notification spec can have both email and SMS templates.

**Comment by brotzmanmj** [comment]
Hi @we-ai  Agreed. We scheduled a meeting for Thursday at noon to discuss requirements.

**Comment by HanaShiho** [comment]
Regarding the testing needs, Twilio has a testing sandbox type environment whereby we can test things like throughput and functionality as well as opt in and out etc- more info on this link[ HERE](https://www.twilio.com/docs/iam/test-credentials). It may also be worth asking our Twilio rep to ask their Solutions Engineer to recommend a Twilio sandbox environment too in case we need to test more functionality. They may have something built out we can use or at the worst give us $x credit so we can at least test real cell numbers without paying for it.

**Comment by Davinkjohnson** [comment]
Met on the requirements for this today: Michelle, Warren, Deanna, Hana, Sandra, Tony, Davin
Follow Ups:
- Walk through the schema UI with Deanna (implement a draft functionality, possibly)
- Review notifications and Schema data structures with Analytics (Nicole, Jake, and Kelsey)
- Hana/Warren review 10 DLC registration
- Discuss Message services (campaigns) with Michael to understand better
[SMS-messeging_warren_01-04.pptx](https://github.com/episphere/connect/files/13833803/SMS-messeging_warren_01-04.pptx)

**Comment by we-ai** [comment]
Error 21606 occurs when trying to use the phone number to send messages. Please check documentation [here](https://www.twilio.com/docs/api/errors/21606) and finish the number setups @HanaShiho.

**Comment by HanaShiho** [comment]
@we-ai From memory Twilio said if SMS does not fail with 30035 or 30034 errors, that would further confirm the number is fully registered. Was there any message associated w/ Error 21606?

**Comment by HanaShiho** [comment]
@we-ai  [This](https://www.twilio.com/docs/api/errors/21606) may be of use. I'll also look into it.

**Comment by HanaShiho** [comment]
@we-ai I've just tested sending a msg to myself and it worked!  You can test it in the platform from the side menu, Messaging, Try it out, Send an SMS. When you enter the number you are sending to, enter the format +13019622427.

**Comment by we-ai** [comment]
Does anyone know concept ID(s) related to permissions to receive SMS messages in participant data?

**Comment by brotzmanmj** [comment]
Should be in the data dictionary. @HanaShiho can you find it? thanks

**Comment by HanaShiho** [comment]
Concept ID 646873644 (var name: RcrtUP_MobileTxt_V1R0)

**Comment by we-ai** [comment]
> Figure out how to format hyperlinks in SMS to direct people to MyConnect and to the CSC help desk.

@brotzmanmj The addresses of the 2 sites are not long.  29 characters for "https://myconnect.cancer.gov/", and 36 characters for "https://myconnect.cancer.gov/support". So they can be safely put in messages of 160 characters. Let me know if you want to see and try them on your phone. I can send a test message with a link above.

If we have long links to send, we can use [link shorting](https://www.twilio.com/docs/messaging/features/link-shortening) provided by Twilio.

**Comment by brotzmanmj** [comment]
HI @we-ai  to clarify, Twilio will stop the messages automatically upon STOP request. You're setting it up so that Twilio will forward information to us so we will know that someone requested STOP. When you say 'label a participant as opt-out in our database' what do you mean logistically by that? Will we change the setting in their user profile that says 'You have permission to text this number' so we will no longer text that number?

**Comment by we-ai** [comment]
Hi @brotzmanmj thanks for the comment.

Twilio stops sending messages upon receiving a 'stop' reply. It maintains a list of phone numbers to be blocked for messaging. If we need only the functionality of out-out, no further implementations are needed.

My words 'label a participant as opt-out in our database'  is a suggestion on handling 'stop' reply forwarded from Twilio, if we want to update participant data in Firestore accordingly. We'll need to discuss and decide which part of participant data need to be updated. Without a decision, currently it's not implemented (incoming messages are not forwarded and handled).  So nothing will be impacted by 'stop' replies, based on recent update in [PR#508](https://github.com/episphere/connectFaas/pull/508).

Should we consider handling incoming messages (from participants) as a separate GitHub issue or part of current issue? It's possible to put more logics in handling incoming messages, or even have a conversation with messages.

**Comment by brotzmanmj** [comment]
Hi @we-ai good question, I wasn't even thinking about handling incoming messages or having conversations with messages, I was sort of thinking of our SMS messages as 'do not reply' in the way our emails are do not reply. I don't think we want to converse with the participants in this way do we @depietrodeanna and @HanaShiho ? At least not initially.

I was only thinking of whether we want to know if someone requests not to get text messages any more. Agreed that our system would not need to do anything to stop the messages, but just for our information.

**Comment by HanaShiho** [comment]
@we-ai @brotzmanmj @depietrodeanna I agree. Perhaps down the road but I don't anticipate us conversing w/ the participants via txt.

**Comment by brotzmanmj** [comment]
The thing it would help most with is communications preference management in a way... if we know someone has stopped receiving our text messages then we know we have to communicate with them via email or phone call or some other way or they are not actually hearing from us.

**Comment by we-ai** [comment]
SMS messaging can be tested in dev @depietrodeanna, @HanaShiho, @brotzmanmj

**Comment by HanaShiho** [comment]
@Davinkjohnson @we-ai @brotzmanmj @sonyekere @depietrodeanna 

Thank you for the update, Warren! Davin, how should we go about testing between now and Friday (before pushing it to Stage on Monday 1/29) to ensure the changes Warren incorporated did not interfere with what we currently have functioning in SMDB (i.e. email notification)? Additionally, we'd like to be able to test the data structure to better understand how event outcomes (e.g. sent msgs) are outputted and stored.

**Comment by Davinkjohnson** [comment]
Test Plans from today's meeting.
In attendance: Michelle, Hana, Deanna, Warren, Davin

Test Cases/Plan
* an SMS only message
    * Configure message to begin with “TEST”
    * Include first name and a link to DEV myconnect (Deanna & Hana have syntax for this)
    * Include “Reply Stop” in notification spec
    * Site=NCI, and consent=Yes, day of consent (primary field)
    * Covered by message #3 scenario (person consented and verified)
* an email only message
    * Cannot be verified? 
    * Put in a new person and mark them as cannot be verified
* a combined SMS/email message
    * Configure SMS message to begin with “TEST”
    * Include “Reply Stop” in notification spec
    * welcome to Connect
    * Put in a new person and verify them
* Create participant who has not consented to receive texts
    * Create participant, consent to the study, and verify

Testing Details
* Use Hana’s cell number to receive SMS for this round of testing
* What sends out text message now? 
    * For this round of testing, use 10DLC (prod account number)
* “STOP” functionality is managed by Twilio
* Twilio has a log of sent messages (not as comprehensive as SendGrid, just a log)

Other Tests included in Jan Scope
* Check/validate previous SMDB issues noted by Ops/Comms team
    * Save notifications as draft
        * Test that drafts don’t go out
        * ?
    * Radio buttons/toggle between SMS and Email
        * Verify functionality of removing an SMS from combined email/SMS spec

Testing Outputs
* Test the sending of notifications
    * SMS only
    * email only
    * combined
* Verifications
    * notification should only be sent once
    * display of first name and PWA or support link in sms
    * participants not agreeing to receive sms shouldn't receive them
    * See the “Stop message”
* Analytics team to analyze data once messages are sent
    * Will need to check on Friday (worst case, Monday)

**Comment by HanaShiho** [comment]
Findings from dev testing 1/25/24

Connect ID: 8473325197 
  - Received the SMS only msg but not the combined SMS/email text 
  - Didn't receive the combined SMS/email email 

Connect ID: 3076819421 
- Received the SMS only msg 
- Did not receive the "cannot be verified email" (i.e. email only msg). Updates: verification status time has been applied on 1/26/24 

Connect ID: 4780501804 (verified & opted out) 
- Received the SMS only message; this TP has not consented to receive texts. 

Other tests included in Jan scope: 
a) Save notifications as draft 
   - Tested that drafts don't go out (1/24) 
   -  Verified TP received the completed spec (1/24) 

b) Radio buttons/toggle between SMS and email  
  -  In dev, when you unselect SMS, the text box goes away (1/25)

**Comment by brotzmanmj** [comment]
Hi Hana,
Can you add the message category for each of scenarios above so Warren will know what the corresponding test message spec ID should be?
And can you indicate more clearly what each case was supposed to receive, what succeeded, and what failed?

On this one: 
a) Save notifications as draft

Tested that drafts don't go out (1/24)
Verified TP received the completed spec (1/24) - was this expected or not expected? I'm not sure what this means.

For this:
b) Radio buttons/toggle between SMS and email

Verified the functionality of removing the SMS field from combined email/SMS spec. In dev, when you unselect SMS, the text box goes away (1/25) If you deselect SMS and then reselect SMS does the text box for the SMS content reappear but blank? If you deselect email, do those email related boxes disappear, and then if you reselect it do they come back blank?

**Comment by HanaShiho** [comment]
Hi, 

You can find the tracking sheet [HERE ](https://nih.app.box.com/file/1426297760791) 

@brotzmanmj to your questions about save notifications as draft:
- Test participants received the completed spec (1/24): This is expected. We wanted to test that they receive the completed spec and the draft specs do not go out. 
- If you deselect SMS and then reselect SMS, the blank text box for the SMS field reappears. 
- If you deselect email and then reselect email, the email related boxes (subject line, body) disappear, and then when you reselect, those boxes come back blank.

**Comment by depietrodeanna** [comment]
![START and STOP](https://github.com/episphere/connect/assets/74061787/d18d210f-ea6f-433e-a6f6-5a91a6b91b22)
Documenting the start and stop messages from Twilio. For launch, STOP respond is fine. START is a bit confusing. Post-MVP- can we tailor these? And, @HanaShiho  let's make sure we can see the START for resubscribing on the Twilio interface.

**Comment by HanaShiho** [comment]
@depietrodeanna I agree. FYI Twilio logs START in the UI. 

<img width="1512" alt="image" src="https://github.com/episphere/connect/assets/148134271/08c551c2-1cf2-4ac0-bd43-098e21fe136d">

**Comment by we-ai** [comment]
@depietrodeanna @HanaShiho Please consider using Box to share files. Some of the shared images may contain person information (phone number).

**Comment by HanaShiho** [comment]
Dev complete

**Comment by sonyekere** [comment]
**Stage testing occurred Tuesday, January 20th. Discussed the below. Attendance: @HanaShiho , @we-ai , @brotzmanmj , @sonyekere ** 

- Minor change indicated - update "undefined" Title to indicate SMS - To be done next release in Feb, Create new issue  

- ACTION: Warren to force stage data to BigQuery, Jake and Kelsey to check once complete (@jacobmpeters , @KELSEYDOWLING7 )

- Pending testing of editing and existing messages in stage still needs to be done. Can be checked once data is pushed  to BigQuery.

- Pending testing of STOP reply when SMS is received ( Discuss further next release)

**Comment by we-ai** [comment]
The SMS messaging functionality is in production. Requirements were met.
