### ISSUE TITLE
Can't skip any questions on an iPad

### ISSUE THREAD

**Issue by cusackjm** [episphere/connect#829]
Can't skip any questions on an iPad. If I try to skip something, nothing happens when I tap Next. I have to enter a response for the next button to work. The pop up error messages are also not being displayed.

Scenario: janprodpush11@mailinator.com
Documentation: https://nih.app.box.com/integrations/officeonline/openOfficeOnline?fileId=1372985523754&sharedAccessCode=
Tier: Stage
Browser: Safari
Device: iPad
Survey/Questions:
- BUM Survey (SLEEPTIME, WAKETIME, and MWBEFORE)
- SSN Survey (SSN)
- Module 4 (HOMEADD1_1)

**Comment by brotzmanmj** [comment]
Elevating the urgency of this since it seems questions can't be skipped an any survey module right now. Could this be related to a recent change to quest?

**Comment by danielruss** [comment]
@cusackjm   Using safari on my mac, I can skip without a problem, but I am have a problem with the grid.  Are you able to make selections on safari?

**Comment by cusackjm** [comment]
@danielruss I can make selections using Safari on iPad, Chrome on PC Laptop, and Chrome on Android. 
I can skip using Chrome on PC Laptop, but cannot skip using Safari on iPad, or Chrome on Android.

**Comment by danielruss** [comment]
@cusackjm   I made a small change to the code.  I can now click the grid in chrome on mac. 

As for skipping, I can only test on safari/edge/chrome/FF on mac and  android, and I can skip on all those platforms.

**Comment by cusackjm** [comment]
@danielruss is this in the renderer or PWA? I still can't skip in Android/Chrome/Stage/BUM

**Comment by m-j-horner** [comment]
> @danielruss is this in the renderer or PWA? I still can't skip in Android/Chrome/Stage/BUM
@danielruss

**Comment by danielruss** [comment]
@m-j-horner I test using using the dev tool and the [dev connect app](https://episphere.github.io/connectApp)

**Comment by danielruss** [comment]
> > @danielruss is this in the renderer or PWA? I still can't skip in Android/Chrome/Stage/BUM

I'll check on my cell phone.

**Comment by danielruss** [comment]
@m-j-horner   I just finish Android/Chrome/Dev/BUM I was able to skip.  You can see my results in dev: Connect_ID: 421823980

**Comment by cunnaneaq** [comment]
iPad/Safari/Dev/BU - able to skip questions
Not able to skip in stage, makes sense based on Daniel's previous comment

**Comment by danielruss** [comment]
Is this still an issue?

**Comment by cunnaneaq** [comment]
I just re-tested this in module 1 in stage and I was able to skip questions as expected
Safari/iPad
Chrome/Android
