### ISSUE TITLE
GetParticipantData API filter

### ISSUE THREAD

**Issue by sarah-hague** [episphere/connect#83]
Can a filter option be added to this API?  For example, when making the GetParticipantData=notyetverfied it would be helpful to only have the necessary variables returned in order to run our match verification rather than all fields in the user profile.

**Comment by jonasalmeida** [comment]
looks like a suggestion for an aggregation parameter, see https://gitter.im/episphere/Connect-AlphaTest-Private?at=5e8fc8c31aaf8e4b8e721da4
