### ISSUE TITLE
December eNewsletter

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connect#830]
Goal to send out in prod week of Dec 12, but the latest we could push is the following Mon/Tues Dec 18/19. Use template created by Abhinav in the past and update the content and graphics per the below:

**What's New content:** 
We’re discussing the future of return of information for Connect, and looking forward to study activities in the new year. (Notes: hyperlink entire paragraph: cancer.gov/connect-prevention-study/news/updates-return-information )
Graphic: https://app.box.com/s/caujtz90k50c6zh066wwf59m5vmyp7sc

**In the Spotlight content:** 
Dr. Matthews is a researcher at the NCI dedicated to understanding how sleep is related to cancer risk. Through Connect, Dr. Matthews hopes to learn more about how we can better prevent cancer using knowledge gained from studying sleep behaviors. (Notes: hyperlink entire paragraph: cancer.gov/connect-prevention-study/news/matthews
Graphic: https://app.box.com/s/2damyichm9rawupil5hc2t96oi39bxha

**Did You Know content:** 
Did you know? **Two in three** Connect participants reported sleep troubles in the past month. Learn some tips to get better sleep and improve your overall health. (Notes: hyperlink entire paragraph, cancer.gov/connect-prevention-study/news/sleep )
Graphic: https://nih.app.box.com/file/1351614397983 (there is another size in the same folder should you need it)

**Comment by jhflorey** [comment]
@depietrodeanna Please help check https://episphere.github.io/dashboard/newsletter/decembernewsletter and confirm.

**Comment by sonyekere** [comment]
Merged to Dev 12/8

**Comment by depietrodeanna** [comment]
This looks good @jhflorey

**Comment by depietrodeanna** [comment]
@jhflorey updated text for spotlight section- see edited issue above (replaced "chuck" with "Dr. Matthews")

**Comment by depietrodeanna** [comment]
@jhflorey please add the "View in browser" back into the email at the top right corner. @HanaShiho this is ready to program and test in stage as soon as Jessica updates the html since otherwise dev testing looked good

**Comment by jhflorey** [comment]
> @jhflorey please add the "View in browser" back into the email at the top right corner. @HanaShiho this is ready to program and test in stage as soon as Jessica updates the html since otherwise dev testing looked good

Hi @depietrodeanna , i've already updated in dev Please help check

- https://episphere.github.io/dashboard/newsletter/decembernewsletter
- https://gist.github.com/jhflorey/fb8619448cebabb64a4581fa6db3fab4

**Comment by sonyekere** [comment]
Team has requested a language update. 
 
![image](https://github.com/episphere/connect/assets/143135758/f51d3a63-b21f-4267-9cd5-90c73dc3d5b1).

**Comment by jhflorey** [comment]
@sonyekere which paragraph did you mention?
