### ISSUE TITLE
Summary pages after [SIBCANC3Y] and [CHILDCANC3Y]

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connect#832]
In the Module 1 specs document, it states:

"Summary screen to appear after questions have been exhausted for each sibling: Here is a summary of the information you shared about sibling [initials/nickname]. If any of the information is incorrect, please select the “Back” button to edit your answers. If all of the information is correct, please select the “Next” button to move forward"

and

"Summary screen to appear after questions have been exhausted for each child: Here is a summary of the information you shared about sibling [initials/nickname]. If any of the information is incorrect please select the “Back” button to edit your answers. If all of the information is correct, please select the “Next” button to move forward."

I did not see these summary pages after the sibcanc and childcanc sections.

**Comment by joshid-ims** [comment]
Ok, I will keep the updates in #305. We will deliver it with the module.
