### ISSUE TITLE
Duplicate FedEx tracking number 635213673400 still on Packages In transit screen even though receipted on 11/24/2023 (Biospecimen)

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#834]
FedEx tracking number 635213673400 is still showing up on the Packages in Transit screen and in the In Transit Report even though it was receipted back on 11/24/2023.
Background to this tracking number: FedEx tracking number 635213673400 was used on 11/16/2023 to ship samples to BPTL from KPGA and again on 11/22/2023 to ship samples to BPTL from Chicago.  This was a mistake on part of the BPTL team.
The second time it was used, it was recipted into the dashboard on 11/24/2023.  

The tracking number is still showing up so BPTL tried to do a receipt of the package again on 12/1/2023 but the package still has not disappeared from the screen or the report.
Please look into why it is still showing up on the Packaged in Transit screen and In Transit report.

**Comment by JoeArmani** [comment]
**Initial notes:**
This is a separate issue from missing tube received timestamps but stems from the same ‘receive packages’ function.
Link to that issue:  https://github.com/episphere/connect/issues/819

The two boxes involved:
Box440 - shipment submitted 11/16/2023
Box972 - shipment submitted 11/22/2023

Box440:
•marked ‘received’ and has received timestamp 12/04/2023.
Specimens in box 440 have received timestamp:
specimen level - 12/4/2023
tube level - 12/4/2023
tube level, mouthwash - no mouthwash tube for collection

Box972:
•marked ‘not received’ and does not have received timestamp.
•Specimens in Box972 have received timestamp:
specimen level 12/4/2023
tube level, non-mouthwash 12/4/2023
tube level, mouthwash - 11/24/2023

The ‘receive packages’ function searched for this tracking number and probably executed correctly the first time.
The second time, it got a list of both boxes (duplicate tracking numbers), and defaulted to picking the first one. There’s no currently logic to tell it which box to pick when setting the received timestamp. We should have more specific logic here so duplicate tracking numbers aren't an issue in the future.

**Action:**
Tighten up the logic & conditions used in the ‘receive packages’ function so it knows what box to pick in a duplicate tracking number scenario.

We have a couple of options here, but I need to recreate this with duplicate tracking numbers in dev and run testing to find the most reliable method for selecting the right box in a duplicate tracking number scenario.

I’ll roll it into the ‘receive packages’ function update I’m currently working on. That's a full stack update with changes on the BPTL end and in ConnectFaas. This will pair well with the ‘package already received’ functionality I'm building.

**Comment by JoeArmani** [comment]
With this update, any time duplicate tracking numbers are found, a scrollable, selectable list of possible box matches will be returned to the BPTL user (ordered by recency).

The BPTL user can manually verify the box based on boxID, shipping date, origin site, and received date (listed as 'not yet received' if new), and select the box to continue processing the shipment. After selecting a box and clicking continue, the receipt process will be handled as expected.

<img width="935" alt="Screenshot 2023-12-08 at 3 31 52 PM" src="https://github.com/episphere/connect/assets/93854858/434adb35-41df-4c9f-a875-d961fc1b67a0">

**Comment by JoeArmani** [comment]
Re: GitHub Project Board - this issue moves with https://github.com/episphere/connect/issues/819. I'm Leaving 819 in the development category during the review cycle to avoid confusion.

**Comment by StephanieWeinstein** [comment]
Thanks @JoeArmani, your solution seems great!
Stephanie

**Comment by JoeArmani** [comment]
Thanks @StephanieWeinstein. I was really under the gun time-wise because of our dev freeze EOD today, so if we find anything that needs fine-tuning that can certainly happen!

**Comment by JoeArmani** [comment]
PRs ready for review.
Biospecimen: https://github.com/episphere/biospecimen/pull/633
ConnectFaas: https://github.com/episphere/connectFaas/pull/487

**Comment by wyattks** [comment]
Domonique tested it in Dev and it worked.  Se issue #819 for her comment

**Comment by wyattks** [comment]
![image](https://github.com/episphere/connect/assets/64605220/bd976565-1d0e-445c-9414-c5cfe940207e)
my test shows error when adding FedEx number in shipping daashboard that is a duplicate.

**Comment by JoeArmani** [comment]
@wyattks Yep, that confused me at first. I traced it out because I was unfamiliar with it -- that warning was implemented to be site-specific, so it does not catch duplicates across different sites, which is (I think) what happened in the case of this issue. One shipment from Chicago, another from KPGA.

I considered this box selection to be a more flexible solution...and also to serve as a code template for other parts of our apps that need similar response flexibility from the server in the future.

We can also strengthen this duplicate tracking number warning in the future or remove it...whatever your team decides.

Please let me know if you need me to set any custom data on the back end in dev so you can test the solution as if the boxes came from different sites. Thanks.

**Comment by JoeArmani** [comment]
Just so my previous comment doesn't obscure the status:
This is tested in dev and ready for stage.

**Comment by wyattks** [comment]
Tested receipt of duplicated FedEx ID.  Worked as expected.


![Image](https://github.com/episphere/connect/assets/64605220/6e02967d-5fc5-46f0-b19c-b02a0a14b92e)

Ready for production

**Comment by JoeArmani** [comment]
Closing, this is in production.
