### ISSUE TITLE
Home Collection Updates - (Biospecimen)

### ISSUE THREAD

**Issue by abhinavjonnada82** [episphere/connect#836]
- Allow the user to type in barcode apart from scan or copy/paste the number
- Notify user when incorrect tracking code is used
- https://github.com/episphere/connect/issues/804#issuecomment-1836201150

**Comment by wyattks** [comment]
Tested in Dev and both functions worked.  Ready for Stage.

**Comment by HopkinsDC** [comment]
Tested in stage. Ready for production.
