### ISSUE TITLE
[PROD] Missing labels in Participants table header

### ISSUE THREAD

**Issue by abhinavjonnada82** [episphere/connect#839]
Title^^
<img width="1476" alt="MicrosoftTeams-image (1)" src="https://github.com/episphere/connect/assets/30497847/b55a0994-1586-4d50-85ac-92c106be8092">

**Comment by Gbarra9** [comment]
PR Review Status- Approved

**Comment by robertsamm** [comment]
@abhinavjonnada82 tested in dev, ready for stage

**Comment by robertsamm** [comment]
@abhinavjonnada82 tested in stage, ready for prod
