### ISSUE TITLE
SSN Decryption QC

### ISSUE THREAD

**Issue by anthonypetersen** [episphere/connect#840]
Creating a GCP Cloud Function that can be used to run defined Quality Control rules on values that have been submitted via the Connect SSN Module

Rules for Nine Digit Entries
- No segment can contain all zeroes
- Cannot be all ones (111-11-1111) or all threes (333-33-3333)
- Cannot start with `666` or `9`

Rules for Four Digit Entries
- Cannot contain all zeroes

TODO
* add status CID to all existing SSN documents
* add status CID to variables that get added when new SSN document is created
* update status CID with results of QC

New Concept IDs
* "SSN Quality Check Status": "605870562",
* "No Check Ran": "875207881",
* "Check Passed": "631498205",
* "Check Failed ~~- Contained all zeroes in a segment": "376136630",~~
* ~~"Check Failed - Contained either all ones or all threes": "263553581",~~
* ~~"Check Failed - Started with 666 or 9": "347764543~~

**Comment by brotzmanmj** [comment]
Per Mia and Nicole on 12/14/23: Please save a flag indicating it was checked and a generic flag indicating if it violated any rule or not (not to indicate which rule it violated).

**Comment by FrogGirl1123** [comment]
@anthonypetersen For the generic flag repurpose the CID for the first specific violation (376136630) to a generic violation and I'll get it updated in the data dictionary and remove the other two options.

**Comment by anthonypetersen** [comment]
@FrogGirl1123 Just to clarify, these are going to be the Concept IDs we use going forward:

* "SSN Quality Check Status": 60587056
* "No Check Ran": 875207881
* "Check Passed": 631498205
* "Check Failed": 376136630

**Comment by FrogGirl1123** [comment]
> @FrogGirl1123 Just to clarify, these are going to be the Concept IDs we use going forward:
> 
> * "SSN Quality Check Status": 60587056
> * "No Check Ran": 875207881
> * "Check Passed": 631498205
> * "Check Failed": 376136630

Yes, this is correct.

**Comment by sonyekere** [comment]
@anthonypetersen - Can this be closed?

**Comment by anthonypetersen** [comment]
Not yet
