### ISSUE TITLE
HP showing up on Receipt csv 2 different ways - (Biospecimen)

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#843]
BPTL notified us that on the 12/9/2023 receipt csv, HP is showing up under the Sample Collection Column as both HealthPartners Research Clinic and HP Research Clinic.  As this file gets uploaded to BSI, we need it to show up as HP Research Clinic.
I'm not sure why it is now showing up both ways. I have attached the csv file from the 9th.

**Comment by wyattks** [comment]
[2023-12-09-BSI-data-export HP listed 2 ways.xlsx](https://github.com/episphere/connect/files/13639573/2023-12-09-BSI-data-export.HP.listed.2.ways.xlsx)

**Comment by JoeArmani** [comment]
Collection CXA019446 is a clinical collection, and the system assigns one set of naming conventions to clinical collections. "HealthPartners Research Clinic" is the active value in that field.

Collection CXA019381 is a research collection, and the system assigns a different set of values to those collections. "HP Research Clinic" is the active value for that category.

I don't have a background on why this is the case -- I'll message you on teams to get updated values for these items.

**Comment by sonyekere** [comment]
Biospecimen team to connect further on BSI and overall decision making to move forward. More to come in Jan.

**Comment by wyattks** [comment]
Closing will open new issue for changes we will need.
