### ISSUE TITLE
PROMIS Survey Integration

### ISSUE THREAD

**Issue by anthonypetersen** [episphere/connect#844]
Summarizing requirements from [here](https://nih.app.box.com/file/1344202856401?s=6yquccomdbxofjavztysd74iikqjtclf)

Forms Being Utilized (Needs Confirmation)
* PROMIS SF v1.0-Physical Function 4a
* PROMIS SF v1.0-Anxiety 4a
* PROMIS SF v1.0-Depression 4a
* PROMIS SF v1.0-Fatigue 4a
* PROMIS SF v1.0-Sleep Disturbance 4a
* PROMIS SF v2.0 - Ability to Participate Social 4a
* PROMIS SF v1.0-Pain Interference 4a
* PROMIS-Global Pain
* PROMIS SF v2.0 - Satisfaction Roles Activities 4a
* PROMIS SF v2.0 - Social Isolation 4a
* PROMIS SF v2.0 - Cognitive Function 4a

Concept IDs Needed
* PROMIS-29 Status (assuming this will be default, existing participants also won't have this)
* PROMIS-29 Start Time
* PROMIS-29 Complete Time

Trigger for Survey Availability
* 3 months post-verifications for those enrolled after PROMIS-29 goes live
* Immediately for everyone else
* DEV OPS NOTE: would be much easier / cleaner to just apply the first rule to everyone

Buckets of Work for Dev Ops
* At some point need to transfer current development API license to a production license
* Need to figure out how to get raw survey answers and scores, determine where to store them
* Develop logic to render questions
* Develop logic to go back and forth between questions
* Develop logic to save responses
* Develop logic to start / continue survey
* SMDB / BSD visual additions

**Comment by brotzmanmj** [comment]
Thanks Tony. Adding requirement:

- Emails to be scheduled via SMDB interface (Hana)

One comment on the Trigger for Survey Availability

- 3 months post-verification for those enrolled after PROMIS-29 goes live
- Immediately for everyone else
- DEV OPS NOTE: would be much easier / cleaner to just apply the first rule to everyone
-Note from Michelle: It should trigger to appear on their dashboard 3 months post-verification for everyone. If a participant is already more than 3 months post-verification at the time that PROMIS goes live, it should appear on their dashboard immediately. It should not disappear from their dashboard until they submit it.
Does that help clarify the programming requirements?

**Comment by brotzmanmj** [comment]
Here is a link to the IRB approved PROMIS survey that contains the content we will use, comprised of 4 forms:
https://nih.app.box.com/file/1350598900472

The forms have these four names:
PROMIS–29 Profile v2.0
PROMIS Item Bank v2.0 - Satisfaction with Social Roles and Activities
PROMIS Item Bank v2.0 - Social Isolation – Short Form 4a
PROMIS Item Bank v2.0 – Cognitive Function- Short Form 4a

**Comment by brotzmanmj** [comment]
Updating with decision that the 3-month PROMIS survey will be programmed in Quest by IMS.

**Comment by robertsamm** [comment]
Closing issue as PROMIS will be programmed in Quest. See https://github.com/episphere/connect/issues/877 for main github issue pertaining to PROMIS survey implementation.
