### ISSUE TITLE
Issues with HP’s self-scheduling links

### ISSUE THREAD

**Issue by HanaShiho** [episphere/connect#846]
The HP’s self-scheduling email was programmed in SMDB per[ the updated script](https://nih.app.box.com/file/1350484797147?s=d09ckgfu0msf4r2ofdpjw04fgyeqisyv) on Box. In the body of the email, there were three identical links to HP’s self-scheduling portal. Upon testing in Stage, only the first link worked as intended. The other two did not take the user to the self-scheduling portal. Instead, they lead to a page displaying an invalid token error message.

**Comment by sonyekere** [comment]
Ready for Prod

**Comment by sonyekere** [comment]
In Prod for the January release
