### ISSUE TITLE
New Age Ranges showing as "ERROR" & update age metric on homepage SMDB

### ISSUE THREAD

**Issue by mnataraj92** [episphere/connect#848]
We received an email from Sanford stating that they see "ERROR" for the new age ranges on the SMDB.

They created 3 test pts:
94e6615b-1afd-4179-a467-a6e69fc1918d for the 30-34 range
42184af9-1ca9-44a7-bbb1-4f621de6073c for the 35-39 range
958533c8-1b6c-4106-9abd-5d3bf3b319f6 for the 66-70 range

In the Dev SMDB, they see “ERROR” for their age ranges.

These values were accepted by the API from Don’s end, but then after that, they double-checked the Dev SMDB for accuracy and that’s when they made note of the “ERROR” value. 

These are the CIDs for the new age ranges: 
Age (state_d_934298480)
713781738	0 = 30-34
631272782	1 = 35-39
722846087	7 = 66-70

Adding @robertsamm to help test the correction

**Comment by JoeArmani** [comment]
Hi @mnataraj92, I implemented the API side of these variables. I'm not sure the SMDB update was implemented.

Here's the original open issue: https://github.com/episphere/connect/issues/761

What's the priority on this?

**Comment by mnataraj92** [comment]
@JoeArmani I just checked with Michelle, if it can be fixed in the January release that would be great but if not, then definitely in the February release since that’s when we plan to launch the age expansion

**Comment by brotzmanmj** [comment]
Hi @sonyekere  letting you know this issue status for the punch list and the January release

**Comment by anthonypetersen** [comment]
Reviewed & Approved

**Comment by robertsamm** [comment]
Hi @abhinavjonnada82 The age ranges for the age variable look good, I don't see anymore ERROR messages. 

For the pie chart metric for age, is there a way to make it so that you don't have to scroll on the key to see all of the categories? Some people pull this metric via a screenshot so it would be great to see all categories at once..

![image](https://github.com/episphere/connect/assets/67074735/8b7e8da9-fab5-495b-ae69-dabb4ce8f200)

**Comment by robertsamm** [comment]
Error message and updated age metric looks good in dev, ready for stage.

**Comment by sonyekere** [comment]
In prod for January release .
