### ISSUE TITLE
BPTL Receipt CSV File - Update Clinical Names displayed in the Sample Collection Center Column (Biospecimen)

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#849]
Please update the names listed in the Sample Collection Center Column for the Clinical Collections in the BPTL receipt csv and home collection csv files only.  
Currently the files pull in the information from variable RcrtES_Site_v1r0 (Concept ID 827220437)
We need the names displayed on the csv files to be displayed as referenced in the Mapping file: https://nih.app.box.com/file/1306346523951
See tab labeled Collection Center Mapping

**Comment by JoeArmani** [comment]
@wyattks can you take a quick look at this before I post the PR? Just want to confirm this is what we're looking for.

Updated values: Separate values on the Finalize screen from Clinical CSV Values. They previously had the same reference.
Research values are unchanged.

<img width="593" alt="Screenshot 2024-01-02 at 4 24 58 PM" src="https://github.com/episphere/connect/assets/93854858/148d874e-f056-4ed7-8fe8-607b1fcc1d5e">

**Comment by wyattks** [comment]
yes this is correct.

**Comment by JoeArmani** [comment]
PR ready for review: https://github.com/episphere/biospecimen/pull/649

**Comment by Gbarra9** [comment]
PR Review Status - Approved

**Comment by anthonypetersen** [comment]
Reviewed & Approved

**Comment by JoeArmani** [comment]
Merged to dev, ready for testing.

**Comment by wyattks** [comment]
receipt csv is correct. - tested with HP, KPCO, KPGA and KPNW
Ready for Stage

**Comment by wyattks** [comment]
Tested in Stage with HP
Ready for production

**Comment by JoeArmani** [comment]
Closing. This is in production.
