### ISSUE TITLE
Update KP My Samples pages

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connect#852]
Update KP My Samples pages, tracked here:

KPCO: https://nih.app.box.com/file/790077248266?s=p0o37qk0ao4zou37korimmxdq6ki06gb
KPGA: https://app.box.com/s/9bkqifdw5zz6kleaj6j12167d0hscofc
KPHI: https://nih.app.box.com/file/790077372511?s=tmxtgx1hh461fwgra3jerbts3bbd3ug7
KPNW: https://nih.app.box.com/file/790079045588?s=k9xap14sgt11wq184dwpl03clkgykog7

**Comment by jhflorey** [comment]
Approved PR https://github.com/episphere/connectApp/pull/694

**Comment by sonyekere** [comment]
Merged to Dev - 1/11

**Comment by ramavavi** [comment]
Tested in dev and ready for stage

**Comment by cunnaneaq** [comment]
Reviewed KP MySamples pages in stage.  A few minor changes needed to each site.

**Comment by JoeArmani** [comment]
This has been given the green light despite minor changes requested - confirmed in teams chat.
Ready for prod.

**Comment by JoeArmani** [comment]
Closing. This is in production.
