### ISSUE TITLE
BPTL Dashboard: Revamp Package Receipt Page to reflect updated functionality (Biospecimen) (September release)

### ISSUE THREAD

**Issue by abhinavjonnada82** [episphere/connect#853]
Title^^

- Remove Home Collection - Collection Card Entry Details
- Remove "home collection" drop down below Receive Packages
- Update _packageReceipt.js_ code accordingly

**Comment by erincschwartz** [comment]
Please also update the section title from "Receipts" to "Site Shipment Receipts" (see screen shot)
![image](https://github.com/episphere/connect/assets/157617486/11464e23-7563-410f-a449-cca2f5a70611)

**Comment by sonyekere** [comment]
DevOps member assigned to this issue will also work on #971

**Comment by sonyekere** [comment]
Could wait until June.

**Comment by erincschwartz** [comment]
@Gbarra9 please make sure that functionality remains for site shipment search in Boxes table when making these updates, there might be underlying programming. Let me know if you have questions/want to screen share as you work on this

**Comment by erincschwartz** [comment]
@Gbarra9 Please update 'Shipping Report' below to say 'Site Shipping Report'

![Image](https://github.com/user-attachments/assets/a4b2c753-c7b1-4f61-956e-4324c68073ce)

Also, when receipting site shipments, this error message is popping up, despite the green banner at the top indicating that the package was successfully receipted: 
![Image](https://github.com/user-attachments/assets/8335f407-a80d-4f1b-bf09-3d1d809b8ae2)


I tried a few packages and got the same message for each, can you look into this?

**Comment by erincschwartz** [comment]
Tested in Dev, ready for Stage. 

- Labeling updates look good
- No error message presenting upon successful package receipt
- Confirmed that packages receipted fell off of the In Transit list 
- Tested using the wrong tracking number and error message presented to indicate 'No box found,' could not receipt package

**Comment by erincschwartz** [comment]
Stage testing complete, ready for Prod

- All titles are updated as requested
- Reports are rendering as expected
- Package receipt functionality working correctly
