### ISSUE TITLE
Biospecimen Dashboard: Sanford user can't create a box or add a box in shipping dashboard 

### ISSUE THREAD

**Issue by abhinavjonnada82** [episphere/connect#854]
One of Sanford's user can't create or add a box only in DEV & STAGE. The variable _user.email_ appears to be undefined and could be a possible cause for not being able to create or add a box.

Here are the console.log screenshots:
<img width="406" alt="Screenshot 2023-12-28 at 11 02 19 AM" src="https://github.com/episphere/connect/assets/30497847/e5ccdb1a-2016-4eca-8ff6-b58b5f3ddb01">
<img width="438" alt="Screenshot 2023-12-28 at 11 05 21 AM" src="https://github.com/episphere/connect/assets/30497847/f73a3eda-f9fe-4918-9087-e3129a9e2999">

**Comment by sonyekere** [comment]
Abhinav to connect with IT - 12/2
