### ISSUE TITLE
Home Collection - Make the warning banner disappear after a few seconds. (Biospecimen)

### ISSUE THREAD

**Issue by abhinavjonnada82** [episphere/connect#855]
**Issue 1:**
Warning messages that appear in Kit Assembly seem to persist until manually closed. To enhance the user experience, the warning message banner should disappear after a few seconds.

Refer this line of [code](https://github.com/episphere/biospecimen/blob/dev/src/pages/homeCollection/kitAssembly.js#L294) & use `alertTemplate()` instead of `triggerErrorModal()`

**Issue 2:**
Need to investigate:
In Kit Assembly, when the cup id/card id & supply kit/return kit are not the same, an error message appears below the input field. Once the fields are the same, the error message disappears. Stephanie noticed that the warning message persists even after submitting a kit. A proper investigation needs to be performed, and the issue needs to be fixed if it exists.

More info: https://github.com/episphere/connect/issues/847#issuecomment-1872263740

**Comment by StephanieWeinstein** [comment]
Hi @abhinavjonnada82 , rather than having the warning banner disappear after a few seconds, can it disappear after the issue is fixed?  (after the user scans in new supply and return kit IDs that have not been used before).  In other words, it conducts another QC check and if ok now, then the banner goes away.

**Comment by Gbarra9** [comment]
PR Review Status - Approved and left comments 
- https://github.com/episphere/biospecimen/pull/650

**Comment by jhflorey** [comment]
Approved PR https://github.com/episphere/biospecimen/pull/650 and left a minor comment.

**Comment by ramavavi** [comment]
In dev and ready for testing.

**Comment by wyattks** [comment]
Tested in Dev, ready fr Stage

**Comment by wyattks** [comment]
Tested in Stage- reasy for Prod

**Comment by sonyekere** [comment]
In Prod for the January release.
