### ISSUE TITLE
Biospecimen Dashboard: Update participants eligibility criteria for home collection

### ISSUE THREAD

**Issue by abhinavjonnada82** [episphere/connect#857]
Title^^
Enable home collection for all sites & update date filter to 01-01-2024.

**Comment by sonyekere** [comment]
In Dev and ready for testing.

**Comment by sonyekere** [comment]
Kathleen to check if participants are showing up only after Jan 1st . A check in Dev is needed.

**Comment by wyattks** [comment]
Tested in Dev - only clinical particpants and nothing before the set date showed up on the Home Collection screen.
Ready for Stage

**Comment by wyattks** [comment]
Tested in Stage ready for prod

**Comment by sonyekere** [comment]
In Prod for the January release.
