### ISSUE TITLE
Mod 1 SOCcer Updates

### ISSUE THREAD

**Issue by anthonypetersen** [episphere/connect#858]
This is for tracking the PWA changes tied to https://github.com/episphere/questionnaire/issues/279

PWA Development Work needed:

update event listener to listen for submission of WORK3B / WORK7B
grab information from WORK3 / WORK7 within event listener functionality
pass all information to SOCcer, along with parameter for n which we want to be 6

**Comment by Gbarra9** [comment]
PR Review Status - Approved
