### ISSUE TITLE
NCI health care system misspelled

### ISSUE THREAD

**Issue by danielruss** [episphere/connect#86]
When a participant joins the connect study with a token/pin, (s)he is asked about his/her healthcare system.  The National Cancer Institute health care system is misspelled as "Nacioal Cancer Institute".  Please correct the spelling

**Comment by danielruss** [comment]
This is a test issue for the github training for non-developers.

**Comment by bhaumik55231** [comment]
Typo is fixed.

**Comment by bhaumik55231** [comment]
Closing this issue.
