### ISSUE TITLE
Implement draft functionality for notification specs in SMDB

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connect#860]
@we-ai, @HanaShiho and Deanna met on 1/8 to discuss requirements and Warren shared mockups of the draft notification functionality in SMDB. This will allow users to save a spec as a draft that will not go out to any test account or real account. Draft notifications will be saved in their own bucket available under the Notifications tab of SMDB and accessible by multiple users just like other specs.

Warren currently working on implementing functionality for review in Dev

**Comment by we-ai** [comment]
This functionality can be tested @depietrodeanna, @HanaShiho, @brotzmanmj

**Comment by HanaShiho** [comment]
tested in dev and looks good. @we-ai can you please remind me whether we'd have an option to delete draft notifications?

**Comment by we-ai** [comment]
Currently there's no option in the UI to delete a notification schema, no matter it's completed or a draft. Adding the deletion functionality is certainly doable. @HanaShiho

**Comment by HanaShiho** [comment]
Thank you @we-ai. No worries, we think it would be useful to have that option but not MVP.

**Comment by HanaShiho** [comment]
@we-ai can you please add an option to save a draft as a completed notification schema? We'd like to be able to convert a draft to final. Currently, on the draft schema page, both "Save Changes" and "Save as Draft" do the same thing which can be confusing. Can we change "Save Changes" to "Save as Completed Schema"?  We are OK with globally changing "Completed" to "Final" if the text/label gets too long.

**Comment by we-ai** [comment]
"Save Change" is what you need, to save a draft as completed schema. The two are not doing the same thing, as I mentioned earlier in my shared slides as well as pop up messages.
We better have a meeting to reach a consensus, instead of messaging back and forth.

**Comment by HanaShiho** [comment]
Deanna and Hana will perform additional testing in dev to ensure everything is working as intended.

**Comment by HanaShiho** [comment]
Dev complete

**Comment by we-ai** [comment]
Tested on 1-30-202. Ready for production.

**Comment by we-ai** [comment]
This functionality is in production.
