### ISSUE TITLE
Reports Dashboard - in the Daily Review Report, the Fargo South University collection location is showing as “undefined.” (Biospecimen)

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#862]
Maddi sent a message letting us know that the the Fargo South University collection location is showing as “undefined" in the Daily Review Report.
I have uploaded teh screenshot she sent.

![Image](https://github.com/episphere/connect/assets/64605220/a32c1d68-62d0-42f9-a7ce-3a9d811db24c)

**Comment by JoeArmani** [comment]
Hi @wyattks, how about the `Filter by Collection Location` dropdown? It looks like 'Fargo South University' should be an option there, but isn't included yet - do we want that option? Thanks.

**Comment by wyattks** [comment]
yes please

**Comment by wyattks** [comment]
Another item mentioned by MArshfield is On the Check Out Report, the time displayed for Check-In Date/Timeis 6 hours later then the actual time the participant was checked in. The example they sent was, the participant was checked-In at 13:09 and it showed up in the report as 19:09.



![Image](https://github.com/episphere/connect/assets/64605220/a2add520-d7f3-4d02-a26f-93ec883edf7b)

**Comment by wyattks** [comment]
Sanford has the same issue with the Check-In Report times.
From 1/19/2024 "I just had some participants donate this morning at the Sanford Fargo site and my report times are incorrect. 
They came in around 8 and 8:30 this morning and are showing after 2pm time stamps."


![Image](https://github.com/episphere/connect/assets/64605220/42535b71-7c85-4de6-a339-83dde488dc75)


From 1/18/2024  "He arrived at 12:28, samples were drawn at 1237. He was checked out at 12:54.
Times in the check out report say 18:28, 20:21 and 20:32."

**Comment by JoeArmani** [comment]
Okay - we'll look into the time handling on these reports. Maybe the time is being stored in UTC and not being converted back to local.
Do you know off hand: are the Marshfield and Sanford sites with this issue in the same time zone?

**Comment by wyattks** [comment]
Yes they are both in the same time zone (CST)

**Comment by JoeArmani** [comment]
That makes sense:
CST is -6 UTC. Thanks!

**Comment by wyattks** [comment]
Ah!  That does make sense then.

**Comment by JoeArmani** [comment]
@brotzmanmj That's a major benefit to storing times in the `ISO 8610` format we use. We should be able to make this conversion to the user's local time zone, assuming this time format is what's stored in Firestore.

Confirming that's the result I'll target when I'm working on this update.

**Comment by JoeArmani** [comment]
Hi @wyattks, I have some questions about Biospecimen reports:

(1) What report is this screenshot taken from? https://github.com/episphere/connect/issues/862#issuecomment-1900634611

(2) I’ve noticed something about the pagination: If you’re on page 2, 3, 4, ect of the shipping report and you click ‘view manifest’, you go into the report. Then, clicking ‘return to reports’ brings you back to page 1. Is this desirable, or would it be better to return to the page you were on when clicking 'return to reports' if possible?

(3) The speed issue only seems to apply to ‘shipping reports.’ Is this accurate?

(4) I’ve found the following reports:
Home -> reports ->
-shipping report
-check out report
-daily review report

Home -> BPTL ->
-shipping report

Is this the complete list, or are there any others?

**Comment by wyattks** [comment]
1 - Screen shot id from the reports page - "Daily Review Report"
2 - I noticed this as well.  It woufl be better to return to the page you were on when click return to reports.
3 - yes, I believe so.  I haven't encountered it elsewhere
4 - This is the complete list. We are working with BPTL on potential Home Collection reports they will need, not close on having that complete.

**Comment by JoeArmani** [comment]
Perfect. Thanks Kathleen

**Comment by sonyekere** [comment]
Pending Norma's feedback of PR.

**Comment by JoeArmani** [comment]
The pending question is whether CSV reports should continue to use UTC or be updated to local time.

**Comment by wyattks** [comment]
Norma wants the time in the csv files left in UTC and would like the receipt time to show up in the receipt csv files with the date.

**Comment by JoeArmani** [comment]
Update: The 'received timestamp' sets the date but not the time portion. This would involve updating search functions, using a Firestore index, and updating a few other items in the app, so the CSV 'Date Received' change to include date and time has additional complexity and will be handled in the future.

**Comment by JoeArmani** [comment]
PR Ready for review: https://github.com/episphere/biospecimen/pull/667

**Comment by sonyekere** [comment]
Pending one final bug check in dev

**Comment by JoeArmani** [comment]
After further discussion with @wyattks, this is tested in dev and ready for stage.

**Comment by JoeArmani** [comment]
Closing - in production.
