### ISSUE TITLE
Biospecimen Dashboard - Remove ACD tube from Collection Data Entry Screen (Biospecimen)

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#863]
At the end of February 2024, the current ACD tubes we have on hand will expire.  After this point we will no longer have the Research or Clinical site collect the ACD tube.

We need the ACD tube removed on March 1, 2024 (but not before) from the Collection Data Entry screens.

**Comment by sonyekere** [comment]
Won't be needed until the March release

**Comment by StephanieWeinstein** [comment]
Hi all - in the Leads meeting now. We would like this for the Feb push. We will plan the push for Feb 29th in the evening so this timing would work.

**Comment by bransteitterbr** [comment]
PR Submitted https://github.com/episphere/biospecimen/pull/666

**Comment by wyattks** [comment]
HI @bransteitterbr the ACD tube is still showing up on the Research Collection Screen in dev.

**Comment by wyattks** [comment]
Was able to test once Brian removed the March 1st date requirement.  ACD tube does not appear.
Ready for Stage.
