### ISSUE TITLE
Home Collection - Unexpected Behavior in Kit Assignment Confirmation (Biospecimen)

### ISSUE THREAD

**Issue by abhinavjonnada82** [episphere/connect#865]
Title^^

**Unexpected Behavior:**
When a kit has been assigned to a participant, a success banner is triggered immediately, which is expected behavior. However, an error banner is also triggered simultaneously.

**Expected Behavior:**
Upon assigning a kit to a participant, either a success banner or an error banner should be triggered based on the predefined conditions.

_Further Investigation Required_

**1/25:** Upon investigation, it was noted that the confirm assignment button is being propagated twice when clicked only once. This leads to double API calls being made, resulting in the success and error banners appearing one after the other. 
**Resolution**: Appropriate safeguards have been implemented to prevent double propagation.

**Comment by wyattks** [comment]
I just tried assigning kits and it is working as expected in Dev.

**Comment by wyattks** [comment]
Tested in Stage- ready for prod
