### ISSUE TITLE
PROMIS Scores Return (April Release)

### ISSUE THREAD

**Issue by mnataraj92** [episphere/connect#870]
Description: we will send PROMIS data via API and receive scores returned to us.

PROMIS Survey Variables:
3-month Quality of Life (PROMIS) survey completion (320303124)
Autogenerated date/time stamp for Start of PROMIS survey (870643066)
Autogenerated date/time when PROMIS survey completed (843688458)
GitHub/Survey Version for PROMIS (490327747)

PROMIS T-scores and Standard Error Variables: 
t-score for physical function, PROMIS-29 (608953994)
t-score for anxiety, PROMIS-29 (328149278)
t-score for depressive symptoms, PROMIS-29 (297016093)
t-score for fatigue, PROMIS-29 (410751656)
t-score for sleep disturbance, PROMIS-29 (990793746)
t-score for ability to participate in social roles and activities, PROMIS-29 (393186700)
t-score for pain interference, PROMIS-29 (370227545)
t-score for social interactions, PROMIS-29 (697423629)
t-score for social isolation, PROMIS-29 (129202138)
t-score for cognitive function, PROMIS-29 (755066850)
Standard error of t-score for physical function, PROMIS-29 (582985641)
Standard error of t-score for anxiety, PROMIS-29 (281351288)
Standard error of t-score for depression, PROMIS-29 (144446277)
Standard error of t-score for fatigue, PROMIS-29 (101862879)
Standard error of t-score for sleep disturbance, PROMIS-29 (218828500)
Standard error of t-score for functioning in social roles and activities, PROMIS-29 (801982443)
Standard error of t-score for pain interference, PROMIS-29 (766974306)
Standard error of t-score for social interactions, PROMIS-29 (424548783)
Standard error of t-score for social isolation, PROMIS-29 (633951291)
Standard error of t-score for cognitive function, PROMIS-29 (132343154)
Physical health summary score (406189298)
Mental health summary score (463357603)
Standard error, Physical health summary score (630061935)
Standard error, Mental health summary score (294735356)

We would send for the PROMIS scores immediately following the submission of the survey.

There isn’t a technical plan in place yet, once development begins, we will assess the structure the PROMIS API requires and determine what transformation needs to be done from our end.

**Comment by jacobmpeters** [comment]
I set up a flattening configuration for this in DEV [3c7b309](https://github.com/Analyticsphere/flatteningRequests/commit/3c7b309bdc4b97a3ba0a27292412d22288ac0534)

**Comment by anthonypetersen** [comment]
Unless I hear back today regarding the production PROMIS API server, this will be pulled from dev and will not go live this release.

**Comment by m-j-horner** [comment]
That's reasonable. Thanks, Tony.

**Comment by anthonypetersen** [comment]
Code has been temporarily removed from dev

**Comment by anthonypetersen** [comment]
@jacobmpeters this is in stage, please let me know when your team has confirmed things look good

**Comment by jacobmpeters** [comment]
@anthonypetersen Thanks for the heads up.

I did notice a couple fields for which there are mixed datatypes. It looks like values for `D_424548783` and `D_697423629` are sometimes given as integers and sometimes given as floats. Can we standardize this so that we don't end up with multiple BQ tables?

environment | table_schema | table_name | column_name | data_type 
-- | -- | -- | -- | -- 
STG | Connect | promis_v1 | D_424548783 | STRUCT<integer INT64, float FLOAT64, provided STRING> 
STG | Connect | promis_v1 | D_697423629 | STRUCT<integer INT64, float FLOAT64, provided STRING>

**Comment by anthonypetersen** [comment]
@jacobmpeters can you check if they look good now?

@sonyekere we probably want to get someone from the ops team to submit a few different PROMIS surveys with various scenarios (answering all question, leaving some blank, varied responses, etc.) to ensure that our data structure is still fine after.

**Comment by jacobmpeters** [comment]
@anthonypetersen I checked the BQ tables and the mixed type issue is resolved.

**Comment by sonyekere** [comment]
@anthonypetersen thanks for the alert. @cusackjm or @m-j-horner , will you be able to submit a few different PROMIS surveys to help us verify the data structure?

**Comment by sonyekere** [comment]
@cunnaneaq will be able to verify this. Thanks, Aileen, for stepping in despite the limited bandwidth available across the Ops team.

**Comment by cunnaneaq** [comment]
I submitted 5 Quality of Life surveys and documented my responses in this [spreadsheet](https://nih.app.box.com/file/1537327369663).  Please refer to tabs labeled 1, 2, 3, 4, and 9 - 1 (responded to all questions), 2 (responded to all questions), 3 (mix of responses and no responses), 4 (mix of responses and no responses), and 9 (did not respond to any questions).  Each tab contains the Connect ID, account email, device, and browser used to test.

**Comment by anthonypetersen** [comment]
@cunnaneaq thank you! can confirm that scoring results posted for participants that have responses, @jacobmpeters do you want to confirm that everything structurally looks as expected?
