### ISSUE TITLE
Data updates/cleanups related to notification functionality

### ISSUE THREAD

**Issue by we-ai** [episphere/connect#871]
After Jan (2024) release, I suggest we do data updates/cleanup in Firestore related to notification functionality as below.

Key in `notificationSpecifications` collection:
- isDraft
  - Reason: This new key is used to identify draft schemas.
  - Todo: Add `isDraft` as false for docs missing this key; after updating data, also update `retrieveNotificationSchemaByCategory` function in "firestore.js" file for quicker data retrieval.
  - Priority: Low.

Keys in `participants` collection:
- query.notificationSpecIdsUsed
  - Reason: After Jan (2024) release, data held inside this key is no longer used for notifications query.
  - Todo: Remove this key from all participants docs
  - Priority: Low.

- 646873644 (can we text to this number)
  - Reason: Mixed data types (string and number).
  - Todo: Convert strings to numbers; remove code handling mixed data types in "notifications.js" file in ConnectFaas repo.
  - Priority: Low.

Please comment on above suggested data changes @anthonypetersen @jacobmpeters  @FrogGirl1123 @brotzmanmj.

**Comment by anthonypetersen** [comment]
All of these sounds like logical cleanup tasks, will want Analytics to confirm work for CID 646873644

**Comment by jacobmpeters** [comment]
Thanks, Warren and Tony.

I don't think that the Analytics team currently uses the `notificationSpecifications` collection or the `query.*` object. So I don't have an opinion on those.

Regarding 646873644, I agree with avoiding/correcting mixed type entries. Converting strings to numbers is fine with me.

**Comment by we-ai** [comment]
Above suggested data updates are done, with details [here](https://nih.app.box.com/folder/249194550185).
