### ISSUE TITLE
store date when survey is triggered

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#872]
Request to store date/time stamp when each survey is triggered to a participant.

Discuss if this is technically possible going forward, ideally to start with release of the PROMIS/QOL survey and apply to all surveys.

Reason is to have definitive date for metrics and also for messaging conditionality.

**Comment by brotzmanmj** [comment]
@anthonypetersen  and @mnataraj92  do we need this separate issue for storing the QOL/PROMIS survey issued date (and perhaps the update to the survey status flag for 'not yet eligible' or track both in the SMDB / Biospec DB issue?

**Comment by anthonypetersen** [comment]
@brotzmanmj doesn't matter to me where they are tracked

**Comment by anthonypetersen** [comment]
to clarify.. we said tracking when surveys became available wouldn't be ready for this release, correct?

**Comment by brotzmanmj** [comment]
I think we would like to track when the PROMIS survey becomes available, but not all the other surveys

**Comment by brotzmanmj** [comment]
@anthonypetersen @mnataraj92 Decided in discussion today that the 3-mo PROMIS survey will trigger based on the first notification (email) being sent, so the date/time of that email in the Notifications table will serve at the date/time the survey was sent. Therefore, no separate variable is needed. Madhuri, can you note this somewhere in the Data Dictionary?

**Comment by mnataraj92** [comment]
Sure, I can add that in the notes of the QOL survey status variable (d_320303124)

**Comment by anthonypetersen** [comment]
@brotzmanmj can this issue be closed?

**Comment by brotzmanmj** [comment]
yes
