### ISSUE TITLE
Update UI displaying notifications that have been sent

### ISSUE THREAD

**Issue by we-ai** [episphere/connect#875]
Errors to fix:
- `undefined` as title of SMS messages
- Incorrect font color when system is in dark mode.

Also, since we're now having emails and SMS messages in notifications, it'll be clearer to change the title of page from "Participant Messages" to "Participant Notifications".

Please comments on these suggested changes @depietrodeanna @brotzmanmj.

**Comment by brotzmanmj** [comment]
Hi @we-ai  The two errors to fix sounds good to me. Thank you for catching those.

For the change the title of page (Issue you mean not he SMDB? There is also a page on MyConnect), I'm less inclined to go to the trouble to change this. Eventually, we will update the MyConnect to a new design and can address this then.

**Comment by we-ai** [comment]
Thanks for confirming the 2 fixes. @brotzmanmj
I meant title of the page in SMDB. I'll leave it as is. 
I didn't know we have a such page in MyConnect.

**Comment by brotzmanmj** [comment]
@we-ai  for the two fixes, can you tell me where these are to be fixed? The SMDB? Also MyConnect? or is this something that also reflects on the particpant's device? Just for planning of where we need to test.

**Comment by we-ai** [comment]
@brotzmanmj The fixes are in SMDB page displaying participant history notifications. Below is a screenshot showing the 2 problems mentioned:
<img width="680" alt="image" src="https://github.com/episphere/connect/assets/47251797/84fc1879-f577-4b8b-814b-610a412183f7">
We know the `undefined` SMS message title (problem 1) before. Also, my computer is in dark mode, and the font color of all notifications is white and is almost invisible (problem 2). These are the 2 fixes I meant.

Tests are very straightforward: 
- Go to check the SMDB page showing participant notifications, to make sure each SMS message have a title
- Change computer system color to dark mode, and check participant notifications to make sure all history notifications are still correctly displayed

**Comment by brotzmanmj** [comment]
Thanks @we-ai . Can you also check MyConnect and see if these changes work there?

**Comment by we-ai** [comment]
MyConnect also has these issues (`undefined` SMS message title; white text color under dark mode), as shown below:
<img width="906" alt="image" src="https://github.com/episphere/connect/assets/47251797/f87df59d-6d32-433f-a3d7-ca10b086ddea">

Code updates in SMDB won't affect MyConnect site. These 2 sites use different code base.
Below fixes are needed for MyConnect:
- `undefined` title of SMS messages
- White text color in email notifications

**Comment by we-ai** [comment]
[Here](https://nih.app.box.com/file/1439354377937) is the file describing how to test above implementations.

**Comment by HanaShiho** [comment]
Confirmed the two fixes in SMDB and PWA

**Comment by HanaShiho** [comment]
Ready for prod
