### ISSUE TITLE
QOL/PROMIS Survey PWA/Trigger

### ISSUE THREAD

**Issue by robertsamm** [episphere/connect#877]
Here is a link to the IRB approved Quality of Life (PROMIS) survey that contains the content we will use, comprised of 4 forms:
https://nih.app.box.com/file/1350598900472

The forms have these four names:
PROMIS–29 Profile v2.0 ( single pain intensity item will be replaced with the IRB-approved pain intensity question from Module 2)
PROMIS Item Bank v2.0 - Satisfaction with Social Roles and Activities
PROMIS Item Bank v2.0 - Social Isolation – Short Form 4a
PROMIS Item Bank v2.0 – Cognitive Function- Short Form 4a

The Quality of Life survey will be programmed and rendered in Quest. Expected delivery from IMS is 2/8. The status of their completion (not started, started submitted and date/times of status) will be programmed similar to other surveys. 

The QOL survey should display on the PWA To Do list as 'Quality of Life Survey' with time est. to complete '10-15' minutes.

For the survey trigger: the survey will be triggered 3 months post-verification 
- For launch: only trigger to people prospectively for those people not yet at 3 months post-verification. Do not trigger to people who have already reached 3 months post-verification.
- Post-launch: We will evaluate the survey data for the people who receive the survey above. And then at a future timepoint (likely 1 month post-launch) we will trigger the survey to render for all those in the backlog who were already at 3 months post-verification at time of launch.

**Comment by anthonypetersen** [comment]
What is the "description" of this survey for the PWA To Do list?

**Comment by anthonypetersen** [comment]
Thoughts on placement / wording for the Biospecimen Dashboard?

![image](https://github.com/episphere/connect/assets/18222069/8ba474dc-dd38-48ce-a450-1a55a5e27f5e)

**Comment by robertsamm** [comment]
> Thoughts on placement / wording for the Biospecimen Dashboard?
> 
> ![image](https://private-user-images.githubusercontent.com/18222069/301958499-8ba474dc-dd38-48ce-a450-1a55a5e27f5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MDQ1NTgsIm5iZiI6MTcwNjkwNDI1OCwicGF0aCI6Ii8xODIyMjA2OS8zMDE5NTg0OTktOGJhNDc0ZGMtZGQzOC00OGNlLWE0NTAtMWE1NWE1ZTI3ZjVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDIwMDQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwMjdkMGY4OTlkMjIzMTE2YWNhZDlkYjliODNkNWUzZDc5OWU4YmZiNTM1ZWIxOGNkY2E0YTg0YTNjYTY0ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.doIEXRXBvHjxHxmy10kAw8C_huAIeFsWu_r8ZLkV-iU)

See separate github issue for BSD update for QOL survey here: https://github.com/episphere/connect/issues/878. Can you add this screenshot there and Erin and Kathleen will weigh in? I think this looks good in my opinion.

**Comment by robertsamm** [comment]
> What is the "description" of this survey for the PWA To Do list?

@cusackjm or @HanaShiho do you have the description of the QOL survey for the PWA to do list? I know you were working on this with Deanna but I don't see it in the requirements doc or the email thread to add it here.

**Comment by brotzmanmj** [comment]
@anthonypetersen  Here's the description from Deanna: Questions about your physical, social, and mental health

**Comment by anthonypetersen** [comment]
@robertsamm @brotzmanmj please see the attached document...

[PROMIS Forms.txt](https://github.com/episphere/connect/files/14181525/PROMIS.Forms.txt)


When calling the PROMIS API these are all of the unique forms that can be referenced when requesting scoring results. None of them exactly match the names of the forms being called out in the requirements for this issue. There are some that are close, but there are plenty that come very close to the names of these forms. Can you all please confirm which forms specifically are being used so I can request the correct results?

**Comment by brotzmanmj** [comment]
@cusackjm  can you get Tony the information he needs? Ask Marie Josephe if you're not sure?

**Comment by anthonypetersen** [comment]
@brotzmanmj Julie is OOO all week. 

@m-j-horner do you know the answer to this?

**Comment by anthonypetersen** [comment]
@brotzmanmj From a dev ops POV I don't think we need to backfill anything. We will set the status CID for the survey to be "Not Eligible" for new participants by default, but the displaying of the survey won't happen for anyone until their status is set to "Not Yet Started" which will be controlled through the first email.

**Comment by brotzmanmj** [comment]
@anthonypetersen For the display of the survey status on the SMDB and the Biospec DB, what will show for people if we don't backfill?

**Comment by anthonypetersen** [comment]
@brotzmanmj good point, we can backfill

**Comment by brotzmanmj** [comment]
Thanks. Also @anthonypetersen  we have one more requirement for the PWA, can we add here? The yellow bar message that appears on the PWA whenever we release a new survey to someone, we forgot to mention that we should have this for the QOL Survey. 
This is the message that appears. 'You have a new survey to complete'
Expected behavior: For our other surveys, the message only shows the first time the participant logs into MyConnect after the survey is triggered.  When the user refreshes the page or signs in for a second time, the yellow bar message does not display.

**Comment by robertsamm** [comment]
Survey trigger looks good in stage, ready for prod.

**Comment by cusackjm** [comment]
Passed stage testing and backend testing
