### ISSUE TITLE
Add QOL/PROMIS survey to SMDB and BSD

### ISSUE THREAD

**Issue by robertsamm** [episphere/connect#878]
Add QOL/PROMIS survey to Study Manager Dashboard and Biospecimen Dashboard

1. On SMDB Participant summary page:
- a new row should be added to the participant summary page for the Quality of Life survey between the 'home mouthwash survey' and the 'blood sample collection' rows
- Timeline: 'Follow-Up' (_to confirm with Michelle)_
- Category: 'Survey'
- Item: 'QOL'
- Status:  PROMIS survey completion status ( CID 320303124) of not started, started, submitted
- Date: time stamp for started' if survey completion status=started (870643066) or time stamp for completed if status=submitted (843688458)
- Setting: 'N/A'
- Refused: Tie to 'refusal of all future surveys' and 'all future study activities'. (_Discussing with Michelle whether we need additional r/w categories for this_)
- Extra: 'N/A'

2. Add QOL survey to check-in screen on BSD - @erincschwartz and @wyattks, please add reqs

**Comment by anthonypetersen** [comment]
Thoughts?
![image](https://github.com/episphere/connect/assets/18222069/5037a7b2-8e07-4901-a85a-c66c11a64609)
@wyattks @erincschwartz

**Comment by erincschwartz** [comment]
I think this looks great

**Comment by anthonypetersen** [comment]
SMDB @robertsamm 
![image](https://github.com/episphere/connect/assets/18222069/c735f9a9-f651-48e9-8692-1b08def75f40)

**Comment by robertsamm** [comment]
Hi @anthonypetersen this looks good. For the timepoint can we change it to 'Follow Up - 3mo'? Since this is a repeated measure and the first 'follow up' item we are putting in Michelle reminded me it would be good to be more specific for the follow up timepoint.

**Comment by anthonypetersen** [comment]
absolutely, see below
![image](https://github.com/episphere/connect/assets/18222069/dbbe981b-23d6-43ac-a6e9-2079da76950f)

**Comment by anthonypetersen** [comment]
NOTE: BSD and SMDB changes will not be seen in dev until initial PR is ready to merge for PWA and API

**Comment by robertsamm** [comment]
Looks good, once in dev will test once the survey has been added so we can confirm the survey completion status and refusal status changes work as expected

**Comment by erincschwartz** [comment]
@anthonypetersen, as previously mentioned, it will be helpful for study teams to know from the check-in screen of the Biospecimen Dash whether a participant is eligible for the QOL survey. Please incorporate "not yet eligible" as a status in the dashboard for participants who are completing their biospecimen visit prior to the survey being triggered 90 days post-verification

**Comment by anthonypetersen** [comment]
@FrogGirl1123 From an analytical perspective do we think it would be helpful to add a new CID to represent that and add it into our grouping of status CIDs? (not started, started, submitted) Or would you rather just keep things as is? From a dev ops perspective we can just add logic to display Not Yet Eligible versus Not Started if we keep things as is. Or else if we add a new CID to represent "Not Yet Eligible" our logic for displaying would remain pretty much as is, but we would probably need to add code to transition surveys into an Eligible state as well as potentially update the default variable of certain CIDs

**Comment by anthonypetersen** [comment]
I'm fine with that, if we want to add the status to other surveys it will likely have to come in later releases.

**Comment by mnataraj92** [comment]
I can add it to the DD change log to add Not Yet Eligible" as an additional status for the PROMIS/QOL survey flag and note that this only applies to this survey for now

**Comment by anthonypetersen** [comment]
@mnataraj92 please ping me when the CID for "Not Yet Eligible" is created, thanks!

**Comment by mnataraj92** [comment]
Will do! Once the DD change log items are approved I'll add them to the DD and let Gene know to run the CIDs

**Comment by robertsamm** [comment]
@anthonypetersen discussed w/ Michelle and the survey status on the SMDB for the QOL survey should not be influenced by the type of refusal they have. So for individuals who refuse 'all future surveys' or 'refused all future activities' it should show whatever their actual survey status is instead of 'N/A' under 'Status' (for people who refused prior to the survey trigger this would be 'not yet eligible'). Can you update this for the QOL survey row?

this is the same for other surveys too, esp as for the baseline surveys the participant could technically complete their baseline survey even after they refused it as it would still appear on the participants To Do list in the PWA. But those survey status rows don't need to be fixed in this release. I'll add as a separate issue for March.

**Comment by robertsamm** [comment]
@anthonypetersen also for 'refused 3-month quality of life survey'. should show as survey status not 'N/A'

**Comment by robertsamm** [comment]
@anthonypetersen Hi Tony, we have several test accounts that were created and verified today. The first message is set to go out +1 days post-verification (so tomorrow, 2/27) but the QOL survey status in the SMDB is showing as 'Not Started' when it should be showing as 'Not Yet Eligible' as the survey hasn't triggered to these people yet. It will trigger tomorrow for the people who meet all the criteria. I doublechecked and they don't have the survey in their PWA To Do List yet nor the first message to complete the QOL survey.

![image](https://github.com/episphere/connect/assets/67074735/b57be545-6483-4f0b-9c4a-77e4f8dd8c80)


Here's some example Connect IDs: 
7869918375
4878672919
2108903868
2418892195
6431657940
1411038445
6738672071
4765218968
1316002636
2518625341

**Comment by erincschwartz** [comment]
@anthonypetersen I looked up a couple of these test participants in the HP Stage BSD and the QOL survey status is presenting there correctly, as 'Not Yet Eligible"

**Comment by robertsamm** [comment]
Thanks @anthonypetersen, tested the fix and looks good

**Comment by robertsamm** [comment]
Looks good in stage, ready for prod.
