### ISSUE TITLE
Add additional refusal options for QOL survey

### ISSUE THREAD

**Issue by robertsamm** [episphere/connect#881]
Michelle and I discussed and think we will need to add additional refusal options for the PROMIS survey. 

Right now the refusal options cover refusal of each specific baseline activity and then for follow up activities it just encompasses 'refuse all future surveys (willing to do specimens) and 'refuse all future study activities'.

For the follow up activities refusals, should we should add 'refuse QOL survey 3-mo (but willing to do other future surveys)' and 'refuse all future QOL surveys (but willing to do other future surveys)' since this is a repeated measure?

@FrogGirl1123  and @mnataraj92  thoughts?

**Comment by brotzmanmj** [comment]
@mnataraj92 can you add these to the Data Dictionary change log?

**Comment by brotzmanmj** [comment]
@HanaShiho and @depietrodeanna  once we have this refusal variable you'll need to add it to the conditionality of the email and SMS messages to exclude people who refused the QOL survey

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj Once these new refusals are tested in stage I can test them in the Operations report. Otherwise I can wait until they have been selected in prod

**Comment by mnataraj92** [comment]
I will add this to the DD change log and pass along the derivation information to Joe. Amelia and I will include the derivation in the test plan for participation status 912301837

**Comment by mnataraj92** [comment]
These variables have been added to the DD change log. These variables should also be displayed in the participant withdrawal page on the SMDB so we can test this as well.

**Comment by brotzmanmj** [comment]
@Davinkjohnson @sonyekere We will need someone to add these two variables to the SMDB on the Participant Withdrawals page so they can be entered. They should go under 'Follow Up Surveys' on the left side of the page 
@robertsamm can point out exactly where on the page

**Comment by robertsamm** [comment]
Please add the two responses to the Participant Withdrawal Page under 'Follow Up Activities - Surveys'. So it should go:

**Follow Up Activities**
  **_Surveys_**
  -Quality of Life 3-Mo Survey (but willing to do other future surveys)
  -All future QOL Surveys (but willing to do other future surveys)
  -All future surveys (willing to do specimens)
  **_Specimen Donations and Specimen Surveys_**
  etc etc

![image](https://github.com/episphere/connect/assets/67074735/b06f4718-6fbf-44f5-8875-134a785a026e)

**Comment by anthonypetersen** [comment]
@robertsamm just to clarify - either of these refusals being selected should cause the QOL to show up as "Refused" on the Participant Summary page?

**Comment by anthonypetersen** [comment]
@robertsamm a better question would be... which items from the Refusal page should cause the QOL survey we are about to implement to show as "Refused"?

**Comment by robertsamm** [comment]
Hi @anthonypetersen 'refusal of the QOL-3 mo survey', 'refusal of all future activities', and 'refusal of all future surveys' should cause the QOL-3 month survey to show as refused in the SMDB Pt Summary.

I think the 'refusal of all future QOL surveys' would be just for the future QOL surveys not encompass the current 3-mo one. @mnataraj92 or @brotzmanmj does that sound correct or am I mis-interpreting?

**Comment by brotzmanmj** [comment]
that sounds correct

**Comment by anthonypetersen** [comment]
This is in dev now

**Comment by KELSEYDOWLING7** [comment]
> d_685002411_d_936015433 Refused QOL survey 3-mo (but willing to do other future surveys) d_685002411_d_688142378 Refused all future QOL surveys (but willing to do other future surveys) d_667960135 Autogenerated date/time for Refused QOL survey 3-mo (but willing to do other future surveys) d_953225775 Autogenerated date/time for Refused all future QOL surveys (but willing to do other future surveys)

Seeing the correct backend data for these variables on the two DEV refusals tests (Connect IDs 4256153654 and 5966690881)

**Comment by KELSEYDOWLING7** [comment]
Refusals are correct on the backend in stage as well for these four test participants (CIDs 1316002636, 2108903868, 2216562729, 3525100951)

**Comment by robertsamm** [comment]
Agreed, looks good in stage ,ready for prod.
