### ISSUE TITLE
BSWH Integration- (Biospecimen) 

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#882]
Biospecimen repository will require an update for site Baylor Scott and White Health (BSWH) integration.

**Comment by Gbarra9** [comment]
Notes from BSWH Integration (Code Changes)

- shared.js
	- siteFullNames
	- siteSpecificLocation
	- locationConceptIDToLocationMap
	- conceptIdToSiteSpecificLocation (specific locations, not site)
	- siteSpecificLocationToConceptId (specific locations, not site)
	- NameToKeyObj (This appears to not be referenced anywhere)
	- keyToNameAbbreviationObj
	- keyToNameObj
	- keyToNameCSVObj
	- keyToLocationObj (specific locations, not site)
	- siteLocations
 
- fieldMapping.js:
	- collectionLocationMapping (specific locations, not site)
	- nameToKeyObj (specific locations, not site)
 
- tubeValidation.js
	- siteSpecificTubeRequirements
 
- welcome.js
researchOnlySiteArray

**Comment by brotzmanmj** [comment]
Update: Here are the sites BSWH would like to start with for research collection and shipping locations.

The one we listed above for BSW Health and Wellness Center should be listed instead as:
BCC- HWC
In addition they would like these four locations for collection and shipping:
BCC- All Saints (FW)
BCC- Plano
BCC- Worth St
BCC- Irving 

Addresses for these are in email from Brittany if needed for the shipping manifests. @wyattks if you can add there here, that would be great, thanks.

**Comment by wyattks** [comment]
BCC- All Saints (FW)- [1307 8th Ave Ste 305, Fort Worth, TX, 76104](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2F1307%25208th%2520Ave%2520Ste%2520305%2C%2520Fort%2520Worth%2C%2520TX%2C%252076104%2F32.73011016845703%2C-97.3431625366211&data=05%7C02%7Ckathleen.wyatt%40nih.gov%7Cfb3c201cc84b4cf64e5108dc54237219%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638477758429425302%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=EDqkvLN%2FilurpXUlePavllz%2B33i1OqSqcLPt23UA4ps%3D&reserved=0)
BCC- Plano- [801 E Plano Pkwy Ste 160, Plano, TX, 75074](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2F801%2520E%2520Plano%2520Pkwy%2520Ste%2520160%2C%2520Plano%2C%2520TX%2C%252075074%2F33.00783157348633%2C-96.70209503173828&data=05%7C02%7Ckathleen.wyatt%40nih.gov%7Cfb3c201cc84b4cf64e5108dc54237219%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638477758429435774%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=qhU6u6Ra4BjIhKr64J3Bd2HiWI8SGYMIq5xmHmzUBao%3D&reserved=0)
BCC- Worth St.- [4001 Worth St , Dallas, TX, 75246](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2F4001%2520Worth%2520St%2520%2C%2520Dallas%2C%2520TX%2C%252075246%2F32.791351318359375%2C-96.77587890625&data=05%7C02%7Ckathleen.wyatt%40nih.gov%7Cfb3c201cc84b4cf64e5108dc54237219%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638477758429443866%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=6i%2BBgPoJhxDXrTPEqDdig7atnYjBPbaXjf%2Bl7OgItI0%3D&reserved=0)
BCC- Irving- [2021 N MacArthur Blvd Ste 210, Irving, TX, 75061](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2F2021%2520N%2520MacArthur%2520Blvd%2520Ste%2520210%2C%2520Irving%2C%2520TX%2C%252075061%2F32.83575439453125%2C-96.96221160888672&data=05%7C02%7Ckathleen.wyatt%40nih.gov%7Cfb3c201cc84b4cf64e5108dc54237219%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638477758429450658%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=2%2B8jKPTMmzxY1QakLCY2AFzHrv0XoAQiKy0iE%2BkDp0o%3D&reserved=0)
BCC- HWC - [4500 Spring Ave , Dallas, TX, 75210](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2F4500%2520Spring%2520Ave%2520%2C%2520Dallas%2C%2520TX%2C%252075210%2F32.77434158325195%2C-96.74207305908203&data=05%7C02%7Ckathleen.wyatt%40nih.gov%7Cfb3c201cc84b4cf64e5108dc54237219%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638477758429457093%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=xPh7FYqVAuAuyFc6r4fBPwS3qZHS%2F%2FfAQgYSHXmvqhk%3D&reserved=0)

**Comment by erincschwartz** [comment]
BSWH would also like the following added as a collection and shipping location: 

NTX Biorepository- 3410 Worth St. Suite 530, Dallas, TX 75246

**Comment by Gbarra9** [comment]
Here are the requested collection and shipping locations so far:

BCC- All Saints (FW)- 1307 8th Ave Ste 305, Fort Worth, TX, 76104
BCC- Plano- 801 E Plano Pkwy Ste 160, Plano, TX, 75074
BCC- Worth St.- 4001 Worth St , Dallas, TX, 75246
BCC- Irving- 2021 N MacArthur Blvd Ste 210, Irving, TX, 75061
BCC- HWC - 4500 Spring Ave , Dallas, TX, 75210
NTX Biorepository- 3410 Worth St. Suite 530, Dallas, TX 75246

I have a question about the manifest portion. What will the naming be for the "Study Team"? What will the email be for the different BSWH site location, will they be the same or different?

Below is a manifest example:

![Image](https://github.com/episphere/connect/assets/33293205/f3bd3178-55ef-49e4-8efb-09eec803c598)

**Comment by erincschwartz** [comment]
@Gbarra9 Please use the following information for the manifest
Study Team: BSWH Connect Study Team
Email: connectbiospecimen@BSWHealth.org  The email will be the same for all BSWH site locations.

**Comment by Gbarra9** [comment]
> @Gbarra9 Please use the following information for the manifest
> Study Team: BSWH Connect Study Team
> Email: connectbiospecimen@BSWHealth.org  The email will be the same for all BSWH site locations. 
> 

 Will do, thanks @erincschwartz

**Comment by erincschwartz** [comment]
@Gbarra9 can you check to ensure BSWH only has access to Research Collection in the Dashboard, not to Clinical Collection at the start

**Comment by Gbarra9** [comment]
Hi @erincschwartz, the code I have at the moment has BSWH with only research dashboard access.

![Screenshot 2024-05-22 at 10 45 01 AM](https://github.com/episphere/connect/assets/33293205/e999375d-d43b-4148-acf2-d691503464ad)

**Comment by erincschwartz** [comment]
@Gbarra9 I just met with BSWH to run through the Biospecimen Dashboard, there are edits needed for the Collection and Shipping Location lists. 

They have requested the following updates to the Collection Location List: 
Location BCC-HWC, BC ---update name to: **BCC-HWC** 
Location BCC-All Saints (FW)---update to **FW All Saints**
Add new location: **BCC- Fort Worth** 

The Shipping Locations are not appearing in Dev, so we could not move through a test shipment. This is what is showing up: 


![Image](https://github.com/episphere/connect/assets/157617486/03556c5a-f49e-4092-87f7-a97c4a297ea0)





BSWH would like all of the Collection Locations listed as Shipping Locations (with edited names and including the new collection location requested above) 

They would also like these lists to appear in alphabetical order. 

Please let me know when these changes are ready for Dev testing.

**Comment by brotzmanmj** [comment]
@erincschwartz  Let's discuss the Fort Worth/All Saints requested changes

**Comment by brotzmanmj** [comment]
@Gbarra9  please hold on this request until we get clarification from BSWH.

**Comment by erincschwartz** [comment]
@Gbarra9 After communicating with BSWH, we do **not** need to add BCC- Fort Worth as a new collection and shipping location (will do this in a later release). 

Please do work to update the name of  BCC-HWC, **BC** location, removing the BC at the end. This location name should just be BCC-HWC


![Image](https://github.com/episphere/connect/assets/157617486/fe2ce583-ab04-4eb1-b6d0-d43acba87444)

And, the shipping locations do need to be added, as mentioned above.

**Comment by Gbarra9** [comment]
> @Gbarra9 After communicating with BSWH, we do **not** need to add BCC- Fort Worth as a new collection and shipping location (will do this in a later release).
> 
> Please do work to update the name of BCC-HWC, **BC** location, removing the BC at the end. This location name should just be BCC-HWC
> 
> ![Image](https://private-user-images.githubusercontent.com/157617486/334912542-fe2ce583-ab04-4eb1-b6d0-d43acba87444.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMTA2MzQsIm5iZiI6MTcxNzAxMDMzNCwicGF0aCI6Ii8xNTc2MTc0ODYvMzM0OTEyNTQyLWZlMmNlNTgzLWFiMDQtNGViMS1iNmQwLWQ0M2FjYmE4NzQ0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQxOTE4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjEwZDYyYzVjOTYzYzNjZThmNTkxY2Q1Y2FjZmE2MjRlYzMyMWNhMzZlNDA0YmI4M2FmNjRjZWRkMDVkYTk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4F8y6_mLxbWqr0qtVcnq_VM79RiDtaqXbrQL50R2By0)
> 
> And, the shipping locations do need to be added, as mentioned above.

@erincschwartz Thanks, I'll start working on this.

**Comment by erincschwartz** [comment]
Adding @rebexxxxxx to this issue since the Collection and Shipping location names will need to be updated in the Data Dictionary when complete.

**Comment by Gbarra9** [comment]
Pull Request was created to address comment issues and suggestions:
- https://github.com/episphere/connect/issues/882#issuecomment-2137784357
- https://github.com/episphere/connect/issues/882#issuecomment-2138092676

Pull Request (pending team review)
- https://github.com/episphere/biospecimen/pull/710

**Comment by erincschwartz** [comment]
@Gbarra9 Shipping locations look good and worked for Jan to ship a collection. I received the collection in the Dashboard and Shipping Manifest and receipt csv file appeared as expected. 

Can you do a check of the backend data and make sure the derived variables look right?  Connect ID: 6391301439 Collection ID: CXA669944

**Comment by Gbarra9** [comment]
> @Gbarra9 Shipping locations look good and worked for Jan to ship a collection. I received the collection in the Dashboard and Shipping Manifest and receipt csv file appeared as expected.
> 
> Can you do a check of the backend data and make sure the derived variables look right? Connect ID: 6391301439 Collection ID: CXA669944

The data looks as expected on the backend. I noted the values and highlighted green for missing keys. 
https://app.box.com/s/shrt7jb9o9powv768u04rj02eqa3fu9n

**Comment by erincschwartz** [comment]
@Gbarra9 I reviewed the backend data document linked above, all derived variables look good. Please note, in the document it states: <265193023>SrvBLM_ResSrvCompl_v1r0 (Blood/urine/mouthwash combined research survey status) - Started (615768760); Firestore and BQ show the status for this variable as 'not started' (which is the expected status)

**Comment by Gbarra9** [comment]
@erincschwartz I'm going to edit the document as 'not started'

**Comment by wyattks** [comment]
Stage testing is complete.  Ready for Prod
