### ISSUE TITLE
BSWH - ConnectFaas Repo 

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#883]
ConnectFaas repository will require an update for site Baylor Scott and White Health (BSWH) integration.

**Comment by mnataraj92** [comment]
CID for BSWH is 827220437 = 472940358

**Comment by Gbarra9** [comment]
Notes from BSWH Site Integration

- Add BSWH to sites object in shared.js file
- Update in shared.js the SSOValidation function’s SSOConfig with new site
	- Add  bswhSSOConfig object to shared.js
- fieldMapping.js -> siteLoginMap (used in convertSiteToLoginNumber())

**Comment by Gbarra9** [comment]
Added Issue: 
- https://github.com/episphere/connect/issues/1028

Status (waiting on PR approval)

**Comment by mnataraj92** [comment]
the BSWH race/ethnicity variable is ready for prod
