### ISSUE TITLE
iframe blocked for HIPAA and Consent forms in Prod

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/connect#887]
There are several issues related to the frames, which are used to display the consent and HIPAA forms, being blocked in prod. This is occurring across devices, browsers, and sites. We have not seen an instance of this occurring in Dev recently. 

<img width="673" alt="image" src="https://github.com/episphere/connect/assets/87718852/f689cf83-ac2c-4a23-a138-b9366884ad16">
<img width="673" alt="image" src="https://github.com/episphere/connect/assets/87718852/6fe0ffe6-3c6e-402a-8345-2936baafde5c">
<img width="669" alt="image" src="https://github.com/episphere/connect/assets/87718852/bd366f82-21b7-4198-8307-7eb1bea18783">

**Comment by Gbarra9** [comment]
Resources:

- [W3 sandbox](https://www.w3.org/TR/2011/WD-html5-author-20110809/the-iframe-element.html#:~:text=If%20the%20allow%2Dscripts%20keyword,out%20of%20the%20sandbox%20altogether.)
- [caniuse](https://caniuse.com/iframe-sandbox)
- [Content Security Policy article](https://web.dev/articles/csp)

**Comment by Gbarra9** [comment]
Tested in Dev by Aileen and ready to be moved to stage.

**Comment by Gbarra9** [comment]
Tested in stage by Amelia and ready to be moved to prod.

**Comment by robertsamm** [comment]
Looks good in stage, ready for prod!

**Comment by Gbarra9** [comment]
From Brian's suggestion, changes should be made to X-Frame-Options header. The X-Frame-Options header is now set to `SAMEORIGIN`

**Comment by Gbarra9** [comment]
Confirmed by Tony no iFrame issues appearing in Datadog.
