### ISSUE TITLE
Birthday Card Return of Data from NORC

### ISSUE THREAD

**Issue by mnataraj92** [episphere/connect#888]
Discuss data structure for NORC to send back birthday card dispositions and updated addresses. 

Currently existing birthday card github issues:
https://github.com/episphere/connect/issues/831
https://github.com/episphere/connect/issues/736

Birthday Card Data Exchange Elements: 
https://nih.app.box.com/file/1385943815887?s=0hf9wj8jtc4vetqlg2n2vogkadnenpg8

Shawna said her team will reach out soon to set up a meeting with us to discuss the requirements so we can establish the data architecture.

**Comment by JoeArmani** [comment]
@FrogGirl1123 The first draft is under review. Linking here for tracking: https://app.box.com/s/dswbmm0cm6368pg1v1u38j3gs6f1zjt9

**Comment by mnataraj92** [comment]
CIDs: 

"birthdayCard" (Source Question- 359309143): {
          "NORCBC_CardVersion_v1r0 (194486780)": 2024,
          "NORCBC_CardDispCode_v1r0 (916186376)": 99,
          "NORCBC_CardMailingDt_v1r0 (768313785)": "ISO_DATE_STRING",
          "NORCBC_CardReturnDt_v1r0 (902078073)": "ISO_DATE_STRING",

**Comment by mnataraj92** [comment]
finalized documents: 
[Data Points for Birthday Card Mailing_20240411.docx | Powered by Box](https://nih.app.box.com/file/1499345425574)
[NORC Birthday Cards - data return.docx | Powered by Box](https://nih.app.box.com/file/1471272352061?s=dswbmm0cm6368pg1v1u38j3gs6f1zjt9)

**Comment by brotzmanmj** [comment]
@mnataraj92 Which of the two documents has the final requirements? Can you archive whichever one does not so we can refer to just one to limit confusion?

And they seem to have some lingering questions and things that are not decided. Is discussion still underway, and if so, with who?

**Comment by mnataraj92** [comment]
@brotzmanmj here is the final document: https://nih.app.box.com/file/1570377597275 and the other is archived. Lauren from NORC was wondering if we wanted them to format and manage this moving forward as a more formal document, or if the way that it is right now is sufficient? 

She also reached out about wanting to run a test to send the birthday card return data back on the Dev environment. I spoke with @Davinkjohnson and he mentioned that while it looks like we have the data structure decided, no one has been able to do the code work to make the API save the data in the agreed structure. He said the timeline for this is the Fall, so the earliest it’ll be ready for testing is September. I have relayed this back to Lauren and told her we'd let her know when this is ready to test.

**Comment by JoeArmani** [comment]
This implementation is coming along well, and I'll only need a day or two to get it into PR once the final items are decided.

Small items to resolve on Friday's call:

(1) dispCode (916186376): These have a leading zero, so sending this value as a string (not a number) is preferable.

(2) dispCode (916186376): Current values (01, 02, 06, 07) appear to all represent failure cases (undeliverable and refusal cases). Are there codes for the success case(s)? It seems best for consistency to require this variable and have a code for the success case. Alternatively we can make it an optional variable and only include it for the failure cases.

(3) mailDate (768313785) and returnDate (902078073): We'll want these in the ISO 8601 format for consistency with other timestamps in our database, as well as our validation, search, and duplicate checking methods. Example: '2024-08-15T00:00:00.000Z'

(4) With dispCode being a string, the only remaining numeric variable is cardVersion (194486780). We may want to specify this one as a string, too, so all birthdayCard data is in string format.

**Comment by JoeArmani** [comment]
This PR is in review.

Note: We expect to receive a more complete list of dispCodes from NORC. That will be a quick PR once we've received them. Current testing can include dispCodes 01, 02, 06, and 07.

**Comment by JoeArmani** [comment]
Update: the dispCode question is resolved and the final PR is in review.

Final documentation: https://app.box.com/s/4jfn84qd0aerkq0k5mweuvz9q6uryjq5
Passing and Failing POST request examples: https://app.box.com/s/yyslltwkjblz6gb1319dewrujiv2dlz3

**Comment by JoeArmani** [comment]
This is in dev and ready to test (it's part of the updateParticipantData API).

It looks like we'll be moving it to stage before dev testing, allowing us to move forward with our release schedule while giving NORC time to set up for testing. This still needs to be tested in dev and stage.

**Comment by sonyekere** [comment]
Ready for Prod

**Comment by JoeArmani** [comment]
•Stage testing completed successfully today.
•This is already in prod but not yet active.
•I believe analytics team is developing the QC process, which will be active when we start to accept birthday card return data.
•NORC requested one more live session for their initial prod push, with a potential timeframe of the second week of January.

**Comment by mnataraj92** [comment]
Adding for documentation purposes from email with Michelle, Joe, and Jake on 1/14/25: 

The addresses we sent to NORC for the birthday card mailing are the Mailing Address fields. And any updated addresses that come back from NORC in the return data update the UP history for the Mailing Address fields.
 
The addition of the Physical Address fields in the January release will not impact either the outgoing or incoming data from NORC. We will still be using the Mailing Address fields.
