### ISSUE TITLE
Biospecimen Dashboard March push - Add Collection and Shipping Locations for HF, HP and Sanford

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#889]
Henry Ford and Health Partners are both adding collection and shipping locations.  These are both Research sites.

Need Concept IDs for both under:
BioSpm_Location_v1r0 (Collection Location, 951355211)
BioShip_LocalID_v1r0 (Location ID, site specific, 560975149)

The following need to be added to the dashboard drop downs
Collection Location: HP Park Nicollet
                                 HFH Pop-Up
Shipping Location: HP Park Nicollet
                               HFH Pop-Up

Please add to the csv files following rules for other research locations.

These locations have already been added to BSI.

**Comment by erincschwartz** [comment]
Sanford will also be adding a shipping site. 

Need Concept ID under:
BioShip_LocalID_v1r0 (Location ID, site specific, 560975149)

The following needs to be added to the dashboard drop downs
Shipping Location: Bismarck Medical Center

Please add to the csv files following rules for other shipping locations.

This locations has already been added to BSI.

**Comment by sonyekere** [comment]
For awareness Concept Ids is pending review @mnataraj92

**Comment by mnataraj92** [comment]
This has been added to the DD Change Log; once Nicole approves I will add it to the DD

**Comment by erincschwartz** [comment]
@amber-emmes we just became aware that Sanford needs another shipping site added in the March push: 


Need Concept ID under:
BioShip_LocalID_v1r0 (Location ID, site specific, 560975149)

The following needs to be added to the dashboard drop downs
Shipping Location: Sioux Falls Sanford Center

Please add to the csv files following rules for other shipping locations.

This locations has already been added to BSI.

**Comment by amber-emmes** [comment]
@mnataraj92 Can you make sure this is also added to the DD change log and get me the concept ID for it? Thanks!

**Comment by Gbarra9** [comment]
Concept id assignments below:

"HP Park Nicollet": "574368418",
"HFH Pop-Up": "322059622",
"Bismarck Medical Center": "127626388",

**Note: Sioux Falls Sanford Center hasn't been created yet**

**Comment by mnataraj92** [comment]
I have added this to the DD change log for Sioux Falls Sanford Center. Once approved, I'll add it to the DD

**Comment by Gbarra9** [comment]
`"Sioux Falls Sanford Center": "246137578"`
https://episphere.github.io/conceptGithubActions/web/#246137578

**Comment by wyattks** [comment]
tested in Dev ready for Stage

**Comment by wyattks** [comment]
Tested in Stage, ready for Prod

**Comment by sonyekere** [comment]
Closing issue, item is in Prod.
