### ISSUE TITLE
Shipping Dashboard March Push- update EDTA and 15 ml Nalgene jar values in the receipt csv file (Biospecimen)

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#891]
2 items need to be updated in the receipt csv file:

- [ ] Under the Additive/Preservative column, "EDTA" needs to be updated to "EDTA = K2"
- [ ] Under the Vial Type column, "15 ml Nalgene jar" needs top be updated to "15ml Nalgene jar"
       Currently there is a space between 15 and ml.  The space needs to be removed.

These have bother been updated in the Tube Mapping file:  https://nih.app.box.com/file/1306346523951

**Comment by sonyekere** [comment]
PR in review

**Comment by wyattks** [comment]
Tested inDev and it works.
Ready for Stage.

**Comment by wyattks** [comment]
Worked in Stage, Ready for Prod

**Comment by sonyekere** [comment]
Closing issue, item is in Prod.
