### ISSUE TITLE
Editing or deleting conditions in SMDB (April Release)

### ISSUE THREAD

**Issue by HanaShiho** [episphere/connect#893]
Currently, we can't edit or delete existing conditions once the notification spec is created; we can only add conditions. We would like to do both in both draft and completed mode.

**Comment by depietrodeanna** [comment]
Option to delete/remove a condition line is necessary. I.e., right now if you add a new condition field and then realize you don't need it, or want to get rid of an existing one completely, you can't remove that empty condition field and have to start over without saving changes. We would like to be able to delete a new or existing condition field.

**Comment by HanaShiho** [comment]
Tested in dev, ready for stage

**Comment by HanaShiho** [comment]
Ready for prod
