### ISSUE TITLE
SMDB - Error in display fields in header for consent date and verification date

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#894]
In the SMDB, in the header on the Participant Details page, Participant Summary page, etc, instead of listing out the dates for when the participant consented or was verified, it lists out numbers which presumably may be concept IDs. 
We're not sure why or how those got changed. Please change them back to display the Consent Date and Verification Date.
Thanks.

**Comment by brotzmanmj** [comment]
Connect_ID : 1026048267   First Name : Dev   Last Name : ParticipantSix   DOB Yr : 1962   Consent Sub : 353358909   Verif Status : 197316935   Site : National Cancer Institute   Year(s) in Connect : 1  Participation Status : No Refusal

**Comment by brotzmanmj** [comment]
<img width="1187" alt="Screenshot 2024-02-14 at 9 47 45 AM" src="https://github.com/episphere/connect/assets/53540067/4d1ef03f-d54c-4efc-9bdc-379b406aacb4">

**Comment by anthonypetersen** [comment]
It looks like this bug is also tied to the changes being seen with the bubbles. The code was written to look for specific variable labels ("Verification status" and "Consent submitted") but the Variable Labels have since be changed in the Data Dictionary to what is shown above.

**Comment by brotzmanmj** [comment]
Thanks Tony. @robertsamm and I will discuss the variable labels with Aileen who was most involved in those changes.

**Comment by Gbarra9** [comment]
> In the SMDB, in the header on the Participant Details page, Participant Summary page, etc, instead of listing out the dates for when the participant consented or was verified, it lists out numbers which presumably may be concept IDs. We're not sure why or how those got changed. Please change them back to display the Consent Date and Verification Date. Thanks.

@brotzmanmj For the header `Consent Sub` which has the date consented value, the previous header was either `Consented: (Ex. 1/2/2023)` or `Not Consented: N/A` depending on if the consent submitted flag was yes or no. Should I change the header name from  `Consented` to `Consent Date` or leave it as `Consented`?

This is also similar to the `Verif Status`. Depending on status the header for `Verif Status` in the past was the following below based on the code:

`Verified: (Ex. 1/2/2023)`
`Can't Be Verified: (Ex. 1/2/2023)`
`Not Yet Verified: N/A`
`Duplicate: (Ex. 1/2/2023)`
`Outreach Timed Out: (Ex. 1/2/2023)`

**Comment by brotzmanmj** [comment]
Hi @Gbarra9 I liked the way it was in the past, before the change

**Comment by Gbarra9** [comment]
@brotzmanmj For one of the test participants, the header names are displayed as the image. The header names also will differ from participant based on the `consent flag` or `verified flag` values. This is already in dev and I believe Amelia is going to test this.

![Screenshot 2024-03-21 at 1 38 14 PM](https://github.com/episphere/connect/assets/33293205/9dc0d262-a98d-49f3-a4f1-deaf3652b474)

**Comment by robertsamm** [comment]
Hi @Gbarra9 , yes I had just taken a look at these a little bit ago and thought it looked good in dev for the different combinations of consent submitted and verification statuses. I think this is good in dev and ready for stage.

@brotzmanmj here is what it would look like for someone not yet consented and not yet verified just as an FYI. I think this is similar to how it was before.
![image](https://github.com/episphere/connect/assets/67074735/a561dadc-2ac8-4bcd-881a-fb52a34f3db6)

**Comment by sonyekere** [comment]
@we-ai - Could you please add this to the March release log to move to stage Monday.

**Comment by robertsamm** [comment]
@Gbarra9 Header fields looks good in stage, ready for prod.

**Comment by sonyekere** [comment]
Closing issue, item is in Prod.
