### ISSUE TITLE
Feedback on Site Aggregate Metrics Graphs 

### ISSUE THREAD

**Issue by HanaShiho** [episphere/connect#898]
Here are our suggestions for the site aggregate metrics graphs. Overall, I think we might want to consider using an alternative format instead of the dual-axis charts as they are hard to interpret and the display trends and data points are a little hard to read. I'd suggest using two side-by-side charts or a line graph (instead of the buttons) with stacked bars for simplicity, but I'm open to other suggestions. 

Graph 1: Age 
- Change title to: Total % of Verified Participants and Response Ratio by Age (2023). Similarly, the format of the titles should be consistent across all graphs e.g. Total % of Verified Participants and Response Ratio by Variable Name(Year)
- "Month" at the bottom of the graph is self-explanatory; please remove 
- The two y-axis titles are to be changed to % of Total Verified & % of Response Ratio. Again, I'd recommend making the axis headers/titles consistent across all graphs
- For all graphs, is it possible to remove the “a” in the middle of the squares for the key? 

Graph 2: Gender
- I can see why the two axes have different heights and the proportions of the two scales are different, but having inconsistent intervals between the numbers is a little confusing. Since you added labels for each data point, I think the numbers can be spaced out consistently. 

Graph 3: Race/ethnicity, Graph 4: Insurance, Graph 5: ADI, Graph 6: RUCA
- Can we have the % of Total Verified axis go up to 80%? 
- For insurance, ADI, and RUCA graphs, please make the Response Ratio % axis go up to at least 12%.
- For ADI graph, please add a note below the key stating “First Quartile represents least deprived and 4th Quartile represents most deprived).
- For RUCA graph, please add a note below the key stating “Code 1 is the most urban and Code 10 is the most rural”.
- With more than 4 response categories, this dual-axis graph is difficult to read. See the overall comment above. 
- Can we remove Unknown (similar to Mia's comment on unknown sex) from all the graphs and add a footnote indicating that unknown responses have been removed? We're OK with leaving 'Other' as is or combining a few categories to 'Other" to simplify further.

**Comment by jeannewu** [comment]
Thank you very much for your comments. For the removal of Unknown ones in the Race, ADI, RUCA and Insurance, the percentages of the Unknown groups in the ADI and race are more than 5 %, even above 10%, it will be questionable if these unknown groups are removed. And the other ADI group in ADI is quite small, I would like to remove this group rather than the Unknown group in ADI.  I agree with you on removing the unknown groups in insurance and RUCA (urbanity) since they are quite few. How about your opinion?

**Comment by jeannewu** [comment]
Hi, Aleah and Hana, with your helpful comments, here attached is a copy of the updated spreadsheet with the plots. Please check the plots and let me know if anything is needed. Thanks a lot.
[Aggregate_Connect_2023_plots_02082024.xlsx](https://github.com/episphere/connect/files/14363693/Aggregate_Connect_2023_plots_02082024.xlsx)
