### ISSUE TITLE
Remove Additional Tabs from PWA Dev

### ISSUE THREAD

**Issue by anthonypetersen** [episphere/connect#899]
Extra tabs shown on the home page of the PWA should be removed as they aren't needed at this point (see image below)

Tabs to be removed include "Report issue", "GitHub Projects", and "Chat with us"

<img width="1350" alt="Screenshot 2024-02-21 at 11 12 08 AM" src="https://github.com/episphere/connect/assets/18222069/7b3dc43a-1ac0-46f9-a614-ede48556ec9f">

**Comment by sonyekere** [comment]
Hi @amber-emmes , Can this issue be closed?

**Comment by sonyekere** [comment]
This item is in Prod.

**Comment by amber-emmes** [comment]
Yep, everything should be good.
