### ISSUE TITLE
Two-Factor Authentication to protect code

### ISSUE THREAD

**Issue by geetajoshi2019** [episphere/connect#9]
(Per Jonas's Gitter notes) Now that our codes are finding their way into a community of alpha users I’m tempted to activate the two factor authentication to minimize the chances of one of us being hacked. Y’all ok with that?

**Comment by jonasalmeida** [comment]
if you are in the assignee list it is because last time I checked you had not activated two factor ;-)

**Comment by theEIC** [comment]
Done!

**Comment by bhaumik55231** [comment]
Done :)

**Comment by geetajoshi2019** [comment]
Done

**Comment by geetajoshi2019** [comment]
Do we need to leave this open until all our Developers complete the action?

**Comment by geetajoshi2019** [comment]
> Do we need to leave this issue open until all our Developers complete the action?

**Comment by jonasalmeida** [comment]
two factor activated - we lots three people we may need to approach for re-enrolment
