### ISSUE TITLE
Kit Assembly Concept ID (Biospecimen)

### ISSUE THREAD

**Issue by anthonypetersen** [episphere/connect#901]
While debugging Notifications that were throwing errors in the production logs I found an issue with a Concept ID being used for the Home Mouthwash process:

`BioKit_Mouthwash - 8583443674`

Concept IDs should not be 10 digits in length. This Concept ID is being referenced in multiple places in the API code base as well as in a handful of Notification Specifications.

Should also be noted that the `kitAssembly` collection was never created in Firestore in production.

One last code issue that looks like needs to be cleaned up, within the main `biospecimenAPIs()` function in `biospecimen.js` there are two different `else if(api == 'assignKit')` statements. One of these should be removed.

**Comment by brotzmanmj** [comment]
8583443674 is the CID for the Secondary source for home mouthwash kit. It will need to be fixed before we can go live with home mouthwash collections.

@Gbarra9 as a first step, can you look into how this 10-digit Concept ID got created? thanks

**Comment by Gbarra9** [comment]
@brotzmanmj The 10-digit Concept ID was possibly created by a manual entry in the Data Dictionary (DD). The code would have read the DD cell with the concept ID `8583443674` and assigned it to the Secondary Source text `BioKit_Mouthwash` . I don't believe this concept ID was generated using the random 9-digit concept ID process.

**Comment by brotzmanmj** [comment]
@Gbarra9 Thank you. With Madhuri and Nicole out until March 4, I don't know exactly how to proceed. We have not yet started home mouthwash collection in prod, so we are still able to fix this and change it to a 9 digit concept ID before that starts. As I understand it, we would need to change the CID in the code and in the notifications and retest. 

@Davinkjohnson Does this need to be coordinated with a release cycle? Should we wait until Madhuri and Nicole are back and add this to March release?

**Comment by anthonypetersen** [comment]
@brotzmanmj I would suggest tying this to a release since it's not technically needed ASAP, this just helps us keep track of all code changes a little easier from a Dev Ops perspective

**Comment by Gbarra9** [comment]
> @Gbarra9 Thank you. With Madhuri and Nicole out until March 4, I don't know exactly how to proceed. We have not yet started home mouthwash collection in prod, so we are still able to fix this and change it to a 9 digit concept ID before that starts. As I understand it, we would need to change the CID in the code and in the notifications and retest.
> 

To my knowledge, that is correct. I would empty the cells with the 10-digit concept `8583443674` and generate a new concept Id.

**Comment by Davinkjohnson** [comment]
@brotzmanmj I agree with Tony's assessment. Let's plan to tie this clean up work to the March release. If FNL can start shipping these sooner than that then we can talk about whether there's a way to hot fix these items.

Also, if the CID in question is a Current Source Question (since columns G and H are a pair) is the code even using the correct CID? @anthonypetersen not sure how it's being utilized in the code, but technically the DD doesn't show any values for that CID. So is it using it in a nesting format? (Ex:8583443674.687158491)

**Comment by anthonypetersen** [comment]
the CID in question is nested a few levels deep: `173836415.266600170.8583443674`

**Comment by brotzmanmj** [comment]
@HanaShiho For the March release, we are going to have to fix this concept ID that is ten digits to one that is nine digits. 173836415.266600170.8583443674 

Can you look at all of the home mouthwash related email specs (including the SMDB side, the client side emails, the ones for kit reminders, the ones for home mouthwash survey reminders) and find out which ones have this concept ID 8583443674 is referenced? When Nicole and Madhuri return next week and we get a new concept ID, we will need to fix that throughout the home collection workflow including the emails and retest all that are involved.

**Comment by HanaShiho** [comment]
The concept ID: 173836415.266600170.8583443674 is included in the following reminders:

Spec: BL Home Mouthwash Reminder (KPHI and non-KPHI sites)
- 1st contact: condition to get reminder & primary field (client side)
- 2nd contact: condition to get reminder & primary field 
- 3rd contact: condition to get reminder & primary field 
- 4th contact: condition to get reminder & primary field 
- 5th contact: condition to get reminder & primary field 

Spec: BL Home Mouthwash Quex Reminder 
- 1st contact: condition to get reminder & primary field (client side) 
- 2nd contact: condition to get reminder & primary field 
- 3rd contact: condition to get reminder & primary field 
- 
Spec: BL Home Mouthwash/Quex Thank You Email 
- 1st contact: condition to get reminder & primary field (client side)

**Comment by brotzmanmj** [comment]
That's pretty much all of the messages. So when it gets replaced with a different concept ID in March, we will need to retest all of the messages. 

@sonyekere, the client side emails will need to be fixed by someone on the DevOps team.
@depietrodeanna will fix the SMDB-side email specs.

@mnataraj92 when you return, please review the home collection testing scenarios and prepare to repeat them with the team. You'll be coordinating retesting including creating the test cases, scheduling and leading the testing, and checking the underlying data as you did in November.

**Comment by mnataraj92** [comment]
New CID- "BioKit_Mouthwash": 319972665

**Comment by Gbarra9** [comment]
The bio kit mouthwash concept id references are now updated in dev. 
BioKit_Mouthwash:
From `8583443674` to `319972665`

**Comment by brotzmanmj** [comment]
Thanks @Gbarra9 are they also updated on the client side emails?

**Comment by Gbarra9** [comment]
@brotzmanmj I am not sure if they are updated in the client side emails. I made the updates in `dashboard, connectApp/PWA, connectFaas` repos. I also updated all of the dev participants that had the previous structure `173836415.266600170.8583443674` to `173836415.266600170.319972665`.

Does the client side emails rely on only the `participants` collection or are there other collections?

**Comment by we-ai** [comment]
> Thanks @Gbarra9 are they also updated on the client side emails?

Client side emails don't use `8583443674`, so any changes/updates on it won't affect client side emails.

**Comment by mnataraj92** [comment]
@brotzmanmj Kathleen and I are meeting tomorrow to go over the workflow testing (except the messages)

**Comment by mnataraj92** [comment]
Discussed on the punchlist call today but just for documentation purposes, Kathleen, Gene, and I tested the workflow in dev and everything looked as expected. We will be testing the messages on Thursday.

**Comment by mnataraj92** [comment]
Tested in dev, for stage. There is one issue noted here https://github.com/episphere/connect/issues/939 where thank you email for mouthwash kit completion + mw survey completion is not always being received as expected. Warren/Gene to look into this.

**Comment by mnataraj92** [comment]
tested in stage, ready for prod

**Comment by sonyekere** [comment]
Closing issue, item is in Prod.
