### ISSUE TITLE
Disable check in button on Check in/Check out screen (Biospecimen Dashboard) (April Release)

### ISSUE THREAD

**Issue by erincschwartz** [episphere/connect#905]
Please de-activate the check in button on the Check In/Check Out screen for any participants who have a Participation Status of 'withdrew consent' or 'revoked HIPPA'. 

![image](https://github.com/episphere/connect/assets/157617486/003749dc-8fe9-4c81-92fb-bfc47a79ddd6)

**Comment by brotzmanmj** [comment]
Also de-activate for Participation Status = Destroy Data or Data Destroyed

**Comment by sonyekere** [comment]
In April release

**Comment by amber-emmes** [comment]
Should this also be extended to statuses of Deceased and Refused All Future Activities?
