### ISSUE TITLE
Fetch sha (commit history) for existing surveys

### ISSUE THREAD

**Issue by JoeArmani** [episphere/connect#906]
We track module version by assigning the sha value of the active module when a participant starts the module. These sha values are missing in some cases. This update fetches the GitHub commit history for a module and returns the sha based on the active version when the participant started the survey.

**Comment by JoeArmani** [comment]
PR ready for review: https://github.com/episphere/connectFaas/pull/548

**Comment by JoeArmani** [comment]
Merged to dev, ready for testing.

**Comment by cunnaneaq** [comment]
Tested in dev, ready for stage

**Comment by cunnaneaq** [comment]
Tested in stage, ready for prod

**Comment by JoeArmani** [comment]
Closing - in production.
