### ISSUE TITLE
PWA - My Connect UI Changes to Emphasize Phone Login 

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#907]
Encourage participants to sign in/create account with their phone number.

-  For the March release, Warren to mock up a plan to de-emphasize emails and emphasize phone numbers
- Operational team to provide feedback on presented plan 
- @robertsamm @brotzmanmj , this is only a placeholder. Please feel free to provide add'l information when ready

**Comment by brotzmanmj** [comment]
@we-ai The intended purpose is to emphasize the phone login option over the email login option when people create a new account in MyConnect. We would like your thoughts on what an effective UI would be for this. Can you mock something up the way you did when you last re-organized the 'create an account' aspect of the MyConnect UI? We can have a few team members review it and give any thoughts and feedback. Thank you!

**Comment by we-ai** [comment]
@brotzmanmj Sure. I'll share it when it's done.

**Comment by we-ai** [comment]
[Here](https://nih.app.box.com/file/1464898895407) is the file with 2 options I can think of. Please provide feedback @brotzmanmj.

**Comment by depietrodeanna** [comment]
@we-ai Mia, Michelle, and I have reviewed and agree that option 2 is preferred. 

Could you also update the screen after someone clicks, "Sign In" which is currently:
<img width="385" alt="image" src="https://github.com/episphere/connect/assets/74061787/d8d7547f-ad0e-4106-8b4f-b089e25f41df">

Please switch "Email or Phone" to, "Phone or Email" to be consistent in emphasizing phone first.

**Comment by we-ai** [comment]
The updates are in dev now, and tests can start. @depietrodeanna

**Comment by depietrodeanna** [comment]
Ready for Stage @we-ai

**Comment by depietrodeanna** [comment]
Looks good in Stage

**Comment by sonyekere** [comment]
Closing issue. Item is in Prod.
