### ISSUE TITLE
Disable Specimen Link button on Participant Search Results screen (Clinical Biospecimen Dashboard) (April Release)

### ISSUE THREAD

**Issue by erincschwartz** [episphere/connect#908]
Please de-activate the Specimen Link button on the Participant Search Results screen of the Clinical Biospecimen Dashboard for any participants who have a Participation Status= Withdrew Consent, Revoked HIPPA, Destroy Data or Data Destroyed. 

![Image](https://github.com/episphere/connect/assets/157617486/49a435a4-1c29-48d8-aaa2-7b3b9c193282)

**Comment by sonyekere** [comment]
In April release

**Comment by amber-emmes** [comment]
Should this also be extended to statuses of Deceased and Refused All Future Activities?

**Comment by amber-emmes** [comment]
Additional clarification: this only specifies the clinical dashboard. When it comes to the check-in/check-out buttons and specimen links on the participant search results for the research dashboard, should the specimen links also be removed for participants who have withdrawn consent? Also, should the check-in/check-out buttons be removed in the lists as well as on the individual participant pages?

**Comment by wyattks** [comment]
No.  Github issue #905 discusses the Research dashboard changes that are needed.

**Comment by erincschwartz** [comment]
During Dev testing we discovered additional changes are needed:

1) Please gray out the Specimen Link button on the Participant Search Results when disabled. Current testing shows the Specimen Link button is correctly disabled for the scenarios listed above but the Specimen Link button appears normal, as though it should still work. We would like sites to have visual distinction that the button is disabled. 

2) Please add text reflecting the participation status below the participation status icon (green check mark/red x) on the Participant Search Results page (No refusal, Withdrew consent, Revoked HIPPA only, Destroy data). Follow example of how this is shown on Research Dashboard Check in/Check Out screen, examples below: 



![Image](https://github.com/episphere/connect/assets/157617486/a5e273cf-438e-4d0c-922f-f313f8a1d5de)



![Image](https://github.com/episphere/connect/assets/157617486/d3772094-e699-40ad-b38f-d8568cb08099)

**Comment by amber-emmes** [comment]
https://github.com/episphere/connect/assets/160774541/c0c548c6-1574-44b1-bc98-928b6441d7c3

Is this the styling you'd like on the Specimen Link button when disabled?

**Comment by brotzmanmj** [comment]
Hi Amber, I don't see anything in the video, maybe it didn't capture it?

**Comment by amber-emmes** [comment]
The video should show the buttons with the `disabled` class added, including the "not allowed" cursor when hovered over.

**Comment by brotzmanmj** [comment]
For some reason, I'm not seeing that. Would you like to hop on a call and show us? Are we trying to get this into the April release, or is this being held until May?

**Comment by erincschwartz** [comment]
Tested in Stage. Ready for Prod.
