### ISSUE TITLE
Survey Loading: Resolve participant access issues on survey continuation.

### ISSUE THREAD

**Issue by JoeArmani** [episphere/connect#909]
Some participants are having trouble accessing or continuing surveys.

TODO:
-Resolve participant access issues on survey continuation.
-Repair sha values and survey numbering:
(1) Find survey sha value and version number based on commit history in GitHub API.
(2) Repair the survey file with sha and version data when it's missing.
(3) Optimize/Parallelize the loading sequence where possible.
(3) Additional error handling to diagnose remaining issues.

**Comment by JoeArmani** [comment]
PR Ready for review: https://github.com/episphere/connectApp/pull/723

**Comment by cunnaneaq** [comment]
Tested in dev, ready for stage

**Comment by cunnaneaq** [comment]
tested in stage, ready for prod

**Comment by JoeArmani** [comment]
Closing - in production.
