### ISSUE TITLE
Enabling Sanford access to clinical biospecimen dashboard

### ISSUE THREAD

**Issue by erincschwartz** [episphere/connect#910]
To prepare for launch of clinical collections at Sanford, please enable their access to the clinical dashboard by end of March in dev and stage. Testing planned to begin in April.

**Comment by wyattks** [comment]
tested in Dev ready for Stage

**Comment by wyattks** [comment]
ready for prod

**Comment by sonyekere** [comment]
Closing issue. Sanford granted Dev and Stage access. Prod access will be granted in April release.
