### ISSUE TITLE
Quest "age" Input Bug

### ISSUE THREAD

**Issue by anthonypetersen** [episphere/connect#916]
The way the "age" input parameter for Quest is being calculated has a logic gap due to how the Date() class handles months. Below is the code in question:

<img width="589" alt="image" src="https://github.com/episphere/connect/assets/18222069/81882d95-1463-4170-8d5d-d943e0d3dab6">

The Date() class handles months referencing them with values 0-11, not 1-12. This causes a small gap where the code above would not show the correct value for age. An example would be if their birthday was on 01/26 and code was ran on 02/24. It appears Day is handled similarly, but the window for that to cause a bug with our currently code is smaller.

Likely solution would be to just subtract 1 from both the birth month and birth day that are passed in from Firestore.

This bug was brought to our attention from NORC Case CS0020649

**Comment by JoeArmani** [comment]
I'll be starting on this late in the day tomorrow or Thursday (3/13 or 3/14).

**Comment by JoeArmani** [comment]
The updated Quest age calculation code is merged to dev and ready for testing.

Some helpful tests to run for confirmation:
•birthday is today's date
•birthday is tomorrow's date
•birthday is yesterday's date
•birthday is next month
•birthday was last month

**Comment by brotzmanmj** [comment]
Hi @cusackjm can you test?

**Comment by cusackjm** [comment]
@JoeArmani how many misc birthdays should i test?

**Comment by JoeArmani** [comment]
@cusackjm Just a couple should be fine. I think the issues were primarily around the edge cases (within 1 month and 1-2 days of the current date).

**Comment by cusackjm** [comment]
@JoeArmani sounds good. Going to test tomorrow

**Comment by cusackjm** [comment]
I tested the following in Dev and everything looked good in AGECOR
![image](https://github.com/episphere/connect/assets/85582895/bab29554-cb9e-4a25-a19c-2d80fac4593a)

**Comment by cusackjm** [comment]
confirmed fix in stage

**Comment by JoeArmani** [comment]
Closing, this is in production.
