### ISSUE TITLE
Spanish Integration Bucket 1 - Surveys 

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#917]
Issue to address Spanish versions of surveys and Quest

**Comment by anthonypetersen** [comment]
@robertsamm @brotzmanmj did we say that the language a survey would be rendered in was to be based on the language they filled out their consent form in? (believe we said we were going to store this as their preferred language in a new CID?) Or are we rendering the surveys in language based on whatever language they are currently viewing the PWA in? (which will be able to be toggled on the PWA itself)

**Comment by brotzmanmj** [comment]
I don't think we have a definitive decision on this. I think it needs discussion, pros/cons of the two approaches.

**Comment by anthonypetersen** [comment]
If we could try to make a decision on that in tomorrow's touch base that would be great.

**Comment by brotzmanmj** [comment]
I'm not sure who is on the touch base tomorrow, I don't think it's something I am on. There is the technical aspect of implementation but also the user experience that we need to consider.

**Comment by brotzmanmj** [comment]
@m-j-horner  do you happen to know how AoU functions in this way? It would be good to leverage their user experience on this.

**Comment by Davinkjohnson** [comment]
@anthonypetersen the decision was made to use the current webpage context language to determine which language the survey should render in. (Deanna will add in some language on the Spanish dashboard page that basically says "once you begin a survey in Spanish it will always appear in Spanish".

**Comment by m-j-horner** [comment]
> @m-j-horner do you happen to know how AoU functions in this way? It would be good to leverage their user experience on this.

I'm following up about querying AoU user experience for Spanish
