### ISSUE TITLE
Spanish Integration Bucket 3 - Communications/Notifications 

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#918]
Elect and render Spanish for notifications
-Newsletter/emails/SMS​
-PWA Messages tab

**Comment by robertsamm** [comment]
More details below:
-Decision made: There will be one notification spec for both English and Spanish content. We will not make changes to conditionality.
-DevOps to create logic to import one spec for both languages where the body of the message renders on the participants device based on the new CID for language election (see https://github.com/episphere/connect/issues/915). 
-Assuming DevOps will need to add a 'Spanish Body' and 'Spanish Subject Line' to the notification specs in the SMDB? @anthonypetersen can you confirm?
-Once built out, Operations team would add Spanish content to the bodies of the current notification specs.

**Comment by anthonypetersen** [comment]
@robertsamm to confirm... are we creating new specs that will hold the Spanish notification content? or will we be storing the Spanish notification spec within the English specs that already exist?

If it's the latter, then yes, we will need to add code so that SMDB shows fields for entering Spanish specific content such as subject and body.

**Comment by robertsamm** [comment]
@anthonypetersen I believe the latter. We want to have one spec for both English and Spanish content.

**Comment by brotzmanmj** [comment]
Adding requirements: 
-System needs to send message in either Spanish or English based on the language preference of the participant (variable still to be determined/created)
-Client slide emails need to do the same as described above for the SMDB side messages

**Comment by we-ai** [comment]
Adding Spanish to existing specs requires data structure changes that need our discussion. Currently the data structure supports only one language. Related data holding email info is:` email : { body: 'Hi, this is a test email', subject: ' Test email'}`. For Spanish (and maybe some other languages in future), we need to decide a modified data structure.

**Comment by anthonypetersen** [comment]
@we-ai correct, discussions will need to be had about how we will manage additional fields in the specs and using the correct fields when sending out emails and text messages

**Comment by brotzmanmj** [comment]
Thanks @we-ai  and @anthonypetersen. We plan to start the programming work on this at the beginning of April. Would you suggest we schedule a discussion on the data structure for later this month? And who is needed for that?

**Comment by we-ai** [comment]
>  -Client slide emails need to do the same as described above for the SMDB side messages

Different from scheduled notifications, client side emails are written in our code base. With client side email templates grow, adding/updating those templates in our code base will be tedious. We had a discussion [here](https://github.com/episphere/connect/discussions/812) about moving client side email templates out of our code base. Not sure whether it's a priority.

**Comment by anthonypetersen** [comment]
@brotzmanmj the discussion will mostly be for internal dev ops purposes, so I will schedule a meeting on our side.. If you want to join and listen in I can include you, but it'll mostly be technical details

**Comment by we-ai** [comment]
SMDB also needs updates, to allow adding email and SMS templates in Spanish to existing notification specs, as well as creating new specs in English and Spanish.

**Comment by anthonypetersen** [comment]
> SMDB also needs updates, to allow adding email and SMS templates in Spanish to existing notification specs, as well as creating new specs in English and Spanish.

We have that called out on a checklist somewhere, it just might not have been called out specifically here :)

**Comment by we-ai** [comment]
Concept IDs related to the task:
- 255077064 (Preferred Language)
- 163149180 (English)
- 773342525 (Spanish)

**Comment by sonyekere** [comment]
In production.
