### ISSUE TITLE
Biospecimen Dashboard- Extra label used on mouthwash container routing to blood/urine bag

### ISSUE THREAD

**Issue by erincschwartz** [episphere/connect#919]
@JoeArmani tagging you because I know you are working on another issue related to the use of the extra specimen labels (0050-0054)

It appears that when extra labels are used for the mouthwash container, they are routing into the blood/urine bag (0008) and not into the mouthwash bag (0009). Everything appears as it should on the collection screen, the mouthwash container scans in as 0054 and the mouthwash bag is showing correctly. 

![Image](https://github.com/episphere/connect/assets/157617486/95f94f4d-800f-43aa-9784-f1028ddc9ef9)

When searching for the Mouthwash Bag (0009) on the shipping screen, the following error appears:

![Image](https://github.com/episphere/connect/assets/157617486/8baa9830-1803-41ae-8245-d9aa012f90b2)

The mouthwash container (0054) is included in the biohazard bag blood/urine (0008)

![Image](https://github.com/episphere/connect/assets/157617486/38b86d7e-0e56-41fa-99d4-6372a41e5c22)

**Comment by JoeArmani** [comment]
@erincschwartz Thanks Erin. I bet this issue resides in the section that sorts available collections. I'll look into it.

**Comment by JoeArmani** [comment]
PR ready for review: https://github.com/episphere/biospecimen/pull/675

**Comment by JoeArmani** [comment]
Merged to dev, ready for testing. Probably best to test alongside https://github.com/episphere/biospecimen/pull/672, so I'll update testers when that one is in dev.

**Comment by wyattks** [comment]
Worked in Dev, ready for Stage

**Comment by wyattks** [comment]
Worked in Stage, ready for Prod

**Comment by JoeArmani** [comment]
Closing, this is in production.
