### ISSUE TITLE
Date Variable to Indicate that RCA Data Was Received

### ISSUE THREAD

**Issue by mnataraj92** [episphere/connect#921]
I have added to the Data Dictionary Change Log that we would like a date/timestamp variable to indicate that the RCA data was received. We would also like to add this variable to add to the stub record to be retained in case of data destruction. 

I spoke with Aileen earlier and we believe when the sites send cancer date, primary cancer site, vital status, and a variable to ensure the pt knows about their cancer, then DevOps will be auto populating it from their side when they receive these variables. @JoeArmani can you confirm? Can you also please save this to your programming so we can create/use this variable? 

@brotzmanmj to check with Amelia, Kaitlyn, and Aileen in regards to whether we'd like a flag indicating that RCA data was received as well. If so, I will also add this to the DD change log. 

Also would like to confirm that these variables would be nested under occurrence?

**Comment by JoeArmani** [comment]
Hi @mnataraj92

I have a few questions on this item:

(1) Is this an additional timestamp variable to indicate when we received the data -- the exact time the site posts the data to our database, separate from the optional occurrence timestamp 345545422?

(2) Can you confirm this timestamp is stored in the cancer occurrence (not the participant profile)?

(3) Do you know how cancer occurrences are handled on data destruction?

Updated RCA details: As far as I know, the updated RCA Variables are currently being discussed, and I plan on implementing all the new details as they're available.
Linking that issue for our reference: https://github.com/episphere/connect/issues/866

Thanks!

**Comment by mnataraj92** [comment]
Hi @JoeArmani I spoke with Amelia and Michelle regarding your questions:

1. Correct
2. @FrogGirl1123 could you confirm where this should be stored? Since we want this variable retained we were thinking it should actually be in the participants table since we wouldn't selectively destroy data in any other table besides the participants table. However, in the participants table, structure would be needed for it because we can get more than one cancer occurrence per person so we may need to discuss?
3. All data would be deleted from the Cancer Occurrence table/all other RCA data will be destroyed aside from this new date/time variable that the RCA data was received

**Comment by FrogGirl1123** [comment]
@mnataraj92 @brotzmanmj @JoeArmani I agree it makes the most sense to have the date variable stored in the participants table which means we'll need some structure to account for repeat occurrences.  @JoeArmani could you propose a json structure for the RCA date in the participants table and I'll review?

**Comment by JoeArmani** [comment]
@FrogGirl1123 @brotzmanmj @mnataraj92

Sure, I just have two more questions:

(1) Will we need to cross-reference this timestamp in the participant profile with the specific cancer occurrence at any point?  If yes, we'll want the participant profile and the occurrence data to share a unique identifier.

(2) If cancer occurrence data is destroyed, do we want any data attached to this timestamp in the participant profile?

**Comment by FrogGirl1123** [comment]
Hi @JoeArmani , For 1) Yes, it's likely we will need to associate the time stamp in the participants table with the cancer info in the RCA table 2) That is more of a @brotzmanmj question, I could see keeping it as we do some of the other flags, but as it indicates a disease state, then we are might to need to delete it.

**Comment by JoeArmani** [comment]
Hi @brotzmanmj @FrogGirl1123, here's an initial proposal for that data structure. It ties the occurrence number to the timestamp to cross-reference the participant and cancer occurrence when needed.
•Option 1 uses the literal occurrence number.
•Option 2 uses a CID for the occurrence number (similar to bags in Biospecimen shipping).

Box Doc: https://app.box.com/s/igzqpbbnlalqp3ut613v5wq001r0eqcq
I'll revise as final decisions are made.

@jacobmpeters, could you please take a look at page 2 of this document to make sure the structure works on your end?
This would be structured as:
•Null (does not exist) if no cancer occurrences have been received for the participant.
•An object with a key:value pairs (one k:v pair per cancer occurrence) when cancer occurrences have been received for the participant. The number of k:v pairs in this object will vary. I want to ensure that it works with your needs in BQ. The alternative would be to define a set number of occurrences once the first is received, set them to empty, and populate as data is received.

**Comment by jacobmpeters** [comment]
@JoeArmani I think the data structure as you described will work fine for our purposes. As I understand it, the resulting BigQuery table will have a column for each key in the `cancerOccurances` collection whether each participant's document contains that key or not. 

So, once a key for a given occurrence number exists for any participants, the entire BQ table will have that key. Hopefully that makes sense.

**Comment by brotzmanmj** [comment]
Hi, can someone add Aileen to this issue? We are waiting for a decision from the working group about whether we need these dates. The purpose of the dates was to retain them in case someone requests data destruction. But @FrogGirl1123  raised a good question about whether we should keep them or not. The working group is meeting on Thursday.

**Comment by mnataraj92** [comment]
for some reason it's not letting me tag Aileen

**Comment by robertsamm** [comment]
@Davinkjohnson Can you add Aileen to the connect repo? Here username is @cunnaneaq

**Comment by FrogGirl1123** [comment]
@brotzmanmj These were my take homes from the Thursday meeting, but I missed the first half due to a conflict:
1) The new variables for manual chart review and vital status need to be added to the RCA documentation here https://nih.app.box.com/file/1393159438842?s=3pemvj2oqylx4c1eez3n8oszqfmilf73
2) The preliminary stage variable needs to be removed from the data dictionary.
3) We need a final decision on date the RCA data are received @cunnaneaq was this discussed on Thursday?
4) It was agreed that the sites would not update RCA variables (details should be in the SOP)
5) We are going to add an Assentation number variable to distinguish multiple primary sites found at the same time, each site will still be sent as separate record.
6) The "Operations" secondary source for "Was the Connect participant diagnosed with cancer?" and "What occurrence number is this? (1, 2, 3, etc)" should be changed to "Occurrence" since that's the table they will be stored under.

**Comment by Davinkjohnson** [comment]
Two updates to note here based on discussions this week. 

1. We will no longer save an RCA date to the participant record, which I believe is what this issue (title) was created for.
2. We have a new requirement to ensure that data will not be saved for a participant if the "manual confirm diagnosis and participant awareness" is "no".

**Comment by brotzmanmj** [comment]
@sonyekere and @cunnaneaq  I think we have another issue that documents the RCA requirements, and since we are not going to add date variables to indicate RCA data was received, can we close this issue and all refer to the other still relevant issue?

**Comment by cunnaneaq** [comment]
yes, please refer to issue #866
