### ISSUE TITLE
Biospecimen Dashboard- Add collection and shipping location for Baylor Scott and White

### ISSUE THREAD

**Issue by erincschwartz** [episphere/connect#922]
Baylor Scott and White Health needs collection and shipping locations added to the Biospecimen Dashboard. This a research site.

Need Concept IDs under:
BioSpm_Location_v1r0 (Collection Location, 951355211)
BioShip_LocalID_v1r0 (Location ID, site specific, 560975149)

The following need to be added to the dashboard drop downs
Collection Location: BSW Health and Wellness Center 
Shipping Location: BSW Health and Wellness Center 

Please add to the csv files following rules for other research locations.

@wyattks please add to BSI.

**Comment by brotzmanmj** [comment]
Thanks Erin. This will be part of the BSWH launch in June. I believe there is already an issue for the BSWH Biospecimen changes where this information should go. @sonyekere could you find that issue and move this information there? Thanks.

**Comment by sonyekere** [comment]
Closing this issues, as it is tied to https://github.com/episphere/connect/issues/882
