### ISSUE TITLE
Individuals that have signed in are missing sign-in time (April Release) 

### ISSUE THREAD

**Issue by mnataraj92** [episphere/connect#925]
These individuals have signed in (230663853 = 353358909) but are missing a sign-in time (335767902): https://nih.app.box.com/file/1468292737911

@sonyekere could you please assign this to the appropriate person on the dev ops team?

**Comment by sonyekere** [comment]
Hi, @bransteitterbr - Since you worked on multiple sign in for the PWA in the past, can you kindly look into this. Thanks!

**Comment by brotzmanmj** [comment]
Noting this should be the time the person first signed in (should not change each time they sign in)

**Comment by sonyekere** [comment]
Hi All, Brian might need some add'l data to understand how the data got lost or if the data was never reported. @bransteitterbr Please feel free to piggy back to share add'l contexts of what you need.

**Comment by mnataraj92** [comment]
I found a couple issues in the past where the sign-in time was not being properly captured (it should be the time that the recruit first signs in; it should not update each time they sign in): https://github.com/episphere/connect/issues/610 and correcting the backlog of sign in time https://github.com/episphere/connect/issues/612

**Comment by sonyekere** [comment]
Thanks Madurai for sharing! @bransteitterbr can you look into the above issues posted. [#610](https://github.com/episphere/connect/issues/610) and [#612](https://github.com/episphere/connect/issues/612).

**Comment by mnataraj92** [comment]
There are a few more individuals this week that have signed in and are missing in sign-in time; I have added them to the spreadsheet: https://nih.app.box.com/file/1468292737911

**Comment by mnataraj92** [comment]
Hi @bransteitterbr 

We were doing some dev testing with UC for the uninvited recruits variable, and Nina noticed that for her test participants, she noticed an issue with the sign-in date/time where both the date and year were off. 

![image](https://github.com/episphere/connect/assets/76711181/189275ed-51cf-4ca0-904d-39173a1278d4)

![image](https://github.com/episphere/connect/assets/76711181/0cc0caf3-0bb3-4711-a181-77e3b448346e)

Would you be able to look into this as well? Please let me know what is needed to get this tested and resolved. Thanks so much!

**Comment by mnataraj92** [comment]
I have reached out to Vijay from HP to help us test this. He will create pts that mimic the duplicate scenario

**Comment by mnataraj92** [comment]
Tested in dev and looks as expected; sign in time populated and did not change with subsequent sign in. Ready for stage.

**Comment by mnataraj92** [comment]
Tested in stage with HP and looks as expected. Ready for prod.

**Comment by mnataraj92** [comment]
Hi @bransteitterbr, HP helped us test the duplicate type scenario that Michelle described, and the fix you implemented worked for that scenario as the sign-in time was populated for the duplicate individual. 

However, on a recent QC report, it was found that for a participant that had signed in but was missing sign in time, they were actually verified. I double checked that their sign-in flag = “yes” but sign-in time is null so I’m unsure why this is happening. 
 
I did a quick check of the individuals that have signed in but are missing sign in time (n = 81) and it’s a mix of verification status = verified, not yet verified, and duplicate.

**Comment by sonyekere** [comment]
Closing. @bransteitterbr A new issue will be created to address Madhuri's findings above.
