### ISSUE TITLE
Spring 2024 eNewsletter- April 2024 

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connect#929]
Content will be outlined in Box document for each section (to be added when ready).

The newsletter for Spring 2024 should be formatted as the previous newsletter was, and html provided to Hana and Deanna for programming/ testing. 

Testing in early April, sending this out in prod to participants by the end of April.

**Comment by depietrodeanna** [comment]
Goal to send this out in prod week of April 23rd. Use similar template as the previous eNewsletter: https://episphere.github.io/dashboard/newsletter/decembernewsletter and modify with the following content and graphics:

Date in the top right corner- April 2024

What's New With Connect section
Body text: Senior Scientist Mia Gaudet shares important announcements including activities participants should expect throughout the rest of the year.
Image: https://nih.app.box.com/folder/257339170838

Did You Know section 
Body text: The overall cancer death rate is declining in the U.S. However, certain groups continue to be at
greater risk of developing or dying from some cancers. Connect aims to help change that.
Usual image: https://nih.app.box.com/file/974705920135?s=ni0cpwnyafrs919quvg4vksiwgr2ndkl


In the Spotlight section
Body text: Through her work with Connect, Aleah Thomas hopes to help shape
the future of cancer prevention for all people, with a special emphasis on those who are
clinically underserved.
Image: https://nih.app.box.com/file/1490508666487

**Comment by jhflorey** [comment]
@depietrodeanna could you please provide some information

- Link of `Read more` in 3 sections
- The introduce of the spotlight section. 

<img width="525" alt="image" src="https://github.com/episphere/connect/assets/24559107/6b8c452e-3314-47dc-8fc2-57a1665b3460">

**Comment by depietrodeanna** [comment]
Hi Jessica- 

In the Spotlight section
Title: Aleah Thomas is a research fellow at the NCI helping the Connect team engage populations that are underrepresented in research.
Body text: Through her work with Connect, Aleah Thomas hopes to help shape
the future of cancer prevention for all people, with a special emphasis on those who are
clinically underserved.
Image: https://nih.app.box.com/file/1490508666487

I will add the links in the next comment.

**Comment by depietrodeanna** [comment]
@jhflorey  

Link to What's New section: https://www.cancer.gov/connect-prevention-study/news/spring2024
Link to In the Spotlight: https://www.cancer.gov/connect-prevention-study/news/aleah-thomas
Link to Did You Know: https://www.cancer.gov/connect-prevention-study/news/minorityhealth

Link to main study news homepage is the same as previous newsletters: https://www.cancer.gov/connect-prevention-study/news

**Comment by jhflorey** [comment]
@depietrodeanna @HanaShiho 
https://gist.github.com/jhflorey/1d9e16cbac9470f67b603c20fd228fba

https://github.com/episphere/dashboard/blob/dev/newsletter/aprilnewsletter.html

**Comment by HanaShiho** [comment]
Programmed in dev, ready for testing

**Comment by jhflorey** [comment]
@HanaShiho sorry for the wrong link. Please try with https://episphere.github.io/dashboard/newsletter/aprilnewsletter

**Comment by HanaShiho** [comment]
tested in dev, ready for stage

**Comment by jhflorey** [comment]
@HanaShiho @depietrodeanna this is the final: https://gist.github.com/jhflorey/1d9e16cbac9470f67b603c20fd228fba

**Comment by HanaShiho** [comment]
Ready for prod
