### ISSUE TITLE
Build mechanism to prevent two notification job requests in quick succession (April Release) 

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#930]
From Warren: One strange thing happened on 2-5 (Feb 5th) was that the code handing notifications ran twice, so each notification was sent out twice.

From Tony: As we discussed it doesn’t appear that a second job was ran manually and seems like two job requests were sent in short succession, although I’m not sure how or why that would’ve happened.
In any case, now that we are using BQ as our data source for sending notifications I think we need to build in some kind of mechanism that would prevent this scenario or the scenario where a second job is ran manually from running our notifications code again. The delay in time between Notifications running and BQ getting updated basically leaves an hour window every day where something like this could happen.

**Comment by we-ai** [comment]
The scheduled job handling notifications should run only once at 3:00pm, to send out notifications. But on 2-5, the job ran twice with an interval about 7 seconds. The cause of 2nd run is still unclear. Likely it was a glitch in Google services. This kind of incident was not seen at other time.

**Comment by we-ai** [comment]
Currently `notifications` in Firestore is synced to BQ once per day at 11 pm, because each notification spec is run only once per day and large number of docs in `notifications` collection.
Since our code sending out notifications is using `notifications` table in BQ to decide whether a participant meets conditions, currently multiple runs, before Firestore to BigQuery sync (at 11 pm), can send multiple notifications. To block the 2nd or multiple unintended runs like we saw on 2-5, we need to save the time of last run and check whether a spec is already run in a day before running it.
An additional field (eg `lastRunTime`) is needed in each notification spec to tack run time.
Please comment @brotzmanmj @anthonypetersen

**Comment by anthonypetersen** [comment]
@we-ai would you rather track run time for each individual spec? Another idea might be to create a Firestore Collection with fields for tracking run times on scheduled jobs. 

For this example we would have a field called `notificationsLastRunTime3pm` that we would write to whenever we that job runs. Each time it is run we could also verify that the last run time wasn't on the same day.

**Comment by we-ai** [comment]
> @we-ai would you rather track run time for each individual spec? Another idea might be to create a Firestore Collection with fields for tracking run times on scheduled jobs.
> 
> For this example we would have a field called `notificationsLastRunTime3pm` that we would write to whenever we that job runs. Each time it is run we could also verify that the last run time wasn't on the same day.

Tracking run time in each spec works for this task. The error occurred at 3 pm run, and it could occur in 8 pm run. 

I agree and I've also been thinking about adding a new collection to track overall status (or metrics) across data collections in Firestore. We need to decide the name and what data we want to track inside this new collection.

**Comment by anthonypetersen** [comment]
@we-ai we also need to make sure the `lastRunTime` field is updated ASAP in our logic. If we wait until later in the logic, there's a chance that another session starts while a previous one is currently running

**Comment by we-ai** [comment]
Tested in dev: scheduled notification specs cannot be run for a second time.

**Comment by we-ai** [comment]
Tested in stage: scheduled notification specs cannot run for a second time in each day.
