### ISSUE TITLE
Magic link delay and updated message on MyConnect

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connect#932]
@cusackjm please continue to monitor in your testing any issues in delays with receiving the magic link email. @we-ai is this message on the PWA after someone enters an email something we can easily edit?
<img width="374" alt="Screenshot 2024-03-20 at 8 52 14 AM" src="https://github.com/episphere/connect/assets/74061787/f6a167d5-6a88-475a-abdc-8d8b4194cfac">

If yes, we'd like to edit to: "We sent a verification email to (email). Please check your email and click the link we sent to finish signing up. Our email may take a few minutes to arrive in your inbox."

**Comment by we-ai** [comment]
Yes @depietrodeanna

**Comment by depietrodeanna** [comment]
Thank you. Let me know when this is ready for review in dev.

**Comment by we-ai** [comment]
The text should be "... to finish signing in. ...", right?
Not sure whether @jhflorey is more suitable to do this update.

**Comment by depietrodeanna** [comment]
Either is fine I think. @jhflorey you can update the text to read, "We sent a verification email to (email). Please check your email and click the link we sent to finish signing in. Our email may take a few minutes to arrive in your inbox."

**Comment by we-ai** [comment]
Since @jhflorey is working on other updates, I'll try to get it done.

**Comment by depietrodeanna** [comment]
Looks good in stage

**Comment by sonyekere** [comment]
Closing issue. Item is in Prod.
