### ISSUE TITLE
Quest Month Selector - fallback method and validation needed

### ISSUE THREAD

**Issue by JoeArmani** [episphere/connect#933]
Safari for desktop and Firefox don’t support the month-based calendar picker used in some surveys. Participants using these browsers currently see an empty text box. This can lead to confusion about the expected data format (see the attached screenshot).

An additional side-effect: data validation is partially skipped, allowing future dates to be entered. This resulted in a recent ServiceNow ticket.

---
**Current**
_Screenshot: current view in Safari desktop and Firefox._
<img width="886" alt="Screenshot 2024-03-20 at 1 44 21 PM" src="https://github.com/episphere/connect/assets/93854858/ac199f6a-e99e-46b0-951c-591fd8cceaf1">

Notes on proposed update:
•This only impacts user experience and data validation to avoid future date input issues.
•No data structures, concept IDs, or existing data changes are needed.

I will add the necessary validation for this scenario. My question is about the UI. We have two UI options to present to the participant:

---
**Option 1**
We can add a text-based placeholder value to guide input when the month-based calendar is not supported. The participant would enter year and month as text in the format “YYYY-MM” - this is what participants using these browsers have been doing. The placeholder text just serves as a guide. This method is probably faster for the participant.
_Screenshot: placeholder value for text-based input._
<img width="905" alt="Screenshot 2024-03-20 at 1 50 07 PM" src="https://github.com/episphere/connect/assets/93854858/81aa4033-62d5-4b50-b505-b91bc8941037">

---
**Option 2**
We can add a date-based calendar when the month-based calendar is not supported. This requires a participant to select a specific date. We would discard the date, retaining the month and year values to align with existing data format.
_Screenshot: day-based calendar._
<img width="897" alt="Screenshot 2024-03-20 at 1 53 36 PM" src="https://github.com/episphere/connect/assets/93854858/011c2fac-0111-4ef3-b4ac-426d7b0bb9be">

**When this will trigger:**
I’ll implement a check that tests whether the month-based calendar is supported by the browser. When it is, the month-based calendar will be used. When it isn’t, the selected backup option (1 or 2 above) will be shown to the participant.

Please let me know your preferred direction, and I’ll implement it.

**Comment by m-j-horner** [comment]
Thank you, Joe.
I prefer option 1.

My rationale: in option 2, participants probably won't remember an exact date and could get frustrated/skip the question altogether.

**Comment by JoeArmani** [comment]
Sounds great. Thanks for your quick review. I'll move forward with adding validation for this text-based version and implementing option 1.

**Comment by JoeArmani** [comment]
This PR is in review: https://github.com/episphere/quest/pull/434

**Comment by JoeArmani** [comment]
Tested in dev, ready for stage.

**Comment by JoeArmani** [comment]
Tested in stage, ready for prod.
