### ISSUE TITLE
Data destruction and withdrawals: blocking data (April Release)

### ISSUE THREAD

**Issue by kmazzilli** [episphere/connect#935]
We want to make sure we block any further incoming data after the data destruction request date and also the withdrawal date for those who are only withdrawn. The way the API is written now, is that as soon as a participant is marked as “data destroyed” (861639549) then we block further data updates. This flag is set by the nightly run when either: (1) The data destruction request form has been signed by the ppt or (2) if not signed, 60 days after date of data destruction request. There are currently no limits on data being sent for only withdrawn participants. Additional requirement: We need to make sure we could still send outgoing notifications about completing the revocation and/or destruction forms and accept/capture data of their signed revocation and destruction forms.

**Comment by maddimayer** [comment]
@mnataraj92 -- If we send a call with data on five tokens, one of which is a withdrawal, will the call accept the four without the withdrawal status? And only send back an error code for the token with a withdrawal status?

**Comment by anthonypetersen** [comment]
@maddimayer that is correct, in this case you would expect to get a 206 status code on the call meaning that the call was successful but at least one error was found in the data that was sent. The response object will also contain an array showing which participants were successfully updated and which participants had errors as well as what the error was.

**Comment by bransteitterbr** [comment]
@kmazzilli After the withdrawn status are there any CIDs that would need to be updated outside of this list?

        consentFirstName: 471168198,
        consentMiddleName: 436680969,
        consentLastName: 736251808,
        consentSuffixName: 480305327,
        userProfileNameFirstName: 399159511,
        userProfileNameMiddleName: 231676651,
        userProfileNameLastName: 996038075,
        userProfileNameSuffixName: 506826178,
        dateOfBirth: 371067537,
        birthMonth: 564964481,
        birthDay: 795827569,
        birthYear: 544150384,
        healthcareProvider: 827220437,
        informedConsentFlag: 919254129,
        informedConsentVersion: 454205108,
        informedConsentDateSigned: 454445267,
        verificationStatus: 821247024,
        verificationDate: 914594314,
        hipaaAuthorizationFlag: 558435199,
        hipaaAuthorizationVersion: 412000022,
        hipaaAuthorizationDateSigned: 262613359,
        userProfileSubmittedFlag: 699625233,
        hipaaRevocationFlag: 773707518,
        withdrawalFlag: 747006172,
        dateOfWithdrawal: 659990606,
        whoRequestedWithdrawal:299274441,
        whoRequestedWithdrawalOther: 457532784,
        reasonsForWithdrawal: 919699172,
        tooBusy: 141450621,
        incentiveTooLow: 576083042,
        tooSick: 431428747,
        unreliableInternetDevice: 121430614,
        worriedAboutStudyResults: 523768810,
        worriedStudyWillFindSomethingBad: 639172801,
        privacyConcerns: 175732191,
        doNotTrustGov: 150818546,  
        doNotTrustRsrchrs: 624030581,  
        doNotWantInfoSharedWithRsrchrs: 285488731,  
        worriedInfoNotSecure: 596510649,
        worriedInsWillGetData: 866089092,
        worriedAboutDataBeingGivenToMyEmployerPotentialEmployer: 990579614,
        worriedAboutDiscriminationFromData: 131458944,
        worriedOthersWillProfitFromMyData: 372303208,
        otherPrivacyConcerns: 777719027,
        unableToCompleteOnlineActivities: 620696506,
        doNotLikeThingsOnline: 352891568,  
        covidConcerns: 958588520,
        partNowUnableToParticipate: 875010152,
        partIncarcerated: 404289911,
        reasonNotGiven: 538619788,
        otherReasonsSpecify: 715390138,
        otherReasons: 734828170,  
        hipaaRevocationFormHasBeenSigned: 153713899,
        hipaaRevocationCategorical: 577794331,
        dateOfSignatureOnHIPAARevocationForm: 613641698,
        versionOfTheHIPAARevocationForm: 407743866,
        nameExtractedFromSignedHIPAARevocationFormFirstName: 765336427,
        nameExtractedFromSignedHIPAARevocationFormMiddleName: 826240317,
        nameExtractedFromSignedHIPAARevocationFormLastName: 479278368,
        nameExtractedFromSignedHIPAARevocationFormSuffix: 693626233,
        dataDestructionRequest: 831041022,
        dateOfDestructionRequest: 269050420,
        whoRequestedDataDestruction: 524352591,
        whoRequestedDataDestructionOther: 902332801,
        dataDestructionRequestFormHasBeenSigned: 359404406,
        dataDestructionCategoricalFlag: 883668444,
        dateOfSignatureOnDataDestructionRequestForm: 119449326,
        versionOfTheDataDestructionRequestForm: 304438543,
        nameExtractedFromSignedDataDestructionFormFirstName: 104278817,
        nameExtractedFromSignedDataDestructionFormMiddleName: 268665918,
        nameExtractedFromSignedDataDestructionFormLastName: 744604255,
        nameExtractedFromSignedDataDestructionFormSuffixName: 592227431,
        dataHasBeenDestroyedFlag: 861639549,
        participationStatus: 912301837,
        incentive: 130371375,
        incentiveEligible: 731498909,
        dateIncentiveEligible: 787567527,
        norcIncentiveEligible: 222373868,
        incentiveIssued: 648936790,
        dateIncentiveIssued: 297462035,
        incentiveRefused: 648228701,
        dateIncentiveRefused: 438636757,
        norcCaseNumber: 320023644,
        bloodUrineMouthwashCombinedResearchSurveyFlag: 265193023,
        autogeneratedDateTimeWhenBloodUrineMouthwashResearchSurveyCompleted: 222161762,
        bloodUrineSurveyCompletionFlag: 253883960,
        autogeneratedDateTimeWhenBloodUrineSurveyCompleted: 764863765,
        mouthwashSurveyCompletionFlag: 547363263,
        autogeneratedDateTimeWhenMouthwashSurveyCompleted: 195145666,
        menstrualCycleSurveyCompletionFlag: 459098666,
        autogeneratedDateTimeWhenMenstrualCycleSurveyCompleted: 217640691,
        covid19SurveyCompletionFlag: 220186468,
        autogeneratedDateTimeWhenCOVID19SurveyCompleted: 784810139,
        surveyCompletionFlag: 320303124,
        autogeneratedDateTimeWhenPROMISSurveyCompleted: 843688458,
        baselineSurveyStatusModuleBackgroundAndOverallHealthFlag: 949302066,
        autogeneratedDateTimeStampForCompletionOfModuleBackgroundAndOverallHealth: 517311251,
        baselineSurveyStatusModuleMedications: 536735468,
        autogeneratedDateTimeStampForCompletionOfModuleMedications: 832139544,
        baselineSurveyStatusModuleSmoking: 976570371,
        autogeneratedDateTimeStampForCompletionOfModuleSmoking: 770257102,
        baselineSurveyStatusModuleWhereYouLiveAndWorkFlag: 663265240,
        autogeneratedDateTimeStampForCompletionOfModuleWhereYouLiveAndWork: 264644252,
        snsnSurveyFlag: 126331570,
        autogeneratedDateTimeWhenSSNSurveyCompleted: 315032037,
        allBiospecimenCollectionDetailsData: 173836415

**Comment by kmazzilli** [comment]
@mnataraj92 might be best to answer that question -  Madhuri, could you take a look at Brian's list?

**Comment by brotzmanmj** [comment]
I'm not sure what you mean by need to be updated. Should we discuss?

**Comment by mnataraj92** [comment]
Update- Brian and Tony to discuss offline and we will figure out what to test from there.

**Comment by mnataraj92** [comment]
Just spoke with Nicole, based on our understanding, the only things that should be able to be updated are fields related to populating the forms and fields indicating that the forms have been signed for those that have withdrawn or requested data destruction. 

Testing scenarios: 
1. One pt that has withdrawn
2. One pt that has requested DD
3. One pt that has just refused something (ex blood) (not withdrawn)
4. One pt that has not refused or withdrawn anything

1 & 2: Pt that has withdrawn and pt that has requested DD- should only be able to update vars related to signing the forms
	-Make sure flags for signed form = yes (check BQ)
	-Check that withdrawn pt and data destruction requested pt should not be able to take a survey
		-Even if they have access, we should not get data populated for survey taken in firestore or BQ
	-Site should not be able to push us any information (check a variable that a site would send us like Blood Order Placed 
        (d_173836415_d_266600170_d_530173840) or Clinical Site Blood Collected (d_173836415_d_266600170_d_693370086)

3. Pt that has refused blood- should still be able to do surveys and we should see something for urine or MW (they should be able to provide those samples). Check to see if they're still able to provide a blood sample or not
	-Even if they can still provide blood sample after refusal, they should not get a blood donation follow up reminder 
         message that they should donate blood samples (check inbox for this & double check cadence for when we would 
         expect to see a follow up reminder email to donate blood sample)
        -Check to make sure that vars related to signing the forms are updateable

4. Pt with no refusal or withdrawal- all data should come in as normal

Will get a site's help (likely Marshfield) to test this in stage next week

**Comment by we-ai** [comment]
To receive a scheduled notification (at 3pm or 8pm), the data in a participant need to meet 2 criteria: 1) conditions specified inside the notification spec; 2) the notification hasn't previously been sent to the participant.
So, if the data destruction doesn't touch data used for condition checking inside a notification spec, there's no need to test notifications generated from the spec: nothing changes. @brotzmanmj @mnataraj92

**Comment by mnataraj92** [comment]
tested in dev, ready for stage

**Comment by mnataraj92** [comment]
Tested in stage with Marshfield, looks as expected. MFH confirmed this morning that test pt that just refused blood is still able to donate all biospecimen samples as expected (biospecimen DB issue in stage yesterday that Erin pointed out where Participant Search wasn't working was fixed yesterday PM, so was able to check this morning). 

This is ready for prod

**Comment by mnataraj92** [comment]
Update on 8/6/24: We became aware that sites can still send verification status and verification table data after withdrawal and we are fine leaving it that way. We just wanted to make a note of this.
