### ISSUE TITLE
BPTL Dashboard -Change Clinical Collection date/time in csv file to a fake date (Biospecimen)(April Release) 

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#936]
Currently the collection Date/time on the receipt csv files is set to the day before receipt (may be set to receipt date/time at the RRL, would need to verify).  The idea is the correct date/time is being pushed by the Clinical sites via API.  
The correct date and time need to be manually updated in BSI.  In order to facilitate this process, and know what records have not been updated, we would like the receipt date/time, for Clinical Collections only, to be set to a fake date.  We would like it to be set to 01/01/1999 12pm.  With it being set to a fake date/time it will make it easier to see what records in BSI need to be updated.
BPTL agrees with this change.

**Comment by erincschwartz** [comment]
@wyattks It appears that update was made as requested in Dev, please confirm that this is what we were expecting:

![Image](https://github.com/episphere/connect/assets/157617486/15917958-fed7-4572-9cb0-b11eeb84cd28)

**Comment by wyattks** [comment]
Confirmed this is what I expected.  Ready for Stage.

**Comment by erincschwartz** [comment]
@amber-emmes During Stage testing, we realized that the date change was applied to the wrong variable. The Date Received was changed to the new set value but should be the actual date/time the specimens were scanned into the Dashboard (should not have been updated to the fake set value). The Date Drawn should actually be set to 01/01/1999 12pm. 



![Image](https://github.com/episphere/connect/assets/157617486/26c233eb-70bb-40a1-8e25-d02979ef09fa)

**Comment by amber-emmes** [comment]
Merged into dev. Please review in dev and confirm that it looks good and I will pull request for dev.

**Comment by erincschwartz** [comment]
@amber-emmes Just tested in Dev, this is now ready for Stage.

**Comment by amber-emmes** [comment]
@erincschwartz  This should now be in stage and ready to test.

**Comment by erincschwartz** [comment]
Stage testing complete. Ready for Prod.
