### ISSUE TITLE
My Samples Page - Sanford (Hybrid Launch) (May Release)

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#942]
Placeholder for requirements, April release.

**Comment by erincschwartz** [comment]
Due to slight shift in timeline of full scale clinical collection launch, the Sanford MySamples page update will not be included in April release, moving to May release.

**Comment by depietrodeanna** [comment]
@jhflorey Tracked edits to the My Samples page for Sanford participants are in this document: https://nih.app.box.com/integrations/officeonline/openOfficeOnline?fileId=1464877175474&sharedAccessCode=

**Comment by depietrodeanna** [comment]
Further edits requested in dev- sent to @jhflorey via teams

**Comment by depietrodeanna** [comment]
ready for stage

**Comment by depietrodeanna** [comment]
Looks good in stage. Ready for prod
