### ISSUE TITLE
Address formatting issues with one year study anniversary newsletter (May Release)

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connect#944]
Tweak html for study anniversary newsletter to fix the formatting issues I'm seeing in the email we tested. I worked on this with Abhinav before he left- he filed the html here: https://gist.github.com/abhinavjonnada82/e9e5bbaf0a34382c422355ceef1d955f

**Comment by jhflorey** [comment]
@depietrodeanna what do you want to adjust?

<img width="852" alt="image" src="https://github.com/episphere/connect/assets/24559107/7353b84f-2e53-41ef-ad63-7dc37eea23de">

**Comment by depietrodeanna** [comment]
@jhflorey the format looks very distorted in Gmail when viewed as an email. We need to ensure that the format does not stretch or distort when I open the email in Gmail or other email clients.

**Comment by jhflorey** [comment]
This is in my side
![image](https://github.com/episphere/connect/assets/24559107/0c3b5312-84a3-4d92-bc54-888a1edabf0c)

**Comment by HanaShiho** [comment]
Tested in dev, ready for stage

**Comment by sonyekere** [comment]
Due to current formatting issues, this will be pulled out from the April release and go into the May release

**Comment by HanaShiho** [comment]
tested in dev, ready for stage

**Comment by HanaShiho** [comment]
Ready for prod; note that formatting has been somewhat inconsistent. See the screenshots. Deanna and Jessica confirmed that it looks good on their end. Once pushed to prod, we'll keep an eye on it to make sure it works as expected. 

![image](https://github.com/episphere/connect/assets/148134271/cc75fd8e-3a44-48a9-829e-52be8175b01a)
