### ISSUE TITLE
Update ConnectApp Firestore Dependencies

### ISSUE THREAD

**Issue by JoeArmani** [episphere/connect#945]
The ConnectApp Firestore dependencies should be updated.
<img width="786" alt="Screenshot 2024-04-01 at 9 18 09 AM" src="https://github.com/episphere/connect/assets/93854858/123b8c04-9533-494a-9c37-27997e10f364">

This 'Failed to execute transaction on IDBDatabase' error is the most prevalent error in DataDog reporting. It's caused by a Firebase null handling bug that's solved in more recent Firebase versions. This error should disappear on a dependency update.

<img width="1015" alt="Screenshot 2024-04-01 at 9 10 29 AM" src="https://github.com/episphere/connect/assets/93854858/9705030a-2c93-4865-8505-5452828ade2c">

The 'compat' versions (link below) are backward compatible - firebase stopped adding new features to these versions, but existing features are updated, and bugs are fixed.
https://firebase.google.com/docs/web/learn-more#web-namespaced-api_1

**Comment by sonyekere** [comment]
This will be tested in the May release

**Comment by sonyekere** [comment]
Perhaps now move testing to June since BSWH and Spanish testing timelines will occur then

**Comment by JoeArmani** [comment]
PR for review: https://github.com/episphere/connectApp/pull/768

**Comment by JoeArmani** [comment]
looks good in dev, ready for stage

**Comment by JoeArmani** [comment]
Tested based on other ConnectApp updates...no issues. ready for prod.

**Comment by JoeArmani** [comment]
closing - in production
