### ISSUE TITLE
Receipt CSV file for HealthPartners Clinical collections showing incorrect vial types (Biospecimen) (April Release)

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#947]
The receipt csv is showing the below for the vial type and Additive/preservative (0003 collections only) values:

![Image](https://github.com/episphere/connect/assets/64605220/61d8aaef-c7e7-42e5-8675-b9da39c61e0e)

The Values should be the foolowing (located here: https://nih.app.box.com/file/1306346523951)

![Image](https://github.com/episphere/connect/assets/64605220/cb70b221-e4ed-4601-977f-a73038cd2a59)

**Comment by sonyekere** [comment]
Pending feedback from HF site and then proceed in adding to backlog for April release.

**Comment by Gbarra9** [comment]
Ready for dev testing.

**Comment by erincschwartz** [comment]
@wyattks I just completed a clinical collection entry from HP, vial types appear to be populated correctly in the Receipt CSV. Please confirm: 



![Image](https://github.com/episphere/connect/assets/157617486/74734325-e188-4c82-bf05-a4b8b541e20b)

**Comment by wyattks** [comment]
Confirmed this is correct.

**Comment by erincschwartz** [comment]
Stage testing complete. Ready for Dev.
