### ISSUE TITLE
Finalized specimens did not appear in list "Available Collections" for shipping in Biospecimen Dashboard (September Release)

### ISSUE THREAD

**Issue by erincschwartz** [episphere/connect#950]
The Henry Ford team finalized several collections on 3/29 that did not appear in the list of "Available Collections" in the Shipping Dashboard. The HFH team handwrote the specimen collection information on the manifest and shipped the specimens to FNL. The HFH team attempted to manually enter the collection ID into the Shipping Dashboard and received the following error message: 

![Image](https://github.com/episphere/connect/assets/157617486/0e0b00de-7148-41cd-9991-7af0f1a62f4f)

on 4/2, Erin got on a call with HFH and confirmed that these specimens were finalized in the Dashboard. Please investigate using Data Dog: 

Research Collection:
Connect ID: 4021769574 Collection ID: CXA015346 

Clinical Collections: 
Connect ID: 6700503882 Collection ID: CXA015609 
Connect ID: 1052229314 Collection ID: CXA015610 
Connect ID: 5527041536 Collection ID: CXA015611 
Connect ID: 2768718443 Collection ID: CXA015612

**Comment by JoeArmani** [comment]
Hi @erincschwartz All of these collections have the boxed status: 'boxed.' That is supposed to indicate the collections are boxed, so they don't show up in 'Available Collections.' That status would keep them from showing up as available in the shipping dashboard.

To my knowledge, we haven't seen this before. I'm wondering if there's a new case we need to look into.

Have we had any other reports along these lines?
Were there any unusual details related to how these collections were finalized?

It looks like they've been able to ship before and after these collections, so any other details would be helpful.

**Comment by erincschwartz** [comment]
@JoeArmani This case is not exactly the same, but seems similar to the issue from KPGA that DevOps is looking into as well, https://github.com/episphere/connect/issues/928 

HFH did not report any differences in how these specimens were finalized and other specimens finalized the same day appeared as expected in the Available Collections list.

**Comment by JoeArmani** [comment]
Note: We do not have a DataDog session with video playback for this session, so the session found for https://github.com/episphere/connect/issues/928 is our most useful data so far.

**Comment by JoeArmani** [comment]
What I think is happening here - Please see: https://github.com/episphere/connect/issues/928#issuecomment-2037633782

**Comment by sonyekere** [comment]
As mentioned above, this issue is tied to  #928 . Issue is currently not critical, however important update in the long run so sites can put multiple staff on packing samples if volume is high.

**Comment by sonyekere** [comment]
Decided - sites to follow standards until the June release

**Comment by erincschwartz** [comment]
This is stale; issue has not re-occurred
