### ISSUE TITLE
Sanford Clinical Receipt csv Values (Biospecimen) (April Release)

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#952]
The CSV mapping table has been update for the tube types Sanford will be using for their clinical collections. 
These values need to be programmed into the receipt csv fill as they are different from the other clinical collections and research collections.

Mapping table: https://nih.app.box.com/file/1306346523951

**Comment by erincschwartz** [comment]
Testing complete in Dev, ready for Stage

**Comment by erincschwartz** [comment]
Stage testing complete. Ready for Prod.
