### ISSUE TITLE
Enable Home Collection Reports tab in BPTL Dashboard of Biospecimen Dashboard

### ISSUE THREAD

**Issue by erincschwartz** [episphere/connect#955]
The Reports tab under the BPTL Dashboard  is disabled. Please enable this tab in Dev so we can take a look at what is in there. 

![Image](https://github.com/episphere/connect/assets/157617486/ffb9c389-bcca-45b9-8309-f99b5d7aee6c)

**Comment by sonyekere** [comment]
Pending feedback from BPTL and Norma on current markup of reports - end of April/First week of May is expected timeline to connect further.

**Comment by erincschwartz** [comment]
Here is the link to Home Collection Reports mock-up: https://nih.app.box.com/file/1369287990412. At this time, we are focusing on the Kits Shipped Report (slide 4). Once it is determined who will be working on this, we will know if preliminary work is needed for data structure familiarity related to the variables of interest in the report.

**Comment by sonyekere** [comment]
Timing of the release of this item should be discussed at the next standup call. To avoid slow loading times on the page, Gene suggests that an additional requirement to include the pagination function to limit the data sent back on the backend in the shipping reports/ bptl reports.

**Comment by Gbarra9** [comment]
@erincschwartz This is in dev and ready to be tested. 


Note: The Kits Shipped table will have the exact 3 rows from the above image. These were manually added to the database before merging the changes to dev for testing on my end.

**Comment by erincschwartz** [comment]
Tested 3 cases in Dev, they all appear in the Kits Shipped Report with accurate information:
![image](https://github.com/episphere/connect/assets/157617486/a02aa7a9-63b6-4116-a64c-7804d2260323)

**Comment by erincschwartz** [comment]
@Gbarra9 Stage testing complete, ready for Prod. However, there are two small changes I would like to request, they don't need to be completed for April push (can be completed in May if possible):

1) Add a column for Collection ID after Supply Kit ID
2) Remove "ID" in Supply Kit Tracking Number (highlighted below) 






![Image](https://github.com/episphere/connect/assets/157617486/24fc8b86-4d19-4489-a0cc-ef0cfb90cca8)

**Comment by Gbarra9** [comment]
> [@Gbarra9](https://github.com/Gbarra9) Stage testing complete, ready for Prod. However, there are two small changes I would like to request, they don't need to be completed for April push (can be completed in May if possible):
> 
> 1. Add a column for Collection ID after Supply Kit ID
> 2. Remove "ID" in Supply Kit Tracking Number (highlighted below)
> 
> ![Image](https://private-user-images.githubusercontent.com/157617486/324985194-24fc8b86-4d19-4489-a0cc-ef0cfb90cca8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MDUyMTMsIm5iZiI6MTcxMzkwNDkxMywicGF0aCI6Ii8xNTc2MTc0ODYvMzI0OTg1MTk0LTI0ZmM4Yjg2LTRkMTktNDQ4OS1hMGNjLWVmMGNmYjkwY2NhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QyMDQxNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNGQ5NzZhZDExNTM0NzNhYTNkODM1ZWE2YzRkMDgyZDViZGI5NDYxYjg0NzY1N2JlZWZlZjRkNDc2NzgwNzFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4naSSMJF1Ypa7IK5kaw6hJs4T9XTTdUEjFQSI7p5mCk)

I am going to make two quick PRs for the suggested changes.

**Comment by erincschwartz** [comment]
@Gbarra9 Tested in Dev, ready for Stage.

**Comment by erincschwartz** [comment]
Stage testing complete, ready for Prod
