### ISSUE TITLE
Update SMDB Participant Search -> getFilteredParticipants API (April Release)

### ISSUE THREAD

**Issue by JoeArmani** [episphere/connect#957]
The old getParticipants 'filter' option will be obsolete with the upcoming release. SMDB needs to use the new getFilteredParticipants API for participant search.

Items to test:
• participant lookup
• data corrections tool
• participant withdrawal

**Comment by JoeArmani** [comment]
PR ready for review: https://github.com/episphere/dashboard/pull/637

**Comment by JoeArmani** [comment]
Merged to dev, ready for testing.

**Comment by robertsamm** [comment]
@JoeArmani tested in dev and everything looks as expected. SMDB participant lookup, data corrections tool, and participant withdrawal tool working as expected. Ready for stage.

**Comment by robertsamm** [comment]
@JoeArmani tested in stage, ready for prod. Looks as expected.
