### ISSUE TITLE
Update Biospecimen Participant Search -> getFilteredParticipants API (April Release)

### ISSUE THREAD

**Issue by JoeArmani** [episphere/connect#958]
The old getParticipants 'filter' option will be obsolete with the upcoming release. Biospecimen needs to use the new getFilteredParticipants API for participant search.

Items to test:
• Biospecimen participant search

**Comment by JoeArmani** [comment]
Working on this now for the April release.

**Comment by JoeArmani** [comment]
PR for review: https://github.com/episphere/biospecimen/pull/684

**Comment by erincschwartz** [comment]
@JoeArmani Tested in Dev using participant Connect ID 7956451897. Participant search worked using both first/last name method and CID search method. No issues with specimen link, collection or check out. Let me know if you need additional details.

**Comment by JoeArmani** [comment]
Thanks @erincschwartz 

Ready for stage.

**Comment by erincschwartz** [comment]
Completed Stage testing. Ready for Prod.
