### ISSUE TITLE
Set 'Any Refusal or Withdrawal' to 'yes' on Data Destruction (April Release)

### ISSUE THREAD

**Issue by JoeArmani** [episphere/connect#959]
The 'Any Refusal or Withdrawal' variable (CID 451953807) doesn't appear to be set to 'yes' in most data destruction cases. This was discovered in a Gitter issue on 4/9/24.

It appears to be null in 43/50 cases according to BQ data.
Report here: https://app.box.com/s/oiqbnmnnyqwecdl101tf5s4774r9fncj

This is impacting sites' ability to reach these participants through the `getParticipants` API with the standard query `getParticipants?type=refusalswithdrawals`.

A current workaround to retrieve data destroyed participants:
`getParticipants?type=refusalswithdrawals&option=dataDestroyed`

However, it seems the 'any refusal or withdrawal' variable should consistently be set to 'yes' on data destruction so those participants are accessible alongside other refusal/withdrawal participants.

**Comment by JoeArmani** [comment]
@jhflorey Hi Jessica, this is what I found researching yesterday.

The desired behavior is to set the ‘any refusals or withdrawals’ (CID 451953807) variable to yes ‘when the participant requests data destruction’ (CID 831041022)…I'm fairly certain that’s just a check that needs to be added in the checkDerivedVariables function where other refusal/withdrawal variables are checked.

connectFaas -> checkDerivedVariables -> checkRefusalWithdrawals()

```javascript
const checkRefusalWithdrawals = (data) => { // TODO: we need to add data destruction to the 'anyRefusalWithdrawal' check.

    const anyRefusalWithdrawal = (
        data['685002411']['194410742'] === 353358909 ||
        data['685002411']['217367618'] === 353358909 ||
        data['685002411']['277479354'] === 353358909 ||
        data['685002411']['352996056'] === 353358909 ||
        data['685002411']['867203506'] === 353358909 ||
        data['685002411']['949501163'] === 353358909 ||
        data['685002411']['994064239'] === 353358909 ||
        data['726389747'] === 353358909 ||
        data['747006172'] === 353358909 ||
        data['773707518'] === 353358909 ||
        data['831041022'] === 353358909 ||
        data['906417725'] === 353358909 ||
        data['987563196'] === 353358909 ||    // <-- added the ||
        // TODO: I think add the check here and it should get computed with derived variables
        data['831041022'] === 353358909
    ); 

    return anyRefusalWithdrawal;
}
```

Also, there are a handful of participants (as of yesterday) that have `831041022: 353358909` and `451953807:null`...please see the Box doc in my previous post for those results. Those participants will probably need to be retroactively updated to 451953807: 353358909 with a cloud function.

Thanks!

**Comment by jhflorey** [comment]
Here is the script to update the participant in firestore.
https://gist.github.com/jhflorey/119311561ed9bdd5cf23eb06bc4f1fcf

**Comment by JoeArmani** [comment]
@jhflorey looks good in Firestore stage

**Comment by brotzmanmj** [comment]
@mnataraj92 can you set up a testing plan for this? we can discuss what to include. thanks.

**Comment by mnataraj92** [comment]
As discussed on the call today, I will test a scenario where a pt requests data destruction to make sure the 'any refusal or withdrawal' variable populates, and another scenario where a pt requests data destruction & another refusal/withdrawal to test a combo, and make sure the 'any refusal or withdrawal' variable populates

**Comment by mnataraj92** [comment]
Joe confirmed the 'any refusal or withdrawal' variable is set to 'yes' in dev for 

Connect ID
4723748117
451953807: 353358909
 
Connect ID
2537423491
451953807: 353358909

This is ready for stage

**Comment by mnataraj92** [comment]
Joe confirmed the 'any refusal or withdrawal' variable = 'yes' in stage for

'any refusal or withdrawal'
Connect ID 5410027070
451953807: 353358909
 
Connect ID 8740957830
451953807: 353358909

This is ready for prod

**Comment by jhflorey** [comment]
Updated 46 participants in prod
```
8437377292
3665757145
6575848257
5810762484
7611644934
7329688967
6880853459
3899176500
6792098176
1974642387
4276016386
6851074592
7570850444
5516837502
9873667215
2468652076
3952268104
2759755942
1720924551
3829528105
5547802251
1905833856
8850194605
5691170745
1308062179
8615148046
7549049278
2925129751
8790139556
1108023704
8868913771
1637720696
9286933970
6363772898
1848404718
6625754395
6522969630
4451434373
9047328610
8409194117
8339529319
9590323728
3388199139
3516658074
9843524210
8777216716
Updated 46 participants successfully
```
