### ISSUE TITLE
Home collection query sort order (April Release)

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#960]
For the Home Collections function queryTotalAddressesToPrint:
The variable collectionDetails -> baseline -> bloodOrUrineCollectedTimestamp.
CID 173836415.266600170.740582332
is sorting in descending order (most recent date/time stamp first)
We need it to sort in ascending order (oldest date/time stamp first)

**Comment by JoeArmani** [comment]
TODO: update sort order to ascending for queryTotalAddressesToPrint (display oldest dates first).

Note: We will need to generate an index for this query. I can force the action link generation (sent by Firestore on initial execution) in dev & stage. I'll reach out to Tony, who has the permissions to create it.

@wyattks We can trigger this first-thing on release day and generate the prod index. I'll ask you to log in to Biospecimen prod and trigger this action. That will generate the update link we need to create the index. This is the same as the item you and I debugged a couple of release cycles ago when a page wouldn't load in prod on the morning of the release.

PR ready for review: https://github.com/episphere/connectFaas/pull/573

**Comment by JoeArmani** [comment]
Note: This is attached to https://github.com/episphere/connect/issues/953. Currently in team review. I'm leaving this in the 'development' category to avoid confusion/duplication within our review process, and I'll update the status here as reviews are completed.

**Comment by brotzmanmj** [comment]
Thanks Joe. Kathleen is out on work travel so @erincschwartz  can test this with you when you are ready.

**Comment by JoeArmani** [comment]
Update: The update to 'Assign Kits' sorting order is now attached to this issue so sorting is coordinated across the 'Print Labels' and 'Assign Kits' screens.

PR ready for review: https://github.com/episphere/connectFaas/pull/577

**Comment by JoeArmani** [comment]
Merged to dev, ready for testing:

Items to test:
• Confirm updated sort order for the 'Print Labels' CSV.
• Confirm updates sort order for the 'Assign Kits' participant list.

**Comment by erincschwartz** [comment]
@JoeArmani tested in Dev, order appeared correctly in 'Print Labels' CSV and 'Assign Kits' participant list.

**Comment by JoeArmani** [comment]
Thanks @erincschwartz 

Ready for stage.

**Comment by erincschwartz** [comment]
Stage testing complete. Ready for Prod.
