### ISSUE TITLE
PWA - MyToDo List Accessibility Enhancements (April Release)

### ISSUE THREAD

**Issue by JoeArmani** [episphere/connect#961]
My ToDo List Accessibility enhancements (JAWS/NVDA/VoiceOver)

•Enhance screen reader capabilities for the MyToDo List page (where participants access surveys). Improve navigation, screen reader output, and Quest wrapper for access via screen reader & keyboard navigation.

**Comment by JoeArmani** [comment]
Currently refining for April release.

**Comment by JoeArmani** [comment]
Merged to dev, ready for testing.

**Comment by cunnaneaq** [comment]
Tested Voice Over on Macbook in the MyConnect To Do list using keyboard navigation - updates look great!

**Comment by cunnaneaq** [comment]
Testing complete in stage
