### ISSUE TITLE
Sanford Clinical Variables Testing 

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#963]
Task check list: https://app.box.com/integrations/officeonline/openOfficeOnline?fileId=1496791472935&sharedAccessCode=

Review issue : https://github.com/episphere/connect/issues/940

Testing file: https://nih.app.box.com/file/1486097355859

Please see the below testing checklist. Please check off when done and note date and initial of completion:

- [x] @mnataraj92 Reach out to Sanford with testing plan and variables to test - MN 4/2
- [x] @mnataraj92 Confirm with Michelle and Erin that testing plan covers all scenarios - MN 4/2
- [x] @mnataraj92 Set up dev testing meeting with Sanford and internal team for 4/11 - MN 4/9
- [x] @mnataraj92 Confirm with Sanford that they will create dev participants for testing - MN 4/9
- [x] @JoeArmani Check firestore during Dev/Stage testing ([√] dev complete / [√] stage complete)
- [x] @erincschwartz or @wyattks Check Clinical Biospecimen Dashboard during dev/stage testing0 ES 4/16
- [x] @jacobmpeters or @jeannewu Sync BQ and Firestore so Jing can check BQ during dev/stage testing - JP 4/16
- [x] @mnataraj92 Set up stage testing meeting with Sanford and internal team for 4/16- MN 4/15
- [x] @sonyekere Alert DevOps to  grant Prod access for the Biospecimen Dashboard

**Comment by mnataraj92** [comment]
Hi everyone, thanks so much for heling with testing yesterday!! @erincschwartz, @JoeArmani, @jeannewu whenever you get a chance, please check off the item you completed and initial and date the item with the date of completion as well (by editing Sandra's comment with the checklist). Thank you!

**Comment by jeannewu** [comment]
> Task check list: https://app.box.com/integrations/officeonline/openOfficeOnline?fileId=1496791472935&sharedAccessCode=
> 
> Review issue : #940
> 
> Testing file: https://nih.app.box.com/file/1486097355859
> 
> Please see the below testing checklist. Please check off when done and note date and initial of completion:
> 
> * [x]  @mnataraj92 Reach out to Sanford with testing plan and variables to test - MN 4/2
> * [x]  @mnataraj92 Confirm with Michelle and Erin that testing plan covers all scenarios - MN 4/2
> * [x]  @mnataraj92 Set up dev testing meeting with Sanford and internal team for 4/11 - MN 4/9
> * [x]  @mnataraj92 Confirm with Sanford that they will create dev participants for testing - MN 4/9
> * [x]  @JoeArmani Check firestore during Dev/Stage testing ([√] dev complete / [√] stage complete)
> * [x]  @erincschwartz or @wyattks Check Clinical Biospecimen Dashboard during dev/stage testing0 ES 4/16
> * [x]  @jacobmpeters or @jeannewu Sync BQ and Firestore so Jing checked BQ during dev/stage testing - JP/WJ 4/16
> * [x]  @mnataraj92 Set up stage testing meeting with Sanford and internal team for 4/16- MN 4/15
> * [ ]  @sonyekere Alert DevOps to  grant Prod access for the Biospecimen Dashboard
