### ISSUE TITLE
SSN Survey Question Text Revisions (May Release) 

### ISSUE THREAD

**Issue by cusackjm** [episphere/connect#964]
Question text revisions to SSN and SSN4d - See tracked changes in: https://nih.app.box.com/file/1348654605060?s=vgtla8c82pl3rj6feschs7ez0zzmmmpv

This can go in the next release cycle (i.e., not part of the regular survey cadence)

**Comment by anthonypetersen** [comment]
@cusackjm please confirm if this looks good

<img width="871" alt="image" src="https://github.com/episphere/connect/assets/18222069/37b53835-9f38-460d-a4bb-bb81ee67c451">

<img width="849" alt="image" src="https://github.com/episphere/connect/assets/18222069/2e073cfd-3632-41a6-a2b5-5c2366c87342">

**Comment by brotzmanmj** [comment]
Adding @depietrodeanna  to make sure we think this will be clear now?

**Comment by depietrodeanna** [comment]
I don't necessarily think we have to say leave them blank.  My only suggestion would be maybe bolding "9 digits" and "4 digits" in the question text on each screen to call that out. And/or, providing a format (XXX-XXX-XXX) or (XXXX).

**Comment by anthonypetersen** [comment]
So the second instance of `4 digits` is bolded here if you look closely. Might be better off underlining as well?
<img width="1020" alt="image" src="https://github.com/episphere/connect/assets/18222069/9c085e66-b505-4f92-bb6c-ad6591ead82f">

**Comment by depietrodeanna** [comment]
I cannot see that at all! I'd suggest adding the underline.

**Comment by anthonypetersen** [comment]
I'm assuming the tracked document will need to be updated, do you guys want to collaborate and let me know when all suggested changes are tracked?

**Comment by cusackjm** [comment]
![image](https://github.com/episphere/connect/assets/85582895/078a9f10-150f-4a3e-8ff5-12a1ea839240)
 @brotzmanmj @depietrodeanna should we delete the part crossed out? It looks redundant otherwise

**Comment by anthonypetersen** [comment]
@cusackjm see my last image, I noticed the redundancy and removed

**Comment by depietrodeanna** [comment]
I agree @cusackjm. Could you add the underlining and then I think we're set?

**Comment by cusackjm** [comment]
https://nih.app.box.com/file/1348654605060?s=vgtla8c82pl3rj6feschs7ez0zzmmmpv SSN survey doc is updated

**Comment by anthonypetersen** [comment]
@cusackjm Please confirm the screenshots below:

<img width="1207" alt="image" src="https://github.com/episphere/connect/assets/18222069/99def9c0-ffa0-44a0-ae3e-0076189532ee">

<img width="1194" alt="image" src="https://github.com/episphere/connect/assets/18222069/9f51d5f3-b288-433a-9b10-90be16ce83b2">

**Comment by cusackjm** [comment]
@anthonypetersen looks good

**Comment by cusackjm** [comment]
@anthonypetersen passed dev testing

**Comment by anthonypetersen** [comment]
@cusackjm this is in stage now, please let me know when it's good for prod

**Comment by cunnaneaq** [comment]
Changes look good in stage
