### ISSUE TITLE
Check in and check out timestamp handling- repeat baseline visits (Biospecimen)

### ISSUE THREAD

**Issue by erincschwartz** [episphere/connect#965]
On 4/11, UCM team reported that Connect ID: 5732093949 had been checked in for baseline collection but could not stay to complete the visit. UCM team member completed specimen link and check out. When the participant returned on 4/11 to complete the collection visit, after check in and conducting the visit, but prior to check out, UCM team member noticed that this participant was not appearing in the "Check Out Report." The participant also was not appearing in the "Daily Review Report." UCM team was able to complete check-out, they just wanted to bring this to NCI's attention. 

Check-in and check-out timestamp handling

Related Concept IDs:
331584571.266600170.343048998 (check-out)
331584571.266600170.840048338 (check-in)
 
Description:
Sometimes participants need to return for a second baseline visit (cases: unable to provide specimens, specimens lost in transit, etc.)
 
Current Issues:
•The check-in timestamp needs to update when a participant is re-checked-in. It currently retains the original date
•The check-out timestamp needs to be deleted on re-check-in for ‘check out reports’ to function correctly.

**Comment by sonyekere** [comment]
Revisit in June
