### ISSUE TITLE
Moving Client Side Emails to Firestore 

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#968]
Placeholder for requirements - Client side emails will move from a code base structure to Firestore.  Aiming for the May release, but could potentially be moved to the June release.

**Please note that a separate issue will need to be created to address Spanish**.

**Comment by we-ai** [comment]
There's a related discussion: https://github.com/episphere/connect/discussions/812

**Comment by HanaShiho** [comment]
ready for stage

**Comment by sonyekere** [comment]
Noted on the punch list - ready for Prod
