### ISSUE TITLE
Participant App - Quest - Data Display Post Module Submission

### ISSUE THREAD

**Issue by meganstead** [episphere/connect#97]
Important functionality:
1) What data should participants be able to view from their baseline questionnaire modules after submission (this is a low priority) 
2) What, if any, of the baseline questionnaire should they be able to edit after submission.  

NOTE: All of Us does not display every question a person submitted- just a subset. Also the data displayed back to participants appear to be curated, not raw. And it is assumed that they don’t allow for direct editing

This topic is being discussed in the Participant Engagement committee.

Response from the PE committee is required to complete this issue and inform Issue #87

**Comment by Davinkjohnson** [comment]
stale
