### ISSUE TITLE
Restore biospec data for participants in prod (May Release) 

### ISSUE THREAD

**Issue by robertsamm** [episphere/connect#973]
It was found that some biospecimen vars are not being retained in the stub record that should be. For participants whose data was destroyed and had biospecimens collected, we will need to restore that data (e.g. flags for biospecimen collection). Madhuri and I are meeting tomorrow to identify the list of participants for this.

We will also need to track any additional participants that may have biospecimens collected and requested data destruction between now and the fix for adding those vars to the stub record to prevent additional data loss. Potential solution: add the additional biospecimen vars to the data destruction report and run it daily until issue has been fixed. 

See related issues #937 and #972

**Comment by robertsamm** [comment]
There is 1 participant with samples collected who had data destroyed that we will need to restore their biospecimen data for. In addition, there are 45 individuals who had data destroyed (with no samples collected) that will need their biospecimen variables reset from null to the default response. 

This will only need to be done for the biospecimen CIDs that were not included in the stub record but need to be added, the rest of these participants CIDs were retained or deleted as expected. See https://github.com/episphere/connect/issues/972

**Comment by mnataraj92** [comment]
Spoke with Michelle and Amelia and this will be added in the prod change log once we add the additional variables to the stub record. Once we make the necessary changes holistically, I'll add to the prod change log to mark the baseline blood, urine, MW collected flags as yes for Connect ID 2468652076, and for the 45 individuals that those flags are "null" instead of "no" I'll add to the prod change log to fix those as well.

**Comment by mnataraj92** [comment]
@robertsamm and I discussed restoring data for Connect ID 2468652076. This participant had samples collected, so 878865966, 167958071, 684635302 (baseline blood, urine, mouthwash collected) need to = yes (353358909). 

Additionally for Connect ID 2468652076, we think the flag for check in (d_331584571_d_266600170_d_135591601) should be set to yes (353358909) as well, and the date/time stamps for check in (d_331584571_d_266600170_d_840048338) and check out (d_331584571_d_266600170_d_343048998) can be backfilled. We did retain data on the date/time the specimens were collected, so perhaps we can use those timestamps to estimate the check in/check out time stamps. Maybe the biospecimen team could provide the average time between check in and check out. @brotzmanmj what are your thoughts on this?


For the 45 individuals that had data destroyed but did not provide biospecimen samples, 878865966, 167958071, 684635302 (baseline blood, urine, mouthwash collected) need to = no (104430631) as these are default variables.  

The other biospecimen variables that were recently added to the stub record are not default variables according to the data dictionary, so those can stay null for these 45 individuals. These variables are:

d_331584571 | BioSpm_Visit_v1r0 | Select visit
d_331584571_d_266600170_d_135591601 | BioChk_CompleteBL_v1r0 | BL Check-In Done
d_331584571_d_266600170_d_343048998 | BioFin_CheckOutTmBL_v1r0 | BL Time Check Out Done
d_331584571_d_266600170_d_840048338 | BioChk_TimeBL_v1r0 | BL D/T Check-In Done
d_526455436 | BioClin_BldAndUrnRef_v1r0 | BL Blood/Ur Ref

These are not default variables. I have excluded the follow up 1/2/3 versions of these variables from this list as it is not pertinent to these participants.

**Comment by brotzmanmj** [comment]
For Connect ID 2468652076, I agree 878865966, 167958071, 684635302 (baseline blood, urine, mouthwash collected) need to = yes (353358909). Was there anything else that was deleted but needs to be restored (i.e. collection setting)?

We should not attempt to restore the check in (d_331584571_d_266600170_d_135591601) or the date/time stamps for check in (d_331584571_d_266600170_d_840048338) or check out (d_331584571_d_266600170_d_343048998).  It will cause complications that are not worth addressing.

For the 45 individuals that had data destroyed but did not provide biospecimen samples, I agree with what you proposed to restore only the few default variables to No and leave the others as null.

**Comment by mnataraj92** [comment]
Hi @jhflorey that is correct.

@brotzmanmj the collection setting vars were retained as they are nested under 173836415 and I confirmed this was the case in BQ for Connect ID 2468652076

**Comment by jhflorey** [comment]
@mnataraj92 Already updated vars for 45 participants by my script https://gist.github.com/jhflorey/948b9ea287c36541f32292c4ca960644. 

`8437377292
3665757145
6575848257
5810762484
7611644934
7329688967
6880853459
3899176500
6792098176
1974642387
4276016386
6851074592
7570850444
5516837502
9873667215
3952268104
2759755942
1720924551
3829528105
5547802251
1905833856
8850194605
5691170745
1308062179
8615148046
7549049278
2925129751
8790139556
1108023704
8868913771
1637720696
9286933970
6363772898
1848404718
6625754395
6522969630
4451434373
9047328610
8409194117
8339529319
9590323728
3388199139
3516658074
9843524210
8777216716`

**Comment by mnataraj92** [comment]
> @mnataraj92 changes for 2468652076 will be done manually by myself, please add to prod change log.

I have added this to the prod change log

**Comment by jeannewu** [comment]
Based on today's checking on BQ in prod, All these 45 pts @jhflorey and @mnataraj92 mentioned above have their biospecimen data on d_684635302,d_878865966 and d_167958071 be restored in participants table with their entries as "no" (concept id = "104430631") as expected.

**Comment by anthonypetersen** [comment]
Single participant updated today, should be able to close this now.
