### ISSUE TITLE
Dev dashboard issues: Mouthwash kit shipment and BPTL Collection ID Search (Biospecimen) April Release 

### ISSUE THREAD

**Issue by erincschwartz** [episphere/connect#975]
Two issues are going on in Dev today: 
1) When attempting to ship kits today, error message popping up:

![Image](https://github.com/episphere/connect/assets/157617486/364ed0c4-d749-46d0-ba5b-27f2c23b0d54)

2) When searching for Collection ID in BPTL instance, error message popping up despite having confirmation that specimens were finalized and should be searchable:

![Image](https://github.com/episphere/connect/assets/157617486/ef1a6eaa-28a0-4867-829c-9b4f8af05cef)

@JoeArmani has spreadsheet with additional information on these two issues.

**Comment by erincschwartz** [comment]
Just tested these two issues, they are now resolved in Dev.

**Comment by JoeArmani** [comment]
ready for stage

**Comment by erincschwartz** [comment]
1) Tested kit shipment in Stage, no issues. Ready for Prod.
2) Tested Collection ID in BPTL instance of the Stage Dashboard. Ready for Prod.
