### ISSUE TITLE
SMS Not Being Sent

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/connect#976]
Data type Mis-match (numerical vs empty string) is causing SMS to no longer be sent from Connect.

**Comment by we-ai** [comment]
There's one doc in Firestore that introduced an empty string ("") as value of "can we text"(CID 646873644), causing mixed data type problem for CID 646873644 downstream in BQ.

The empty string was changed to "no" (CID 104430631) before 3pm today, fixing current mixed data problem in BQ.

Two more steps are need as short term and permanent solutions:
- As a quick fix, add code to handle mixed data types for "can we text"
- Find the cause of assigning string data type to "can we text", and fix the problem

**Comment by brotzmanmj** [comment]
There are three places the 'can we text' question can get updated in three places: (1) On the User Profile when someone enters a mobile number ('can we text' is not required, but can only select yes or no from the dropdown if they choose to answer). (2) MyProfile page - they can add/edit their phone numbers and add/edit the 'can we text' response. (3) SMDB participant details page - NORC and site staff can add/edit phone numbers and 'can we text' field. See if we need to check each and if someone a string response can get inserted. If history is captured for UP updates, check that too.
