### ISSUE TITLE
Shipping Dashboard - Sanford Box showed up in Shipping dashboard after it was shipped and received (Biospecimen)

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#977]
Sorry was unable to add this to the Site Issues Tracking board.

Sanford sent a message that their Box 667 is still showing up on the shipping dahboard. This packages was shipped on 4/19 and received by BPTL on 4/20. This information shows up in the reports section.
The FedEx tracking number is 725733539980.

This is similar to the following GitHub Issue
https://github.com/episphere/connect/issues/833

**Comment by wyattks** [comment]
Jessica confirmed there 2 people in the shipping dashboard at one time.  One person did logout and let the other person continue.

**Comment by JoeArmani** [comment]
Upon back-end inspection, the box is missing shipment data:

Shipped (145971562): 104430631 (no)
Submit shipment timestamp (656548982): null
Received (333524031): 104430631 (no)
Tracking number (959708259): null (not assigned)
Shipment courier (666553960): null
Shipper email (948887825): null

Based on the data, it shouldn't have been visible on the BPTL packages in transit, either. Can you confirm this?

The user may have forgotten to complete the shipment. I'll share a DataDog session I found with you @wyattks.

**Comment by wyattks** [comment]
725733539980 shows up in the shipping report as Box666 and not Box667. 
Samples associated with 725733539980 (Blood and Urine) show up on the receipt file.
725733539980 does not show up on the In Transit file from friday 4/19/2024 (attached).


[2024-04-19-In-Transit-XLSX-data-export.xlsx](https://github.com/episphere/connect/files/15077292/2024-04-19-In-Transit-XLSX-data-export.xlsx)

**Comment by wyattks** [comment]
After reviewing with Joe, It appears this issue is on Sanfords side with how they were completing the shipping.  Jessica was trying to sign off using Kimberly's account.  There does not appear to be any issues with the dashboard.
