### ISSUE TITLE
Data Destruction Re-test Check list ( May Release) 

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#978]
Hello Everyone, Please see the below checklist for testing. We ask that you review the list and check off the item with your initial and date of completion.

- [x] @cunnaneaq to create test participants in Dev to test the recent variables added to the stub record - (AC 5/1/24) 
- [x] @mnataraj92 to reach out to site to create participants for stage testing- MN 5/16/24
- [x] @mnataraj92 to send out an invite to the team for dev [x] and stage [x] testing- MN 5/2/24 & 5/13/24
- [x] @jeannewu to share the listing of nested variables from BQ with @rohanjay10 (RJ 5/1/24)
- [x] @rohanjay10  to make an excel list of variables (all stub records including biospecimen and nested variables) that will be retained in the stub records and post in this GitHub issue (RJ 5/2/24)
- [x] @jhflorey will run the data destruction program in dev and stage during testing 
- [x] @jhflorey  to bypass the 60 day rule to sign the data destruction form 
- [x] @jacobmpeters to sync Big Query with Firestore (JP 5/6)
- [x] @jeannewu to generate listing of retained variables 
- [x] @rohanjay10  to work with @jeannewu to verify variables retained

**Comment by rohanjay10** [comment]
Here is the Excel list of stub variables to be retained (including biospecimen and nested variables).

[Connect_0902.01 Data Destruction_03132024_T1_pg4_6_updated_biospe_3envir_updated05012024T (3) - Copy.xlsx](https://github.com/episphere/connect/files/15194149/Connect_0902.01.Data.Destruction_03132024_T1_pg4_6_updated_biospe_3envir_updated05012024T.3.-.Copy.xlsx)

@jhflorey These are good for you to do a final check before testing.

**Comment by jeannewu** [comment]
- Hi, everyone, I can check my work in the checking list above. I have marked down the work I did here. Sorry for the inconvenience. 

 **@jeannewu to generate listing of retained variables (WJ 4/30/2024)**
 **@rohanjay10 to work with @jeannewu to verify variables retained (WJ 5/2/2024)**

**Comment by mnataraj92** [comment]
Tested, in stage, ready for prod. 

Spoke with @brotzmanmj and just wanted to note that d_507120821 (an old participation status variable that hasn't been in use since October 2021) was retained during stage testing. We will discuss with @FrogGirl1123 whether this variable should be removed from the data upon her return.
