### ISSUE TITLE
Bug causing an empty string for variable d_271757434 (May Release)

### ISSUE THREAD

**Issue by mnataraj92** [episphere/connect#979]
It looks like there's a bug causing an empty string for d_271757434 (Can we leave voicemail at this number?- Mobile). There are 3 unique responses in the data: 

"{integer:104430631,string:null,provided:integer}",
"{integer:null,string:,provided:string}",
"{integer:353358909,string:null,provided:integer}"

and over 25,000 participants have one of those responses for this variable. Could you please look into this? Thank you!

**Comment by we-ai** [comment]
Related GH issue: [938](https://github.com/episphere/connect/issues/938)
