### ISSUE TITLE
Participant App - Quest - Data Display Prior to Module Submission

### ISSUE THREAD

**Issue by meganstead** [episphere/connect#98]
Third issue for whether and how participants should be able to review the data from their questionnaire module before submission (this is a higher priority). Tag Neal Freedman if he is a GitHub user. 

Important functionality:
1) Should participants be able to review the data from their questionnaire module before submission?
2) How would the participant review information?
3) What, if any information might the participant be able to change before submission?  

This topic is being discussed in the Participant Engagement committee.

Response from the PE committee is required to complete this issue and inform Issue #87

**Comment by Davinkjohnson** [comment]
Stale
