### ISSUE TITLE
My samples UChicago (May Release) 

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#982]

**Comment by depietrodeanna** [comment]
Tracked page here: https://nih.app.box.com/file/1483588446048?s=ybghe8orfhtk8pt5nxl4rmiw6dpi8q01
There are a lot of tracked changes to implement. If you prefer to view a clean copy side by side, let us know and we can add one here.
@jhflorey please review changes in Dev with Hana/me as you're ready.

**Comment by depietrodeanna** [comment]
@jhflorey ready for prod

**Comment by sonyekere** [comment]
In Prod
