### ISSUE TITLE
HP Consent and HIPAA forms (June release) 

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#984]
As part of the June release, we need to update the HP ENGLISH consent and HIPAA forms in the PWA and SMDB to reflect their change in PI. This is only being updated for HP in English, no other sites.

**Consent**	
Finalized Form Box Link: https://nih.app.box.com/file/1530308479199	
Link	Tracked Version for HTML: https://nih.app.box.com/file/1516740340472	
Variable Response Label: HP_Consent_V0.05

**HIPAA**	
Finalized Form Box Link: https://nih.app.box.com/file/1512222085228	
Tracked Version for HTML: https://nih.app.box.com/file/1516735041045	
Variable Response Label: HP_HIPAA_V0.03

This should be updated the same we have for past consent updates where the consent and HIPAA version that is displayed will be tied to the date the participant consented. New participants will receive the updated forms, while old participants will receive the old forms they signed under.

PWA: The revised consent+HIPAA should be updated in the PWA in the following places for recruits who sign the consent on and after time of prod push: (1) HTML consent form preview box on pg 9 of eConsent, (2) downloadable unsigned consent form on pg9 eConsent, (3) downloadable signed consent form on next screen after signing, (4) downloadable signed consent form on ‘Forms’ tab

SMDB: The revised consent+HIPAA should be updated in the SMDB in the following places for recruits who sign the consent on and after time of prod push:(1) Add consent and HIPAA forms to SMDB downloadable rows on Participant Summary page, (2) 'consent version' and 'HIPAA version' variable bubble fields

**Comment by robertsamm** [comment]
@Davinkjohnson @sonyekere @bransteitterbr Deprioritizing the HP consent/HIPAA form PI change to the June release as we have not yet gotten approval from IRB yet on the consent form.

**Comment by robertsamm** [comment]
Hi @bransteitterbr, I've just updated this github issue with the updated HP consent and HIPAA forms (in English) for their PI change.

**Comment by bransteitterbr** [comment]
Hi @robertsamm do we have the consent pdf yet or is that still pending approval?

**Comment by robertsamm** [comment]
@bransteitterbr unfortunately still pending approval, IRB just sent back a request today to make changes to the certificates of translation before they will approve it. However, I would be fine with going ahead and uploading the model consent form in dev to the NCI site without the stamp of approval on it as the NCI site isn't in stage/prod.

**Comment by bransteitterbr** [comment]
@robertsamm do you have the HIPPA v3 pdf

**Comment by robertsamm** [comment]
@bransteitterbr scratch that, I didn't look closely enough at the issue and thought your question was about the Spanish consent and HIPAAs! My apologies. For HP English, yes we have both PDFs of consent and HIPAA! All approved and ready to be loaded in.

Consent: https://nih.app.box.com/file/1530308479199
HIPAA: https://nih.app.box.com/file/1540534912308

**Comment by robertsamm** [comment]
@amber-emmes looks good in dev. Will do a quick sanity check once Spanish is pulled out to make sure the new HP forms remain. But otherwise, looking ready for stage.

**Comment by robertsamm** [comment]
My initial quick test of this looked good in stage. HP is conducting a more thorough test in stage and will report back. @kmazzilli or @brotzmanmj to update this issue once we receive HPs testing results to confirm this is ready ready for prod (but I don't expect they will find any issues).

**Comment by kmazzilli** [comment]
Ready for prod - this looks fine but HP noted some minor formatting issues we can focus on in a future release
