### ISSUE TITLE
BPTL Dashboard Home Collection Updates (Biospecimen)

### ISSUE THREAD

**Issue by erincschwartz** [episphere/connect#988]
General edits:
1) Automate advancing to next data entry field throughout all pages (currently requires FNL team to manually click into the next field) 

Kit Assembly Screen: 
1) Change 'Tracking Number' to 'Return Kit Tracking Number'
2) Add another field for 'Confirm Return Kit Tracking Number' and add programming to cross check the tracking number data to ensure a match 

![Image](https://github.com/episphere/connect/assets/157617486/f64071b3-dcd7-4719-86a5-710ddc941986)

Assign Kits Screen: 
1) Change 'Tracking Number' to 'Supply Kit Tracking Number'
2) Add another field for 'Confirm Supply Kit Tracking Number' below 

![Image](https://github.com/episphere/connect/assets/157617486/07237849-d76d-4afe-9e12-e49c1695d944)

and add programming to cross-check the tracking number data to ensure a match 

Kit Shipment Screen: 
1) Change 'Scan tracking number' to 'Scan Supply Kit Tracking Number'

![Image](https://github.com/episphere/connect/assets/157617486/bf1fbb3a-7b7a-4912-9755-0f6bce5c6b75)

Kits Receipt
1) Change 'Scan Barcode' to 'Scan Return Kit Tracking Number'

![Image](https://github.com/episphere/connect/assets/157617486/33a48ada-c021-43a3-aba5-12e1f1802ad6)

**Comment by erincschwartz** [comment]
Additional request on Kit Receipt screen: 
1.  Add validation to ensure that the Collection ID matches the Collection ID (Cup ID) that was linked to the Return Kit Tracking Number during Kit Assembly
2. Ensure that system does not partially write any data that doesn't save 


![Image](https://github.com/episphere/connect/assets/157617486/0f30b82c-1b44-4598-b558-f664ebcb8ef7)

**Comment by amber-emmes** [comment]
The Biospecimen-specific work is now in dev and ready for review. That consists of all features _except_ the two listed below:

* Add validation to ensure that the Collection ID matches the Collection ID (Cup ID) that was linked to the Return Kit Tracking Number during Kit Assembly
* Ensure that system does not partially write any data that doesn't save

**Comment by amber-emmes** [comment]
The connectFaaS work is now also ready for review in dev. This consists of the following work:

- Add validation to ensure that the Collection ID matches the Collection ID (Cup ID) that was linked to the Return Kit Tracking Number during Kit Assembly
- Ensure that system does not partially write any data that doesn't save

Please also generally re-test the Kit Receipt page to ensure the functionality looks good.

**Comment by erincschwartz** [comment]
@amber-emmes Testing this now. 

Can you add "Kit" to "Return **Kit** Tracking Number" on Kit Assembly Screen?

Also, when attempting mis-matched tracking numbers on Assign Kits screen, the system will not allow (which is great) but there is no warning message. Can this be added? Similar to what you built into the Kit Assembly screen for the tracking number check would be great.

**Comment by erincschwartz** [comment]
@amber-emmes, I tested Kit Receipt page, it worked as expected and did not allow receipt of the wrong Collection ID. Tested functionality with correct Collection ID and everything looked good. 

FYI, I will create an issue for next release to make error message more specific when Collection ID does not match what was originally linked to the Return Kit Tracking Number during kit assembly (will help FNL team and us understand the problem more quickly)

**Comment by amber-emmes** [comment]
Your two requested changes are now in dev and ready for re-testing. Please re-review both the Kit Assembly and Assign Kit screens to be safe. Thanks!

**Comment by Gbarra9** [comment]
Added new issue: https://github.com/episphere/connect/issues/1018

Tested in dev and ready to be merged to stage

**Comment by wyattks** [comment]
Tested in Stage. Ready for Prod.

**Comment by amber-emmes** [comment]
This is now in prod.
