### ISSUE TITLE
Home Collection Receipt CSV File- default values not populating (Biospecimen) (June Release)

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#989]
On the Home Collection receipt csv, the default values for Vial Type, Additive/Preservative, Material Type and Volume are not populating.  They only populate if the Collection Center is Kaiser Permanente Colorado RRL.  The default values need to populate for all the collection centers in the Home Collection.  The values are located on the Home Collection tab of this file: https://nih.app.box.com/file/1306346523951

**Comment by sonyekere** [comment]
June release

**Comment by wyattks** [comment]
This issue is slowing he lab receipt process down.  can we get this done soon?

**Comment by brotzmanmj** [comment]
Let's discuss priorities among biospecimen items on the call on Tuesday, if we need to prioritize this over some other biospecimen items we can decide then

**Comment by wyattks** [comment]
Hi Amber,
To repeat this issue, you need to send a clinical collection through that is not from KPCO.  You add a colection through data entry and ship the same collection.  Receive the shipment on the BPTL dashboard and click on "Create cvs file".  On that screen you enter the date received under "Receipted CSV File" and click "Create File".  THe csv file shoould pop up.  As long as KPCO is not the site you will see the fields needed are not pre-populated as expected.  Please let me know if you need more informaiton.
Thanks!

![Image](https://github.com/episphere/connect/assets/64605220/69bc1541-7343-4685-803e-83491330cd9b)



![Image](https://github.com/episphere/connect/assets/64605220/11c29d16-11a3-4487-8fb3-95d5de7f97d4)

**Comment by amber-emmes** [comment]
@wyattks 

I have some theories about what's going on here but I'm having some trouble actually getting through the full workflow for generating and shipping a collection. Is it possible to generate this CSV using existing received collections by putting in a date which would generate collections, and if so, is there a way to view the appropriate dates/a good date to use?

**Comment by wyattks** [comment]
Hi @amber-emmes  USe the following date:  5/22/2024
This will still have the date drawn issue but will give you an idea of the default values not populating.

**Comment by amber-emmes** [comment]
@wyattks I do not see any entries when I use that date for this report:

![image](https://github.com/episphere/connect/assets/160774541/00ff2e27-21b3-48d4-9a8c-d2f2716cf9ce)

Can you send me an example of the csv file you are receiving?

**Comment by wyattks** [comment]
Hi Amber attached is the file.  Sorry, I had you going to the incorrect csv create location.  If you go to the Create csv under the Home Collection, that is where this csv is created.  Thanks!
[NAN Issue Testing 5-22-2024.csv](https://github.com/user-attachments/files/15838814/NAN.Issue.Testing.5-22-2024.csv)

**Comment by amber-emmes** [comment]
@wyattks 

Okay! I know why this is happening and it's an easy fix. I want to make sure I'm interpreting this file correctly, however. Since all of these are home collections, do we want them all to have the values listed here regardless of site?

![image](https://github.com/episphere/connect/assets/160774541/fa0fb9a5-529b-4e9f-bc8c-cdd2f6fd8e86)

Or should I be using the values listed for each individual site here?

**Comment by wyattks** [comment]
Home collections should all have the same information.

**Comment by amber-emmes** [comment]
This fix is in dev and ready for testing.

**Comment by wyattks** [comment]
Works in Dev  ready for stage

**Comment by wyattks** [comment]
Tested in Stage, ready for prod
