### ISSUE TITLE
QuestApp - Grid - Styling or Logic?

### ISSUE THREAD

**Issue by meganstead** [episphere/connect#99]
Discussed during the 5/5 internal prep meeting.

Requirements needed.

Potential new question type in modules 2 through 4 - grids. The current design requests grids as visuals for logical question series (i.e. for task X how many times, how much, etc). Need to evaluate, for the QuestApp technology, whether grids are a preferred styling or logic component? Note, the grid styling was intentionally selected (i.e. preferred) during questionnaire design.

Will have a call with Neil to discuss further.

**Comment by Davinkjohnson** [comment]
Quest has grids
