### ISSUE TITLE
Sanford Clinic Location Identifiers

### ISSUE THREAD

**Issue by mnataraj92** [episphere/connect#991]
Currently, 185243482 (blood location ID) and 452847912 (urine location ID) only allow for a variable length of 10. Sanford recently received the crosswalk, which includes the clinic names and the numeric identification numbers associated with each. Some of the clinic identifiers are more than 10 digits long. 

We would like to expand the variable length to 15 digits for each of these variables.

@sonyekere could you please check with dev ops to see if anything needs to be updated in the API to allow for the longer collection location to be sent?

**Comment by Davinkjohnson** [comment]
It looks like, as long as they send a valid number type (int) they should be fine. 
https://github.com/episphere/connectFaas/blob/master/updateParticipantData.json

<img width="334" alt="image" src="https://github.com/episphere/connect/assets/87718852/8a0fc021-c948-430a-8e2b-7bf0df8ed26f">

I believe this can be closed.

**Comment by mnataraj92** [comment]
@brotzmanmj can i close this issue?

**Comment by brotzmanmj** [comment]
yes thanks
