### ISSUE TITLE
Change description of home mouthwash survey on PWA (May Release)

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#992]
Currently the description for the mouthwash survey on the PWA says this: Contains questions about your oral health and hygiene practices.

We propose to change it to this:
'Complete this survey **on the day you collect your home mouthwash sample**. Contains questions about your oral health and hygiene practices that are related to your sample.' 

This is to make clear that even though the survey is available to be completed as soon as we ship them their kit, we don't want them to fill it out until the day they actually collect their sample.

@depietrodeanna can you review the proposed wording and make any suggested changes?

**Comment by depietrodeanna** [comment]
Proposed wording looks good to me. I would just switch the sentences for consistency, but keep the "**on the day you collect your mouthwash sample at home**" bolded to highlight that piece. 

So, "Contains questions about your oral health and hygiene practices that are related to your sample. Complete this survey **on the day you collect your mouthwash sample at home**."

**Comment by bransteitterbr** [comment]
@depietrodeanna and @brotzmanmj I posted a screen shot of the updated language.  Can you review it before I submit the PR

**Comment by depietrodeanna** [comment]
@bransteitterbr  this looks fine to me- there is an extra space between "home" and the period of that sentence that you can adjust.

**Comment by bransteitterbr** [comment]
ready for stage

**Comment by depietrodeanna** [comment]
@bransteitterbr do you have a screenshot in stage so I can check this?

**Comment by bransteitterbr** [comment]
@depietrodeanna I don't have a screenshot of this in stage.

**Comment by depietrodeanna** [comment]
Reviewed in stage. Ready for Prod.

**Comment by sonyekere** [comment]
In Prod
