### ISSUE TITLE
Edits to User Profile (May release)

### ISSUE THREAD

**Issue by cusackjm** [episphere/connect#993]
Edits to [User Profile](https://nih.app.box.com/file/501193852134?s=8p7esmx0eafr7ela6gbne4zorvsgnwal) 

1. Revised Suffix options (Edits are in DD)

**Comment by Davinkjohnson** [comment]
@cusackjm  is this the same as #941?

**Comment by cusackjm** [comment]
@Davinkjohnson yes

**Comment by Davinkjohnson** [comment]
OK thanks. I'll merge your doc above with the existing issue so all requirements are in one issue.
