### ISSUE TITLE
Part 1: User Profile Enhancements for Intro and MyProfile page (December Release)

### ISSUE THREAD

**Issue by cusackjm** [episphere/connect#994]
Requirements here: https://nih.app.box.com/file/1674557082093
Edits to [User Profile Criteria](https://nih.app.box.com/file/501193852134?s=8p7esmx0eafr7ela6gbne4zorvsgnwal) 

1. Language Content Changes and introduction text update on the introduction/main screen page(before User Profile page). Changes listed on [Criteria here](https://nih.app.box.com/file/501193852134?s=8p7esmx0eafr7ela6gbne4zorvsgnwal) in orange
2. Require double entry of data of birth field with a QC check before committing data(with confirmation entry and error if both entries doesn't match). Only needs to be stored in data once 
- Confirmation Entry should be formatted vertically and to the right of the initial DOB entry(that is saved)
3. Add place of birth under 'Date of birth' section

- New Variables to be created to be stored in participants table: 
Place of Birth (not nested, not required) 
       1. City
        2. State
        3. Country

- Open text fields added for fields 'City', 'State', 'Country'. No dropdown for State if 'Out of US'

4. Lock middle name and suffix from being editable on user profile. Should be exported from consent and not be changed

**Comment by rohanjay10** [comment]
[User Profile Enhancement Requirements:](https://nih.app.box.com/file/1674557082093)

[Latest Technical Requirements:](https://nih.app.box.com/file/1682708732760)
Current Items for discussion: 
* Guidance on what modal/confirmation looks like when invoking USPS API check, once development starts
* Confirm Physical Address is also run through USPS API
* Confirm that storing names under the UserProfile history nested structure for UP Name fields before initial API pull of UP data will not break sites process

**Comment by rohanjay10** [comment]
Hi all, messaged with @bransteitterbr and adding that all the new UP update text and error messages on the PWA needs to be translated into Spanish (including Former Name #1150 and Contact Information #1149 changes). Messaged with @depietrodeanna about this and once we  have everything that needs to be translated finalized, it would be helpful to have it all compiled in one place. 
          **Some error messages we need**: Double Entry DOB if 2nd entry does not match, Possibly Place of Birth, email validation typo messages, and Mailing/Physical address errors.

@robertsamm I think we may have to add this to the requirements document

**Comment by rohanjay10** [comment]
Updating that we met today to discuss UP Spanish Translations:
**Next steps/Updates**

- UP Content for translation is almost finalized and should be coming back tomorrow 
- MyProfiles page translations should mimic translations done on User Profile Page, for respective matching components
- Me and Amelia to work on a document compiling a list of error messages and labels to be translated into Spanish 

Please feel free to add on or update the above

**Comment by robertsamm** [comment]
Spanish translation of the User Profile content is located on Box here: https://nih.app.box.com/file/1699219693658

**Comment by rohanjay10** [comment]
Here is the latest draft of the UP updates error messages, to be translated, located on Box here: https://app.box.com/s/h1jdjwe8ah3ydkwfcaow223q3irae2i4

Please feel free to review/add on

**Comment by jhflorey** [comment]
@rohanjay10 @mnataraj92 have we had the new conceptids

**Comment by mnataraj92** [comment]
User Profile Updates Variables/CIDs:

Place of Birth- City (RcrtUP_PoBCity_v1r0): d_876546260

Place of Birth- State (RcrtUP_PoBState_v1r0): d_337485417

Place of Birth- Country (RcrtUP_PoBCountry_v1r0): d_384576626

Flag for if Mailing address is a PO Box (RcrtUP_POBox_v1r0): d_250235523


The following will get added to the User Profile History (under d_569151507):

Physical Address- Address line 1 (RcrtUP_PhysAddressLn1_v1r0): d_207908218

Physical Address- Address line 2 (RcrtUP_PhysAddressLn2_v1r0): d_224392018

Physical Address- City (RcrtUP_PhysCity_v1r0): d_451993790

Physical Address- State (RcrtUP_PhysState_v1r0): d_187799450

Physical Address- Zip (RcrtUP_PhysZip_v1r0): d_449168732

**Comment by mnataraj92** [comment]
The following will get added to the User Profile History (under d_569151507):

Physical Address- Address line 1 (RcrtUP_PhysAddressLn1_v1r0): d_207908218

Physical Address- Address line 2 (RcrtUP_PhysAddressLn2_v1r0): d_224392018

Physical Address- City (RcrtUP_PhysCity_v1r0): d_451993790

Physical Address- State (RcrtUP_PhysState_v1r0): d_187799450

Physical Address- Zip (RcrtUP_PhysZip_v1r0): d_449168732

**Comment by depietrodeanna** [comment]
<img width="852" alt="Screenshot 2024-11-19 at 8 11 38 AM" src="https://github.com/user-attachments/assets/aacb5108-a124-4302-91c2-9d9d676bd8ed">

@rohanjay10  I can pass these off for quick translation today. Are the rest of the error messages in that document finalized for translation as well or should I wait on those?

**Comment by rohanjay10** [comment]
@depietrodeanna Great thanks. The other error messages(pt 3) are not finalized yet so yes please wait on those

**Comment by depietrodeanna** [comment]
Submitted and asked for delivery by EOW.

**Comment by rohanjay10** [comment]
Thanks for the update. @jhflorey @robertsamm @sonyekere keeping all of you in the loop on this as well - Pt 1 and Pt2 error messages translations should be delivered by EOW.

**Comment by rohanjay10** [comment]
Hi all, confirmed with @jhflorey that the UP Part 1 changes are ready for Dev testing (apart from the pending pt 1 Spanish translations noted above)

**Comment by depietrodeanna** [comment]
@rohanjay10 and @jhflorey NORC relayed this content back in Spanish for DOB and former name error messages:
<img width="732" alt="Screenshot 2024-11-21 at 12 46 57 PM" src="https://github.com/user-attachments/assets/931c572b-2e12-4cb4-a806-fdb6cd45958c">

**Comment by rohanjay10** [comment]
Great thanks for the update. Copying to UP Pt2 Issue #1150

**Comment by jhflorey** [comment]
> @rohanjay10 and @jhflorey NORC relayed this content back in Spanish for DOB and former name error messages: <img alt="Screenshot 2024-11-21 at 12 46 57 PM" width="732" src="https://private-user-images.githubusercontent.com/74061787/388689408-931c572b-2e12-4cb4-a806-fdb6cd45958c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMjIzNDUsIm5iZiI6MTczMjIyMjA0NSwicGF0aCI6Ii83NDA2MTc4Ny8zODg2ODk0MDgtOTMxYzU3MmItMmUxMi00Y2I0LWE4MDYtZmRiNmNkNDU5NThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDIwNDcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwYTEzYmYyOTMwOGE1ZTA4NjFjNGJhNzljY2JjZDQwZTQxOGNjYmE3NjM1OGJhYmUxMDExMzI5ZGQ0ODU1OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.taVfCA711OVkHMJwYBimEZ7ybh98A14VbHgxsHqoenk">

@depietrodeanna could you please paste the text. You just sent the image and i can not copy/paste it.

**Comment by robertsamm** [comment]
Hi @jhflorey I have copied and pasted the Spanish translation of pt 1 and pt 2 error messages into the error message doc on Box here: https://nih.app.box.com/file/1699379771757

**Comment by rohanjay10** [comment]
Hi all, I've added notes/action items from UP Pt1, Pt2 testing. Please add anything else needed.

UP Pt1/2 Testing

**Introduction Text**

- Remove extra hyper link for "myconnect.cancer.gov/support" in last part of introduction text

**DOB**
-  Suggestion is to have this formatted horizontally: 
Month Day Year
Please re-enter DOB
Month Day Year
- Language text to indicate why there are two sets of fields for DOB double entry(@robertsamm and @depietrodeanna  to work on this)

**When zooming in for a smaller screen:**

- Former name and DOB fields need to be formatted correctly

@jhflorey  to go through UI on phone/tablet and look into implementing responsive design checking with DevOps

UP Pt 1, Pt2 Testing Day 2:

**Scenario 6: HP, Scenario 7: Henry Ford**

- Site to pull UP name and confirm. @mnataraj92  to confirm site is able to pull back former name data and does not affect current procedures for verification

**Former Names**

- When Former Names name value has a number there is no error when submitted. It needs the same QC and error message shown when a number is entered in the Consent Name

**Spanish Translations:**
Introduction Text
•	Introduction text page before User Profile needs to have hyperlink removed(MyConnect.cancer.gov/support)
•	Last sentence: "Si tiene alguna pregunta, comuníquese con el Centro de Asistencia de Connect desde MyConnect.cancer.gov/support."

DOB
•	"Please re-enter Date of Birth" to be translated into Spanish 
•	Month/day/year language changes from English testing to be translated to Spanish, indicating why DOB requires double entry.
•	Confirm double entry of "month"/"day"/"year" are in Spanish

Former Names
•	Error message for former name dropdown shows up in English but should be in Spanish
 
User Profile Review responses confirmation screen(after submitting)
•	Former names(first name, middle name, last name) and Place of Birth(city, state, country) shows up in English and needs to be translated into Spanish

**PWA Bootstrap changes**
•	Check list of Bootstrap 5 changes/updates for PWA #1167

**Comment by rohanjay10** [comment]
Additional information/items for UP testing (also updated in the appropriate fields in previous comment:

> **Former Names**
> 
> * When Former Names name value has a number there is no error when submitted. It needs the same QC and error message shown when a number is entered in the Consent Name

- The Spanish error message shown for this error on the Consent Name field also needs to be shown in the Spanish text for the Former Names field 
- @depietrodeanna to double check the Spanish state dropdown values

**Comment by mnataraj92** [comment]
Vijay from HP and Eusuf from HFH both confirmed that they are able to pull back former name data and it does not interfere with any of their existing processes.

Vijay noted that he feels the user profile history could be extremely useful for their manual matching process and wants to have a discussion with the HP internal team to explore how they can best utilize this information.

**Comment by depietrodeanna** [comment]
> Hi all, I've added notes/action items from UP Pt1, Pt2 testing. Please add anything else needed.
> 
> UP Pt1/2 Testing
> 
> **Introduction Text**
> 
> * Remove extra hyper link for "myconnect.cancer.gov/support" in last part of introduction text
> 
> **DOB**
> 
> * Suggestion is to have this formatted horizontally:
>   Month Day Year
>   "Please re-enter DOB"
>   Month Day Year
> * "Please re-enter DOB" Language text to indicate why there are two sets of fields for DOB double entry(@robertsamm and @depietrodeanna  to work on this)
> 
> **When zooming in for a smaller screen:**
> 
> * Former name and DOB fields need to be formatted correctly
> 
> @jhflorey to go through UI on phone/tablet and look into implementing responsive design checking with DevOps
> 
> UP Pt 1, Pt2 Testing Day 2:
> 
> **Scenario 6: HP, Scenario 7: Henry Ford**
> 
> * Site to pull UP name and confirm. @mnataraj92  to confirm site is able to pull back former name data and does not affect current procedures for verification
> 
> **Former Names**
> 
> * When Former Names name value has a number there is no error when submitted. It needs the same QC and error message shown when a number is entered in the Consent Name
> 
> **Spanish Translations:** Introduction Text • Introduction text page before User Profile needs to have hyperlink removed(MyConnect.cancer.gov/support) • Last sentence: "Si tiene alguna pregunta, comuníquese con el Centro de Asistencia de Connect desde MyConnect.cancer.gov/support."
> 
> DOB • "Please re-enter Date of Birth" to be translated into Spanish • DOB language changes from English testing to be translated to Spanish, indicating why DOB requires double entry. • Confirm double entry of "month"/"day"/"year" are in Spanish
> 
> Former Names • Error message for former name dropdown shows up in English but should be in Spanish
> 
> > * When Former Names name value has a number there is no error when submitted. It needs the same QC and error message shown when a number is entered in the Consent Name
> 
> • The Spanish error message shown for this error on the Consent Name field also needs to be shown in the Spanish text for the Former Names field
> 
> User Profile Review responses confirmation screen(after submitting) • Former names(first name, middle name, last name) and Place of Birth(city, state, country) shows up in English and needs to be translated into Spanish
> 
> • Deanna to double check the Spanish state dropdown values
> 
> **PWA Bootstrap changes** • Check list of Bootstrap 5 changes/updates for PWA #1167

Language for DOB double entry in English: "Please confirm your date of birth by re-entering your information." Getting this translated and will update here.

**Comment by depietrodeanna** [comment]
First set of error messages in Spanish delivered from NORC (I know the soft suggestion is for a future release, but so we have it on record):

<head></head><p class="MsoNormal" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; margin: 0in; font-size: 11pt; font-family: Aptos, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><o:p> </o:p></p>
English | Spanish
-- | --
This email address is invalid. Please enter a valid email before continuing. | Esta dirección de correo electrónico no es válida. Por favor, introduzca un correo electrónico válido antes de continuar.
Warning- this email address may be invalid. Please double check your entry before continuing. | Advertencia: esta dirección de correo electrónico puede no ser válida. Por favor, vuelva a revisar su entrada antes de continuar.
Did you mean [insert email @ email client]? | ¿Quería decir [insert email @ email client]?

**Comment by jhflorey** [comment]
@rohanjay10 @depietrodeanna we need the Spanish text for the following:

- "Your former name should contain only uppercase and lowercase letters. Please do not use any numbers or special characters."
- "Mailing address is PO Box"

**Comment by sonyekere** [comment]
@depietrodeanna Thanks for passing on the translations to NORC! Do you foresee us not receiving those translations within the next hour? No immediate rush, it's just that Jessica may not be able to include the Spanish content in time for testing this afternoon. The translations can be incorporated into the code once NORC delivers them to us.

**Comment by depietrodeanna** [comment]
@sonyekere We will have the translation sometime this week but not by EOD.

**Comment by rohanjay10** [comment]
Hi, @jhflorey here are the discussed UP pt 1/pt2 changes discussed in today's call: 

•	Introduction text
    Intro text page currently has no hyperlink. There should be one hyperlink for the "MyConnect.cancer.gov/support" part of the text linking to that same URL 
•	Former Name
-	Currently there are two "former name" fields plus "name category". There should only be one field for "former name" and one field for "name category". With the add more button for additional fields.
-	Have the regular expressed called "ValidNameFormat" in shared.js implemented for former names field. This is likely also used in the consent Names field 
-	Consent Names field is accepting all characters apart from numeric while former names is currently giving errors for hyphens Ex: Amelia-Roberts"
-	Validation spot to be updated(regular expression below between "if" and "text"):
<img width="360" alt="image" src="https://github.com/user-attachments/assets/869b8398-a1f3-475a-8953-e45abf078101" />

**Comment by rohanjay10** [comment]
> @rohanjay10 @depietrodeanna we need the Spanish text for the following:
> 
> * "Your former name should contain only uppercase and lowercase letters. Please do not use any numbers or special characters."

Messaged with Deanna earlier and NORC provided the Spanish translation here, passed off to Amber : "Su antiguo nombre debe contener sólo letras mayúsculas y minúsculas. No utilice números ni caracteres especiales."
> * "Mailing address is PO Box"
We are still waiting on this translation from NORC @depietrodeanna please update when its ready for @amber-emmes to incorporate

**Comment by rohanjay10** [comment]
> > * "Mailing address is PO Box"
> 
> We are still waiting on this translation from NORC @depietrodeanna please update when its ready for @amber-emmes to incorporate

Hi all, updating that @depietrodeanna provided the translation over teams from NORC
English: "Mailing address is PO Box"
Spanish : "La dirección postal es PO Box"

**Comment by rohanjay10** [comment]
The changes are in Dev and this is ready for stage - Confirmed with Jessica and Amelia

**Comment by rohanjay10** [comment]
The changes are in stage and ready for prod
