### ISSUE TITLE
Handling clincial and research collections for the same collection timepoint

### ISSUE THREAD

**Issue by erincschwartz** [episphere/connect#995]
Past discussions have led the Biospecimen team to believe that if participants complete both research and clinical collections at the same timepoint (i.e. baseline), this will cause problems with the data. In some cases, a participant is invited in to complete a re-draw (samples dropped by lab staff and destroyed, samples delayed/lost in transit, etc). Sites have current instructions that any re-draws should occur under the same collection type (research or clinical) but errors may occur. Additionally, with the launch of clincal collections at additional sites in the coming months, there may be situations where collections at the same timepoint accidentally occur under both research and clincial collections. 

In Dev, **Connect ID 5773487914** has both clincal (blood and urine) and research (blood, urine, mouthwash) specimens entered. Please look at the data to see if entry of both collection types caused issues.

If having both visit types at the same timepoint does cause an issue, can the dashboard be programmed so that when team members go to add a specimen link in either research or clinical dashboards, the system checks if they already have a sample of the other kind for the same timepoint before Specimen Link is allowed to be saved?

**Comment by brotzmanmj** [comment]
@erincschwartz can you enter another case where a participant does urine and mouthwash research and does blood clinical, for baseline?  I think that was the scenario we were most concerned about that would 'break' something in the data structure. Thanks

**Comment by erincschwartz** [comment]
@brotzmanmj In Dev, Connect ID: 5027907288 had mouthwash and urine entered under Research; blood entered under Clinical. 

I did not take a screenshot of the SMDB but did confirm that urine and mouthwash showed as collected with Setting= Research before I entered the clincal blood collection. Now, the SMDB shows mouthwash as not collected. Urine still shows as collected but the Setting= N/A; also  collection dates are not present in the SMDB.

**Comment by brotzmanmj** [comment]
This seems to confirm what we suspected that the system has issues with clinical and research samples for the same timepoint. We should continue to disallow the sites from splitting a collection at a given timepoints between clinical and research. We have a GitHub issue created to prevent this; we can discuss prioritization.

@Davinkjohnson  should we close this issue? And do we need to back out these data from dev?

**Comment by JoeArmani** [comment]
> If having both visit types at the same timepoint does cause an issue, can the dashboard be programmed so that when team members go to add a specimen link in either research or clinical dashboards, the system checks if they already have a sample of the other kind for the same timepoint before Specimen Link is allowed to be saved?

Relevant properties to query in the 'biospecimen' collection data:
(1) 650516960 'CollectionSetting' has either the value 534621077 'Research' or 664882224 'Clinical.'
(2) 331584571 'Select visit from from drop down menu' has the value 266600170 'Baseline' (important to make sure we're handling the right visit for the future).
(3) Connect_ID

-We should be able to query these properties to determine whether the participant has an existing specimen collection and allow/disallow the operation as needed.

**Comment by erincschwartz** [comment]
Closing this issue that was used for investigating whether collection entry at the same timepoint into Research and Clinical Dashboards would cause an  issue---appears from operations side that it does. Will open new issue for July release for Biospecimen Dashboard changes to prevent sites from entering a collection in Research/Clinical if a collection had been entered at that timepoint in the other instance.

**Comment by sonyekere** [comment]
Closing this issue as suggested above. Erin has created a new issue #1004 to address the error in clinical and research collections at the same time point.
