### ISSUE TITLE
Chicago Research Dropdown - remove River East and South Loop (Biospecimen)

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#999]
Please remove River East and South Loop from the Research Location dropdown located on the specimen link screen of the Research Dashboard.
Chicago is converting these 2 locations to Clinical when they launch those collections.

**Comment by amber-emmes** [comment]
This is now in dev and ready to test there.

**Comment by erincschwartz** [comment]
Tested in Dev, ready for Stage

**Comment by erincschwartz** [comment]
Tested in Stage, ready for Prod

**Comment by amber-emmes** [comment]
This is now in prod.
